### ISSUE TITLE
Feature request: Show date and time-zone in the logs

### ISSUE THREAD

**Issue by hrj** [gorhill/uMatrix#100]
In Dashboard -> Statistics page, the log only shows the time. It is hard to analyse the effect of changes without knowing the date & time.

Also, is the time shown in UTC or in local timezone? It seems like it is in local timezone, in which case it seems fine to omit the TZ.

Else, please indicate the TZ as well.

**Comment by CrisBRM** [comment]
It's obviously local timezone.

As for the date... I don't find it relevant. The logging of network requests has an upper bound of 999 and there really is no point for it to be any higher, save maybe for someone researching HTTP requests  using statistics, in which case you can easily modify the value and compile the extension yourself.
What would be the point of logging _countless_ requests from unknown tabs? You could argue that this should be already a feature (knowing which tab the HTTP requests originated from) but this would affect the memory footprint and wasting programmer time on extremely niche features that only a very small subset of the user base would enable doesn't seem like smart use of it.
I digress, what I really wanted to say is that even if you set the maximum logged requests to 999, that would still only account for about 20 websites worth of requests (unless you go to really bloated news sites, in which case, about 5), and would OBVIOUSLY know when you visited them.
