### ISSUE TITLE
Feature request: Configure User-Agent on a per site basis

### ISSUE THREAD

**Issue by m-j-r** [gorhill/uMatrix#105]
First thing, thanks for the extension - best one I've ever used for 'blocking'.

I was wondering if it were possible to change the User-Agent from a global setting to a per-site setting, thereby making it a part of 'the matrix'.

I've had a look through your source, but haven't had much luck finding the right code - I don't have any experience in extensions, but I have been coding in JS for the best part of 10 years. If you could even give me an indication of where to look - I can then put together a pull request for you...

**Comment by gorhill** [comment]
You can turn on/off selectively on a per-site basis: [Per scope switches](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches).

**Comment by CrisBRM** [comment]
@gorhill I think he's talking about the ability to pick a specific UA string on a per site basis (i,e, FF32 for github, Chromium 41 for youtube, and so on).

**Comment by gorhill** [comment]
@CrisBRM I rather that he answers himself than wasting time speculating.

**Comment by m-j-r** [comment]
Hi, Thanks for the info on switches, but I was asking what @CrisBRM spoke about - a per site UA string. My company's mail only works for FF, a different internal system rejects all non IE UAs, etc, etc. Is this something I can help you work on?

Thanks,

Matt

PS I don't always have internet access over the weekend, so in future might need until a Monday morning to reply...

**Comment by gorhill** [comment]
> _My_ company's mail only works for FF ... I can help _you work on_?

Frankly, it's such a specific and narrow case, it's starting to look like a job for a programmer for hire, and you have in mind I will code it voluntarily for you.

**Comment by m-j-r** [comment]
Wow, there is no need to get your knickers in a twist. All I was asking for
was pointers to the right place in your code (as I said in my mail on
Friday), and maybe some suggestions for solutions (a lot of people won't
accept pull-requests for reasons of style, or the design conflicts with
other plans, etc). I am more than happy to do it myself (as I also said in
my mail on Friday).

In the meantime, I've read the chrome extension API, have forked your repo,
and have worked out what and I want to change - so please feel free to
continue ignoring this request, but as a favour to me, please try to relax
a bit.

Cheers,

Matt

**Comment by gorhill** [comment]
![b](https://cloud.githubusercontent.com/assets/585534/5803152/c2e682de-9fc9-11e4-9f08-503c0526ebbc.png)

This applies to this feature request, as well as some others which have been requested elsewhere.

Development is driven by features which are likely to be used by a wide number of users, not a rather specific feature useful in a very specific scenario for someone in particular.

**Comment by CODYQX4** [comment]
If you do need this feature, and I myself like having this option...

I use https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg for User-Agent per domain.

I also use https://chrome.google.com/webstore/detail/djflhoibgkdhkhhcedjiklpkjnoahfmg for Referers.

You'll want to completely disable the uMatrix options for spoofing those, as well as any extension (I disabled TamperMonkey from modifying headers, because I have scripts that set their own Referer and UA and you get extension conflicts). If you run them both, they will conflict and the last installed extension wins and chrome will have an orange menu indicating the error.

I'd love to have these options under one shop, sure, but there are ways and means to still configure the browser this way with the right add-on configuration.

I'm not at the moment actually spoofing my UA anywhere, but I use the Referer thing to TARGET_HOST all domains except font domains that break otherwise (EX: TypeKit).

**Comment by gorhill** [comment]
> I'd love to have these options under one shop

The requested feature here makes sense for an add-on which specializes in spoofing UA. It does not fit at all for uMatrix, which primary purpose is the matrix as per UI and filtering engine.

**Comment by CODYQX4** [comment]
Yeah, I can't think of any good place to put it in the UI if you did
decide to add that anyway.

**Comment by m-j-r** [comment]
Ok, I've read your comments, and you have persuaded me. The more I think about it, the more I realize that the feature I asked for doesn't fit the 'purpose' of uMatrix.

Having said that, I love the way uMatrix has been implemented, and can see it becoming more than it is now (I may be the only one to use it..., but), I love the matrix idea, and can see it being a nice 'one-stop-shop' for all your(my) automatic header 'fiddling' (or request blocking) needs. Then again, I can have a habit of over-engineering...

Thanks for responding to my request, and for explaining your reasoning - I genuinely appreciate that.

Please feel free to let me know if there is some development that I can help with (I quite enjoyed going through the source).  I do have one more feature request that you'll see soon - maybe you'll let me look into that one.... ;)
