### ISSUE TITLE
Feature request : View details of blocked items

### ISSUE THREAD

**Issue by gaijin42** [gorhill/uMatrix#106]
When viewing the matrix, it would be helpful to easily get the list of blocked items, sorted into the matrix. You can get this information already in the "Statistics" tab,  but if you could get the list filtered by domain/type right out of the matrix, it would make "fixing" broken websites much easier by deciding which elements need to be turned on, vs which can remain blocked.

**Comment by gorhill** [comment]
You want a full detailed lists in each small matrix cell?

**Comment by tlu1024** [comment]
I assume that this suggestion is meant to show such a list by hovering
the cursor over a specific cell. We had discussed such an idea in the
past already. I remember that you declined it for performance reasons.

**Comment by gaijin42** [comment]
Yes, via hover or click. Each cell is already divided into two parts horizontally for white/black listing. Perhaps a small vertical divide on the right side for "details"

Since the information is already in the statistics tab, it seems like filtering that list at the time of click should have negligible performance impact?

This could also dovetail nicely into a nice down-the-line feature where once you had the details up, you could easily introduce rules to allow or disallow specific items through that are "exceptional exceptions"

**Comment by gorhill** [comment]
I will just save myself time and close this without further comment. Sometimes I am at lost for words and when it happens the project just become no fun anymore.

**Comment by gaijin42** [comment]
If you don't like the feature, thats ok, its your project. 

But I'm somewhat confused as to why this would cause you to be at a loss for words. I made a straightforward suggestion to increase the usability of the product, in an area you apparently get enough grief about that you wanted to comment on it on the homepage.

If you disagree, or things its a bad ROI, as I said its your project, do what you want. But don't treat me like I'm trolling you please.
