### ISSUE TITLE
Update for Opera version...

### ISSUE THREAD

**Issue by Havokdan** [gorhill/uMatrix#107]
Update for Opera version...thanks.

**Comment by gorhill** [comment]
I thought I had updated it. I will download and see the differences with the current state of the project.

**Comment by Quurks** [comment]
At least my Opera Beta installation didn't auto-update uMatrix and uBlock. There are newer version available in the store, but they aren't updated automatically. Is it setup to autoupdate? https://developer.chrome.com/extensions/autoupdate

**Comment by gorhill** [comment]
The stores manage auto-update, not the extensions.

**Comment by Havokdan** [comment]
Again...  :D

**Comment by Havokdan** [comment]
Again..., uBlock is okay, but uMatrix is old...
