### ISSUE TITLE
Blocking in global scope overrides 1st-party rules in narrower scopes

### ISSUE THREAD

**Issue by adotey** [gorhill/uMatrix#109]
If you choose to block a domain in the global scope (that happens to be the same as the 1st-party domain), it will override the rule in narrower scopes to allow 1st-party domains (default rule in uMatrix).

For example (using default uMatrix settings):

1) Go to facebook.com
2) In uMatrix, with global scope selected, find domain cell for "facebook.com" and click to make it red (blocked).

The page will reload and facebook.com will now be blocked. You would expect facebook.com to still load, since in narrower scopes (facebook.com and www.facebook.com) the 1st-party domain cell is dark green (whitelisted).

I expected that blocking facebook.com in the global scope would effectively make the rule "block facebook.com everywhere except on facebook.com". You can still achieve it by going to facebook.com and specifically whitelisting the facebook.com domain in the facebook.com scope, but it is cumbersome and more work to do so.

**Comment by gorhill** [comment]
It works as expected.

The `1st-party` cell is more generic than the `facebook.com` cell, so this means the `facebook.com` has to be evaluated first, then if and only if it doesn't have an own rule, uMatrix will find the closest ancestor (the Y axis), which will be the `1st-party` cell (when on `facebook.com`).

A rule which reads "block facebook.com everywhere" **is more specific** than a rule which says "do not block 1st parties", I don't see how the opposite can be argued.

Changing the logic to comply with your expectation would lead to the terrible scenario of now having any blacklisted hostnames being free to load in your browser (as per 1st-party row) if you happen to visit one (mistakenly or not).

The current logic protects users against this happening. Yes, you will have to explicitly override the global blacklisting of `facebook.com` by toggling its state back to "gray" in the `facebook.com` scope: the rigorous precedence logic of the rules is more important than the inconvenience of having to graylist `facebook.com` after having blacklisted it globally.
