### ISSUE TITLE
Youtube HTML5 videos are not blocked

### ISSUE THREAD

**Issue by Corrodias** [gorhill/uMatrix#110]
I'm trying to prevent multimedia objects from automatically loading with µMatrix. When I visit a Youtube page, it loads the HTML5 player and starts playing the video. I'm blocking "plugin" and "other" types for all hosts, which should include video objects. I believe that should prevent them from loading.

Sorry if this has been discussed before; I didn't see any issues regarding youtube nor videos.

**Comment by gorhill** [comment]
HTML5 videos are not plug-ins. HTML5 media are reported into the `other` column, so this is where you have to block/allow them.

**Comment by Corrodias** [comment]
Yes, I am also blocking the "other" type, and that column shows as blank, indicating that µMatrix didn't catch it trying to load anything.

**Comment by gorhill** [comment]
I am looking at it now, and it appears the video data is fetched through XHRs. So the rule `youtube.com googlevideo.com xhr block` prevented the video from playing.

**Comment by Corrodias** [comment]
Oh, I see. Thank you.

I am curious why this is not blocked as a <video> object. Inspecting the page shows that the video data comes in as <video class="video-stream html5-main-video" src="blob:(url)" style="width: 640px; height: 360px; left: 0px; top: 0px; transform: none;"></video>

**Comment by gorhill** [comment]
> why

I don't know, it's just how they implemented it in their `html5player.js`.
