### ISSUE TITLE
Causing Chrome crash at start-up with proxy settings( forked from httpswitchboard issue#427)

### ISSUE THREAD

**Issue by Buddle** [gorhill/uMatrix#111]
https://github.com/gorhill/httpswitchboard/issues/427
> **Browser:Chrome x64 39.0.2171.99 Stable on Windows
> [igrigorik/node-spdyproxy](https://github.com/igrigorik/node-spdyproxy) is running on my server.**
>
> ### `Two way SSL authentication` is turn on and all settings on both server and client,my conputer > seem correct.
>
> * It doesn't matter Chrome is set with arguement `--proxy-server' or with [SwithcSharp](https://chrome.google.com/webstore/detail/dpplabbmogkhghncfbfdeeokoefdjegm),Chrome crashes >as been expected.
> * If proxy settings is on,Chrome crashes with a prompt windows from system asking me whether to >let Chrome restart as soon as it is started and it doesn't generate any report which could be found in`chrome://crashes`.
> * If proxy settings is on,but there is any issue that causes failure of client authentication,Chrome doesn't crash.For example,it is able to start when server cert or client cert is untrusted.
> * If proxy settings is on,and an issue is made that I disable the cleint cert, as mentioned above and I enable the client cert after Chrome starts without crashes as expected,Chrome is still able to work well beyond my expectation.It can access the Internet via proxy with authentication of client certificate.
> * If proxy settings is on and HTTPswithcboard is disabled,Chrome is able to work as usual and access the Internet through proxy after starting up with no crash.

> ### `Two way SSL authentication` is turn off and authentication is based on `Basic-Auth`.
> No matter HTTPswithcboard is disabled or not,all works fine without issue,no crash.

> **Is it compatible with SSL client auth?**

## Reply from [gorhill](https://github.com/gorhill/httpswitchboard/issues/427#issuecomment-70921540)
> Two things:
>
> HTTP Switchboard is no longer maintained, it is superseded by uMatrix.
> HTTP Switchboard is javascript: javascript doesn't crash. When a browser crashes, it means there  is a bug in the browser, and this needs to be reported to the browser devs.
>
> 

**Tested uMatrix of the lastest version on Chrome 64Bit 40.0.2214.91 stable for Windows and got the same result.**
_I am sorry to bother again.But I wonder how to report to Google?It is obvious that without the extension Chrome couldn't crash and it might help much in report to find out what uMatrix does causes Chrome bug._

Thanks a lot for help.

**Comment by gorhill** [comment]
I am not equipped here to debug Chromium crashes. Please report to the Chromium devs: https://code.google.com/p/chromium/issues/list
