### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Havokdan** [gorhill/uMatrix#112]
I had an idea, see if it is appropriate and possible implements it:

With μMatrix, on several occasions it is possible that some item in the matrix shows various items, whether or not permitdos, I wonder if it is possible, say for example, the script item for a particular domain / address, the matrix shows that there twenty items, regardless of their being allowed or not, when you click the right mouse button on this matrix, it expand and sobreposse the main, and that in this new matrix, indicate each item with only two quadrodos on your right , one for permit and another square to block. And that this matrix subsidiary, there was only one icon, that was the return to the main matrix or ESC did.

I'm sorry I do not speak English, so I turned to google translator.

**Comment by gorhill** [comment]
I do not intend the matrix to be more granular than it is now, that would be a feature which would be deemed useful to an [ever smaller fraction of uMatrix users](https://github.com/gorhill/uMatrix/issues/105#issuecomment-70517330). uMatrix is already a fraction of users of uBlock.

Dup of #106.
