### ISSUE TITLE
Feature Request: 3rd party placeholder

### ISSUE THREAD

**Issue by p-b--** [gorhill/uMatrix#113]
Could you create a "3rd party" placeholder as well? This is primarily for convenience, I'd rather not click  a few extra times in my configuration.
To explain this is my current configuration

```
* * * block
* * cookie block
* * css inherit
* * frame block
* * image inherit
* * other block
* * plugin block
* * xhr block
* 1st-party css allow
* 1st-party image allow
```

What I want to be able to do however, is to be able to allow 1st party xhr, plugin and other by clicking the 1st party cell. As it stands right now, I have to do that and then also allow xhr, plugin and other on the 1st party row, which is somewhat inconvenient.

The reverse implementation (not explicitly blocking it) means that for each third-party domain I add I have to block it for that domain. 

What I would be looking for as a solution would be something like this:

```
* * * block
* * cookie block
* * css inherit
* * frame block
* * image inherit
* 1st-party css allow
* 1st-party image allow
* 3rd-party other block
* 3rd-party plugin block
* 3rd-party xhr 
```

This would allow for the blocking of specific elements for third party (less trusted) options while allowing third for first party (ideally more trusted).

Thanks!

**Comment by gorhill** [comment]
I have to admit I don't understand the request. Could you attach a screenshot of the matrix for the **result** you want?

**Comment by CrisBRM** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/9098352/5880436/727bb764-a330-11e4-816a-b3c23bf2e9da.png)

**Comment by p-b--** [comment]
Sure - so basically I am looking to be able to do is replicate the functionality of the "1st party" place holder with a "3rd party" which will represent all the other urls. That way I can implement functionality such as this.

![matrix](https://cloud.githubusercontent.com/assets/10670536/5880443/9b8b4784-a306-11e4-835b-73db1d5dd486.png)

**Comment by gorhill** [comment]
@p-b-- Why not use the header cells? That's why I didn't include a 3rd-party row (I considered it at design time), because the header cells can accomplish the same thing, without the need to clutter the matrix further.

**Comment by p-b--** [comment]
@gorhill, that does not really allow me to block all third party cells by policy. So if you look at my earlier example, what I want to be able to do is blanket block stuff for all "3rd party" hosts, but not for the 1st-party. 

![matrix](https://cloud.githubusercontent.com/assets/10670536/5880747/c99fb19e-a308-11e4-881f-7ae1d991d92f.png)

So if you look at that picture, If I select 1st party I can allow everything except for cookies and frames. However, if I enable something like blogger.com it would not allow cookies and frames (from global) but also plugin, xhr, and other (from the 3rd-party line). So it gives me the ability to apply policy to the "not 1st party" group.

**Comment by tlu1024** [comment]
@p-b-- >that does not really allow me to block all third party cells by policy. So if you look at my earlier example, what I want to be able to do is blanket block stuff for all "3rd party" hosts, but not for the 1st-party.

I'm not sure that I understand. IMO, just block everything except 1st-party in the global scope and you'll get what you want.

**Comment by p-b--** [comment]
@tlu1024 so if you look at the image above, if I click on **1st-party** I can enable *plugin, script, xhr and other* for all **1st-party** domains. In one click I can enable all of that functionality, which I usually want from the **1st party** domain. However if I click any individual **3rd-party** domain (such as say google.com) it would only enable css, image, and script; due to the fact that I have *cookies and frame* blocked at a **global scope** and *plugin, xhr, and other* blocked at a **3rd-party** scope.

Also I realize that the global blocks are temporary in my picture, that is because I did not chance the colors for it. It has no bearing on my example at all.

**Comment by gorhill** [comment]
I understood your pic @p-b-- , I decided to give more thought on this.

The workaround for that specific case is that instead of clicking **once** one the `robertmuth.blogspot.com`, you have to click thrice, i.e **two more clicks**. Now the issue is that you don't want to click two more times -- for when you actually want to give more permission to 1st-party domain.

So this is essentially this:

Two extra clicks

vs.

One extra row, extra code path in the core of the filtering engine (not a big deal), extra code in the popup UI (not fond to add even more complications in there).

And that difference is relevant only for when you actually decide to grant more permissions to the 1st-party domain.

**Comment by p-b--** [comment]
Fair enough on that point, it is not a huge deal. It was 2/3 a convenience factor thing for me.

The 1/3 would just be a portion of adding another layer of abstraction to the ui, which at least I thought was useful. However - if it is complicated enough, not an issue.
Thanks!

**Comment by gorhill** [comment]
I didn't decide against or for, I am just still assessing about the overall benefit versus amount of work. If I come to see this as worth it I will look into this.

**Comment by p-b--** [comment]
@gorhill I was actually thinking of trying it myself. I can submit a pull request with what I come up with?

**Comment by gorhill** [comment]
Well I can't prevent you from trying to add the feature but I know myself and to be honest in the current case I will find it hard to not do this myself as I want to keep complete grasp of how the code work. The real hard work is really in popup UI -- the filtering engine it is mostly a cut/paste (though I always run benchmarks as part of QA). There is always the possibility there is something I am not thinking which I would hit while coding this.

**Comment by p-b--** [comment]
Fair enough. I can respect wanting to maintaining control of your work. Let me know what you think. Will keep a watchful eye on the thread :)

**Comment by p-b--** [comment]
Hey -- is there any update on this issue? I'd be interested in submitting a pull request to include this feature but I am not sure if you want pull requests for these things.

**Comment by TimySch** [comment]
This use-case is unfortunately not possible without 3rd-party filter.
![2016-11-09 12_44_39-](https://cloud.githubusercontent.com/assets/23357426/20137399/790fd3b8-a67a-11e6-876b-3161328fb0f7.png)
I just want the 1st-party to be green here.

**Comment by p-b--** [comment]
I haven't looked at it that closely, but can't you make the default block and then just click on 1st-party?

**Comment by TimySch** [comment]
It seems if default is block, it cannot be unblocked later down.
If the default is allow or neutral, I have to block each 3rd-party domain (and that for each 1st-party domain).

The rule "1st-party allow" cannot be also placed higher than "all block" manually, because of autosort.

So you basically need all three: all, 1st-party, !1st-party to complete filter logic

**Comment by gorhill** [comment]
> I just want the 1st-party to be green here.

Then why create an _allow_ rule for _all_?

**Comment by TimySch** [comment]
Maybe because I want to allow all by default?
And I want to restrict only explicit elements?
Like I wanted to restrict 3rd party cookies above, thought it was pretty obvious.

Anyway, here without the allow all rule:
![2016-11-09 14_02_45-](https://cloud.githubusercontent.com/assets/23357426/20139302/a78325be-a685-11e6-9d2f-1ec9ef968607.png)

**Comment by gorhill** [comment]
> Maybe because I want to allow all by default?

You are contradicting yourself:

> I just want the 1st-party to be green here.

**Comment by TimySch** [comment]
Ok, don't bother.

**Comment by p-b--** [comment]
@gorhill while I have you here, could you let me know the plan for this?
I've made a crude fix in my local extension which I can submit as a PR, but I know you wanted to implement something like this yourself.

**Comment by gorhill** [comment]
I will decline, I do not see the point to throw in more code and code paths which only purpose would be to save two clicks in _some_ use cases for _some_ users.

I do not accept pull requests other than trivial fix. This would turn me into a code reviewer, and this is not the hobby I picked with my presence on GitHub. And really, if _ever_ I wanted to volunteer code review work, I would volunteer as a code reviewer for Firefox extensions.

**Comment by p-b--** [comment]
That's fine, I understand that it is your project. I'll maintain the codebase locally and merge in changes.

However, I will add that the only advantage is not the clicks. I have found having a 3rd party option in the config has been extremely useful. It allows for classifying the entire "other" category specifically which helps when writing rules for sites. Moreso than anything when dealing with something like `github.com` I can call it `github.com` as a first-party, but I can address all the other domains with 3rd-party.

pb

**Comment by TimySch** [comment]
@p-b-- Or could you perhaps fork and merge your changes?

I would be glad to try it out
