### ISSUE TITLE
drop down menu to narrow?

### ISSUE THREAD

**Issue by lenabauer** [gorhill/uMatrix#114]
I have a small problem with the menu of Umatrix. the upper part is too narrow by me. how can I change this?

![1](https://cloud.githubusercontent.com/assets/10672591/5877975/b0726b2e-a323-11e4-9d5b-b709c5357b2d.jpg)
![2](https://cloud.githubusercontent.com/assets/10672591/5877977/b076ea32-a323-11e4-8152-21ed9f891844.jpg)

**Comment by gorhill** [comment]
Did you select "Large" for _"Text size"_ in the _Settings_?

**Comment by gorhill** [comment]
There is something peculiar with your browser settings. Even if I use large text for uMatrix, the popup is larger than yours:

![a](https://cloud.githubusercontent.com/assets/585534/5878835/d937a370-a2f7-11e4-9d10-25311563eb55.png)

What are the settings for _"Web content"_ in your browser settings? (font size, page zoom)

**Comment by lenabauer** [comment]
no, the Text size ist normal. i have have the scale of windows by 125% but change zu 100% also does not solve the problem

**Comment by gorhill** [comment]
Thing is uMatrix (or any extension) does not control the popup size, the browser decides. Normally on a stock browser, I have designed the popup content to fit comfortably -- large text included -- into the the max width the browser will allow. So something is you setup (OS, browser) is causing the fonts to be larger than stock. Look at the tabs at the top: yours are rather small compared to what I get (I took care to resize my window close to what you have in the pics).

Bottom-line is that the browser has a max width in pixels for extension popup, and an extension has no say about this. You need to adjust whatever settings on your side which causes the problem, as making the matrix smaller is of course not an option (the header labels are already overflowing in your screenshot)

**Comment by tikurahul** [comment]
I have a different manifestation of a similar problem. uMatrix popup is clipped and unclickable many a times. I have to constantly try again, and finally the popup is of the right size.

![image](https://cloud.githubusercontent.com/assets/624211/6737664/477151da-ce2a-11e4-8a48-e497b1daa295.png)

**Comment by gorhill** [comment]
It's the browser picking the popup size, extension have no say. The issue should be filed with Chromium, there is nothing I can do. The matrix was designed in such way that it fits in the largest allowed popup.

**Comment by gorhill** [comment]
uMatrix can't control system/browser fonts, this is were the issue lies. In all cases I have seen, system fonts appear to be significantly smaller than the browser fonts, so there is some settings which only the users control which are changed from normal. It's for the user to fix.
