### ISSUE TITLE
Matrix choices not remembered after restarting chromium

### ISSUE THREAD

**Issue by John-Gee** [gorhill/uMatrix#115]
Hello,

I was on chromium 39, just moved to 40, and using uMatrix 0.8.1.3.
My issue is that the matrix is not remembered after restarting chromium, and since it's fairly time consuming to set it 'right', it's fairly cumbersome.
I am not sure why though... it's the only extension that has this issue.
In the extension tab I see: "Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined", for line js/messaging-handlers.js:292 (contentScriptSummaryHandler).

I am not sure what else to give, please ask.

(I'm also using ublock, but I haven't made any change there so I cannot say if it'd have the same issue or not, but at least there is none displayed in the extension tab for it)

Thanks!

**Comment by gorhill** [comment]
Are you using the padlock when you make changes?

Also, there is a backup feature in the _About_ tab, it's a good idea to use it regularly after you made many changes, so you can just restore all at once if something happen.

**Comment by John-Gee** [comment]
What is the padlock?
Maybe I'm not.

Thanks!

**Comment by gorhill** [comment]
https://github.com/gorhill/httpswitchboard/wiki/The-matrix-toolbar#persist-temporary-rules

**Comment by John-Gee** [comment]
ooooh I see, that's probably why then.
Sorry for the nuisance!

**Comment by John-Gee** [comment]
Actually, looking back I know why I didn't see that option.
When setting Text Size to Large, 2 icons are hidden by the others, the lock and the remove tempory changes for this scope. Setting the text size to small, I see them.

**Comment by gorhill** [comment]
Setting text to large should not break the UI. Do you have other browser/system settings which affect font size?

**Comment by John-Gee** [comment]
Not that I can think of.
I usually zoom in pages quite a bit as I'm on a 1080p resolution on a 50"
TV.
A bit different, but if that helps, I also don't see the full matrix, I
have to scroll to the right for about 1.5 column, but the titles don't move
with the rest so I do not know what column comes after frame (well I only
see up to "fram"). This behavior is in normal size, in large I don't see
past the script column title.

Thanks!

**Comment by gorhill** [comment]
What's the DPI as per you OS on that screen?

**Comment by John-Gee** [comment]
It's set to 96x96.

**Comment by gorhill** [comment]
The only way I can get a matrix which doesn't fit in the limited space (the browser sets a maximum size for the popup) and which results in the padlock disappearing is when I set the default page zoom to 175% or higher. Is this your case?

**Comment by John-Gee** [comment]
That is set to 100%, though I usually manually zoom to 150% or higher.
It does not seem to relate to the current page zoom, as changing it has no
effect of umatrix's size.
So I am not sure...

**Comment by gorhill** [comment]
Are we talking about the same zoom setting? I am talking of the one in the _Settings_ page of the browser. This one definitely changes the zoom of the extension popups:

![c](https://cloud.githubusercontent.com/assets/585534/5994391/4d3d8520-aa3f-11e4-91c7-1c2a80edb4d0.png)

**Comment by John-Gee** [comment]
Hmmm yes the same.
I didn't restart chromium after changing it,  maybe that's why.

**Comment by John-Gee** [comment]
Oh just in case, what I meant by:
"It does not seem to relate to the current page zoom, as changing it has no
effect of umatrix's size."
is when I manually zoom in/out a page, it does not change umatrix's size,
even though the current page obviously changes.

And when I tried playing with the default page zoom settings, umatrix's
size didn't change either, but I did not restart chromium in between, I'll
have to try that.

**Comment by John-Gee** [comment]
I just looked back at this, having a similar issue with another extension.
And yes, the panel size changes with the page zoom, but I need to restart Chromium for it to matter, which I didn't do back then (not sure why anymore).
With uMatrix I can see everything with a default page zoom of up to 150% (that is not true with the other extension though).
