### ISSUE TITLE
XHR and Other requests are not blocked with everything blocked by default

### ISSUE THREAD

**Issue by requiredregistration** [gorhill/uMatrix#117]
also, there are no logged XHR and Other requests in the request log anymore

tested with youtube, this problem appeared with the 40.0.x releases

**Comment by requiredregistration** [comment]
steps to reproduce, allow only css, image, and script, the video file will be requested and it will start playback as it is downloaded

with wikipedia, again allow only css, image, and script, clicking in the search bar and typing for the incremental search should log XHR requests and they should be blocked, they are sent as if the user has permitted that

**Comment by emanueLczirai** [comment]
with master uMatrix or a version pre 0.8.1.3 ?

**Comment by requiredregistration** [comment]
this is what broke it,

to prevent it from connecting to github i changed:
```
projectServerRoot: 'https://raw.githubusercontent.com/gorhill/umatrix/master/',
```
to
```
projectServerRoot: '',
```
and it resulted to those problems

**Comment by requiredregistration** [comment]
gorhill, it should be possible to use uMatrix without requiring a connection to github

**Comment by gorhill** [comment]
@requiredregistration 

I agree, but a specific issue should be opened for this.

**Comment by requiredregistration** [comment]
all right
