### ISSUE TITLE
it should be possible to use uMatrix without requiring a connection to github

### ISSUE THREAD

**Issue by requiredregistration** [gorhill/uMatrix#119]

**Comment by anothermindbomb** [comment]
Where are you seeing the requirement to connect to github?

**Comment by anothermindbomb** [comment]
Scratch that - just read #117

**Comment by CrisBRM** [comment]
Is this still a thing?

**Comment by gorhill** [comment]
I imported code from uBlock for this part. There should be no connection to github at start time. If auto-update is not enabled, the only connection to github is supposed to occur when visiting the _Hosts files_ page (to find out what needs to be updated). I will also revert [this fix](https://github.com/gorhill/httpswitchboard/issues/202), so a user could ccompletely block uMatrix itself from fetching its own resource.

**Comment by gorhill** [comment]
Fixed in 0.9.0.0.
