### ISSUE TITLE
Youtube constantly loads new elements

### ISSUE THREAD

**Issue by kniddl** [gorhill/uMatrix#120]
Youtube loads quite many elements so I blocked the most and allowed one element after the other of which I thought were related to the playback. That worked like on other sites. At the beginning of the playback, the matrix looks like following:

![at_the_beginning](https://cloud.githubusercontent.com/assets/10777535/5982074/ecf90084-a8bf-11e4-9eca-c1bb2613c050.PNG)

The number of elements increases successive. This increase is visible in the s.youtube.com and the googlevideo,com rows. 

![high_number](https://cloud.githubusercontent.com/assets/10777535/5981837/ce9d92b4-a8bd-11e4-8e70-5fc3c045aa78.PNG)
 
The amount of elements doesn't stop at 700 but increased to above 2000. To reload the site, to copy the video link and paste into a new tab or to load a new video doesn't fix the problem only loading the start page works. 
s.youtube.com is used for statistics so a solution without allowing would be preferable. (http://upcommons.upc.edu/pfc/bitstream/2099.1/15251/1/YouTube_Traffic_Monitoring_and_Analysis.pdf).
 
I hope you can recreate my problem and find a solution. Thanks.

**Comment by gorhill** [comment]
> I hope you can recreate my problem and find a solution

What problem?

**Comment by kniddl** [comment]
The problem is that the amount increases as long as I'm on Youtube. Thereby the memory and cpu usage increases successively. The cpu usage increases averagely about 5 % with 1000 elements. That happens only on Youtube so it feels like a problem.

**Comment by gorhill** [comment]
> The cpu usage increases averagely about 5 % with 1000 elements

Sorry but that makes no sense, for many reasons. Looks to me you are making assumptions of how uMatrix works internally, and using these assumptions to make more assumptions that the count is correlated to the CPU usage. Also "5%" is completely not significant measurement, I would like to know how you measured this. Let me see: **eyeball** the task manager?

The statistics for a specific URL won't be flushed from memory until some minutes after you leave that URL. The reason is that if you set temporary rules on some entries, you still want to see these entries after you refresh the page, as there are explicit rules onto them. It's per URL, not per site, so "as long as I'm on Youtube" is also wrong.

I don't see any issue aside that the count is bothering you for some reasons.

**Comment by gorhill** [comment]
I have to battle so many bad myth re. uBloc or uMatrix, that just for the record regarding

> the cpu usage increases averagely about 5 % with 1000 elements

I am currently at 1000 requests, and uMatrix's CPU is pretty much all the time at 0%.

It's completely unsubstantiate to say that uMatrix adds 5% CPU usage after it blocks a lot. Not only un-substantiate, but if you understand how it works internally, it makes no sense at all.

The only thing uMatrix currently crippling severely uMatrix is that horrible [Chromium memory leak](https://code.google.com/p/chromium/issues/detail?id=441500), which by the look of it will take forever to have fixed.

**Comment by kniddl** [comment]
If you are that certain then it indeed isn't the fault of uMatrix. And probably I don't understand totally the functionality; I read through the documentation but I'm just an user so bear with me.
 My question is then whether you know why youtube loads constantly new elements and why the memory and CPU usage is so high. Without uMatrix the playback seemed less CPU demanding. Is it perhaps due to the HTML5? 
I haven't written that yet but I really appreciate your work and I find uMatrix and his ancestor very useful extensions.

**Comment by gorhill** [comment]
> whether you know why youtube loads constantly new elements

If you try the network request logger in uBlock (better than the one in uMatrix -- plan to bring it to uMatrix eventually), you can see what are all these requests in real-time.

uMatrix is actually more efficient than HTTPSB in processing network requests -- that part of the code was improved and significantly simplified. Regarding the content scripts injected on the page, it's virtually a no-op relative to uBlock, i.e. there is pretty much nothing happening on a Youtube video page.

When you say your CPU usage is high, what is it actually? Does it bounce a lot widely? Do you have hardware acceleration enabled? Did you try forcing Flash to see if there is a difference? What browser version? Did you try rebooting the browser (sometimes things can become weird, it has happened to me)? Best is probably to post about your observations on Chromium forum somewhere along with all the pertinent details.

**Comment by kniddl** [comment]
The statistics page shows a particularly high amount of  blocked cookies, about 70-95 % of all blocked elements. So the problem what I thought regarding the matrix isn't the amount of scripts but the high number of cookies.
 The CPU usage bounces pretty widely when I play a video. 
Yes, I enabled hardware acceleration. 
No, I haven't tried yet but I actually don't know how I can force to use flash. For few days HTML5 is enabled automatically so I didn't think about forcing flash.
I have Opera 27.
Perhaps I should restart my browser; I haven't done that for days...
I'll restart my computer and look what happens. Thanks for your explanations.
