### ISSUE TITLE
CIDR/Address range support

### ISSUE THREAD

**Issue by junkblocker** [gorhill/uMatrix#122]
Certain websites use IP addresses directly (for cheap CDN style load balancing or whatever reasons). Unblocking them IP by IP gets very tedious. It'd be very useful to be able to specify CIDR ranges for unblocking 123.45.67/24 etc. just like for domain names.

**Comment by gorhill** [comment]
The easiest way for me to implement this is to allow:

    123.45.67
    123.45
    123

In rules, i.e. no need for a formal CIDR declaration.

**Comment by junkblocker** [comment]
That would be sufficient for µMatrix use, Thanks!

**Comment by Stebalien** [comment]
This has been fixed and should probably be closed.

**Comment by 4nd3r** [comment]
> The easiest way for me to implement this is to allow:
> 123.45.67
> 123.45
> 123
> In rules, i.e. no need for a formal CIDR declaration.

/24, /16 and /8 aren't only prefixes. for example, one of google's network is 216.58.192.0/19. that's 216.58.192.0 - 216.58.223.255. okay, you can define 216.58.192, 216.58.193, 216.58.194 etc, but how do you define range 1.2.3.0/25, for example (last possible address is 1.2.3.127)?
