### ISSUE TITLE
Adguard AdBlocker 1.0.3.8 Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, Youtube and all other websites. Details Options "Warning: This extension failed to modify the request header "Referer" of a network request because the modification conflicted with another extension (µMatrix)." "ID: bgnkhhnnamicmpeenaelnjfhikgbkllg"

### ISSUE THREAD

**Issue by dyingjedi** [gorhill/uMatrix#123]
@adgaurd  @µMatrix 

Adguard AdBlocker 1.0.3.8
Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, Youtube and all other websites.
Details Options
Warning:
This extension failed to modify the request header "Referer" of a network request because the modification conflicted with another extension (µMatrix).
ID: bgnkhhnnamicmpeenaelnjfhikgbkllg
Inspect views: background page

Allow in incognito
  
What do I do? I need both of these apps? I didn't realize my adguard was changing the REFERER of sites anyhow. Please let me know what I can do thank you!

Premium member
Justin Cram
DyingJedi

**Comment by gorhill** [comment]
> I didn't realize my adguard was changing the REFERER of sites anyhow

uMatrix is documented to modify referrer header if the feature is active. Please bring that issue with AdGuard devs if **their** extension is doing something unexpected. I can't possibly be asked to investigate everybody else's software undocumented feature.

In any case, it's a Chromium API limitation: only one extension can [modify a header entry](https://developer.chrome.com/extensions/webRequest#conflict_resolution).
