### ISSUE TITLE
Feature request: Show applicable rule on matrix cell hover

### ISSUE THREAD

**Issue by adrianguenter** [gorhill/uMatrix#126]
This would be an extremely helpful feature. @gorhill is this something you would consider pulling if I submitted a PR?

![Mockup](http://i.imgur.com/gDDdpCG.png)

**Comment by gorhill** [comment]
Sorry, I am not ready to accept pull request for that project. Doing so I fear the code would grow out of control from my point of view.

Not sure about the "extremely"in "extremely useful". Already at a glance one knows there is an `allow` rule for `googlevideo.com` while in `www.youtube.com` scope. The only kink is that the rule could belong to a broader scope, but I don't see this as so terrible.

Probably what I would personally prefer is to be able to use arrow keys to quickly move between scopes, but not to further clutter the UI.

**Comment by adrianguenter** [comment]
>The only kink is that the rule could belong to a broader scope, but I don't see this as so terrible.

That's exactly the problem, but I understand your position. I'll fork then.

Thanks for the quick response.
