### ISSUE TITLE
Matrix cells not responsive to touch

### ISSUE THREAD

**Issue by sardiax** [gorhill/uMatrix#127]
Tried to use uMatrix on a Tablet running Chrome 40.0.2214.95 in Windows 8.1 32 bit and the matrix cells do not respond to touches. The Matrix toolbar buttons ( like power, reload, options) all respond to touches correctly, and everything works correctly with a mouse.

**Comment by gorhill** [comment]
Setting rules works fine on Firefox for Android.

Closing, issue is old and probably obsolete given it works on Firefox for Android.
