### ISSUE TITLE
Keyboard shortcut to open popup

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uMatrix#132]
Be great to have a keyboard shortcut (e.g., CTRL+SHIFT+<letter> or ALT+<letter>) to open the uMatrix popup. The idea being that I could tap the keyboard shortcut to open the popup and then use the mouse to select my settings within the popup. It would be faster and easier on my wrists to not have to move the mouse all the way across the screen everytime I want to interact with the popup.

**Comment by my-password-is-password** [comment]
https://github.com/gorhill/uMatrix/issues/84

**Comment by vdcbb** [comment]
Oh man. I saw these shortcuts before posting but the top one was greyed out and I didn't realize I had to create my own. Sorry!

**Comment by vdcbb** [comment]
But if uMatrix is ported to Firefox, can you keep the keyboard shortcuts in mind? I haven't been able to find Keyboard Shortcuts for the uBlock port of Firefox.

**Comment by CrisBRM** [comment]
Is this still a thing on the FF version? Can't find any information about this.

**Comment by drivencompassion** [comment]
Looking forward to Firefox getting some keyboard shortcut love <3
