### ISSUE TITLE
 How to solve audio transfer issue on WEBRTC

### ISSUE THREAD

**Issue by chandus134** [gorhill/uMatrix#134]
I'm currently working on a WebRTC project.
We have a small issue related to audio transfer. The problem is that the voice  transfer works in a local network. But when connected to another network i.e., remote access, the connection is establishing but voice is not transferring.
I'm looking for solution for this audio transfer over different networks.

**Comment by gorhill** [comment]
I can't help you. uMatrix shows you what is blocked or not blocked. You are the best placed to know what network traffic should be blocked or not.
