### ISSUE TITLE
how to upgrade from httpsb to uMatrix/uBlock

### ISSUE THREAD

**Issue by anarcat** [gorhill/uMatrix#139]
hello!

considering how httpsb is marked as deprecated, how would i migrate my various chromium profiles to the new combo? are settings imported?

**Comment by anarcat** [comment]
from what i can tell, the import/export syntax is not the same, how would i import httpsb rules into uMatrix? or do they split between the two as well?

thanks for those awesome tools...

**Comment by gorhill** [comment]
uMatrix rules do not have the same semantic as HTTPSB rules, so HTTPSB's rules cannot be imported in uMatrix, while retaining their meanings. The difference is that in HTTPSB, the `source` part of a rule is not "seen" by lower scopes, while it is the case in uMatrix. As a result, in uMatrix there is only one ruleset, while there as many as there are scopes in HTTPSB.

**Comment by anarcat** [comment]
it would still be nice to have an upgrade path, even if with reduced functionality...

**Comment by tlu1024** [comment]
Well, there is none. However, if you make a backup of your rules in HTTPSB and open the generated text file while you're surfing your favorite websites with µMatrix, it's much easier and faster to determine which cells have to be whitelisted. This simplifies the migration to µMatrix.
