### ISSUE TITLE
http://hosts-file.net/download/hosts.txt adding error

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#140]
uMatrix can't add http://hosts-file.net/download/hosts.txt in `3-rd party filters`, it seems to just ignore it.
I know it has almost 700,000 hostnames, but can you add it right?

**Comment by gorhill** [comment]
That file is over 30 MB, no way I will ever add this to the package. If you are on Chromium, setup a local server to host it, if you are on Firefox, save the file locally and then you can add it as a `file:///` URL.

**Comment by mikhaelkh** [comment]
I know there is no point of adding it to package, But why when I add a custom URL http://hosts-file.net/download/hosts.txt, it can't process it? The list updates monthly.
