### ISSUE TITLE
images from code.google.com issues are not loading even with "disable filtering on this site" enabled

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#142]
![2015-03-26_12-19-50](https://cloud.githubusercontent.com/assets/2054302/6843397/915ddaaa-d3b3-11e4-94c6-ae27a737c666.png)

only disabling uMatrix completely makes images load.
tested on latest chrome dev channel, using windows xp 32 bit and windows 10 64bit

**Comment by gorhill** [comment]
Give me a URL which I can just click please.

**Comment by mailinglists35** [comment]
https://code.google.com/p/hddguardian/issues/detail?id=69

**Comment by gorhill** [comment]
The server return `400 OK` when that image is requested.

The site does not like referrer spoofing, just disable referring spoofing for that site.

**Comment by mailinglists35** [comment]
thank you, apologies for not thinking about referer! :)
