### ISSUE TITLE
µMatrix -> uMatrix

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#143]
Do you plan this change?
1)"µ" isn't on standard keyboards
2)you can pronounce it "your Matrix"
3)uBlock & uMatrix will be close in chrome://extensions/
4)get rid of "µ" as "tiny" in favour of "u" as "you(r)"

**Comment by RandomAcronym** [comment]
I was wondering about this as well.

**Comment by CrisBRM** [comment]
Oh gosh, not this crap again.

**Comment by lewisje** [comment]
He did it with uBlock, so at least there's the consistency argument.
