### ISSUE TITLE
When Downloading a file, uMatrix "forgets" the current page ( same issue as uBlock #516 )

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uMatrix#145]
I think its the same issue @Mikey1993 reported for uBlock, https://github.com/gorhill/uBlock/issues/516.

Don't know if you need new steps for this.

1.) Go to http://www.reddit.com/r/PushBullet/
2.) Observe the matrix ( reddit.com )
3.) Try download from the "Pushbullet Windows app" link, you can cancel the download
4.) Observe the matrix ( pushbullet.com )

---
![umatrixdownloadingfile](https://cloud.githubusercontent.com/assets/6408935/6929506/1d39359c-d7b0-11e4-95d1-52f0744f75c7.gif)

```
Chrome (stable)
uMatrix 0.8.1.3
Win XP
```

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uMatrix/commit/7cd060a15f995215941641428a866bee8c109563#diff-e89c0f548b51d6b02baea1e832b9d8baR460>.
