### ISSUE TITLE
How to allow all but blacklisted websites?

### ISSUE THREAD

**Issue by TK3600** [gorhill/uMatrix#146]
I am someone with very limited computer skill, and I cannot just tweak with this with every single broken website. However, I don't want to run things completely without it either. So, how could I just allow everything except those blocked by default such as google analytic?

**Comment by gorhill** [comment]
> how could I just allow everything except those blocked by default such as google analytic?

I don't uinderstand what you mean by "except those blocked by default".

**Comment by TK3600** [comment]
When I click the extension icon on chrome, there is a list of red/green domain. Those on the bottom with a separate category appears to be blocked by default. Those are what I was talking about.

**Comment by gorhill** [comment]
> there is a list of red/green domain

I understand even less. You seem to be talking about dynamic filtering, but it's for advanced users -- while you say you have "limited computer skill". Dynamic filtering is never enabled by default, and when enabled, there are no rules at all, so no such thing as "blocked by default".

If by "blocked by default" you mean no dynamic filtering and just like a plain blocker, go to the _Settings_ pane in the dashboard, then un-check "I am an advanced user". This will disable dynamic filtering and web sites should cease being broken.

**Comment by TK3600** [comment]
https://i.imgur.com/U5r4AyT.png

Does this help clarify?

**Comment by gorhill** [comment]
Very funny, the whole time I thought I was talking about uBlock... Oops...

Ok, now I understand better.

What you want is to allow everything by default, except to keep blocking whatever is in the hosts lists.

Here are the steps:

- Select the global scope (`*` in the drop down list at the top left)
- Click the `all` cell so that it turns green
- Save -- click the padlock so that the new rule sticks

This way uMatrix will run in allow-all/block-exceptionally mode.

Keep in mind some hosts lists can break stuff, so you may still stumble on broken sites. So use the hosts lists which are less likely to break something.

**Comment by gorhill** [comment]
It's how it should look like:

![d](https://cloud.githubusercontent.com/assets/585534/6934371/773c04d8-d801-11e4-9eae-db48319d9607.png)

I forgot about frames, I added a step in the previous comment.

**Comment by TK3600** [comment]
Thank you!

**Comment by Maxxee** [comment]
After adding

https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easylistgermany.txt

to the Hosts files, your instructions don't work at all for me. Everything is blocked by default. E.g.

https://google.de
https://heise.de

None of these 3 lists include the whole above mentioned hosts, just portions of them, but uMatrix keeps blocking everything, even after going through all your steps and restarting Chrome.
Interestingly enough https://github.com/ is not blocked at all.

**Comment by gorhill** [comment]
> After adding [...] to the Hosts files

Are EasyList, EasyPrivacy and EasyGermany [hosts files](https://en.wikipedia.org/wiki/Hosts_(file))?
