### ISSUE TITLE
Trouble intercepting "data:" URI scheme?

### ISSUE THREAD

**Issue by adepasquale** [gorhill/uMatrix#149]
**uMatrix could not redirect a network request to `data:text/html,<REDACTED>` because another extension (Ghostery) has redirected to `about:blank`.**

May this be a problem or is it simply caused by a wrong interaction with/by Ghostery?

**Comment by offhub** [comment]
> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

https://developer.chrome.com/extensions/webRequest#conflict_resolution

**Comment by adepasquale** [comment]
Thanks, so I guess I'll uninstall Ghostery. :smile:
