### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#150]
@gorhill, In the last 2.5 months there are 2 commits here while over 800 commits to uBlock. Does that mead you're tired of maintaining this project?

**Comment by gorhill** [comment]
it's alive.

**Comment by mailinglists35** [comment]
gorhill. I want to say this: discovering uMatrix is like reinventing the web browser. it's like all I did since netscape navigator 4 until now was done in darkness and now somebody switched on the lights. seriously. thank you! noscripts and scriptsafe have suddenly become rudimentary archaic toys.
