### ISSUE TITLE
pdf blocked. probably i'm doing something wrong but can't figure it out

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#153]
trying to open this url http://dcsplus.net/upload/files/online-marketing-manager-bpo_36_file1.pdf
clicked "disabled for this scope", but still pdf is blocked (f12 in chrome shows "(canceled)")
what I am doing wrong?

here are the rules:

Permanent rules

https-strict: * true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: opera-scheme true
referrer-spoof: * true
referrer-spoof: hotnews.ro false
ua-spoof: * true
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party frame allow
* translate.googleapis.com * allow

 
Temporary rules

https-strict: * true
https-strict: dcsplus.net false
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: dcsplus.net true
matrix-off: localhost true
matrix-off: opera-scheme true
referrer-spoof: * true
referrer-spoof: dcsplus.net false
ua-spoof: * true
ua-spoof: dcsplus.net false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party frame allow
* translate.googleapis.com * allow

![1](https://cloud.githubusercontent.com/assets/2054302/7037259/8bb0981e-dda8-11e4-9eee-c104be24ce04.jpg)
![2015-04-08_04-25-31](https://cloud.githubusercontent.com/assets/2054302/7037264/9684d124-dda8-11e4-8a9b-a9529f9f6029.png)

**Comment by gorhill** [comment]
- I don't know from where you downloaded that PDF, I need an exact URL please.
- How did you try to download it? Left-click? Right-click?
- Do you have an extension to render the PDF?

I tried to download a PDF from <http://dcsplus.net/> and it worked fine.

**Comment by mailinglists35** [comment]
1. just click the url
2 & 3. it automatically opens with chrome internal pdf viewer if I disable umatrix

**Comment by gorhill** [comment]
With the following rules:

    https-strict: * true
    https-strict: dcsplus.net false
    matrix-off: chrome-extension-scheme true
    matrix-off: chrome-scheme true
    matrix-off: dcsplus.net true
    matrix-off: localhost true
    matrix-off: opera-scheme true
    referrer-spoof: * true
    referrer-spoof: dcsplus.net false
    ua-spoof: * true
    ua-spoof: dcsplus.net false
    * * * block
    * * css allow
    * * frame block
    * * image allow
    * 1st-party frame allow
    * translate.googleapis.com * allow

I enabled Chrome PDF viewer, went to <http://dcsplus.net/about-us/careers>, clicked any PDF, and it loaded just fine.

I cannot reproduce with the information you have given me, using Chromium 41. Does the problem also occur for Chrome 41?

**Comment by mailinglists35** [comment]
the issue was not reproductible on a second portable instance of stable release 41.
I have uninstalled and reinstalled the extension and now it's loading.
I think I might have deleted behind the scene requests :D
