### ISSUE TITLE
becomes damaged after random interval, forgets saved settings

### ISSUE THREAD

**Issue by olmy** [gorhill/uMatrix#154]
Using Opera developer 30.0. The umatrix icon disappears after some (seemingly) random amount of time. Going to the extensions manager, umatrix is disabled and says it's corrupted or damaged (forget the exact wording), and there's a button to Repair. Clicking the Repair button does get it working again, but it's forgotten all its saved settings.

**Comment by gorhill** [comment]
I don't provide support for dev verion of browser. Try with an official release and if the problem does not occur, close the issue please.

**Comment by olmy** [comment]
Not available for release Opera/Linux, apparently.
