### ISSUE TITLE
Opening PDF files no longer possible in Chrome v. 42 unless allowed in behind-the-scene.

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#156]
https://www.wilderssecurity.com/threads/umatrix-the-http-switchboard-successor.369601/page-13#post-2481971

If behind-the-scene requests are blocked, it's now necessary to whitelist "other" for the respective site in the behind-the-scene matrix.

**Comment by gorhill** [comment]
Not much I can do really.

A while ago I tried a trick to find a possible tab from where a behind-the-scene request originate (using referrer), but that just didn't work really -- so I ended up with lot more complicated code paths for no result at all.

We will have to accept this, a browser-specific behavior.

**Comment by tlu1024** [comment]
Okay, I just remembered our discussion [here](https://github.com/gorhill/httpswitchboard/issues/335). The `chromium-extension-scheme` is also available in uMatrix. I disabled the Chrome PDF viewer and installed the PDF Viewer extension. After allowing XHR it works. 

What do you think of this? A viable alternative?

**Comment by gorhill** [comment]
> A viable alternative?

That's for each user to decide. If for some users blocking completely behind the scene requests is very important, I guess then it is a viable alternative to them.

**Comment by tlu1024** [comment]
Thanks! Unfortunately the `chromium-extension-scheme` is nowhere documented as far as I know. Is it possible that other extensions will be negatively affected if, say, only the XHR column therein is whitelisted?

**Comment by gorhill** [comment]
I suppose it is possible some extensions pull stuff from remote servers -- bottomline is if you filter something in a scope, then yes, it may affect whatever make use of that scope, which in the current case means yes, other extensions could be affected if you filter something in the `chromium-extension-scheme` scope.

**Comment by tlu1024** [comment]
I see. What's still unclear to me is. What exactly does the `chromium-extension-scheme` or, in other words: How does it differ from the `behind-the-scene` matrix?

**Comment by gorhill** [comment]
`chrome-extension-scheme` is used for when the URL in the address bar starts with `chrome-extension://[...]`. So when you are visiting an extension's pages.

**Comment by tlu1024** [comment]
Now that you saying this it seems obvious ;-)

Thanks again!
