### ISSUE TITLE
XHRs getting through without being blocked or logged

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uMatrix#161]
Posted this over on Wilders but didn't get a response, so I thought I should file an issue in further detail.

Steps to reproduce:

Chrome 44.0.2376.0 dev-m

1) Everything set to deny in uMatrix, just for this purpose
2) Enable chrome://flags/#enhanced-bookmarks-experiment
3) Open Bookmarks Manager
4) Open the console (with "Log XMLHttpRequests" checked)
5) Start typing in the top search input and observe XHRs to Google

For now I have the flag set to disabled, but I'm still concerned because it's not captured by uMatrix. I also wonder if other extensions–or Chrome itself–could be behaving similarly without me knowing.

I don't know the full extent to which you can detect and block certain requests in Chrome (I mean, maybe there's some things that can't be blocked/logged), so any info on that would be appreciated, too.

Thanks for your time.

**Comment by gorhill** [comment]
Observations:

- All the requests were fetched from the cache from what I've seen (no remote connection)
- The `webRequest.onBeforeRequest` is not called

It seems to be an integrated "extension" or "app", in that it has an extension id, and you can actually step through the javascript source.

But in any case, as said, if the `webRequest.onBeforeRequest` listener is not called by Chromium, there is nothing uMatrix can do.

**Comment by luxoflux** [comment]
That settles it then... kind of a bummer. I was under the assumption this sort of thing falls under behind-the-scenes or extension-sheme requests, etc. But as you said, onBeforeRequest is not called.

Anyway, to be clear, a remote connection is made (it's how instant results are served):

Headers
Remote Address:173.194.65.139:443
Request URL:https://clients1.google.com/complete/search?client=stars&gs_rn=64&gs_ri=stars&cp=4&gs_id=h&q=test&xhr=t
Request Method:GET
Status Code:200 OK

I could add clients1.google.com to my hosts file, but it might be needed for possibly important stuff, haven't looked in to it.
