### ISSUE TITLE
Timer on the disable/enable feature

### ISSUE THREAD

**Issue by Piste** [gorhill/uMatrix#162]
I would love a timer on the disable/enable feature so that I could stop using uMatrix for 5, 10, 30 minutes at a time. And have it re-enabled automatically after this amount of time has passed.

**Comment by CrisBRM** [comment]
But why? What potential use case could there be for something like that?

**Comment by Piste** [comment]
Well for one uMatrix can get pretty click-intensive. You arrive on a new website and things don't appear or some features are broken. So you start enabling this. The page loads partially then you enable that, etc. In the case you are browsing with someone else (say, troubleshooting, following instructions...) this can become tedious and slow you down.
A second case is CDN subdomain. And I apologize if this is due to my minimal knowledge of the rule file. But basically anything that uses CloudFront for example will force me to allow a (different?) .cloudfront.net subdomain every time I land on a CDN-enabled page. I think [issue 121](https://github.com/gorhill/uMatrix/issues/121) referred to it. Since AFAIK there is no way to allow all CloudFront within any site it can be useful for watching videos on random sites, for example.

**Comment by gorhill** [comment]
The matrix switch is temporary, it needs to be padlocked to stick.
