### ISSUE TITLE
Popup is not refreshed when navigating back if site is blocked

### ISSUE THREAD

**Issue by colaas** [gorhill/uMatrix#163]
If you go to any site while it is blocked and then go somewhere else and come back in the same tab, the pop-up is not refreshed. Refreshing the page does nothing and the actual URL is not visible.

![Imgur](http://i.imgur.com/djYt3qJ.png)

**Comment by gorhill** [comment]
What version is this?

**Comment by colaas** [comment]
This is on µMatrix 0.8.1.3

**Comment by gorhill** [comment]
Fixed in 0.9.0.0.
