### ISSUE TITLE
uMatrix 0.8.1.4 : "Uncaught SecurityError" on Google Image search

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uMatrix#164]
1.  Go to http://www.google.com/imgres?imgurl=http://7-themes.com/data_images/out/24/6850090-jaguar.jpg&imgrefurl=http://7-themes.com/6976545-jaguar-the-big-cat.html&h=2048&w=3072&tbnid=nWZRiLkOy3m_mM:&zoom=1&docid=pKYPXoINKggC_M&ei=0h5GVaCyBYyaNv2qgIgL&tbm=isch&ved=0CCMQMygGMAY
2. Open up the console

----

<b>uMatrix 0.8.1.3</b>: Preview page works.

![umatrix0813_googleimage](https://cloud.githubusercontent.com/assets/6408935/7445221/7d84eaaa-f15e-11e4-90bf-a7bf6f8591df.png)

-----

<b>uMatrix 0.8.1.4</b>: The page is blank and theres an error in the console,

![umatrix0814_googleimage](https://cloud.githubusercontent.com/assets/6408935/7445214/4fd69f4a-f15e-11e4-9934-3bb7bbd112a2.png)

```
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://www.google.com" from accessing a frame with origin "null".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "data". Protocols must match.
```

```
Chrome (stable)
Win XP
```

**Comment by gorhill** [comment]
I get "Redirect Notice" when I click your link:

> The previous page is sending you to http://7-themes.com/6976545-jaguar-the-big-cat.html.
> 
> If you do not want to visit that page, you can return to the previous page.

**Comment by my-password-is-password** [comment]
@gorhill Whoops, I think you have to allow `google` in the matrix

**Comment by gorhill** [comment]
Does work.

Just tell me how you end up on that page, so I can create my own query.

**Comment by my-password-is-password** [comment]
1) Search for something on https://images.google.com/
2) Click on any image

Thats how i got there.

**Comment by gorhill** [comment]
Doesn't work, I can't get to what you have, a full page image preview, mines are just embedded. Anyways, I clicked you link again and finally it went there. It's the page itself the issue, not uMatrix.

You will get same message however the frame is blocked, be it with uBlock or ABP (which do not replace the frame content like uMatrix.) The browser itself tries to put in a placeholder, and even this one is refused.
