### ISSUE TITLE
[FF] Destroys 4ch's css occasionally

### ISSUE THREAD

**Issue by CrisBRM** [gorhill/uMatrix#165]
Doesn't happen on Chromium using the exact same rules, nor does it happen when using Policeman, or after disabling uMatrix.
Problem persists even after disabling the filter for that scope.

![issue](https://cloud.githubusercontent.com/assets/9098352/7520864/c685b7b2-f4e1-11e4-9ecc-a28e710e2b10.png)

Bonus: Can't upload images on github (works on Chromium) Problem persists even after disabling the filter for this scope. 

![web console](https://cloud.githubusercontent.com/assets/9098352/7520924/3012505a-f4e2-11e4-9c41-043c322895b4.png)

**Comment by gorhill** [comment]
Check your behind the scene matrix -- from the logger.

**Comment by gorhill** [comment]
![d](https://cloud.githubusercontent.com/assets/585534/7521106/47c61a02-f4b9-11e4-8e1f-0dfe756c2107.png)

**Comment by CrisBRM** [comment]
Oh! I naively figured I would have no problems as I imported the same profile I use on Chromium. My bad!

**Comment by gorhill** [comment]
I still need to look if there anything to be done, the amount of b-t-s request in Firefox is worrying.

**Comment by CrisBRM** [comment]
Agreed. 
Which reminds me, you once said you were waiting for Chromium dev support websockets, in order to make them interceptable via chrome.webRequest.onBeforeRequest. Are you going to add websocket support to firefox?

Anyway, a good solution to the b-t-s requests problem, would be to bring it to the front UI, like so 
![mockup](https://cloud.githubusercontent.com/assets/9098352/7521370/4b08619e-f4e5-11e4-9259-37abc598bdbd.png)

I suppose a per-tab B-T-S scope would be rather hard to do.

**Comment by gorhill** [comment]
Not hard to do, but it's supposed to be exceptional, it should not be required. There is something to fix in there, if I step through the code, no requests end up behind-the-scene for that scenario. If I let the code run uninterrupted, I see b-t-s requests.

**Comment by CrisBRM** [comment]
Found a problem with the b-t-s matrix layout -- it doesn't resize itself.
![bts](https://cloud.githubusercontent.com/assets/9098352/7522346/8b11db10-f4ec-11e4-961e-76f776bce148.png)

**Comment by gorhill** [comment]
Yes, these quirks go into cosmetic issues, I know about these and how to fix them.

**Comment by gorhill** [comment]
Ok the code ported from Firefox had some requirements meaningful to uBlock only, no so for uMatrix. It's much simpler for uMatrix, it doesn't need to keep track of embedded frame ids etc. The output is cleaner now, the only b-t-s requests I see are _really_ behind-the-scene ones.

**Comment by gorhill** [comment]
I consider this fixed with latest build.

**Comment by gorhill** [comment]
> Are you going to add websocket support to firefox?

webSocket requests are currently reported in the `other` column, they can already be blocked. In all likelihood, there are only one webSocket upgrade request per page, so to create a separate column would not be good. Because only one request uppgrade to webSocket, a better UI for this would be a per-scope switch, or to just leave it in the `other` column.

You can test the blocking of webSocket upgrade request [here](http://ephemeralp2p.durazo.us/2bbbf21959178ef2f935e90fc60e5b6e368d27514fe305ca7dcecc32c0134838).

**Comment by bayun** [comment]
I'm not sure if you accept any bug reports for SeaMnkey - but uMatrix works fine in it... except that all CSS requests end up as behind-the-scene. Yes, I know that default set of rules allows all for css - but is it the only way?

**Comment by gorhill** [comment]
What version of Seamonkey are you using?

**Comment by bayun** [comment]
2.33.1.
I have found some strange half-workaround that works sometimes. If after starting uMatrix (i.e. browser loading) with default rules (uMatrix does not save settings on Seamonkey for some reason) I load rules from text file things are usually good. But if I load saved settings - almost all requests become "behind-the-scene".
