### ISSUE TITLE
[0.9.0.0-dev0] Root doc blocked if only CSS and image allowed

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#166]
I tested the Firefox version a bit with Firefox 37.02 64bit under Arch Linux. 

I changed the default behaviour by allowing **only** the CSS and image columns in the global scope. 

![spiegel](https://cloud.githubusercontent.com/assets/1099173/7521345/747886fa-f4ed-11e4-89c8-fc5dab54e763.png)

Then I tried to open `www.spiegel.de`. Result:

![spiegel1](https://cloud.githubusercontent.com/assets/1099173/7521267/dc63d126-f4ec-11e4-908e-e62da08837a0.png)

The logger says:

`19:09:21		--	doc	http://www.spiegel.de/ `

In the `www.spiegel.de` line of the matrix I allowed one cell after the other and reloaded the site  - but to no avail. The site didn't load.

![spiegel2](https://cloud.githubusercontent.com/assets/1099173/7521388/ce72096a-f4ed-11e4-83b1-98ac5adce22a.png)

Only after whitelisting the complete `www.spiegel.de` line by clicking the respective cell in the left matrix column the site loaded - although all cells in that line had been already whitelisted before.

![spiegel3](https://cloud.githubusercontent.com/assets/1099173/7521460/3927a274-f4ee-11e4-9415-b238363eba50.png)

I don't think that's the intended behaviour.

**Comment by tlu1024** [comment]
Aargghh - how embarrassing ... I must have had a blackout ...

**Comment by gorhill** [comment]
I plan to show the "offensive" rules in the logger, but not sure this will be part of 0.9.0.0.

**Comment by gorhill** [comment]
Ok the code ported from Firefox had some requirements meaningful to uBlock only, no so for uMatrix. It's much simpler for uMatrix, it doesn't need to keep track of embedded frame ids etc. The output is cleaner now, the only b-t-s requests I see are _really_ behind-the-scene ones.
