### ISSUE TITLE
[FF] Pages not reloading

### ISSUE THREAD

**Issue by dogbite** [gorhill/uMatrix#167]
Web pages are not being reloaded automatically after changing some uMatrix settings, as it happens in Chrome.
A manual reload makes these changes effective.

**Comment by gorhill** [comment]
I removed that feature.

**Comment by acidicX** [comment]
Any special reason why? I think this was a very essential feature. I always forget to click on the reload button. It is just so much easier to leave it on automatic reload...

**Comment by Phoenix616** [comment]
Any chance on getting this feature back? I am currently considering reverting to httpswitchboard (or running my own fork when I find out where this change was made)

**Comment by bael0r** [comment]
I'd hardly call this an "essential feature" or worthy of a fork but feel free to do so.

**Comment by Phoenix616** [comment]
Well it brakes my workflow and I loose dozens of seconds every time I expect the page to reload after a change... btw. this is the commit that removed that feature be3e86e055f05e80bdc7c98804e9c2cb1a616872, maybe I get around reimplementing it in a new version, for now I probably stick to httpsb or a pre 0.9 µMatrix version.

**Comment by gitgetgot** [comment]
I just tested the addon the first time and that feature is one of the most important missing ones!
