### ISSUE TITLE
[Firefox] Connection count constantly increasing?

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#169]
First time using uMatrix. I noticed the connection count is constantly increasing on sites like Youtube and Twitch. See image:

![Imatrix count](http://i.imgur.com/pbXavnz.jpg)

At the time of posting the count was in excess of 1000. Is this normal?

**Comment by gorhill** [comment]
> Is this normal?

Yes. It's the number of **distinct** URLs the page has seen. On streaming sites especially, it will keep going up.
