### ISSUE TITLE
[Firefox] Adding hosts files erroneous

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#170]
If I add a new hosts file to the Firefox version (dev3), pressing the enter key does not create a line break. Additional hosts file are added to the same first line. After clicking the apply button they are loaded but as "undefined".

![hosts](https://cloud.githubusercontent.com/assets/1099173/7534922/d2f853c6-f57f-11e4-9680-4ec0ffb063fb.png)

The problem does not seem to exist in the Chrome version.

EDIT: I disabled uMatrix in about:addons and enabeld it again. Now it looks this way:

![hosts1](https://cloud.githubusercontent.com/assets/1099173/7535048/2e84c778-f581-11e4-9fde-b4638b8b58fc.png)

However, after clicking the apply button it looks the same as in the first screenshot.

**Comment by gorhill** [comment]
> pressing the enter key does not create a line break

What is your OS?

**Comment by gorhill** [comment]
> pressing the enter key does not create a line break

Never mind, I was testing in the user agent field, I can reproduce in the_Hosts files_ pane.

**Comment by gorhill** [comment]
Can you give me URLs for me to paste in? Easier than me wandering on the web to find stuff to put in there.

**Comment by tlu1024** [comment]
Sure:

https://zeustracker.abuse.ch/blocklist.php?download=hostfile
https://zeustracker.abuse.ch/blocklist.php?download=badips
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist
https://zeustracker.abuse.ch/blocklist.php?download=compromised

**Comment by gorhill** [comment]
Thanks.

**Comment by tlu1024** [comment]
I just noticed that there is also a problem in the Chrome version: If I disable dev3 and enable it again I have to click the apply button in order to make the new hosts files work. They are still shown but with "0 used out of ...". Obviously those settings are not remembered by uMatrix.
