### ISSUE TITLE
[Chrome] Lastpass autofill doesn't work anymore

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#171]
With dev3 the login fields for, e.g., github.com are no longer filled out by Lastpass in Chrome 42. Up to uMatrix 0.8.1.3 it worked flawlessly with the following b-t-s rules:

chromium-behind-the-scene lastpass.com cookie allow
chromium-behind-the-scene lastpass.com script allow
chromium-behind-the-scene lastpass.com xhr allow

In dev3 I added the follwing corresponding rules:

behind-the-scene lastpass.com cookie allow
behind-the-scene lastpass.com other allow
behind-the-scene lastpass.com script allow
behind-the-scene lastpass.com xhr allow

but no no avail. I have to manually copy username and password to the login fields. The logger doesn't show anything blocked.

Whats's interesting: It works with Firefox 37.0.2. without the need to define any b-t-s- rules.

**Comment by gorhill** [comment]
Ok, I installed LastPass, created an account, disabled browser's own auto-fill, cleared the user/password for Wilders Security, entered the login info in LastPass, etc.

Visited <http://www.wilderssecurity.com/>, clicked LastPass' _AutoFill_, the user/password were properly filled in, I could login.

I don't trust LastPass enough to give it my credentials for Github. Is the problem only on Github?

**Comment by tlu1024** [comment]
I've tried several sites. On some sites it works (e.g. for Gmail), on some other sites it doesn't. I will try to find a reason for this.

**Comment by gorhill** [comment]
See if you can spot an error from `contentscript_*.js` in the console of a web page where it doesn't work.

**Comment by tlu1024** [comment]
Couldn't find anything, still investigating ...

**Comment by tlu1024** [comment]
Here's an example to illustrate my point. Load

`https://www.deka.de/privatkunden`

with Chrome and uMatrix 0.8.1.3. This is how it looks:

![deka1](https://cloud.githubusercontent.com/assets/1099173/7541733/c513dae0-f5b7-11e4-9241-738353068271.png)

There is a button called "Depotzugang" at the top of the site. If you click it the site looks like this:

![deka2](https://cloud.githubusercontent.com/assets/1099173/7541779/0ff42952-f5b8-11e4-8e6f-e7d994a1dc1d.png)

Now the login fields can be filled out by Lastpass. No problem.

Now load the site with uMatrix 0.9.0.0-dev6:

![deka3](https://cloud.githubusercontent.com/assets/1099173/7541831/587c0a28-f5b8-11e4-9b5c-c145a0910eaf.png)

4 things are different compared to 0.8.1.3:

1. You'll notice that the **big** image (below PERSPEKTIVEN PRODUKTE ...) is not displayed.
2. In the matrix there is no line for `stats.deka.de` and it does not appear in the logger, either.
3. In the Chrome address line there is now a button that says that javascript is blocked for this site.
4. If you click the button "Depotzugang" at the top of the site nothing happens, hence the login fields cannot be filled by Lastpass.

In both versions the following rules were used:

deka.de deka.de cookie allow
deka.de www.deka.de cookie allow
deka.de www.deka.de script allow
deka.de www.deka.de xhr allow

Please note that I can **not** observe this behaviour in the Firefox version. Only the Chrome versions seem to behave rather differently. 

All settings were identical.

**Comment by gorhill** [comment]
> Please note that I can not observe this behaviour in the Firefox version

If I allow `stats.deka.de` with uBlock only, the script is downloaded (normally blocked by some filter in EasyPrivacy). However, if I unallow, the entry `stats.deka.de` is no longer reported as blocked by uBlock. It's because of the Chromium memory-based cache. When something is in the memory-cache, it won't be reported to the webRequest API. This is typical case where Firefox API does a better job.

> In the Chrome address line there is now a button that says that javascript is blocked for this site.

Ok, this must be it. With 0.9.0.0, I completely removed mingling with user settings, so if you have custom javascript rules (the browser ones), uMatrix 0.9.0.0 won't override them.

**Comment by tlu1024** [comment]
> Ok, this must be it. With 0.9.0.0, I completely removed mingling with user settings, so if you have custom javascript rules (the browser ones), uMatrix 0.9.0.0 won't override them.

Aha! That's interesting. I had, indeed, some custom javascript rules created in the old ages before HTTPSB but none related to `deka.de`. However, I had javascript blocked by default in Chrome as it hadn't mattered before. Now after allowing javascript by default above problems are gone. I just wonder why not **all** websites were affected it that was the culprit.

**Comment by gorhill** [comment]
> In any case this should be prominently communicated as this is an important change which might affect many users

I guess I should just put back that code, that would be one less thing to explain.

**Comment by tlu1024** [comment]
I guess so ;-)
