### ISSUE TITLE
Inline javascript not blocked with Firefox version

### ISSUE THREAD

**Issue by tlu1024** [gorhill/uMatrix#172]
On your javascript test site

http://raymondhill.net/httpsb/httpsb-test-js-1.html

Inline javascript is reported as ON while it is reported as OFF with the Chrome version dev5.

**Comment by tlu1024** [comment]
Similar results on 

http://www.javatester.org/javascript.html
and
http://sveinbjorn.org/check_if_javascript_is_enabled

Firefox: JS enabled and Chrome: JS disabled on both sites.

**Comment by gorhill** [comment]
I can reproduce.

This is a regression, I remember specifically testing this with the Firefox version.
