### ISSUE TITLE
[FF] Heads up: It's possible there may be a major memory leak

### ISSUE THREAD

**Issue by CrisBRM** [gorhill/uMatrix#173]
Switched to uMatrix from Policeman and every now and again, memory usage will skyrocket to 5, sometimes 7gb, with only 5 tabs open, until I am forced to kill the process.
Tried to save the memory report, but to no avail, as everything had slowed down to a crawl.

Disabled uMatrix for the time being, and I'm back on Policeman. Will report back with results to exclude the possibility of it being caused by the browser (FF dev edition x64).

Is there anything you'd like me to do? Like replicating what happened and actually saving the memory report?

**Comment by gorhill** [comment]
I have been keeping an eye on memory usage and it held pretty well from what I've seen.

However, it is my experience that when I install uMatrix, I remove the current version first, quit Firefox, restart Firefox, and install the new version of uMatrix.

I've seen in the past remove/disabled extension being kept alive somewhere in Firefox, and with memory footprint increasing. Given that in development reloading the extension happens quite often, the remove/quit/launch/install steps have given me the best result so far.

**Comment by CrisBRM** [comment]
>I've seen in the past remove/disabled extension being kept alive somewhere in Firefox, and with memory footprint increasing. Given that in development reloading the extension happens quite often, the remove/quit/launch/install steps have given me the best result so far.

Could be it. I'm going to do that and try to replicate it.

**Comment by gorhill** [comment]
I've been running FF/uMatrix since a bit now. I will keep running it the whole day without restarting, and will log here mem usage on a regular basis, and see how it looks like at the end of the day.

12h00: 195MB (10 + 6MB)

***

`explicit` (`add-ons/uMatrix@raymondhill.net` + `top(resource://gre-resources/hiddenWindow.html, id=1)`, after a _"Minimize memory usage"_.

3 tabs opened: uMatrix's logger, About add-ons, a page on Github.

**Comment by CrisBRM** [comment]
I'm doing the same. I've done what you said, in regards to addon installation and so far so good.

**Comment by gorhill** [comment]
Been using Nightly e10s most of the day, opened/closed logger on a regular basis, etc. and two tabs opened (here + about:addons), and allocated memory is 165 MB for allocated memory figure, uMatrix shows at under 1.4 MB + the `top(resource://gre-resources/hiddenWindow.html, id=1)` entry at 7 MB under Window objects.

So its doing well.

**Comment by CrisBRM** [comment]
Been monitoring usage for the past 3 days and you're right. Glad to know it supports e10s out of the box too (I don't think policeman does, for instance, so it's definitely good to know).
