### ISSUE TITLE
[0.9.0.0-dev.6] [Firefox] Cookie Blocking

### ISSUE THREAD

**Issue by Blutgang** [gorhill/uMatrix#174]
Cookie blocking on the Firefox version of uMatrix does not exhibit the same behavior as the Chrome version of uMatrix.

Rules:
````
matrix-off: opera-scheme true
* * * block
* * cookie block
* * css allow
* * frame block
* * image allow
reddit.com reddit.com * allow
reddit.com redditstatic.com script allow
````
Chrome `42.0.2311.135`
1. `[nsfw]` Go to `reddit.com/r/nsfw` (not logged in)
2. Click `Yes` for the `Over 18?` page
3. You stay on the `Over 18?` page if the cookie is blocked

Firefox `37.0.2`
1. `[nsfw]` Go to `reddit.com/r/nsfw` (not logged in)
2. Click `Yes` for the `Over 18?` page
3. You do not stay on the `Over 18?` page and you are redirected to the `reddit.com/r/nsfw` page
4. Click on `comments` for the first post and you are redirected to the `Over 18?` page
5. Click `Yes` again and you are redirected to the first post page

From observation, cookie blocking on the Firefox version of uMatrix seems to be partially working (Ex. I block cookies on GitHub. I try to log into Github. Github will show a message: `Cookies must be enabled to use GitHub.`)

**Comment by gorhill** [comment]
It's going to take some digging. There is a redirect involved, so I thought it was just a matter of modifying the request headers of the new channel, but it doesn't work. Looks like Firefox is re-adding the cookie header after the redirect occur.
