### ISSUE TITLE
[0.9.0.0-dev.6] [FF] Blocking some scripts from loading even when disabled on the page

### ISSUE THREAD

**Issue by asherdavidson** [gorhill/uMatrix#175]
More specifically, Google Calendar loads a script so that I can scroll between different months. With uMatrix, that script fails to load even when I explicitly allow everything for that page. I temporarily disabled uMatrix and the problem went away, but it came back after I re-enabled uMatrix.

**Comment by gorhill** [comment]
What does the logger says about that script?

**Comment by asherdavidson** [comment]
Let me clarify. I don't know exactly what script is running, all I know is that it only works when the whole addon is disabled. I checked the logs and the network tab, and I can't see any difference between the scripts loaded when uMatrix is enabled and when it's not. I don't know why uMatrix is doing this, and perhaps I was too quick to assume it was blocking a script, but I do know that it is the root of the problem.

**Comment by gorhill** [comment]
Did you try to disable Strict HTTPS? This switch is independent of the matrix switch.

**Comment by asherdavidson** [comment]
It wasn't enabled to begin with. I use HTTPS Everywhere for that.

On Fri, May 8, 2015 at 7:01 PM, Raymond Hill <notifications@github.com>
wrote:

> Did you try to disable Strict HTTPS? This switch is independent of the
> matrix switch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uMatrix/issues/175#issuecomment-100390706>.
>



-- 
-Asher

**Comment by gorhill** [comment]
Can you give me a URL please so that I have an idea what to look at.

**Comment by asherdavidson** [comment]
I figured out the problem. I had the User Agent spoofing enabled, and it
didn't like that. I don't know why, but that fixed it. Thanks!

On Fri, May 8, 2015 at 7:02 PM, Asher Davidson <usherdavidson@gmail.com>
wrote:

> It wasn't enabled to begin with. I use HTTPS Everywhere for that.
>
> On Fri, May 8, 2015 at 7:01 PM, Raymond Hill <notifications@github.com>
> wrote:
>
>> Did you try to disable Strict HTTPS? This switch is independent of the
>> matrix switch.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gorhill/uMatrix/issues/175#issuecomment-100390706>.
>>
>
>
>
> --
> -Asher
>



-- 
-Asher

**Comment by asherdavidson** [comment]
https://www.google.com/calendar/render

On Fri, May 8, 2015 at 7:04 PM, Raymond Hill <notifications@github.com>
wrote:

> Can you give me a URL please so that I have an idea what to look at.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gorhill/uMatrix/issues/175#issuecomment-100391025>.
>



-- 
-Asher
