### ISSUE TITLE
[Firefox] Cookies issue

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uMatrix#176]
First of all, thanks for the Firefox version of uMatrix. I have been waiting for this since a long time.

I have some cookies problem that's preventing me from logging to github and Amazon. I am not sure if its a bug or something to do with my browser/addons.

uMatrix doesn't show cookies count and the website refuses to login because of cookies blocked issue despite enabling for the domain. 

Attached are the screenshots. If it's related to a known bug please feel free to close this. uMatrix is working absolutely fine on Chromium.

![umatrix cookies](https://cloud.githubusercontent.com/assets/3329844/7548865/a568bb42-f63a-11e4-90ba-e3bee6a5646a.png)
![umatrix cookies 2](https://cloud.githubusercontent.com/assets/3329844/7548870/ae5fbe62-f63a-11e4-9373-f33ff6d14b18.png)

**Comment by gorhill** [comment]
It definitely should show you the cookie count. Can you look at the browser console (ctrl-shift-J) and se if there are errors which seem related to uMatrix?

**Comment by tlu1024** [comment]
No problems here. Perhaps cookies are blocked in the Firefox settings or through another extension?

What's different for me: 
1. If I enter `github.com/session` I'm directed to `github.com/login`
2. In the matrix there is also a line for `api.github.com` where I see a number in the XHR column (which I allowed)
3. I also see a number in the CSS column for `assets-cdn.github.com`

**Comment by gorhill** [comment]
The way uMatrix work is that it records a cookie each time it is notified by the FF API that a cookie has changed (added, modified, cleared). So it is as if the FF PI is not notifying uMatrix, **or** uMatrix was unable to build its cookie dictionary at launch time. Console hopefully gives hints about this.

**Comment by castor-troy** [comment]
I am using Firefox Developer Edition 39.0a2 (2015-05-08). I have a number of add-ons installed. CanvasBlocker, Downthemall, greasemonkey, Httpseverywhere, lastpass, localload, minimizetotray revived, ublock origin, umatrix, self-destructing cookies, x-notifier.

I will try to look through the browser console and then disable add-ons one by one to find the culprit.

**Comment by castor-troy** [comment]
My apologizes. I used to run Cookie Monster earlier which disabled all cookies by default. In my excitement to use uMatrix, I uninstalled Cookie Monster but it didn't re-enable cookie settings in Firefox. It was disabled for all sites when I checked a few minutes ago. Everything is fine and working as expected. Sorry for wasting your time.
