### ISSUE TITLE
Cookies created, even though disabled in uMatrix

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uMatrix#179]
For the Cookies column in uMatrix panel, everything is in red. When I open the site, I could see cookies being created. They are shown in "show cookies" option of Firefox. In the uMatrix log, all cookies entries are in red. I also checked disabling all add-ons except umatrix and ublock.

![screen1](https://cloud.githubusercontent.com/assets/3329844/7550529/5110ca96-f683-11e4-85a0-aad7db6fb9bc.png)
![screen2](https://cloud.githubusercontent.com/assets/3329844/7550530/547dbcca-f683-11e4-89a3-ce4bb001886f.png)
![screen3](https://cloud.githubusercontent.com/assets/3329844/7550532/5cdd1e42-f683-11e4-9db8-3f07cebfbda8.png)
![screen4](https://cloud.githubusercontent.com/assets/3329844/7550533/600a7ff6-f683-11e4-9ddd-9373043ba3cc.png)

**Comment by gorhill** [comment]
By design, _as explained in the dashboard_:

> Blacklisted cookies are not prevented by uMatrix from entering your browser. However they are prevented from leaving your browser, which is what really matters. Not blocking cookies before they enter your browser gives you the opportunity to be informed that a site tried to use cookies, and furthermore to inspect their contents if you wish.
Once these blacklisted cookies have been accounted for by uMatrix, they can be removed from your browser if you wish so.
> 
> Important note: Extensions can make web requests during the course of their normal operation. These requests can result in cookies being created in the browser. If the hostname from where a cookie originate is not whitelisted, the cookie will be removed from the browser by uMatrix if this option is checked. So be sure that the hostname(s) with which an extension communicate is whitelisted.
