### ISSUE TITLE
1st party detection

### ISSUE THREAD

**Issue by arthurtiteica** [gorhill/uMatrix#180]
A real life example:

I'm on https://example.wordpress.com/ and I want to allow scripts from this sub-domain only. If I allow 1st party with the 'example.wordpress.com' **scope** selected scripts from wordpress.com are also allowed.

I'm not sure this is the intended behavior but in my opinion this may lead to security issues if scripts allowed for good.example.com are able to also run in bad.example.com.

![Screenshot](https://i.imgur.com/g3HuPiX.png)

**Comment by gorhill** [comment]
`wordpress.com` is not in the Public Suffix List, which means that it is really a 1st-party. The Public Suffix List rules **is** the reference for this. For your specific case, the solution is to remove the `allow` rule for `wordpress.com`, i.e.:

    wordpress.com 1st-party * inherit

I can't create arbitrary exceptions to the PSL, it dictates everything about what is 1st-/3rd-party. If we disagree about its content, the solution for a user is to work around it with his own rules.

**Comment by arthurtiteica** [comment]
Yeah, this was a misunderstanding on my part thinking that allowing scripts in the scope of good.example.com would allow example.com globally, which is not the case.
