### ISSUE TITLE
Firefox: uMatrix ui does not appear if Navigation toolbar is hidden.

### ISSUE THREAD

**Issue by sigma914** [gorhill/uMatrix#181]
### Reproduction steps:
1. Install add-on that hides the "Toolbar" ie the main navigation/search/add-on bar (I use pentadactyl)
2. Use firefox's customize feature to drag the uMatrix icon onto another bar (I tried the tab bar, and others)
3. Click uMatrix icon
### Expected:

uMatrix UI appears
### Actual:

uMatrix UI does not appear.
### Notes:

Watching the output of top while clicking the uMatrix icon indicates that firefox is allocating memory every time the icon is clicked, but the UI fails to appear.

**Comment by a4xxx** [comment]
See https://github.com/gorhill/uBlock/issues/112.

**Comment by Raziel-23** [comment]
I had the same problem and here #288 is a proper solution.

**Comment by josch** [comment]
If #288 is a proper solution then I fail to find the setting `extensions.umatrix.forceLegacyToolbarButton`.

**Comment by josch** [comment]
Manually adding `extensions.umatrix.forceLegacyToolbarButton` as a boolean value set to `true` to `about:config` fixes this issue indeed with pentadactyl.

**Comment by gorhill** [comment]
Legacy Firefox is not longer maintained.
