### ISSUE TITLE
Check website reputation/security

### ISSUE THREAD

**Issue by Snapy** [gorhill/uMatrix#185]
Close this if it's on your todo list.
Are you still considering adding this feature as described in gorhill/httpswitchboard#106 but also regarding security ?
> Very rough idea, a user click of the middle button while in the matrix would open an extension 
> web page which would list all the hostnames reported in the matrix, with links to the most prominent trustworthiness web sites.

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/65#issuecomment-93733679>:

>  I regretted to have put it in, so it's not back in uMatrix.

**Comment by Snapy** [comment]
I understand for WOT but checking the security of site is different from the rating based on a handful of users (those willing to rate). For example VirusTotal uses a lot (~60) of antivirus engines and has no reputation feature.

**Comment by gorhill** [comment]
https://www.virustotal.com/en/documentation/browser-extensions/

I won't let uMatrix fall to [scope-creep](http://en.wikipedia.org/wiki/Scope_creep), and also won't have uMatrix endorse (through features) any specific 3rd-party vendors.
