### ISSUE TITLE
Firefox: Custom placeholders not kept after restart

### ISSUE THREAD

**Issue by one23** [gorhill/uMatrix#186]
Per https://github.com/gorhill/uMatrix/commit/44f1a61c42fb3c0357774ea176ef0ea6a9591642#commitcomment-11015765, I tried to customise placeholders in `about:config` using `extensions.umatrix.placeholder*` prefs, but it seems they are set back to default every time I close/open Firefox or just disable/enable uMatrix.  Is this intended?

Browser info: Firefox 38b9, uMatrix 0.9.0.0-rc.1

**Comment by gorhill** [comment]
For now they are overwritten at start. I may need to change them -- like I did in a recent commit -- and these changes need to take effect. 

Please do not file issue for stuff which are not documented features.

**Comment by one23** [comment]
Alright, sorry, and thanks for reply.

**Comment by gorhill** [comment]
Version 0.9.0.2-dev.0 will no longer overwrite your customizations. Document placeholder for frames cannot be customized though.

**Comment by one23** [comment]
Thank you for this!  Although, the frame placeholder was one I had customised.

Just having the little up arrow as a link was very small for me, so I had moved the URL inside the `<a>` tag, then gave it `display: block; height: 100%;` styling, so the entire area of the placeholder was clickable.  Of course, I can always modify the extension itself locally, so it's not a big deal.
