### ISSUE TITLE
Not an issue: just a place to drop images for doc

### ISSUE THREAD

**Issue by gorhill** [gorhill/uMatrix#187]

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/7592491/8a7bc1a8-f8a1-11e4-8258-fbdec534f801.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/7592521/af96e53a-f8a1-11e4-8cb1-d736f17bbb5b.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/7666597/5f287288-fbb9-11e4-877d-83d0fbc1c777.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/9806858/8b03ad08-5818-11e5-8de2-3f1281e178f0.png)

**Comment by jjohns71** [comment]
![step01_panel_global](https://cloud.githubusercontent.com/assets/6795795/25504702/eb3cc6ae-2b6c-11e7-9757-cbc740abeed9.png)
![step01_panel_onedomain](https://cloud.githubusercontent.com/assets/6795795/25504703/eb3f9b18-2b6c-11e7-8659-92d34ff358aa.png)
![step02_whitelistrules_global](https://cloud.githubusercontent.com/assets/6795795/25504704/eb3ff162-2b6c-11e7-94da-062444c1ce65.png)
![step02_whitelistrules_onedomain](https://cloud.githubusercontent.com/assets/6795795/25504705/eb426ad2-2b6c-11e7-99e1-1dd33bc7f059.png)
![step03_commit](https://cloud.githubusercontent.com/assets/6795795/25504706/eb428db4-2b6c-11e7-868d-20be7594e9de.PNG)
![step03_saverules_global](https://cloud.githubusercontent.com/assets/6795795/25504707/eb46c848-2b6c-11e7-81b6-857cf5c996b0.png)
![step03_saverules_onedomain](https://cloud.githubusercontent.com/assets/6795795/25504711/eb563224-2b6c-11e7-8a14-88622f4f8a17.png)
![step03alt_saverules_global](https://cloud.githubusercontent.com/assets/6795795/25504708/eb50f516-2b6c-11e7-9f78-e3b825a36a2c.PNG)
![step03alt_saverules_onedomain](https://cloud.githubusercontent.com/assets/6795795/25504709/eb53a28e-2b6c-11e7-92b1-c88baa65b889.PNG)
![step04_refresh](https://cloud.githubusercontent.com/assets/6795795/25504712/eb584654-2b6c-11e7-87d3-cdea667edf26.png)
![step05_youtube_global](https://cloud.githubusercontent.com/assets/6795795/25504710/eb54d564-2b6c-11e7-8a2c-48a0613b2ca1.png)
![step05_youtube_onedomain](https://cloud.githubusercontent.com/assets/6795795/25504713/eb60db98-2b6c-11e7-8921-18f411e490d6.png)
