### ISSUE TITLE
Chrome: Random UA Spoof logs without UA Spoof enabled

### ISSUE THREAD

**Issue by CODYQX4** [gorhill/uMatrix#191]
I have this disabled globally, but I get the occasional entry:
spoofing user agent with: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36

Is this a bug or just not clear that it is selecting that UA but not activating it? The wording implies that this is my active UA, but it isn't and I confirm that sites aren't seeing the fake UA.

**Comment by CrisBRM** [comment]
uMatrix rotates the user agents internally, even if the preference isn't set, but, if the latter is correct, it won't override yours, so it's all good.

**Comment by gorhill** [comment]
Yes, it's just for information purpose. One can disable the global UA spoof setting, yet enable it for one single site. That would be very inefficient for uMatrix to check if there is at least one switch each time the rotation occur just to see if it should log or not.

**Comment by gorhill** [comment]
Can someone suggest me a better wording to avoid confusion?

**Comment by CrisBRM** [comment]
For the entry in the logger? Just "rotating user agent, current string: {{string}}". Perhaps with a little tooltip next to the UA spoofer which states they are rotated constantly, but the browser's UA will only be overridden if the box has been checked.

**Comment by gorhill** [comment]
I could just remove it as well too if it makes the logger too "noisy" and if the entry really doesn't add much informational value.

**Comment by 5t3f4n** [comment]
Removal seems like a reasonable approach.
IMHO it just adds clutter/confusion while providing little to no value.

**Comment by alejandrolemus** [comment]
Since you were asking for suggestions, instead of logging the rotation, maybe you could just highlight the currently active ua-string on the Dashboard textbox (where all strings are listed).
