### ISSUE TITLE
Chromium: The matrix menu has disappeared.

### ISSUE THREAD

**Issue by absorber** [gorhill/uMatrix#194]
First of all, thank you for making such an awesome project to what it has become.

I have no idea how to reproduce this, it appears that the issue appeared suddenly and is not showing any interest of going away.

This is what my menu looks like at this moment:
![screenshot from 2015-05-13 01 14 02](https://cloud.githubusercontent.com/assets/2358532/7598735/94a9e22e-f90d-11e4-9abd-dfcca2175cb0.png)

The pushing of those buttons does not produce any visible result.

Things I tried doing to fix this:
* Checking whether this is only in normal or also in incognito mode (issue is in both).
* Removing everything except browsing history from the beginning of time.
* Re-installing the extension.
* Closing Chromium completely and re-opening.

Version 37.0.2062.120 Built on Ubuntu 12.04, running on elementary OS 0.2.1 (281580) (64-bit)

**Comment by CrisBRM** [comment]
Has happened to me after reinstalling Chromium. Deleting the "application" folder and installing it again might fix it, it did for me, assuming this problem started as soon as you updated chromium.

**Comment by gorhill** [comment]
Are there any errors reported at the extension's own dev console? Tell me if you don't know about how to access extension's own dev console.

**Comment by dboshardy** [comment]
I'm getting this as well.  

Ubuntu 14.04
Chrome Version 40.0.2214.111 (64-bit)

**Comment by gorhill** [comment]
Best first is if you guys can tell me if there are any errors at the extension's dev console.

**Comment by dboshardy** [comment]
The only errors I see are related to content on the page not loading due to being blocked.

**Comment by gorhill** [comment]
@dboshardy I am guessing you were looking at the web page console. The extension console is at a different place:

![a](https://cloud.githubusercontent.com/assets/585534/7600872/dd67c664-f8dd-11e4-8a9b-c23427b25a61.png)

- Go to `chrome://extensions/`
- Check _Developer mode_ (top right)
- Click `background.html` of uMatrix
- Dev console for the extension will open
- Select the _Console_ tab
- Click _Reload_ for uMatrix
- See if the console contains error messages (report here if so)

**Comment by dboshardy** [comment]
Couldn't find Reload in the console window.  However, when I right click on the uMatrix button on the toolbar and click "Inspect popup." I get this:
```Uncaught SyntaxError: Use of const in strict mode.```

**Comment by gorhill** [comment]
> `Uncaught SyntaxError: Use of const in strict mode. ... popup.js:36`

I see. I will provide an emergency fix. Are you guys installing from the Chrome store?

**Comment by dboshardy** [comment]
Yes, from the Chrome store.

**Comment by gorhill** [comment]
Ok, I will create a new package shortly.

**Comment by gorhill** [comment]
OK I pushed a new version to the Chrome store, might take an hour or so before it becomes live -- hopefully it won't be marked as "pending review" (this has been happening randomly lately).

**Comment by dboshardy** [comment]
Getting an error from the Chrome store:

```Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'```

**Comment by gorhill** [comment]
Ugh.. Let me see.

**Comment by gorhill** [comment]
I don't see what is the problem. Is your language different than `en`?

**Comment by gorhill** [comment]
I could install it fine from the store from here.

**Comment by dboshardy** [comment]
Nope.  It tries to download the .crx file then throws that error.

**Comment by gorhill** [comment]
I have no clue what can be the problem, and no way to diagnose, it's the store causing the issue. The default locale is `en`, and I checked and `_locales/en/messages.json` is in the package.

**Comment by dboshardy** [comment]
Ok.  It's probably an issue on my end.  Thanks for the quick fix!

**Comment by absorber** [comment]
I confirm observing normal operation once I un-installed the extension and re-installed it through the Chrome store.

Thank you for your swift operation.
