### ISSUE TITLE
[Firefox] Wrong popup content after clicking a download link

### ISSUE THREAD

**Issue by quilloss** [gorhill/uMatrix#195]
# Details

Firefox 38 - New Profile
uMatrix 0.9.0.0 - Default settings
# Steps
1. Go to https://github.com/gorhill/uMatrix/releases
2. Click a link to download the source
3. Click cancel at the download dialog
# Result

The context of the popup is now set to the download instead of the page.
## Popup before download

![before](https://cloud.githubusercontent.com/assets/8151080/7599464/d1f5795a-f934-11e4-8831-e548806c7148.png)
## Popup after download

![after](https://cloud.githubusercontent.com/assets/8151080/7599470/dbef5caa-f934-11e4-83db-6246f5291f4e.png)
Not shown is the scope that has changed to codeload.github.com

**Comment by gorhill** [comment]
I will need to come up with some kind of heuristic to detect these download operations, using the response headers is unreliable.
