### ISSUE TITLE
Split "Revert all temporary changes" and "Go to dashboard"

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#196]
In 0.9.0.0 this two buttons were united and it takes one more click to get to them. But they have nothing in common!

**Comment by gorhill** [comment]
What do you mean by "split"?

**Comment by RandomAcronym** [comment]
I believe they want the drop-down removed.

**Comment by gorhill** [comment]
There is no space elsewhere in the popup -- especially on Firefox, for whatever reason the button are more spaced despite same CSS.

I had to choose between removing the ability to clear all temporary changes, or use a menu for all the extra functionality -- adding to this I might add more in there, as needed.

**Comment by mikhaelkh** [comment]
I see space around button "reload current page" in both Firefox and Chrome. Or you can make popup wider.

**Comment by gorhill** [comment]
I can't make popup wider. Chromium limits the horizontal size, and when using large font, it's close to the limit, that would cause horizontal scrollbar to appear if it goes beyond.

**Comment by mikhaelkh** [comment]
You can remove "reload current page" button. I guess advanced users can use F5 to reload page.

**Comment by gorhill** [comment]
> remove "reload current page" button

No way, this is way to convenient to have it right there. This might make you happy but I have no doubt this will make more user unhappy -- me first.

**Comment by alejandrolemus** [comment]
>especially on Firefox, for whatever reason the buttons are more spaced despite same CSS

I got the opposite with uMatrix 0.9.0.1, Chrome wastes more space than Firefox. It looks like one more icon can be squeezed in there, with some CSS-fine tuning?

![popo](https://cloud.githubusercontent.com/assets/9505902/7617204/a5649ef0-f977-11e4-8580-c199a175e745.png)

**Comment by gorhill** [comment]
The buttons are closer to each other on Chromium. The space around the reload button is on purpose: it's a button that will be used often, I do not want user to pressed another button by mistake because it would be too close to the reload one.
