### ISSUE TITLE
[0.9.0.2-dev.1] [Firefox] Webm video not blocked?

### ISSUE THREAD

**Issue by Blutgang** [gorhill/uMatrix#199]
Hi, Raymond. Thanks for the great work on porting uMatrix to FF. I came across issue `#177` and I clicked on a ~~hotdogman's~~ video ~~(https://a.pomf.se/avonjf.webm)~~ (pomf.se seems to be going under) (http://video.webmfiles.org/big-buck-bunny_trailer.webm). On Firefox `38.0` the webm video loads and the matrix does not show a request for `other` on ~~`pomf.se`~~ `webmfiles.org`. On Chrome `42.0.2311.152` the webm video does not load unless I allow `other` for ~~`pomf.se`~~ `webmfiles.org`.

Rules (github rules basically)

```
matrix-off: opera-scheme true
* * * block
* * css allow
* * frame block
* * image allow
github.com github.com * allow
github.com raw.githubusercontent.com xhr allow
github.com render.githubusercontent.com frame allow
github.com render.githubusercontent.com script allow
github.com github-cloud.s3.amazonaws.com other allow
github.com github-cloud.s3.amazonaws.com xhr allow
```

**Comment by gorhill** [comment]
This is a Firefox bug: Firefox report the request as being a main document, not a media one. It does not file a request for the `video` tag, the video is pulled as the top document. If I block the top document, there won't be navigation to the new document, i.e. an unacceptable workaround.

I don't see any sensible solution for this, will have to accept this is a difference in behavior between Chromium/Firefox.

**Comment by 5t3f4n** [comment]
How come when you're trying to display a webm "in-line" with the page, such as on https://boards.4chan.org/wsg/catalog the webm gets blocked? You have to allow "Other" for 4cdn.org to make them work.

Opening the video in its own tab makes it work by default however, and no content is seen as either blocked or allowed, like in OP's example.

**Comment by gorhill** [comment]
Look at the what appear in the network tab.

When the video is opened as a doc, no secondary request (just `TYPE_DOCUMENT`), when embedded, there are secondary requests (`TYPE_MEDIA`)

**Comment by gorhill** [comment]
Thinking more about this, there might be a solution, but it won't result in FF behaving like Chromium.

Solution: try to detect whether a root document is media, if so, evaluate it as such, and if it is blocked, fallback on the blocked page warning.

**Comment by vzjrz** [comment]
This seems to be fixed for me. When loading http://video.webmfiles.org/big-buck-bunny_trailer.webm firefox shows the video ui but when clicking play an `other` request is block and the video does not play.

**Comment by SXZ1** [comment]
It looks like I came across a similar issue. Nightly 01-04-17, disable 1st party in uMatrix 0.9.9b9. Open these links in a new tab:
https://secure.fanboy.co.nz/test.mp4
Result: video is blocked, video is listed in media
https://2ch.hk/s/src/2002539/14906383487550.webm
Result: video is not blocked, video is not listed anywhere including media

**Comment by gorhill** [comment]
> video is not blocked, video is not listed anywhere including media

Same issue with the webext version, which suggests that the issue is really with Firefox.

**Comment by gorhill** [comment]
Probably obsolete by now. Couldn't find a working repro cases above. If there is still an issue with this, a new one will have to be opened with all detailed repro steps.
