### ISSUE TITLE
[Firefox] All requests classified as behind-the-scene

### ISSUE THREAD

**Issue by covoe** [gorhill/uMatrix#200]
Fresh install of `Firefox 34.0` and `uMatrix 0.9.0.2-dev.1` with default rules.

All requests are classified as "behind-the-scene" in the "other" column, according to the log:

![log](https://cloud.githubusercontent.com/assets/12437851/7624656/dc19d0aa-f9db-11e4-98a8-785478f8ab3e.png)
![panel](https://cloud.githubusercontent.com/assets/12437851/7624660/e52fafa2-f9db-11e4-95c1-85bd7f4a3809.png)

Requests are correctly classified in `Firefox 35.0.1`.

**Comment by gorhill** [comment]
I could fix the behind-the-scene issue, but that uncovered another issue that all request types ends up as `other` with FF 34 and below, which render uMatrix rather useless.

uBlock was dealing with the issue by having messaging across processes, which is something I completely removed in uMatrix, as this was causing too many requests to be spuriously labelled as behind-the-scene (see [#165](https://github.com/gorhill/uMatrix/issues/165#issuecomment-99939177)).

Also synchronous messaging across processes is discouraged for e10s -- this may lead to the warning about CPOW slowing down the extension. I could experiment with bringing back that cross-process messaging for FF versions older than 35, but really, I don't think the amount of effort to support FF 29-34 is worth it, I rather put effort is better supporting FF35+.

So for now I will just mark uMatrix as being compatible with FF35+.

**Comment by gorhill** [comment]
Fixed with 1f4ba9dda90cee7c0afb0dbbb23d537ed0425220.
