### ISSUE TITLE
Bring back old color-blind colors

### ISSUE THREAD

**Issue by oherrala** [gorhill/uMatrix#201]
I don't want to be rude, but the new colors are so horrible they make me blind. The black-white/greyscale theme was easy for eyes and I think it looked professional.

The change was made to src/css/popup.css in commit 0e77cbd15d1617d21dfb178958e230f2fc2ead78 I think.

**Comment by gorhill** [comment]
This is the research that went into picking those new colors: <https://github.com/chrisaljoudi/uBlock/issues/467#issuecomment-95081254>.

The is the research that went into picking the old colors: _[none]_.

**Comment by oherrala** [comment]
I'm sorry about the bad tone in my opening message.

I can't provide any research into this subject. The colors are subjective to personal taste. But I can say the old greyscale colors hit the spot for me (and maybe others).

I really loved the greyscale colors where black was "blocked", and white was "allowed". It looked really great and it was intuitive (from the day one for me).
