### ISSUE TITLE
[Request] Temporary site bypass like uBlock.

### ISSUE THREAD

**Issue by CODYQX4** [gorhill/uMatrix#203]
uBlock relatively recently had the ability to temporarily click through a blocked page, and uMatrix has adopted a similar page layout, but without temp/permanent whitest.

I have some RSS feeds, and sometimes  they have a page they go through (like CultOfMac FeedsPortal), and if I use uBlock I can bypass it quick enough to read that feed and be on my way. uBlock also trashes the exception quite quickly, whereas I often accumulate temp rules throughout the day/week if visiting one-off sites, and I sometimes make them permanent (I review the uncommitted rules, and if I will use a site frequently I allow it, and purge the rest).

On uMatrix you simply get a page blocked, with no op page options, and would have to make a temporary rule to unblock that domain/hostname, and view later. I figure that advanced users would know to do that, but it would be more convenient to have the same mechanism as uBlock, and have those temp rules purged quickly as uBlock does.

It is rare, but sometimes I do also find false-positives in the HOSTS files from time to time, but I like enabling them as they sort of act as a failsafe to me if I inadvertently allowed a domain on a site in the process of configuring.

**Comment by gorhill** [comment]
I didn't see the point of a temporary bypass, because even if one allows the root document to bypass matrix filtering, all the secondary resources for the site will be blocked, which means in all likelihood the page would be severely broken, which means one will have to play with the matrix anyways, hence no real time saving.

So this led to me wondering whether I offer to remove the block rule from the temporary ruleset, and then thinking about all the consequences, I figured this was to complications over complications (code-wise and UI-wise), so simplest solution in the end is to simply let the user remove the block rule.

**Comment by CODYQX4** [comment]
True, although in the case of redirect feed sites, that basically just redirect you server side, it in that case really isn't relevant in the case of the Matrix.

I usually get caught up on this on things like that, when content is locked behind such a technique and I have no way to bypass it.

MacUpdate is notorious for click throughs solely to track clicks.

**Comment by gorhill** [comment]
True, server-side redirects is a case where a one-time bypass would be useful -- grant passage, without cancelling a block rule from one of the hosts file. Ok, I will offer the choice for a one-time by pass (this won't modify the ruleset at all).

**Comment by berrythesoftwarecodeprogrammar** [comment]
possibly unrelated, but how about adding the little magnifying glass to show all of the url params too? didnt know it existed til i saw https://github.com/gorhill/uBlock/issues/973 but it seems to be uBlock only

**Comment by Ineluctable** [comment]
This would be really useful to have. The current process isn't too hard - 3 clicks to open the UI, whitelist, and reload compared to uMatrix's 1 click - but sometimes they chain multiple redirects sites together which can be a pain.

**Comment by rainbowdesign** [comment]
This is from may 2015 so nearly a year old when will it come?

**Comment by gorhill** [comment]
- Click the uMatrix icon while on the blocked-document page
- Remove the block rule for the site
- Force a refresh

> when will it come?

It's not a showstopper, workaround is above.

**Comment by rainbowdesign** [comment]
Oh i found which rule to remove i did not recognize it because in that field there is no item (cookie, script)... Its just not easy to see how to do this

**Comment by gorhill** [comment]
The page is blocked because the whole domain is blocked. It's just a matter of removing the block rule for the whole domain:

![a](https://cloud.githubusercontent.com/assets/585534/13433560/59732722-dfa0-11e5-9bf7-f774a52de286.png)

**Comment by rainbowdesign** [comment]
Add the explanation and the screen to the the error message an i would consider the issue resolved ;)

**Comment by hydroid7** [comment]
What about this box? It gives a hint for the normal user, who just want to visit the PlayStore.

![umatrix](https://cloud.githubusercontent.com/assets/16509320/17677208/0c2cf2c0-6332-11e6-9c3c-a67bd6bd5e79.png)


Here is the source code of the main-blocked.html. Since Github doesn't support *.html files, its a txt.
[main-blocked.txt](https://github.com/gorhill/uMatrix/files/418817/main-blocked.txt)

**Comment by qwertier** [comment]
> I didn't see the point of a temporary bypass, because even if one allows the root document to bypass matrix filtering, all the secondary resources for the site will be blocked, which means in all likelihood the page would be severely broken, which means one will have to play with the matrix anyways, hence no real time saving.

I don't see any broken pages in my case. As for this [example](https://sematext.com/blog/2016/09/13/logstash-alternatives) there's no any rules which need user's interaction in uMatrix popup window! 

I see two solutions to make users happy:
* Enable the domain for fixed time (domain is an address with all the "secondary resources")
* Enable the domain *only* for this page (better solution)

**Comment by dubitably** [comment]
Throwing in my own two cents, it took me quite a while to figure out that the row headers on the matrix doubled as a default value setters for the columns and as toggles for requests to the domains themselves. Maybe the best solution to this issue involves a little reworking of the matrix UI, either an extra column, or some extra toggle, or something?

**Comment by gorhill** [comment]
Closing -- Turns out I just won't spend time on this, like everything else, the matrix is where thing are worked on.
