### ISSUE TITLE
Recipes - Missing?

### ISSUE THREAD

**Issue by RobotCaleb** [gorhill/uMatrix#204]
I'm a big fan of the recipes in HTTPSB. Setting a site to allow everything needed for youtube embeds to work is great in one go, instead of having to set one script to be allowed, refresh the page, set a frame to be allowed, refresh the page, set a new domain to be allowed, etc.

Any chance of the recipes being brought back?

Thanks for your hard work on this.

**Comment by gorhill** [comment]
Duplicate of #30.

**Comment by RobotCaleb** [comment]
Thanks. I searched recipes, but not preset. I missed that issue.
