### ISSUE TITLE
[Firefox] Google Maps doesn't work correctly

### ISSUE THREAD

**Issue by Faberman** [gorhill/uMatrix#205]
`Firefox 37.0.2` and `uMatrix 0.9.0.1`. I don't have this issue in Chrome.

All behind-the-scene requests are allowed, all "intercepted" requests are allowed as well. There are no more requests in matrix after a few reloads. Also there aren't any blocked requests in logger. However, [Google Maps](https://www.google.com/maps) can't load properly — there are no map controls and search doesn't work.

![enter image description here](http://i.imgur.com/7ml5ajs.png)

After disabling matrix filtering for Google Maps everything works fine. And it turns out there are far more requests.

![enter image description here](http://i.imgur.com/DX0oMIL.png)

**Comment by gorhill** [comment]
I am unable to reproduce, all my cells were properly filled, especially the highest-count `mt0.google.com xhr`, which is empty in your picture.

**Comment by gorhill** [comment]
Bu the way, the link in your first picture is `https://www.google.co.uk/maps?source=tldso`. If I enter that link, I am always automatically redirected to `https://www.google.co.uk/maps/@53.800651,-4.064941,6z`.

**Comment by gorhill** [comment]
Ok, I finally was able to reproduce, not sure what I did.

Investigating, and using the Firefox network request tool, there was nothing in there which was not reported in the matrix.

**Comment by gorhill** [comment]
Ok, to reproduce:

1. Open new tab
2. Do not allow `frame` for `www.google.co.uk`
3. Go to `https://www.google.co.uk/maps?source=tldso`

The `xhr` cell for `mt0.google.com` won't be filled.

**Comment by gorhill** [comment]
So the issue is that in Firefox, the content scripts execute earlier than in Chromium, thus preventing some embedded frames in there from working properly.

For some reasons, that `iframe` element, placed directly after the `body` element, does not exist with Chromium.
