### ISSUE TITLE
Block 1st-party by default

### ISSUE THREAD

**Issue by temporarium** [gorhill/uMatrix#206]
1st-party stuff seems to be enabled by default - green across the board. Am I correct? What if I wish to block all scripts and cookies on first party domains by default. How do I accomplish that?

**Comment by Havokdan** [comment]
Remove rules (maybe chango allow to deny):
* 1st-party * allow
* 1st-party frame allow

**Comment by gorhill** [comment]
> What if I wish to block all scripts and cookies on first party domains by default

    * 1st-party cookie block
    * 1st-party script block
