### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by AsukaLangleyfag** [gorhill/uMatrix#210]
I got a strange bug on FF41.0.1a/Win10 with all versions of uMatrix: on some sites it makes Firefox unusable.
How to reproduce:
1. http://build.antergos.com/browse/release with default settings of uBlock

**Comment by gorhill** [comment]
- You are not explaining at all what is the "strange bug"
- You provide a URL with no explanation of what is the point of the URL

**Comment by AsukaLangleyfag** [comment]
Well, seems like the problem was in how uBlock dims blocked frames, it makes my firefox not responding.

**Comment by gorhill** [comment]
So it's a uBlock issue, not a uMatrix one? This issue tracker is for uMatrix.

uBlock doesn't dim blocked frames, it collapses them or leave them alone.

For the URL you provided, there was not a single frame blocked using default settings.

**Comment by AsukaLangleyfag** [comment]
I misstype, uMatrix of course. 
![2015-05-16 17_51_53-program manager](https://cloud.githubusercontent.com/assets/8681532/7666188/6e465326-fbf4-11e4-8ae8-b6f47a1492f3.png)
After this my firefox became not responding. Sometimes it does, but sometimes it doesn't.

**Comment by gorhill** [comment]
Using uMatrix with same set of rules as seen in your pic, I can't reproduce the reported "non-responsiveness", no matter how often I refreshed the page. I am completely trusting that when you say "default settings", it is really default settings.

- What other extensions do you have enabled for that test case?
- You didn't provide the version of your uMatrix, so I am assuming your are using 0.9.0.2-dev.3.

The only peculiarity I see on that page is that it sends a `xhr` request every 10 seconds -- nothing which can cause any problem.

Check your logger output, see if there is something out of the ordinary in it.

**Comment by AsukaLangleyfag** [comment]
lots of "Error in parsing value for 'background-image'.  Declaration dropped." by build.antergos.com/static/css/skin-blue.css
and lot of errors from build.antergos.com/static/js/bootstrap/dist/css/bootstrap.css too.

**Comment by gorhill** [comment]
I don't get any such error. This has nothing to do with uMatrix, uMatrix does not change the content of pulled resource, and those errors indicate the content of some `css` files is broken.

**Comment by AsukaLangleyfag** [comment]
Thank you for your time. So, as it's not a uMatrix bug - closed.
