### ISSUE TITLE
Fanboy Adblock filters issue

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#213]
Can µMatrix work with filters from https://fanboy.co.nz/ ? After adding those filters, I don't see any of them applied to µMatrix scope. That's the reason why I can't completely replace µBlock with µMatrix.

**Comment by hotdogman** [comment]
>Can µMatrix work with filters from https://fanboy.co.nz/ ? 
The filters on https://fanboy.co.nz are for Adblock Plus. uMatrix supports host files, not ABP filterlists.
>That's the reason why I can't completely replace µBlock with µMatrix.
Use both of them.

>https://github.com/gorhill/httpswitchboard
>Important: No longer developed. Project has been split into two distinct, more advanced extensions: uBlock Origin and uMatrix.
HTTPSwitchboard originally had support for ABP filters, but it was then split in to two different projects, so people who want matrix/scope filtering can have matrix filtering, and people who only want an adblocker can have "just an adblocker."

**Comment by gorhill** [comment]
You can use only plain list of hostnames. If you feed it anything else, results are undefined, probably all messed up internally. I need to write some code to prevent obvious non-sensical hostnames from being used.

**Comment by mtu346** [comment]
Thanks.

**Comment by mtu346** [comment]
By the way, please update the extension on Opera store. It's still at version 0.8.1.4.

**Comment by gorhill** [comment]
In the end, garbage in-garbage out. "Hosts files" is clearly stated, and I expected advanced users to understand this.
