### ISSUE TITLE
uMatrix doesn't work at all with pinned tabs

### ISSUE THREAD

**Issue by 5t3f4n** [gorhill/uMatrix#214]
Upon launching Firefox, pinned tabs will load without uMatrix intervening whatsoever. Hostnames, scripts and any other objects that should normally be blocked are simply not. Everything appear whitelisted by default.

Steps to reproduce:
- Load any website that has content which should be blocked according to your rules
  - For example http://www.nytimes.com/
- Right-click the tab
  - Pin Tab
- Quit Firefox
- Launch Firefox
- Any script/content from any hostname is loaded

Ways to confirm:
- Content you know should be blocked is visible on the website
- The uMatrix popup displays all cells in light green
- The uMatrix logger shows all content as loaded and none as blocked

`uMatrix 0.9.0.1`
`Firefox 38.0.1`
`OS X 10.10.3 (14D136)`

**Comment by 5t3f4n** [comment]
Screenshot showing scripts, frames and everything that should be blocked being loaded from hostnames that shouldn't even be loaded at all. Also notice the scrollbar.

![uMatrix](https://i.imgur.com/VaBwNjv.png)

**Comment by gorhill** [comment]
Can you reproduce with 0.9.0.2-dev.4 as well?

**Comment by 5t3f4n** [comment]
Can't seem to reproduce using `0.9.0.2-dev.4`. What has been changed related to this that fixes it?

![uMatrix](https://i.imgur.com/PSWWKcI.png)

**Comment by gorhill** [comment]
> What has been changed related to this that fixes it?

#189.

**Comment by gorhill** [comment]
Will assume #189 fixed this.
