### ISSUE TITLE
[Firefox] Unexpected behavior with strict HTTPS switch

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uMatrix#216]
1) Visit https://openuserjs.org/ or any page with mixed content with uMatrix (0.9.1.0) filtering disabled
![umatrix-firefox-scope-disabled-strict-https](https://cloud.githubusercontent.com/assets/9421932/7716747/37155f56-fe4b-11e4-9275-505058946bba.png)
2) Strict HTTPS enabled
3) Mixed content is still allowed

User agent spoofing is also enabled and working fine with filtering disabled.

Behaves as expected in Chrome with the same setup, no mixed content is allowed.

edit: apparently there's more than meets the eye here; results are different if I block/allow scripts.

**Comment by gorhill** [comment]
What is unexpected?

With Strict HTTPS enabled, I tried your URL, <https://openuserjs.org/>, and I saw only connections to `https://`.

With Strict HTTPS disabled, for the same URL I saw conenctions to `http://` in there.

Works as expected.

**Comment by gorhill** [comment]
Also please, always browser version. Could you describe in details me how you came to the conclusion that non-HTTPS connection occurred with Strict HTTPS?

**Comment by CrisBRM** [comment]
FF 40 (aurora) here, cannot replicate this issue.
Disabled security.mixed_content.block_display_content in about:config, and toggled the mixed content switch off: 31 requests (25 https requests, 6 images fetched from http sources); turned it back on: 25 https requests.

**Comment by luxoflux** [comment]
- With `security.mixed_content.block_display_content` set to true, insecure items are blocked: `Blocked loading mixed display content ...`

- When set to false and using only uMatrix to control it, I get `Loading mixed (insecure) display content ... on a secure page`.

I'm on v38.0.1.

**Comment by gorhill** [comment]
> I get Loading mixed (insecure) display content ... on a secure page

Show me the Firefox log showing that non-`https` content is actually loaded.

**Comment by luxoflux** [comment]
With uMatrix handling it:
![without-display-content-block](https://cloud.githubusercontent.com/assets/9421932/7718966/cfbbaa2c-fe6d-11e4-9ed0-3f432b33a8a6.png)
With manual mixed display content block:
![with-display-content-block](https://cloud.githubusercontent.com/assets/9421932/7718972/ecfc3692-fe6d-11e4-8ab9-0ae16c49a9c4.png)

**Comment by gorhill** [comment]
Use the browser console instead, <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-J.

The warnings above do not show up in the browser console, neither in the _Network_ pane of the dev console for the page. Those warning do no seem reliable, it might be Firefox detecting the mixed content **before** uMatrix processes them. It's all blocked fine.

**Comment by luxoflux** [comment]
> Those warning do not seem reliable, it might be Firefox detecting the mixed content before uMatrix processes them. It's blocked all fine. [...] nowhere is there a matching GET

That's exactly what it is. I feel like an idiot now for not seeing that.

Maybe that can be explained in the Wiki though, because I expected to see a nice, reassuring padlock icon for a fully https page. Although, now that I think about it, in a way it can be a good thing to see the warning icon in the address bar, just so you know what the page is trying to load.
