### ISSUE TITLE
uMatrix not blocking network requests it is supposed to block

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#217]
I have used the latest version of uMatrix, 0.9.1.0.
When I was browsing thespiritscience.net (http://thespiritscience.net/2015/05/11/a-science-icon-died-17-years-ago-in-his-last-interview-he-made-a-warning-that-gives-me-goosebumps/), I noticed that these two domains font.googleapis.com and font.gstatic.com was shown to be blocked as third-parties on uMatrix scope, but in uMatrix log they were allowed. I checked the browser events to make sure, this was confirmed. Is there something wrong? Or did I miss something?
I'm currently using Opera 29.

**Comment by gorhill** [comment]
Please, show me a screenshot of the matrix where this occurs, and a screenshot of the log entries.

Confirmed to work all fine with Chromium.

**Comment by 5t3f4n** [comment]
Are you referring to the .woff files?
CSS is whitelisted by default in uMatrix and I believe that means those will automatically be allowed.

**Comment by gorhill** [comment]
User deleted his github account, so will never get feedback about this. The issue reported is most certainly just user confusion, uMatrix has been stable since months now, and there are no other reported issues of "something which should be blocked which is not blocked".
