### ISSUE TITLE
Latest version of umatrix blocks all scripts

### ISSUE THREAD

**Issue by ikeboy** [gorhill/uMatrix#220]
Latest version of umatrix on chrome, from webstore, blocks everything. Autoupdated, I didn't change any settings, not sure why. Disabling umatrix makes the problem go away. Any recent changes may have caused this?

ubuntu 15.04, chrome 43.

**Comment by ikeboy** [comment]
This is how it looks for an example site (all sites break)


![](https://i.imgur.com/VHY7T5e.png)

**Comment by gorhill** [comment]
Looks like you are missing the `* * * allow` in your ruleset, so it falls back to the built-in rule, which is to block everything. By default uBlock ships with an explicit rule for `* * * block`, and it seems you removed it -- thus falling back on the built-in rule, which used to be "allow", while it is now "block".

**Comment by ikeboy** [comment]
So how should I fix this? It shouldn't change behavior like that, anyway.

**Comment by gorhill** [comment]
Add the rule `* * * allow` to your ruleset, as apparently you were working in allow all/block exceptionally mode.

**Comment by ikeboy** [comment]
That worked, thanks. Should the default be changed (umatrix should automatically add that rule if it doesn't exist upon this update?)

**Comment by gorhill** [comment]
If I were to create a root rule by default if none is present, it would be `* * * block` anyways, that's the one present in a new install of uMatrix -- this did not change. So you would end up with the same issue. Just be sure to never remove your root rule, so that it can not be overriden.

**Comment by ikeboy** [comment]
>If I were to create a root rule by default if none is present, it would be * * * block anyways, that's the one present in a new install of uMatrix -- this did not change. So you would end up with the same issue. Just be sure to never remove your root rule, so that it can not be overriden.

I still think the rule should be added when updating. If I'd seen * * * block in my rules, I'd have removed it and not filed an issue. So someone who checks their rules should be able to tell that default behavior has changed.
