### ISSUE TITLE
Corrupted matrix...

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#222]
First time I've seen this. uMatrix 9.1.1/firefox 38.0.1

![Imgur](http://i.imgur.com/cJMC42c.jpg)

**Comment by gorhill** [comment]
Was it after launching the browser? Looks like #56.

**Comment by gorhill** [comment]
What is corrupted?

**Comment by gorhill** [comment]
I am going to guess you refer to the long hostname, duplicate of #182.

**Comment by 5t3f4n** [comment]
The problem goes away if you collapse the hostnames (thus truncating the long ones) so gorhill's guess is probably accurate.

![uMatrix](https://i.imgur.com/Wx9RMbR.gif)

**Comment by SergeiShir** [comment]
New user of uMatrix
Noticed the same cosmetic issue
![example](https://cloud.githubusercontent.com/assets/17823400/19017316/f947e940-883d-11e6-8a70-2c4ddbc8e62d.png)
