### ISSUE TITLE
Feature request: Icecat compatibility

### ISSUE THREAD

**Issue by anschch** [gorhill/uMatrix#223]
Is there any specific reason uMatrix seems to be incompatible with Icecat or is it just a default because no "allow Icecat" code is in the code of uMatrix? uBlock Origin works perfectly in Icecat. (Icecat is a rebranding of Firefox by GNU.)

More specifically I get this: "uMatrix could not be installed because it is not compatible with Icecat 31.6.0" when installing manually from https://github.com/gorhill/uMatrix/releases
It have also happened on previous versions of Icecat when I have tried installing it. (I don't remember what exact version numbers.)

**Comment by Snapy** [comment]
It's normal. gorhill recently changed the minimum Firefox version to 35.0 because of #200 ([commit related] (/gorhill/uMatrix/commit/1aa8b4fc1e7b2e7a87d8c53da2da34de31f9f632)). I know Icecat follows Firefox ESR for its releases so when it will be on ESR 38 everything should be fine

**Comment by gorhill** [comment]
I could bring support for FF 29 and up to uMatrix, but as usual, this would require some work and at some point it's just a matter of time and if the time invested benefit more than just a handful of users.

**Comment by anschch** [comment]
I see. I had no idea about Firefox ESR, but it makes more sense now. In that case Icecat should be on ESR 38 soon I guess, since that should be the next release or the one after that.

Apologies if this was filed in the wrong place. Is there a better place for questions like this, since it's not a bug per se?

And thanks for your hard work gorhill, I couldn't live without uBlock Origin. :)

**Comment by Snapy** [comment]
You can still use an older version if it's not too buggy.

**Comment by anschch** [comment]
Well, now I feel stupid. Should have thought of that. Thanks!
