### ISSUE TITLE
Suuport for pre-australis firefox 28.0 / palemoon

### ISSUE THREAD

**Issue by coniptor** [gorhill/uMatrix#224]
I am a hold out and as such I cannot benefit from uMatrix currently because I am not upgrading beyond Firefox 28.
Could you please add support for the UI elements in pre-australis firefox. I think that alone would cover Palemoon as well. Thank you so much for the awesome work and extensions. It's over my head right now.

**Comment by gorhill** [comment]
I don't have the manpower for this. Best is for another developer to provide the work. And this will have to go in its own branch, or worked out as a fork.

**Comment by TheLoneWolfling** [comment]
Also a Pale Moon person, also want to run uMatrix, but cannot due to incompatibility.

Too bad you don't have the manpower.

**Comment by ParticleMon** [comment]
@gorhill I'm sorry you don't have the manpower for this--would a donation help?! :)

If not you, then hopefully someone will step up to the challenge. Pale Moon is my browser of choice, and apparently others' too.

I appreciate your high-quality work and attention to under-the-hood improvements. I'm grateful that you included legacy Firefox support in uBlock, and so I await the same for uMatrix, which I use in Chromium and Firefox. But it seems odd that adding pre-Australis support isn't as straight-forward as it was for uBlock.

**Comment by bael0r** [comment]
@ParticleMon ```it seems odd that adding pre-Australis support isn't as straight-forward as it was for uBlock.```

That work was done by @AlexVallat and was [imported in 0.9.9.2](https://github.com/gorhill/uBlock/issues/264). If you would like to see support for Pre-Australis versions of Firefox, how about reviewing Mr Vallat's changes and see how "straight-forward" it is?

**Comment by gorhill** [comment]
I could import @AlexVallat work into uMatrix. The current issue is that even FF 34 and less is not supported, it's less an Australis issue than a an issue of reliable associating a tab id with a network request/ I did use code as suggested in FF doc, just to find out that this code does not work in pre-FF 35.

**Comment by gorhill** [comment]
Fixed with 1f4ba9dda90cee7c0afb0dbbb23d537ed0425220.

**Comment by LimboSlam** [comment]
@gorhill, all is good. Thanks for implementing the pre-australis/Pale Moon code into uMatrix and ublock origin. Also when you get the chance, come around our forums and see how much we appreciate your hard work towards these powerful and handy tools.  
 
-Pale Moon Users and Devs/Admins.  :+1:

**Comment by TheLoneWolfling** [comment]
Thank you very much!

**Comment by gorhill** [comment]
@LimboSlam So both latest release of uBlock Origin/uMatrix support explicitly Pale Moon (through Pale Moon GUID), and I have summarily tested that they both work fine on Pale Moon 26 beta. Should then these added to Pale Moon's collection of add-ons? If you think so, could you take care of this? If so, the latest stable `xpi` version in the release section should be used.

**Comment by LimboSlam** [comment]
@gorhill Both installed and functioned well under our own GUID, so yes as far as I can tell. The adding to our store I'm not sure because I wouldn't be the guy for this with my little knowledge of coding/programing, that and I don't want to yes to something that's above my authority here. Though I'm sure if you contact one our add-on devs/devs (Moonchild, Matt A Tobin) they could answer your question. You can do this through our forum (need to sign up first) as a private message or public notice and here at github.

**Comment by LimboSlam** [comment]
@gorhill I went ahead and contacted MC and he's ok with this, but to clarify, Matt A Tobin is the lead dev on this so you will have to talk to him directly on this, ok. 

Anyways here's our exact conversation: 
 "I'm perfectly fine with it being listed on APMO directly as a download, also hosted by us if desired. Tobin is in charge of these updates, though, and the system that's currently in place to add/update extensions and serve updates to Pale Moon users. uMatrix and uBlock are more than welcome as additions."  :)

**Comment by LimboSlam** [comment]
resource://jid0-9xfbwuwnvpx4wwsfbwmcm4jj69e-at-jetpack/self-destructing-cookies/data/introduction.html
