### ISSUE TITLE
[Firefox] Logger tab selector titles not updating

### ISSUE THREAD

**Issue by quilloss** [gorhill/uMatrix#225]
# Details
Firefox 38 - New profile
uMatrix 0.9.1.1 - Default settings

# Steps to reproduce
1. Have the logger open
2. In another tab navigate to a page (eg. https://github.com/gorhill/uMatrix)
3. Switch to the logger (before the page completely load?)
4. Check the tab selector

# Issue
The title of the tab is not updated. It is either stuck at `Connecting..` or the previous page title.
It could be reliably reproduced if the step 3 and 4 is done quickly, but sometimes it happens anyways long after the page has completely loaded.

#### Image of logger a minute after all pages have loaded:
![issue](https://cloud.githubusercontent.com/assets/8151080/7790218/2f8a4f2e-02b2-11e5-9535-bccfa8ea560a.png)

**Comment by requiredregistration** [comment]
i was planning to create an issue for this

**Comment by 5t3f4n** [comment]
Same issue here.

`uMatrix 0.9.1.1`
`Firefox 38.0.1`
`OS X 10.10.3 (14D136)`

**Comment by Radagast** [comment]
More of the same. According to fx the tabs have finished loading...

![Imgur](http://i.imgur.com/WhgYfmy.jpg)
