### ISSUE TITLE
Use reverse DNS lookup when pages make requests by IP address

### ISSUE THREAD

**Issue by fragmer** [gorhill/uMatrix#226]
I've been running into cases (e.g. any time [JW Player](http://www.jwplayer.com/products/jwplayer/) is used on web pages) where requests are made to often-changing IP addresses, which often refer to CDN endpoints. For example, player on [http://cinemassacre.com/2015/05/25/mario-kart-64-nintendo-64-james-mike-mondays/](cinemassacre.com) can make requests to 174.127.86.19, 206.217.201.111, or 174.127.103.127. Running reverse-DNS queries on these IPs reveals that they all point to subdomains of "static.midphase.com". However, because uMatrix uses IP addresses, I have to whitelist them individually.

If uMatrix could perform reverse-DNS lookup and apply filters on the resulting domain, my life would be a bit easier! :)

**Comment by gorhill** [comment]
uMatrix has to evaluate network requests while the browser is waiting for an answer -- it's a blocking operation -- and this must be performed as fast as possible.  What you suggest does not fit into this. What would help is fixing #122.
