### ISSUE TITLE
Incompatibility with Vimperator

### ISSUE THREAD

**Issue by b-rodrigues** [gorhill/uMatrix#228]
uMatrix does not open when using Vimperator. The only way to make it work is by having the navigaton bar visible. As soon as the navigation bar is not visible, clicking the uMatrix button doesn't do anything.

**Comment by gorhill** [comment]
Related: https://github.com/gorhill/uBlock/issues/112.

**Comment by gorhill** [comment]
Meanwhile, someone [here](https://github.com/gorhill/uBlock/issues/112#issuecomment-95848638) suggested a workaround:

> Fix 1 (As a userstyle or in userChrome.css)
> 
>     #nav-bar {
>         height: 0;
>         overflow: hidden;
>         visibility: hidden;
>     }
>     
>     #nav-bar * {
>         visibility: visible;
>     }
> 
> /* Blacklist the known nav-bar children */
> #nav-bar-customization-target, #PanelUI-button, #window-controls, #nav-bar-overflow-buton {
>     display: none;
> }
> 
> Fix 2 (Requires Pentadactly, code below goes in .pentadactylrc)
> 
>     style -name ublick * #nav-bar * { visibility: visible; }

**Comment by b-rodrigues** [comment]
That second Fix works great with Vimperator also!

**Comment by Raziel-23** [comment]
I had the same problem and here #288 is a proper solution.
