### ISSUE TITLE
uMatrix in Firefox seems to break Self-Destructing Cookies

### ISSUE THREAD

**Issue by tYYGH** [gorhill/uMatrix#230]
Self-Destructing Cookies destroys cookies that are not used anymore by currently opened tabs. For example, 10 seconds after I close the github.com tabs, all cookies pertaining to GitHub should be destroyed.
With uMatrix installed, days later, my cookies are still there. It seems that uMatrix keeps S-D C from doing its job. Please allow both extensions to play fine with each other :-) Because they are a perfect combination.

**Comment by gorhill** [comment]
If SDC doesn't do its job,. please file an issue with SDC. uMatrix merely uses Firefox APIs to do it's job.

**Comment by tYYGH** [comment]
Hi, you were right to close this. I did some additional tests (among those are disabling uMatrix and reverting to some better known extensions combinations), and it seems to be rather some altered behaviour since Firefox 38.
So it is unrelated to uMatrix after all. My apologies for not testing this before. Keep up the good work. I find uMatrix much more enjoyable to use than requestpolicy!
