### ISSUE TITLE
[Firefox] Frame blocking

### ISSUE THREAD

**Issue by Blutgang** [gorhill/uMatrix#231]
`Firefox 38.0.1` + `uMatrix 0.9.1.1` blocks the frame on this page (http://maplestory.nexon.net/community/#\%2Fshowthread.php\%3F1427862-NOTICE-Update-Compensation-for-Change-to-Maple-Leaf-Conversion-Rate\%26p\%3D11801990\%23post11801990) even though I allow frames on `nexon.net`. `Chrome 42.0.2311.152` + `uMatrix 0.9.1.1` does not block the frame with the same rules as on Firefox.

Rules:
```
matrix-off: opera-scheme true
* * * block
* * css allow
* * frame block
* * image allow
nexon.net ajax.googleapis.com script allow
nexon.net nexon.net cookie allow
nexon.net nexon.net frame allow
nexon.net nexon.net script allow
nexon.net nexon.net xhr allow
nexon.net nxcache.nexon.net other allow
nexon.net s3.amazonaws.com script allow
```

`Firefox 38.0.1` logger
![ffx frame](https://cloud.githubusercontent.com/assets/4369039/7844737/7f8ec386-0480-11e5-840d-3ae0cf12a45a.png)

`Chrome 42.0.2311.152` logger
![chrome frame](https://cloud.githubusercontent.com/assets/4369039/7844742/9325b54e-0480-11e5-82d2-965b7a015bc4.png)

Observation: The logger shows a slightly different url on Chrome.
Firefox: `http://forum2.nexon.net\/` 
Chrome: `http://forum2.nexon.net//`

**Comment by gorhill** [comment]
The site has a bug, it uses an invalid URL: `http://forum2.nexon.net\/[...]`.

Now on Firefox, uBlock makes use of the native URI parsing, and Firefox returns a hostname which is `forum2.nexon.net\`, while on Chromium there is a custom regex-based parser, where the extracted host is `forum2.nexon.net`. Chromium URL parser is based on the regex found in [RFC 3576](http://tools.ietf.org/html/rfc3986#page-50).

Now which one is right/wrong between Firefox or the regex found in RFC 3576?

In any case, the site has a bug in its code, it's probably a very rare occurrence, and I won't make code change to uMatrix to address such an unlikely 3rd-party issue.
