### ISSUE TITLE
[Firefox] Blank page when searching on google with scripts blocked

### ISSUE THREAD

**Issue by Blutgang** [gorhill/uMatrix#232]
Rules:
```
matrix-off: opera-scheme true
* * * block
* * css allow
* * frame block
* * image allow
``` 

On `Firefox 38.0.1` + `uMatrix 0.9.1.1` go to `google.com` and type in `testing` for the search query. The page will momentarily flash (looks like a redirection) and the search results page will be blank (white page). Repeat the process on `Chrome 42.0.2311.152` + `uMatrix 0.9.1.1` and the end result is different (the search results actually show - not a blank page).

**Comment by mdln** [comment]
Loading the script on google.com is required, it seems google requires confirming which browser your using before displaying content (or rather, blocking the content if it doesn't detect Chrome and can't load the js asking the user to switch to Google search and/or use the browser).

Trying to spoof the UA had no impact im my experience. You could possibly download the script and use greasemonkey/etc to offer the same functionality, but this doesn't appear to be an issue with uMatrix.

**Comment by CrisBRM** [comment]
It's only a problem if you're using the search-as-you-type script (https://code.google.com/p/search-as-you-type/), which you can (and should) disable on google's settings.

**Comment by gorhill** [comment]
> Loading the script on google.com is required

I tested with NoScript and the page did not go blank.

I suspect this is caused the by uMAtrix's attempt to "revive" the `<noscript>` tags on the page (necessary because CSP directive to prevent scripting do not trigger the parsing of `noscript` tags). I have to find out if anythign has changed about this, this is very old code.

**Comment by my-password-is-password** [comment]
Inside the `<noscript>` theres this, `<style>table,div,span,p{display:none}</style>`.  Since the workaround for `<noscript>` was to use `<div>` it gets hidden too.  I think thats whats happening.

**Comment by AndrewKvalheim** [comment]
Sorry for the reference spam. I'll try to strip that out in the future.
