### ISSUE TITLE
matrix-off - root domain only??

### ISSUE THREAD

**Issue by dallas7** [gorhill/uMatrix#233]
Directives
matrix-off: specificDomain.com/onePageInThere true
matrix-off: specificDomain.com/oneOtherPageInThere/yetAnotherPage true
does the same as
matrix-off: specificDomain.com true
so, only a root domain is subject to the matrix directive?

Any ideas on how to "matrix-off" specific pages?

Thanks.

Windows 7x64 - Cyberfox64-portable 38.0.1 - uMatrix 0.9.1.1.

**Comment by gorhill** [comment]
Only hostnames, not URLs.
