### ISSUE TITLE
[Question, Firefox] Are uMatrix settings synced with Firefox Sync?

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uMatrix#236]
It's not an issue, but a question. I don't know where else to post to get answers about uMatrix.
I am using Firefox developer edition.

1. Are uMatrix settings synced with Firefox Sync? Including the rules?
2. If I Install uMatrix manually from github releases, will they be automatically updated to the next pre-release or full-release?

**Comment by Snapy** [comment]
@castor-troy The short answer is no but when it will be implemented it will be cross-platform.

**Comment by gorhill** [comment]
Duplicate of #66.
