### ISSUE TITLE
uMatrix facebook plugin likebox it is not blocked

### ISSUE THREAD

**Issue by hqxriven** [gorhill/uMatrix#239]
I've noticed that on Firefox 38.0.5, uMatrix 0.9.1.1 not block facebook plug-in in the site http://adrenaline.uol.com.br/forum/index.php

My rule

    matrix-off: about-scheme true
    matrix-off: behind-the-scene true
    matrix-off: chrome-extension-scheme true
    matrix-off: chrome-scheme true
    matrix-off: google.com true
    matrix-off: localhost true
    matrix-off: opera-scheme true
    * * * block
    * * css allow
    * * frame block
    * * image allow
    * 1st-party * allow
    * 1st-party frame allow
    adrenaline.uol.com.br www.facebook.com * block

Screenshot uMatrix 
![du1](https://cloud.githubusercontent.com/assets/12661256/7885928/1786b676-05fd-11e5-81e3-646299071377.jpg)

Screenshot uBlock

![du2](https://cloud.githubusercontent.com/assets/12661256/7885930/1e0f1d62-05fd-11e5-8258-cc25133cf06d.jpg)

**Comment by gorhill** [comment]
- uMatrix says: no connection to Facebook.
- Firefox network pane says: no connection to Facebook.
- _Copy Image Location_ for the thumbnail says: `http://adrenaline.uol.com.br/files/upload/usuarios/2014/redatores/joao_redator.jpg`

So no issue.

**Comment by hqxriven** [comment]
The uBlock eliminated the frame of the page and left the black background while the uMatrix not.

This is normal?

**Comment by hotdogman** [comment]
Just guessing, but look at your uMatrix settings, and then your uBlock settings.
In uBlock, is "Hide placeholders of blocked elements" enabled?
In uMatrix, is "Collapse placeholder of blocked elements" disabled?

**Comment by hqxriven** [comment]
Bull´s eye!

Thanks!
