### ISSUE TITLE
Firefox will soon allow only signed extensions in Stable and Beta channels

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#240]
More info [here](https://wiki.mozilla.org/Addons/Extension_Signing). The signing process is expected to be faster than reviews in Firefox AMO. I hope uMatrix will be signed soon. Do you plan to publish signed versions in [releases](https://github.com/gorhill/uMatrix/releases)?

**Comment by gorhill** [comment]
> Do you plan to publish signed versions in releases?

I will have to read about this if this can be done, and if so, how.

**Comment by CrisBRM** [comment]
>How do I get my add-ons signed if they are hosted on AMO?
>No action is required. We will automatically sign the latest reviewed versions of all add-ons currently hosted on AMO. You'll receive an email notification when this has been completed, and users will see that the add-on was updated. After the signature system goes live, all new versions will be signed automatically after they pass review.

>How do I get my add-ons signed if they are not hosted on AMO?
>You will need to create an AMO account and submit your add-on. There will be an option where you indicate the add-on isn't hosted on AMO, and you'll be able to submit your add-on files without having them published on the site.

Mozilla's wiki.

**Comment by anewuser** [comment]
uBlock Origin is already signed: https://addons.mozilla.org/firefox/addon/ublock-origin/

**Comment by robertleeblairjr** [comment]
The uMatrix releases up to version 1.0.0 are still not signed so that users can install them on the latest stable channel of Firefox. Will there be plans to sign the latest uMatrix, version 1.0.0, so that it can be installed on Firefox version 52+?

**Comment by gorhill** [comment]
Install from there please: <https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/beta>.

**Comment by robertleeblairjr** [comment]
I just came across the feature to add an extension via the development version section on the Firefox extension page for uMatrix, which I must have overlooked previously. I was just recently able to install uMatrix version 0.9.9b12 with Firefox version 52.0.2. No reports of any problems, thus far. Thanks for the reply and assistance.

**Comment by robertleeblairjr** [comment]
It would be nice if Mozilla would implement an automatic reporting feature to extension/add-on developers, similar to the Firefox crash reporter, and/or performance/usage reports to aid them with improving the product. Perhaps, this is available and I'm unaware of it.
