### ISSUE TITLE
Disconnect Filter Lists (Not an Issue)

### ISSUE THREAD

**Issue by puff-m-d** [gorhill/uMatrix#242]
Hello,

This is not an issue but just a question regarding the Disconnect filter lists that were added to uBlock Origin's "3rd-party filters" list - https://github.com/gorhill/uBlock/commit/47e7405be9f6b52efd504949e7ee733930149fb4
Would these lists work just as well, if not better in uMatrix if I manually added them there? I am curious as well as others as some have asked about this over on Wilders Security - https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-50#post-2494878

**Comment by gorhill** [comment]
I was thinking about this earlier, to have them part of the set of host files available out of the box. I will have to confirm they really add value though, i.e. that most entries do not end up being duplicates of what is already in other hosts files.

**Comment by danieljl** [comment]
@gorhill Can you consider add uBlock's privacy lists (EasyPrivacy and Fanboy’s Enhanced Tracking List‎) to uMatrix as well? Thanks.
