### ISSUE TITLE
Comments are not saved

### ISSUE THREAD

**Issue by gqqnbig** [gorhill/uMatrix#243]
I open the control panel, go to my rules tag. Edit the rule and write 
\# my comment

Then click save. The comment disappears.

**Comment by gorhill** [comment]
By design. These rules are _first_ managed by uBlock through the UI - and everything which is not a valid rule will be discarded by uBlock. The _My rules_ panes is a secondary UI for convenience.

**Comment by gqqnbig** [comment]
Thanks for your timely reply. I read [Rules syntax](https://github.com/gorhill/uMatrix/wiki/Rules-syntax) wiki page, then I think comment is supported. If actually there is nowhere to write comment, you may revise the wiki page to avoid new users being misled.
