### ISSUE TITLE
Image downloads fail

### ISSUE THREAD

**Issue by mathew832** [gorhill/uMatrix#248]
Firefox version: 38.0.1
Umatrix version: 0.9.1.1 & 0.9.1.2

Issue: png and jpg images fail to download. Other times some filetypes fail to download when uMatrix is enabled and I get the error below as is the case when downloading from a videogame soundtrack site (khinsider):

![capture](https://cloud.githubusercontent.com/assets/12698938/7917451/1e449384-0850-11e5-895c-ec22449bbcf5.JPG)

Things tried: 
Allow all globally
Disabling all privacy options
Disabling all rules
Disabling all extensions

Extensions I use:

![capture](https://cloud.githubusercontent.com/assets/12698938/7916816/da5f5d1a-084b-11e5-9d5e-6516126009c7.JPG)

Resolution: Disabling uMatrix in addon options. Clicking the Power icon in the uMatrix menu doesn't fix it, I have to totally disable uMatrix and I can download images again.

Edit: Just tried a few previous releases. The latest release that works for me is 0.9.0.1 and the previous two before it worked also.

**Comment by gorhill** [comment]
Can you look in the logger to see what gets blocked and in which context?

**Comment by gorhill** [comment]
Probably related to this: [Why can't I save an image using contextual menu?](https://github.com/gorhill/httpswitchboard/wiki/Why-can't-I-save-an-image-using-contextual-menu%3F).

**Comment by CrisBRM** [comment]
You need to go to the behind-the-scenes matrix and whitelist "other".
Alternatively, add [code]behind-the-scene * other allow[/code] to the "My rules" panel.

**Comment by mathew832** [comment]
CrisBRM, that did it. Thanks. Also thanks gorhill for this fine extension. It's replaced no-script and adblock.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@gorhill maybe this can be closed?

i was just testing in the latest version if downloads still fail when `behind-the-scene * other` is blocked and it seems like they arent anymore. it seems like the context is set to the correct site. was there a fix for that?
