### ISSUE TITLE
[Feature Request?] Element Blocker

### ISSUE THREAD

**Issue by WernerCD** [gorhill/uMatrix#249]
With AdBlock, there was an extension that basically allowed one to block custom sections of a page:
    https://addons.mozilla.org/en-US/firefox/addon/elemhidehelper/

So, for example, with some slight work you could right click and block a div in a page called &quot;&lt;div class='swads'&gt;&quot;
    https://addons.cdn.mozilla.net/user-media/previews/full/11/11793.png?modified=1331247702

Does the ability exist, or could it be added to block sections of a website within uMatrix? Either I don't know how to do it (Documentation I don't see? or needs to be created?) or I'd like to know if it could be incorporated.

**Comment by gorhill** [comment]
> Does the ability exist

It exists in uBlock, not in uMatrix. uMatrix's purpose is to deal with network requests, not DOM elements.

**Comment by WernerCD** [comment]
Thanks for the reply.

Not sure if this will reopen this or not, but should the two (uBlock and
uMatrix) be run side-by-side, or would it be preferable to run one instead
of the other?

**Comment by gorhill** [comment]
> would it be preferable to run one instead of the other?

This is best answer by you. I don't know what level of blocking control you are seeking. For most people uBlock does provide plenty of control, as it is also able to act as a default-deny firewall. uMatrix is really for those who wants to be able to also block by classes of requests, not just according to their origin.

**Comment by WernerCD** [comment]
Thanks again for the reply (and again for the quick reply).

I definitely don't think I'll remove uMatrix at any point soon (I've been
using it for ages now) so I think I'll explore using both, as it looks like
that's where the signals my tin-foil hat catches suggests me to do.

I'll also explore the differences between the two approaches more than I
have previously as it seems like there are more differences between the two
products than I realized.

Chris
