### ISSUE TITLE
[Feature] Always list all parent domains

### ISSUE THREAD

**Issue by Zantier** [gorhill/uMatrix#250]
if anything was loaded from s3.eu-west-1.amazonaws.com, then instead of only listing:

s3-eu.west-1.amazonaws.com
![image](https://cloud.githubusercontent.com/assets/146909/7945544/5ec01c66-0969-11e5-8b0b-aa571a4c72cd.png)

it would be useful if the following were listed:

amazonaws.com
west-1.amazonaws.com
s3-eu.west-1.amazonaws.com
![image](https://cloud.githubusercontent.com/assets/146909/7945549/669e552e-0969-11e5-8c2f-d33d22c47414.png)

Sites will often load from variable subdomains within a domain, and it would be useful to be able to easily set permissions on the parent.

This could be set as an option, but I don't know that anybody would want it disabled.

**Comment by offhub** [comment]
s3-eu-west-1.amazonaws.com is listed as a suffix in the [Public Suffix List](https://publicsuffix.org/list/).

https://github.com/gorhill/uMatrix/issues/54#issuecomment-62480877
https://github.com/gorhill/uMatrix/issues/121#issuecomment-72319230
https://github.com/gorhill/uMatrix/issues/155#issuecomment-93024880

**Comment by Zantier** [comment]
Ah, I see. Thanks.
