### ISSUE TITLE
Blocked domain XHR POST request got through

### ISSUE THREAD

**Issue by woky** [gorhill/uMatrix#251]
Hi,

I noticed that while google-analytics.com GET requests are blocked, one POST request got through. The request has form payload with usual GA tracking stuff (site, ga account, ...) and the response is empty image/gif. In Wireshark, I could find the endpoint only by IP 173.194.44.69 (ham02s14-in-f5.1e100.net).

![umatrix-ga](https://cloud.githubusercontent.com/assets/620147/7966488/a681354c-0a24-11e5-9d31-c1f296b6f389.png)

**Comment by Snapy** [comment]
The size of the data transferred is 0 B so it's as good as blocked or am I missing something ?

**Comment by woky** [comment]
@Snapy No. The response size is 0B. The request contains same kind of payload that is in URL query part in GET requests to google-analytics.

**Comment by Snapy** [comment]
So just to be sure, there is no privacy issue. What is your point in reporting this ?

**Comment by gorhill** [comment]
> one POST request got through

Use the logger, you will find out it's a behind-the-scene request. You can block it if you enable matrix filtering for the behind-the-scene scope, like I do:

![c](https://cloud.githubusercontent.com/assets/585534/7969104/a6e2cc8e-0a02-11e5-9420-3e9d2220de5d.png)
