### ISSUE TITLE
Cookies getting through? 

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#252]
I'm sure this is a case of misunderstanding but can someone explain the situation here please. From what I can see, uMatrix is set to block cookies but, as can be seem from cookie manager, cookies are being set on the system...

![Imgur](http://i.imgur.com/QIja5gR.jpg)
![Imgur](http://i.imgur.com/EXmQVMK.jpg)

**Comment by 5t3f4n** [comment]
>Blacklisted cookies are not prevented by uMatrix from entering your browser. However they are prevented from leaving your browser, which is what really matters. Not blocking cookies before they enter your browser gives you the opportunity to be informed that a site tried to use cookies, and furthermore to inspect their contents if you wish.

>Once these blacklisted cookies have been accounted for by uMatrix, they can be removed from your browser if you wish so.

>Important note: Extensions can make web requests during the course of their normal operation. These requests can result in cookies being created in the browser. If the hostname from where a cookie originate is not whitelisted, the cookie will be removed from the browser by uMatrix if this option is checked. So be sure that the hostname(s) with which an extension communicate is whitelisted.

**Comment by gorhill** [comment]
> cookies are being set on the system

uMatrix does not prevent cookies from entering your browser (as quoted by @5t3f4n). Blacklisted cookies however will not leave your browser. From a server's point of view, the cookies are write-only, i.e. they can't be read back.

Stripping `Set-Cookie` headers would prevent uMatrix to report accurately all the cookies. A single cookie header can contain a whole lot of distinct cookies at once, and parsing these in JS makes no sense when the browser does it for free, especially that there are some special cases to deal with etc. Very early that was the approach used by HTTPSB, but this was really bad.

What you may want is to check the _"Delete blocked cookies"_ in the dashboard.

**Comment by ganego** [comment]
I would like to bring this up again. 
Using uMatrix 0.9.1.2 on FF Nightly 41.01a.

For me the cookies work as expected by issue opener:
If I have uMatrix enabled and go for example on www.focus.de only a cookie for the root domain will be created (as this is allowed in the matrix). 
If I disable uMatrix for this site there will be several 3rd partie cookies saved.
The option in uMatrix to delete blocked cookies is _disabled_.


And I also have a question regarding this feature - _if it would work as explained by the help text_:
1) If, for example, I go on a website that gives me a google.com 3rd party cookie, but it does not get deleted by uMatrix and I then go to google.com, will they be able to read that cookie?
2) If I have some legitimate google.com cookies (login or so) but on another website the google.com cookie wants to be saved as a 3rd party (tracking) cookie, and uMatrix is set up to delete blocked cookies, will uMatrix also delete my legitimate login cookie?

Thank you for all your work with uMatrix and uBlock Origin :)

**Comment by gorhill** [comment]
> 1) If, for example, I go on a website that gives me a google.com 3rd party cookie, but it does not get deleted by uMatrix and I then go to google.com, will they be able to read that cookie?

Yes, if `cookie` is not blacklisted on `google.com`, it will not be stripped from request headers.

> 2) If I have some legitimate google.com cookies (login or so) but on another website the google.com cookie wants to be saved as a 3rd party (tracking) cookie, and uMatrix is set up to delete blocked cookies, will uMatrix also delete my legitimate login cookie?

No. If a cookie is whitelisted anywhere, it will not be deleted. If in a specific scope a cookie is blacklisted, the outgoing `cookie` header will be stripped from requests made in that scope.
