### ISSUE TITLE
Using-uBlock-with-uMatrix site should be corrected ...

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#254]
The https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix site should be corrected, because ublock Origin CAN also block the root document.

**Comment by CrisBRM** [comment]
You can update it yourself...

**Comment by Alpengreis** [comment]
Ahh, ok, I see, thanks for the hint! But with MY "english" (is not my normal language) - maybe I'll give it a try :-)

**Comment by Alpengreis** [comment]
I have changed the site ...
