### ISSUE TITLE
"Make ALL temporary changes permanent" button

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#257]
Actual, we have the possibility to undo ALL temporary changes, so far so good.

Sometimes (often?), I make a change temporary only - over different sites. Then, after a such session, it would be good, if I could apply ALL these changes with ONE function (button) (to make it permanent), with no need to go first to the rule window.

So, it would be nice to have a "make ALL temporary changes permanent" button too.

**Comment by gorhill** [comment]
I think in such case the _Commit_  button in the _My rules_ pane is best suited for this. Blindly committing all temporary rules does not seem a good idea to me. Forcing users to do it from the _My rules_ pane will allow them to revise at the same time if all the temporary rules are worth committing. Also, the space left in the matrix toolbar is very precious, I want to keep it for future buttons for which it will make sense to put in there.

**Comment by Alpengreis** [comment]
Okay, I can understand this.
