### ISSUE TITLE
Chromium's Local Extension Settings

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#258]
1) update now
Now there's ~3MiB 000003.log in Local Extension Settings
2) add http://hosts-file.net/download/hosts.txt & parse & update now
Now there's ~7MiB 000005.ldb in Local Extension Settings
3) remove http://hosts-file.net/download/hosts.txt & parse & purge all caches & update now
Now there's ~7MiB 000005.ldb and 000004.log in Local Extension Settings
It seems that one of the file (my guess is 000005.ldb) is obsolete, it is also strange how database file changes from uncompressed *.log to compressed *.ldb. Isn't it better to always store compressed version, like in uBlock?

**Comment by gorhill** [comment]
uBlock uses the [`chrome.storage.local` API](https://developer.chrome.com/extensions/storage), and whatever the browser does behind that API is hidden from uBlock, and out of control of uBlock.

**Comment by mikhaelkh** [comment]
This issue is not about uBlock.

**Comment by gorhill** [comment]
> This issue is not about uBlock.

Sorry I did not notice it's uMatrix. Same answer anyways.
