### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by CrisBRM** [gorhill/uMatrix#259]
Troubleshooted by duplicating my profile folder and deleting uMatrix and uBlock's extension data (backed up both profiles and DID NOT restore them afterwards; this was done before FF was launched), and reinstalling them. This was done to rule out my prefs.js, and extension compatibility issues (https everywhere, https finder, and betterprivacy), which it did. 

Firefox: Aurora (40.0a2), e10s is disabled
uMatrix: 0.9.1.3
uBlock: 0.9.8.7

On uMatrix:
⋅⋅* Parse https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
⋅⋅* Hosts file is added to available list
⋅⋅* No filters are actually loaded (0 out of 0)
..* ~~Clicking on the hosts file gives you an empty text file chrome://umatrix/content/asset-viewer.html?url=https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt~~ Presumably because it takes time to load.

On uBlock:
..* Select _any_ of disconnect's hosts files
..* ~~None will load, and clicking on them will give you aforementioned text file~~ Presumably because it takes time to load.
(Conversely, other links will parse and load filters/hostnames properly)

I really don't know how to troubleshoot this minor annoyance, but it's worth noting that simply deleting the sql dbs in /extension-data (using the original, non duplicated profile) fixed it. Restoring it using the built-in feature broke it again (merely restoring the ruleset didn't break it), but fixed it on uBlock(???).
Could this have something to do with the recent sql code refactoring?

Disclaimer: I know github markdown doesn't work on issues.

**Comment by gorhill** [comment]
I will admit I don't understand the issue reported.

Is this an SQLite issue? You tried to copy the SQLite from one profile to another new one, and it didn't work?

**Comment by CrisBRM** [comment]
No. It simply refused to parse/load disconnect's hosts files for some unknown reason, but deleting the sqlite file and restoring ONLY the _rules_ (not the whole profile) fixed it.

... It's a very peculiar issue indeed, and serves no real purpose seeing as though it no longer haunts me.

**Comment by gorhill** [comment]
Did you copy the SQLite file while uBlock was running?

**Comment by CrisBRM** [comment]
No, I didn't do it manually, I used the restore button (I take it that generates the same SQLite file).
To delete the SQLite file, I closed the browser, deleted it, and then reopened it.

**Comment by gorhill** [comment]
> No filters are actually loaded (0 out of 0)

Is it possible the file did not download because it was blocked by some behind-the-scene rule?

**Comment by CrisBRM** [comment]
No, I restored my uMatrix rules before trying it again. I suppose that rules it out.
Doesn't uBlock come bundled with it though? Or does it fetch each list on demand before caching them?

**Comment by gorhill** [comment]
In uBlock it's an external stock list, meaning it appears in the built-in selection of filter lists, but the list itself is not in the package.

This kind of symptoms did occur to me in the past, and there are two possible explanations:

- A behind-the-scene rule blocks the fetching of the list.
    - Easily overlooked, and I got myself fooled exactly with the Disconnect filter lists when I tried them the 1st time in uMatrix.
    Even went to investigate the code until I realized my behind-the-scene matrix was blocking the Disconnect URLs.
- The remote server is transiently not available for whatever reason.

**Comment by CrisBRM** [comment]
You are right, it was a b-t-s request that I had overlooked. It appeared as an XHR request and I mistakenly thought it was going to be categorized as 'other'.
Nonetheles, shouldn't it throw a warning that the filter list wasn't successfully downloaded?

**Comment by gorhill** [comment]
> shouldn't it throw a warning that the filter list wasn't successfully downloaded

Yes, that would be helpful.
