### ISSUE TITLE
Missing option to approve bare domain of *.cloudfront.net

### ISSUE THREAD

**Issue by quinncomendant** [gorhill/uMatrix#264]
The site duolingo.com loads resources from CDNs with what appear to be randomized subdomains of cloudfront.net, e.g.:

* d37gvrvc0wt4s1.cloudfront.net
* d7mj4aqfscim2.cloudfront.net

uMatrix doesn't offer an option to allow *all* cloudfront.net domains. I can allow each of these subdomains, but later new subdomains are used and need to be allowed too.

In the meantime I've manually added a global rule to allow all subdomains of cloudfront.net:

    * cloudfront.net * allow

However, I think the uMatrix UI should permit allowing the bare domain, no?

![duolingo screenshot](http://i.imgur.com/nj7XHqQ.png)

EDIT: actually, I see this problem on github.com too: it loads resources from `avatars1.githubusercontent.com` and `avatars3.githubusercontent.com` but does not give me the option to allow the bare domain of `githubusercontent.com`:

![github screenshot](http://i.imgur.com/NpsgyBU.png)

**Comment by gorhill** [comment]
> I can allow each of these subdomains

These are not subdomains, they are base domains. uMatrix extract base domains as per the Public Suffix List ("PSL"), and the PSL says that `couldfront.net` is a public suffix, not a base domain. Same for `githubusercontent.com`.

See:
- #54
- #121
- #155
- #250

**Comment by quinncomendant** [comment]
Ok, that is logical. I can see how it is more secure to consider each base domain unique, since the content behind the domains is not under one authority. Blanket-allowing all of them would open a security gap. Thanks for the clear explanation.

**Comment by Bluscream** [comment]
I tried ```
* cloudfront.net * allow
* cloudfront.net script allow
* *.cloudfront.net * allow
```
but umatrix is still blocking all cloudfront scripts:

![](https://i.imgur.com/TH4fQkn.png)

**Comment by gorhill** [comment]
For the same reason a rule such `* com * allow` won't override the block rule `* hotjar.com * block` seen in your screenshot. Read the documentation please.

**Comment by Bluscream** [comment]
So i need to find which hosts file is blocking these and disable that?

**Comment by gorhill** [comment]
You should assume they are blocked by the hosts file for a good reason. Best is to just locally remove the block rule itself of whatever `[...].couldfront.net` server you found the site needs.

**Comment by Bluscream** [comment]
Well, there are a lot of websites using cloudfront scripts that break when they're blocked, when i try to "whitelist" them one by one my browser would probably crash. Why is there no simple regex support?
