### ISSUE TITLE
images blocked, but popup UI shows them as allowed

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uMatrix#266]
As said in the title,

### Steps to Reproduce
1. open umatrix request logger in tab 1
2. Enable strict https everywhere
3. goto below site in tab 2.
<code>https://paytm.com/shop/g/electronics/personal-care/trimmers?sort_new=1&brand=2573,2572&price=153,10999</code>
4. you will see images are not loaded!! Looking at request logger one can see requests are blocked from assetscdn.paytm.com. however matrixUI says otherwise.

As strict https switch is turned on for this site, the images are blocked. It took me a while to figure this out, since this is not logged anywhere and i completely forgot about these switches. 
        Is there any possibility to make some kind of improvement to request logger, to see why the request is blocked and matrix ui not to show as allowed as it was blocked 

Also, even if you whitelist the site, it will still be blocked. not sure if it was by design or not. 

##### Config
- Firefox v38.0.5
- uMatrix 0.9.3

![umatrix paytm](https://cloud.githubusercontent.com/assets/779630/8144729/41b4fac6-1209-11e5-9c4e-549b617b11e2.png)

**Comment by gorhill** [comment]
Strict HTTPS?

**Comment by harshanvn** [comment]
> Strict HTTPS?

Yes, the issue occurs with Strict HTTPS switch turned on.
As said in my earlier post, even when you whitelist a page, Strict HTTPS will continue to be active on that page (when it is enabled). Not sure if this is by design.

**Comment by gorhill** [comment]
> Not sure if this is by design

Yes it is. The matrix is separate from the switches, in UI and internally as well.

**Comment by harshanvn** [comment]
Ok Thanks. Now the things are clear to me.
