### ISSUE TITLE
OpenBSD: Not available for your platform

### ISSUE THREAD

**Issue by kevlar700** [gorhill/uMatrix#267]
The addon says not available for your platform. I guess because OpenBSD is not on a whitelist! I doubt that's correct and guess it would make much more sense to blacklist systems it won't run on, Android??

**Comment by gorhill** [comment]
> it would make much more sense to blacklist systems it won't run on, Android??

Yes it would make more sense. I guess I had to select "All platforms" in AMO, despite uMatrix not being compatible with Fennec... The Fennec GUID is not in `install.rdf` anyways. Not sure how this would work, I wouldn't want Android users to end up downloading something that won't work on Firefox Mobile.

**Comment by LifeIsStrange** [comment]
It will be wonderful that you adds support for Fennec (Firefox on Android)

**Comment by TeddStriker** [comment]
@LifeIsStrange You can get uBlock0 for Fennec, if you manually download the latest .xpi from the release page [here](https://github.com/gorhill/uBlock/releases).

**Comment by LifeIsStrange** [comment]
Oh yes I know and use, thanks =]  
I spoke of uMatrix.

**Comment by msva** [comment]
Btw, @gorhill, can you add few more words about the reasons to not allow using uMatrix in Firefox for Android? ;)

**Comment by Atavic** [comment]
Android OS has IMEI, a unique identifier provided by manufacturer.
It has zero privacy on hardware/OS level: does an addon like umatrix make sense on such devices?

**Comment by gorhill** [comment]
Should no longer be an issue, I no longer mark the extension as being incompatible with Android platform.
