### ISSUE TITLE
Strange problem if external link starts browser (Firefox)

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#269]
If I click on an external link such as you can see in the following picture, this links starts Firefox. So far so goo.

![umatrix problem0](https://cloud.githubusercontent.com/assets/11355601/8221617/03fe0eb0-1561-11e5-9f1c-4d11d35eaccf.jpg)

Then, uMatrix shows "blank.about-scheme", which is not correct and of course not desired. This is always reproducable if the browser was not already open!

![umatrix problem](https://cloud.githubusercontent.com/assets/11355601/8221622/0fe575ce-1561-11e5-8707-857e9b10be16.jpg)

If the browser is already open it is correct (shows adobe.com ...).

I know, I could problably prevent this behaviour with remove the related matrix-off switch, but this is not the point.

**Comment by CrisBRM** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/262

**Comment by Alpengreis** [comment]
Note: this was NOT in private browser mode ...

**Comment by CrisBRM** [comment]
@Alpengreis Doesn't matter, it's the same bug, happened to me as well (last post there).

**Comment by Alpengreis** [comment]
Okay, yes, I see, thank you! Then I close here ...
