### ISSUE TITLE
Typo in hosts files?

### ISSUE THREAD

**Issue by colaas** [gorhill/uMatrix#273]
I'm trying to update the hosts files in Firefox 38.0.5, uMatrix 0.9.1.2 and it won't update "hpHosts’s Ad and tracking servers‎ (hosts-file.net)".
The actual list can be found at:
http://hosts-file.net/ad_servers.txt 
while the file seems to be called "ad-servers" internally in uMatrix. Is it using the correct url?

**Comment by gorhill** [comment]
The file name is fine: <http://hosts-file.net/.%5Cad_servers.txt>, as seen in `filter-list.json`.

**Comment by colaas** [comment]
Sorry, it is actually uBlock not letting it update. It's been reported before in https://github.com/gorhill/uBlock/issues/302 and you reversed a pull request which should have fixed it.

**Comment by gorhill** [comment]
The list name is fine, there is just no guarantee remote servers will always be up and running.

**Comment by colaas** [comment]
The list was down the other day so I couldn't follow up but I found the problem:
in  **uBlock/assets/ublock/filter-lists.json**             it's   .%5Cad_servers.txt so it isn't blocked
in  **uMatrix/assets/umatrix/hosts-files.json**         it's   ad_servers.txt  so it trips the *".net/ad_"* rule in Easylist
Another mention in  **uMatrix/tools/update-3rdparties.sh** is .%5Cad_servers.txt

**Comment by gorhill** [comment]
> in uMatrix/assets/umatrix/hosts-files.json it's ad_servers.txt so it trips the ".net/ad_" rule in Easylist

Ok, I did not realize I was commenting in uMatrix project. Yes, that list needs to be renamed to prevent a hit on EasyList.
