### ISSUE TITLE
Add ability define tld.* scope

### ISSUE THREAD

**Issue by lkraav** [gorhill/uMatrix#274]
uMatrix 0.9.1.2 Firefox

I'm looking to define a single set of rules for multiple similar TLD-s, in this case it happens to be a client of mine that has websites for 7 countries.

Quite annoying to define the exact same ruleset separately.

Defining tld.* didn't seem to apply to tld.eu. Thoughts?

**Comment by CrisBRM** [comment]
I don't think uMatrix's rule syntax supports regex, but this https://github.com/gorhill/uMatrix/issues/108 sounded so good. Maybe one day.

**Comment by gorhill** [comment]
> Thoughts?

I don't plan to implement this.
