### ISSUE TITLE
if use custom page colors, the ui is unreadable

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#277]
if you set

user_pref("browser.display.use_document_colors", false);
user_pref("browser.display.background_color", "#000000");
user_pref("browser.display.foreground_color", "#999999");

and the ui became unreadable because it follow these rules, uMatrix should use his own colors...

**Comment by haasn** [comment]
I've worked around this issue by making my own custom style-sheet that contains the colors from the popup.css but with !important after each attribute.

However, this does not seem to work on the images (background-image). Any ideas?

**Comment by gorhill** [comment]
I can't reproduce with current version of uMatrix.
