### ISSUE TITLE
uMatrix blocking entire domains inappropriately

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uMatrix#279]
1) disable all 3rd party domains and set the EasyList filter: https://easylist-downloads.adblockplus.org/easylist.txt

2) visit site: https://reddit.com

3) uMatrix blocks the entire domain, yet best I can tell the EasyList filter does not block the entire domain reddit.com

4) visit http://www.gardeners.com/

5) uMatrix flags the domain edgesuite.net as "deep red." But demandware.edgesuite.net host is required for images and edgesuite.net domain (best I can tell) is not a domain blocked in EasyList. EasyList blocks some edgesuite.net hosts but not the entire domain.

6) disabling uMatrix and trying above items with uBlock0 equipped with EasyList filter does not produce the same blocking behavior (i.e., both reddit.com and edgesuite.net are allowed).

**Comment by gorhill** [comment]
_EasyList_ is not a [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)).

If you feed uMatrix anything than a hosts file or a plain list of hostnames, results are undefined.

**Comment by Geremia** [comment]
@vdcbb See [the Perl script here](https://newspaint.wordpress.com/2014/08/18/filtering-easylist-for-hosts-file-style-adblock/) for converting [EasyList](https://easylist.to/easylist/easylist.txt) to a hosts file.
