### ISSUE TITLE
how do I use uMatrix??

### ISSUE THREAD

**Issue by gooly** [gorhill/uMatrix#280]
I have no idea how can I use uMatrix - I mean I have a problem with one site, I load this site and now I want to open the uMatrix - but how? 
- There is no entry in the right mouse click menu.
- There is no entry in the AddOn-Menu
- There is no entry in the Extra => Web-Develloper.

So how?

**Comment by TeddStriker** [comment]
What browser are you using? What OS? Please read [this](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md) before opening new issues. There's not much people can do to help without the necessary informatin. Can you confirm that the add-on is indeed installed? Please provide more information.

**Comment by gooly** [comment]
Yes uMatrix is installed. I use FF 38.0.5 but now I have found the green spot in the Menu. I haven't expected that uMatrix places it's spot there by itself, while I arranged all the icons myself..
