### ISSUE TITLE
[Feature Request] Disallow plugin enumeration

### ISSUE THREAD

**Issue by spaghetti2514** [gorhill/uMatrix#282]
navigator.plugins can be read by websites to aid in fingerprinting (see [panopticlick](https://panopticlick.eff.org)). It would be nice if there was an option in uMatrix to disable access to it

Similar to how umatrix redefines the user agent, it would aid in fighting against tracking to redefine navigator.plugins to undefined or an empty PluginArray or something.

In a single personal test, redefining navigator.plugins to undefined brought my "bits of identifying information" in the plugin details category from 19.82 to 9.24. I expect it would be even less if there's something else more common that non-plugin-supporting browsers set navigator.plugins to, but I have no idea what that might be.

Side note: I wasn't entirely sure whether to suggest this as a setting for uMatrix's Privacy tab, or as a setting in uBlock's Privacy section of the Settings tab (like the WebRTC fix). Settled on uMatrix because it's possible that this option being enabled would give away that the user is using whatever addon it ends up in, which would be a bigger deal for uBlock.

**Comment by d-kr** [comment]
Dublicate #271, #118

**Comment by spaghetti2514** [comment]
>Duplicate #271, #118

I would suggest that you actually read issues before declaring them duplicates. This request has nothing to do with user agents

**Comment by d-kr** [comment]
The issues are not only about the user agent but also about window.navigator itself (including plugins).
In both cases uMatrix "fails" / "does not try" / "is not meant" to hide that personal information other than some fields.

gorhill's second answer in 271 already talks about fingerprinting,the navigator object in general and why he does not extend the spoofing much futher. I assumed it applies here too.

Maybe you are right that there are not duplicates, but they have the same cause.

> I would suggest that you actually read issues before declaring them duplicates.
I commented in them.

**Comment by spaghetti2514** [comment]
>gorhill's second answer in 271 already talks about fingerprinting,the navigator object in general and why he does not extend the spoofing much futher. I assumed it applies here too.

It's entirely possible that it does, but I'd rather Gorhill say that himself than have you "assume" it.

Further, if it's actually Gorhill's stance that the important part of preventing fingerprinting is preventing third party scripts and XHR entirely, then why is the user agent spoofer in uMatrix at all?
The help text for the user agent spoofer setting in uMatrix's option page says
>your browser sends a ‘User Agent’ header to the website saying precisely which operating system and web browser you are using. This information could help distinguish Internet users from one another because these versions differ, often considerably, from person to person

That's fingerprinting in a nutshell. Based on that, it would seem to be that Gorhill has at least some interest in preventing fingerprinting through spoofing, and plugin enumeration is the next most substantially helpful way to achieve that.

>I commented in them.

I was referring to this issue

**Comment by CrisBRM** [comment]
You can already do that on FF.

[code]user_pref("plugins.enumerable_names", "");[/code]
