### ISSUE TITLE
Does not treat LAN hostnames (without suffix) as 1st-party domain

### ISSUE THREAD

**Issue by jimbo1qaz** [gorhill/uMatrix#283]
I have a Gitlab web-server in my LAN. I access it from http://server . The server requests javascript from http://server, which is perfectly normal. However, uMatrix does not grant "http://server" 1st-party privileges, instead treating it as a different domain. By blocking required Javascript from executing, it prevents me from logging in. I believe this is incorrect behavior, because the first-party rule is failing to apply to a first-party domain. I verified on a brand-new Firefox Linux profile and a modified Windows profile.

This behavior does not occur when going to http://localhost , because uMatrix is automatically disabled.

**Comment by gorhill** [comment]
I can reproduce with `localhost` as well -- I agree this is should not happen.
