### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by CrisBRM** [gorhill/uMatrix#286]
Tried to see if I could block individual scripts (eg: THIS page has 2 scripts originating from assets-cdn.github.com) and it didn't work.
Namely, I used this custom rule ```` github.com https://assets-cdn.github.com/assets/frameworks-3241a40a58a82e21daef3dd3cdca01bde189158793c1b6f9193fff2b5293cd1d.js script block ````

By design, or..? I'd expect a similar rule to work on uBlock, however (My filters -> |https://assets-cdn.github.com/assets/frameworks-3241a40a58a82e21daef3dd3cdca01bde189158793c1b6f9193fff2b5293cd1d.js).
It makes sense given the rule syntax, since that is not a hostname, but still.

**Comment by gorhill** [comment]
Your ruke worked for me:

![a](https://cloud.githubusercontent.com/assets/585534/8602993/4b71986e-2643-11e5-9893-35b60d4e161b.png)

**Comment by CrisBRM** [comment]
Weird. Firefox is due a reinstall anyway. Joke's on me for using Aurora.
I tried to create this scenario to see what the matrix UI would look like.

**Comment by gorhill** [comment]
My bad, I though I was answering for uBlock. uMatrix does not support dynamic URL filtering.

**Comment by CrisBRM** [comment]
Ah, that clears it up then.
