### ISSUE TITLE
Need a way to use uMatrix when the toolbar is hidden

### ISSUE THREAD

**Issue by quinncomendant** [gorhill/uMatrix#287]
Often on popup windows, the toolbar is hidden, thus it is impossible to access the uMatrix controls. One example are "Live Chat" features of websites (see example [screenshot](http://i.imgur.com/dIpX5CA.png)). Is there any plans to add a feature to invoke uMatrix from the keyboard?

**Comment by haasn** [comment]
Similar issue here. I moved the uMatrix icon to the addon bar (the one at the bottom), and it works “fine” there (the dashboard opens at the bottom, too, where I'd expect it), but as soon as I hide the toolbar again it simply stops showing up.

I'd personally expect something like this to be available from the context menu (like NoScript / RequestPolicy), if that would be at all possible.

**Comment by TeddStriker** [comment]
I haven't yet been in a position to **need** this, but I would really like to have if the option. That is, assuming its not too much work, seeing as its not **really** a must-have feature.

**Comment by gorhill** [comment]
You can invoke the popup from the logger.

**Comment by haasn** [comment]
> You can invoke the popup from the logger.

Interestingly enough, this also solves my issue, even though it may have been somewhat orthogonal - if opening the popup from the logger, it works fine even with the toolbar disabled.

Now I just need to bookmark the logger or something and I can avoid having to constantly turn the toolbar on and off again just to access umatrix. :p

**Comment by quinncomendant** [comment]
I can invoke the popup from the logger, but the scope is set to the domain `ogfcmafjalglgifnmanfmnieipoejdcf.chrome` (the extension URI), not the hostname of the window I have which has its toolbar disabled. So not helpful at all. This is uMatrix 0.9.1.2 with Chrome Version 43.0.2357.130 on OS X.

![screen shot 2015-07-10 at 11 39 56](https://cloud.githubusercontent.com/assets/6884276/8623756/da6a83fe-26f8-11e5-8f24-add4ad4539c6.png)

**Comment by gorhill** [comment]
> I can invoke the popup from the logger, but the scope is set to the domain [...]

<https://github.com/gorhill/uMatrix/wiki/Logger#special-status-indicators>:

> It is possible to click on the status indicator area to open the matrix for the associated tab

**Comment by quinncomendant** [comment]
Aha, found it—the "status indicator area" is the second column of the logger (I had to basically click around randomly on the page until I discovered what that "area" was). For those who haven't found it yet, here's a screenshot with the location to click circled in red:

![screen shot 2015-07-10 at 13 45 54](https://cloud.githubusercontent.com/assets/6884276/8626382/6b492cb6-270a-11e5-920f-407d373ed9b8.png)

Yes, this works to invoke uMatrix for any tab. =)

**Comment by vdcbb** [comment]
@quinncomendant: you can set a keyboard shortcut to open uMatrix if you are using Google Chrome. This will open the matrix whenever the keyboard shortcut is tapped. Far as I know though, there is no way to set a keyboard shortcut in Firefox :-(

**Comment by quinncomendant** [comment]
> you can set a keyboard shortcut to open uMatrix if you are using Google Chrome. 

How? I don't see that option. I'm on Chrome on OS X.

**Comment by gorhill** [comment]
> I don't see that option

`about:extensions`, scroll to the bottom, click _Keyboard shortcuts_.

**Comment by quinncomendant** [comment]
WOW! You just blew my mind.

**Comment by drivencompassion** [comment]
Looking forward to Firefox getting some keyboard shortcut love <3

**Comment by AdKiller** [comment]
at this point I am willing to pay to get keyboard shortcuts in Firefox.

https://github.com/gorhill/uMatrix/issues/453

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/wiki/How-to-access-the-popup-panel-when-there-is-no-toolbar
