### ISSUE TITLE
[Firefox] Popup does not show up when toolbar is hidden

### ISSUE THREAD

**Issue by haasn** [gorhill/uMatrix#288]
Issue: Popup does not show up. (Clicking the button does nothing, apart from pentadactyl telling me I have a menu open for a brief fraction of a second)

Steps to reproduce: I dragged the uMatrix icon to the status bar. I then hid the toolbar (I'm using pentadactyl: ```:set guioptions=Cs```) and tried opening the popup. If I enable the toolbar again (```:set guioptions=CsT```), it works fine. (Even though the popup is attached to the status bar, not the toolbar)

Firefox versions I tested: 38.0.1 (dev edition), 38.0.5 (stable channel), GNU IceCat 31.7.0
uMatrix versions I tested: 0.9.1.2 (AMO), 0.9.1.3 (pre-release)

I could reproduce this issue on a blank profile containing just uMatrix and pentadactyl.

Edit: Upon trying to reproduce this on a blank profile containing just uMatrix, I realized that Firefox no longer has a status bar, and also no longer has an official method of disabling the toolbar. It seems this particular status bar is added by pentadactyl. I was under the incorrect assumption that you could still selectively enable/disable the tool- and status-bars as you could in previous Firefox versions. (Why the fuck Mozilla would remove this functionality is beyond me, however)

In other words, this is not an issue inherent to uMatrix but rather a compatibility issue with **pentadactyl**. (Although it might still be caused/fixable by uMatrix)

Edit 2: There's another way to trigger this bug without requiring pentadactyl, on a fresh profile: Just drag the uMatrix icon to something else (eg. the bookmark bar), and then hide the navigation bar by using ```#nav-bar { display: none !important; }``` in userChrome.css.

This actually suggests another way to solve this issue. Instead of hiding the toolbar, I can simply move it out of sight using something like ```#nav-bar { height: 32px !important; margin-top: -32px !important; }```. If it's simply off-screen like that, uMatrix continues to work fine. I consider this an acceptable work-around, so you may disregard this issue.

**Comment by panaino** [comment]
gorhill/uBlock#112 related.

**Comment by Raziel-23** [comment]
There is another way (more official way), you can manually add extensions.umatrix.forceLegacyToolbarButton entry as boolean type and set it to true. After restarting firefox it should works. Tested on pentadactyl-git and uMatrix versions 0.9.1.2 (AMO).

**Comment by haasn** [comment]
Thanks, that fixes my issue perfectly.

**Comment by timss** [comment]
Can confirm that it's working as intended with vimperator as well. 

I would also like to emphasize the part where you need to restart your browser. Wouldn't work without it.

**Comment by Tanath** [comment]
This fix doesn't work for me:
  extensions.umatrix.forceLegacyToolbarButton to true/false
Using pentadactyl hg7226 (Sept. 06/15) on Firefox 42.0.2 with uMatrix 0.9.2.1.

**Comment by Raavizz** [comment]
> @haasn : Why the fuck 

Stop your drama / insulting / vulgar words / negativity.

**Comment by hukkay** [comment]
> @haasn : the fuck

@haasn stop your drama / vulgarity
