### ISSUE TITLE
uMatrix breaks youtube when completely disabled

### ISSUE THREAD

**Issue by nguillermin** [gorhill/uMatrix#289]
http://imgur.com/MP0I1mK

OS X 10.10.4, Firefox 39.0

youtube chrome is broken, a bunch of images don't make it, including video thumbnails on the sidebar (which you can't see in this screenshot, but the first two thumbnail images in this case).

**Comment by gorhill** [comment]
Turn off user agent spoofing for that site, or use only Firefox-based user agent strings, i.e.:

    Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
    Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by gorhill** [comment]
By the way, regarding "completely disabled": that button disabled matrix-filtering specifically, it does not completely disable uMatrix.

**Comment by nguillermin** [comment]
Solution works, thanks!
