### ISSUE TITLE
needed download failed

### ISSUE THREAD

**Issue by gooly** [gorhill/uMatrix#290]
Hi,
I want to download the TickDataDownloader (http://www.strategyquant.com/tickdatadownloader/)
which links me to this page http://www.strategyquant.com/tickdatadownloader/download.
After I entered a name an emailaddress I am blocked by uMatrix because behind this link is awerber https://www.aweber.com/scripts/addlead.pl

Ok, I disabled uMatrix on page where I have to enter the email address but still I am blocked by uMatrix.
Is there no way to accept even this without disabling or de-install uMatrix?
Thanks in advance,
Gooly

**Comment by gorhill** [comment]
Use the logger, it will show you the blocked request. Bring the matrix from there to unblock the request. I do't to give my email address to that kind of site, so I will let you figure the fix. uMatrix is for advanced users, I should not need to attend this kind of problem.
