### ISSUE TITLE
Partial domain match in Rules ( *.googlevideo.com )

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [gorhill/uMatrix#293]
The following rule, when manually created does not take effect
youtube.com *.googlevideo.com other allow
youtube.com *.googlevideo.com xhr allow
This would help in creating rules for allowing CDNs too.

**Comment by Snapy** [comment]
You might want trying
youtube.com googlevideo.com other allow
youtube.com googlevideo.com xhr allow

Wildcards are not supported and SLD are included by default.

**Comment by jagan-veeraraghavan** [comment]
That worked. Thanks for the help.
