### ISSUE TITLE
HTTPS protocol use not indicated

### ISSUE THREAD

**Issue by lukestanley** [gorhill/uMatrix#295]
Obviously HTTP is readily hackable at a cafe or such with a MitM attack.
HTTPS is less easy to hack for updated browsers.
I would like to whitelist sites using HTTPS but I cannot see HTTPS in the matrix.

Steps to reproduce:
1. Go to a webpage that uses Javascript like http://facebook.com
2. Click the uMatrix menu button
3. Try and click to allow scripts on requests to sub/domains using HTTPS, by looking for HTTPS in the sub/domains.

**Comment by gorhill** [comment]
That's the purpose of [_Strict HTTPS_](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches#strict-https), to prevent any non-HTTPS requests when the main document is HTTPS.

**Comment by lukestanley** [comment]
It's close but that wouldn't help if some HTTP content was desired or if using a non-HTTPS main document.

**Comment by gorhill** [comment]
I don't intend to implement anything more granular than this.

**Comment by lukestanley** [comment]
Is this due to the a concern with making the UI too busy? Because if so, people may prefer the ability to control execution of HTTP vs HTTPS scripts over other types like images etc.

A related idea might be better exposure of Strict HTTPS mode, perhaps getting rid of the padlock icon that may confuse users.

I don't know if it's best to close this or leave it open, or maybe label it "free to take and work on it".
BTW thanks for all the great work anyhow.

**Comment by CrisBRM** [comment]
When you go to an http site you are less secure by default if you're using an untrusted connection, regardless of where you load your scripts from. The attacker can inject iFrames, scripts, and so on so forth, into your page.

https://github.com/mitmproxy/mitmproxy

**Comment by gorhill** [comment]
> Is this due to the a concern with making the UI too busy?

- doesn't fit readily in the matrix UI
- doesn't fit readily in the current core architecture
- feature unlikely to be useful to many users of uMatrix
    - keeping in mind uMatrix is already appealing to a fraction of users compared to uBlock (~1%)
- the more complex a feature, the less likely it will be used -- I rather contribute dev work where it has most impact:

![b](https://cloud.githubusercontent.com/assets/585534/8783819/33d72320-2eec-11e5-9d19-67f24833d919.png)<br><sup>Source: guts</sup>
