### ISSUE TITLE
Install process and possible problems (without deinstall first) ...

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#296]
@gorhill 

I know, in the README.md file is the text ...

"Although uMatrix is a restartless addon, I found that installing a newer version over an older one often will glitch the installation."

Also, we had already spoken about this. Nevertheless, I did some more tests without deinstall first (with uBlock too). I had never a problem - till now.

Raymond, can you please tell me, WHAT problems did YOU have? I mean the technical side: crashed the PlugIn, worked it not right, was it the same with uBlock too, etc.

Thank you very much in advance and

kind regards!
Alpengreis

**Comment by gorhill** [comment]
> WHAT problems did YOU have?

Trying to debug using the debugger, the debugger was seeing only the previous version, not the new one.

**Comment by Alpengreis** [comment]
Ok, all right, thank you!
