### ISSUE TITLE
[0.9.1.3-dev.6] Firefox compatibility extended to FF 24-34. --> 24-42.

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#299]
Because I cannot edit the release notes, I open an Issue ...

Change ...
[0.9.1.3-dev.6] Firefox compatibility extended to FF 24-34.

... to ...

[0.9.1.3-dev.6] Firefox compatibility extended to FF 24-42.

... please.

**Comment by gorhill** [comment]
uMatrix was already compatible with FF35+, hence the compatibility has been _extended_ to FF24-34.

**Comment by Alpengreis** [comment]
Ohh, all right, SORRY!
