### ISSUE TITLE
[Palemoon] uBlock filters take precedence before uMatrix

### ISSUE THREAD

**Issue by Tharn** [gorhill/uMatrix#300]
I noticed that on Firefox (Palemoon 25.5, uBlock 1.0.0.1-dev.0 and uMatrix 0.9.2.0-rc.0), the traffic will pass through uBlock first before it passes through uMatrix, indicated by the green bars and + signs in advanced mode.

Wouldn't it logically work the other way around? With uMatrix being the low-level, fine-grained firewall for what goes in and what doesn't, leaving uBlock to do cosmetic filters and stuff like that?

Thanks for supporting PM and writing these great extensions!

**Comment by gorhill** [comment]
Extensions have no control of the order they are being call by the browser. In the case of Firefox, the [documentation says](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy) order of installation decides the order in which the extensions are called to do their job:

> The order of content policies in the above case depends on the precedence of installation

Above is for `shouldLoad`, I am assuming this also applies for HTTP observers.

**Comment by Tharn** [comment]
I'm assuming since both extensions came from the same flock, there is no functional or performance difference depending on who catches what first? I'll close this, cheers.
