### ISSUE TITLE
Local Hosts file

### ISSUE THREAD

**Issue by drm200** [gorhill/uMatrix#302]
I would like to include my own local hosts file to block/blacklist some sites not found in the built-in hosts lists.  I'm using uMatrix in Ubuntu 64 with google chrome.

So I created a small hosts file and located it on my desktop.  I then went to the "Hosts files" tab and added the local url for my hosts file.

file://home/user1/Desktop/MyHosts.txt   (I also tried:  file:///home/user1/Desktop/MyHosts.txt)

When I click on "parse" the file shows up in the list of hosts but the contents are not read or updated into uMatrix.

Should this work?  If not, I'd like to suggest this feature be added so that user defined Hosts list could also be included.

**Comment by gorhill** [comment]
`file://` does not work on Chromium-based browser, it is seen as being a cross-origin request. This work for Firefox though.

**Comment by drm200** [comment]
Ok, I understand the problem.   It would be nice if I could add some additional host sites using something similar to how you have implemented the ability to add additional spoofing agents without a text file.  But understand if not a priority.

Also, I was not able to see any errors in the uMatrix error log when trying to load file:// ... This reports nothing with chrome running under ubuntu for me.

During this testing I was able to crash the plugin under this scenario:

First I add the local url for my hosts file: 
file://home/user1/Desktop/MyHosts.txt and then click "parse"

Next, I deselect ALL other hosts files so that only my hosts file is selected and then click "Apply Changes", The extension will then hang.

Interestingly, If I have at least one other hosts file "selected" ... there is no failure when I click "Apply changes".  

This is a rather esoteric error of no importance, I only relate the experience to you.

**Comment by gorhill** [comment]
> Also, I was not able to see any errors in the uMatrix error log when trying to load file:// ... This reports nothing with chrome running under ubuntu for me.

![c](https://cloud.githubusercontent.com/assets/585534/8889629/37d78f74-32b0-11e5-80be-dda536764488.png)

You have to look in the extension's dev console.

> Next, I deselect ALL other hosts files so that only my hosts file is selected and then click "Apply Changes", The extension will then hang.

I will look into this.

**Comment by drm200** [comment]
Yes, I see the same in the extension's dev console now.
Many thanks,

>
> You have to look in the extension's dev console
>
