### ISSUE TITLE
uMatrix doesn't store permenantly which cells I whitelist

### ISSUE THREAD

**Issue by Jokerswild2412** [gorhill/uMatrix#303]
Not sure if this is a "feature" or a bug, but every time I visit a website, I have to reenable the cells that I whitelisted.  For example, every time I visit Reddit I have to constantly enable all of the other reddit related content websites in order to upvote or downvote anything.

Is there a way to make changes permanent instead of globally whitelisting everything, or is this a "feature"  that isn't removable?

**Comment by hotdogman** [comment]
![haoxm4g717tb 1](https://cloud.githubusercontent.com/assets/4343306/8868592/f6302344-319f-11e5-9c9b-8a8d9a32bf34.png)
Does the lock/save button not work?

**Comment by gorhill** [comment]
No _exact_ steps for me to reproduce, as per <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>.
