### ISSUE TITLE
Collapse blocked element feature should be more aggressive

### ISSUE THREAD

**Issue by lainverse** [gorhill/uMatrix#304]
Example here: http://censor.net.ua/news/345266/za_minuvshie_sutki_ranen_1_voin_3_boyitsa_pogibli_i_4_travmirovany_v_dtp_spiker_ato

Try to forbid iframes from censor.net.ua from loading. You will notice that placeholders for them will remain visible due to fixed-size DIV elements on the level above.  I've seen such behavior on several sites. In some cases size were hard-coded, in some other it was applied through CSS styles. So, I think the collapsing feature should try to check the size of the element directly above the blocked one for being fixed. And if it is and there is nothing else to display, attempt to collapse them as well or subtract at least a height of the blocked element if it's available.

**Comment by gorhill** [comment]
> I think the collapsing feature should try to check the size of the element directly above the blocked one for being fixed

That's a job for filter list maintainers, doing this programmatically could lead to false positives, with no way to work around. And then there are performance concerns.
