### ISSUE TITLE
Local Javascript (Bookmarket) Blocked

### ISSUE THREAD

**Issue by ldgbc** [gorhill/uMatrix#306]
Setup: Windows' Firefox 39, uMatrix 0.9.2.
Setting: Disable 1st and 3rd party script.

Issue: Bookmarklet does not work if 1st script is blocked
With the way uMatrix is design it seem to work with local script while blocking {inline_script} if 1st party script is blocked. For example using Greasemonkey with user.js (Userscript) it will work without enabling {inline_script}. Unlike NoScript where you must Whitelist website to use local script.

The issue is that Bookmarklet does not work unless you enable {inline_script}

An example Bookmarklet is below, where it will clean all the color of the page. To use it, enable 1st party script in uMatrix, and the code in a bookmarklet under URL part. And clicking on the bookmark while you are viewing a website.

```
javascript:(function(){var%20newSS,%20styles='*%20{%20background:%20white%20!%20important;%20color:%20black%20!important%20}%20:link,%20:link%20*%20{%20color:%20#0000EE%20!important%20}%20:visited,%20:visited%20*%20{%20color:%20#551A8B%20!important%20}';%20if(document.createStyleSheet)%20{%20document.createStyleSheet("javascript:'"+styles+"'");%20}%20else%20{%20newSS=document.createElement('link');%20newSS.rel='stylesheet';%20newSS.href='data:text/css,'+escape(styles);%20document.getElementsByTagName("head")[0].appendChild(newSS);%20}%20})();
```

Will it be possible to whitelist Bookmarklet script like it is currently working for Greasemonkey+User.js

**Comment by luxoflux** [comment]
Technically, CSP directives should _not_ affect bookmarklets, but in Firefox they do – see https://bugzilla.mozilla.org/show_bug.cgi?id=866522. I don't know if @gorhill could implement a workaround within uMatrix/uBlock, but this is a browser issue mainly.
