### ISSUE TITLE
Can't send text in Pusbullet extension

### ISSUE THREAD

**Issue by spartanhooah** [gorhill/uMatrix#307]
Using the Pushbullet extension, I'm unable to send or reply to a text in either the incoming text pop-up or from the extension's toolbar icon. Sending through the full Pushbullet website works fine. When I tried on the site, I made sure to allow and save all Pushbullet-related things.

**Comment by gorhill** [comment]
What does the logger says?

As said in the extension description, uMatrix is for advanced users, and as such the logger should already have been checked to find out what is blocked and why.

**Comment by CrisBRM** [comment]
Check the behind-the-scenes matrix. It works for me, so.

**Comment by spartanhooah** [comment]
Sorry for being a regular user using this, I guess. I've restarted Firefox, and now I can send/reply from the extension popup accessed via the toolbar icon, but not the popup that appears when someone texts me. Here's the logger's output when I got a text and tried to reply:

15:56:36			xhr	https://api.pushbullet.com/v3/set-app-state
15:56:36			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:36			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjzX6H2Gtga_threads
15:56:27			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:27			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjzX6H2Gtga_threads
15:56:26			xhr	https://zebra.pushbullet.com/
15:56:26			xhr	https://api.pushbullet.com/v2/ephemerals
15:56:26			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:26			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjzX6H2Gtga_threads
15:56:24			xhr	https://api.pushbullet.com/v2/permanents/phonebook_ujxMVQfJMlgsjAzB10eZga
15:56:24			xhr	https://api.pushbullet.com/v2/permanents/phonebook_ujxMVQfJMlgsjAzB10eZga
15:56:24			xhr	https://api.pushbullet.com/v3/set-app-state
15:56:24			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:24			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjzX6H2Gtga_threads
15:56:24			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:23			xhr	https://api.pushbullet.com/v3/set-app-state
15:56:23			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjAzB10eZga_threads
15:56:23			xhr	https://api.pushbullet.com/v2/permanents/ujxMVQfJMlgsjzX6H2Gtga_threads

I can't find anything on the GitHub page about the behind-the-scenes matrix, so I can't speak to that.

**Comment by gorhill** [comment]
Seen in the [review section of the extension](https://addons.mozilla.org/en-us/firefox/addon/pushbullet/):

> Big annoyance is how it needs to have 3rd party cookies and trackers enabled to log in !! WHY !! I don't want 3rd party nonsense when I'm logging in to YOUR service !!

Could your issue be related to this?

**Comment by spartanhooah** [comment]
I suppose it's possible. I'll try disabling uMatrix and see what happens.

**Comment by spartanhooah** [comment]
Disabling uMatrix allows Pushbullet to work fine. I've got Firefox set to never allow third-party cookies.

**Comment by IV2KBMoFxYIA** [comment]
Try this: 

Go to the logger, and select "Behind the scene" from the drop down menu. Try using the Pushbullet extension. 

You should see the listings that you mentioned before. Now click on the eye icon to the right of the time. 

You should now see the matrix for the 'behind-the-scene' scope. 

Go through the list and allow anything related to push-bullet. 

Personally, I have ALL css/images/xhr and other allowed for the 'behind-the-scene' scope. 

Try that and it should work. Otherwise, I recommend that you ask over at the user-side forum (http://goo.gl/6f1Ejb) instead of here which is more for bugs.

**Comment by gorhill** [comment]
Something else to try if you still can't find anything blocked, is to turn off referrer and/or UA spoofing for the behind-the-scene scope.
