### ISSUE TITLE
uMatrix popup doesn't always open to expected height/width

### ISSUE THREAD

**Issue by filipecatraia** [gorhill/uMatrix#309]
Hi,

First of all: I love uMatrix. It's a neatly crafted piece of software, that provides me with a great service. Reading the _guidelines for contributing_, and loving uMatrix, I __do__ want to file a proper issue. I'd like to have steps for replication, with carefully detailed instructions.

However, I've no idea why this happens. I've inspected everything in the popup itself and read the entire javascript of the extension. Nothing seems to justify this behavior. My best guess is that the DOM implementation for the plugin lacks something. But that's a wild guess.

The best I could do was [upload a video showing the issue](https://vid.me/GWQO).

Issue:

1. Click on uMatrix icon in the browser's top bar.
2. The dialog should open completely.
    a. Sometimes this happens.
    b. Sometimes it doesn't.
3. Refresh the page, or scroll up and down.
    a. Sometimes this solves the problem.
    b. Sometimes it doesn't, but clicking the icon repeatedly will eventually make the issue go away.

Tested on Chromium and SRWare Iron (41.0.2200.0 (64-bit), Chromium-based). It might be a Chromium thing. Both on a Mac running 10.10.4.

Sorry for the little info and thanks for the effort and extension!

**Comment by gorhill** [comment]
> It might be a Chromium thing

It has to be, as the popup container size is controlled by the browser in Chromium. I suspect it could be an issue specific to Chromium for OSX as I've never seen/heard such issue with Linux.

The particularity of uMatrix popup is that it is built dynamically, so it seems this is not handled well in your specific environment. You should report this to Chromium devs: <https://code.google.com/p/chromium/issues/list>.

**Comment by filipecatraia** [comment]
It's very possible. And not a deal-breaker :)
