### ISSUE TITLE
Improve "My Rules" tab to better distinguish allow and deny

### ISSUE THREAD

**Issue by adrienbeau** [gorhill/uMatrix#312]
Browser: Firefox 39.0 (Mozilla Firefox for Ubuntu - Canonical - 1.0)
uMatrix: v0.9.2.1

When a significant number of global rules is accumulated, it becomes hard to visually distinguish "allow" rules from "deny" rules. Maybe some kind of keyword coloring, or icons, could be used?

![umatrix-rules](https://cloud.githubusercontent.com/assets/13599352/9067325/128fb57c-3add-11e5-9d05-49770b975d7e.png)
(Spot the lone allow rule in the screenshot. ;-))

This is less of a problem for domain-level rules, because there are less rules per domain, but any improvement at the global level would be a bonus there.

**Comment by 5t3f4n** [comment]
This is by no means a solution, but a workaround for the time being.

Press <kbd>CMD</kbd>+<kbd>F</kbd> or <kbd>CTRL</kbd>+<kbd>F</kbd> then type either allow or block in and select Highlight All.

**Comment by gorhill** [comment]
Recent versions of uMatrix allows to filter out displayed rules, so just enter `block` or `allow` as a filter expression.
