### ISSUE TITLE
Not compatible with Firefox Beta 40.0 (Android)?

### ISSUE THREAD

**Issue by Manouchehri** [gorhill/uMatrix#313]
I can't figure out what's causing this, but Firefox doesn't want to let uMatrix be installed on Firefox Beta 40.0 (Android). `install.rdf` seems to allow from 24.0 to 42.0, so it _should_ fall under that range. 

I have no problem with uBlock (Origin) on Firefox 40.0, and I don't see any difference in that `install.rdf`.

![Attempting to install .xpi from GitHub release.](https://cloud.githubusercontent.com/assets/7232674/9076895/e7641eec-3af5-11e5-80d2-818473d1fde8.png)
![Attempting to install via Firefox's official site.](https://cloud.githubusercontent.com/assets/7232674/9076896/e7650abe-3af5-11e5-82b2-975dabf2e977.png)

**Comment by gorhill** [comment]
uMatrix is not compatible with Android.

**Comment by Manouchehri** [comment]
Is it currently being blocked purely because of the `install.rdf`, or is there another thing blocking it? I wouldn't mind trying it out even if it's somewhat unstable/unusable.

**Comment by gorhill** [comment]
It's more than `install.rdf`, I removed the UI code for Firefox Mobile when I ported uBlock's Firefox code to uMatrix.

**Comment by Manouchehri** [comment]
Ah, thanks for explaining. Is there enough removed that it flat out won't run, even without a proper UI? At the moment I'm mostly using uMatrix to handle enforcing strict HTTPS with a few exceptions, so it would still be quite useful with just the dashboard.

**Comment by adrienbeau** [comment]
@gorhill Do you have plans to have uMatrix run on Android at a later time?

**Comment by gorhill** [comment]
Maybe. As time permits, but especially as testing permits, as I had no way to test whether it worked for Firefox Mobile when I ported Firefox code into uBlock (now I have access to someone else's mobile device to test).

**Comment by requiredregistration** [comment]
for testing, if you don't have any android devices, you can download SDK Tools only [https://developer.android.com/sdk/index.html#Other], then download through the SDK Manager one or more ARM system images, then through the AVD (Android Virtual Device) Manager, you can create and manage Android Virtual Devices (AVDs) that run in the Android Device Emulator, and lastly, with adb you can install APKs, and do many other things.

**Comment by LifeIsStrange** [comment]
Oh I can do tests for you on my oneplus one ! 
I use everydays 4 hours of Firefox mobile, I am often using the nightly but I May use all the Firefox versions that you want for tests.

**Comment by defkev** [comment]
+1 for Android Support
