### ISSUE TITLE
Keep comment and order when importing a rule file

### ISSUE THREAD

**Issue by orklah** [gorhill/uMatrix#314]
Hi,

I find the import tool very difficult to use.

I followed the page https://github.com/gorhill/uMatrix/wiki/Rules-syntax to create my own rule file. It contains comments, empty lines for lisibility and I ordered it so I can see the most important rules first.

I use a file because when I add a lot of rules through the UI, I end up with a messy blob of rules I can't maintain anymore.

My file look like that:

```
#Global CDN
* cloudfront.net * allow
#External tools
* youtube.com * allow
#Image hosting
* imgur.com image allow
```

With a lot more rules than that.

When I import it, the tool automatically rearrange my rules and it doesn't make sense anymore:
![capture](https://cloud.githubusercontent.com/assets/9605520/9142088/c142b3fa-3d3d-11e5-9664-0ae9c4a12892.PNG)

The whole set of rules is working perfectly but the comments are treated as rules and were grouped together and every rule was rearranged by alphatically.

I don't mind deleting every rule each time before reimporting my file, what I do mind is that I can't export my file the same way I imported it and I won't be able to find the rules I added since the last import (I would like them to be inserted at the bottom so I can rearrange them later).

I use Firefox in version V39.0.0.3, the last version of uMatrix V0.9.1.2, I also have uBlock Origin and plenty other addons but I don't think they are relevant for this issue.

Thanks a lot.

(Sorry for my bad english)

**Comment by gorhill** [comment]
For the comment, ensure you have a space after the `#` character.

For the rest, not trivial at all: essentially, the _My rules_ pane is a view into uMatrix's internals, and internally there is no comment in a ruleset, and there is no order. Trying to keep the same layout as the imported data would be quite complex actually, because the mere action of adding/removing a rule through the matrix UI  would become way too complicated and inefficient.

**Comment by orklah** [comment]
Thank you for your very quick answer!

It works fine with the space after the #. Thank you.

For the file, I understand. Would it be possible to sync with an external file the same way we sync hosts files? That way I could keep my file updated, knowing that the rules will be imported in whatever order needed.

I may be asking a lot for a simple issue. Feel free to close this issue if it's too much a bother to develop.

Thanks again!
