### ISSUE TITLE
Performance under fx Nightly...

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#315]
I've recently been seeing uMatrix performance 'issues' when running under Nightly 42.0a1. Checking about:performance I regularly see:

![Imgur](http://i.imgur.com/2E4xssd.jpg)

For what it may be worth, it seems related to watching videos on Youtube.

**Comment by gorhill** [comment]
I am not seeing this at all, quite the contrary. uMatrix incurs significantly less overhead than uBlock, and when I play a vide on Youtube, I see it using pretty much 0% user. I do not have what your screen shows even though I have 42.0a1:

![a](https://cloud.githubusercontent.com/assets/585534/9153481/03af1352-3e27-11e5-9b50-1ee8d6dbd6e4.png)

Knowing how uMatrix works internally matches quit well my screenshot, but not at all yours, and what I see on Firefox matches what I see with the Chromium version: uMatrix's overhead is negligible.

You will have to share more details about your environment: disclose everything which is relevant for me (or anybody else) to produce your results.

**Comment by gorhill** [comment]
Did you have the logger opened?

**Comment by Radagast** [comment]
> You will have to share more details about your environment: disclose everything which is relevant for me (or anybody else) to produce your results.

I can reproduce the 'issue' at will by watching several videos on youtube back-to-back. In firefox Nightly, open **about:performance** and play several videos. uMatrix appears under both Performance of Add-ons and Performance of Web pages. As soon as youtube is closed uMatrix returns to normal.

As far as details:

Windows 10 Pro 
Firefox 42.0a1 (2015-08-08)

In the logger the only items blocked are youtube cookies and doubleclick ads.

Here's a pestbin with firefox details and the relevant about:memory section.
http://pastebin.com/rqxWLvyB

let me know if you need anything else.

**Comment by gorhill** [comment]
Got the latest Nightly with the same `about:performance` page as yours, and I can't get your numbers, even with the logger opened (yours was opened as per your pastebin). There are a lot of other add-ons in your profile, and it's best if you can try uMatrix on its own and see if the issue is still there. Hopefully other users will report whether they see the same issue.

**Comment by Radagast** [comment]
Apologies for the delay in replying, I've switched back to Windows 7, now I need to investigate.
