### ISSUE TITLE
Why not a proxy based web filter?

### ISSUE THREAD

**Issue by cm-mc** [gorhill/uMatrix#317]
I see all these browser addon based webfilters and ask myself:
Why not a proxy based app, à la Webwasher (Classic), which would instantly filter requests, not just for each and every browser installed, but also for any other app (online help, telemetry, etc.), while still allowing to easily bypass it whenever desired (and which could also have app/port/protocol specific rules)?
From the user's pov that would surely be the best option possible, and from the developer's, at least would allow to focus on just a single piece of code (could possibly be java based, as well?).

**Comment by gorhill** [comment]
Please, here is to file issues specific to uMatrix.
