### ISSUE TITLE
Is uMatrix still intended to be used in conjunction with uBlock?

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#32]
If this is a duplicate issue (or can be easily explained by another issue that I overlooked) please feel free to close without explanation to avoid clutter. 

I see that the ad/host blocking has been simplified but the 'Hosts' tab still appears to replicate some of the same functionality. Is this by design, or is this something that will change in the future? In <a href="https://github.com/gorhill/httpswitchboard/issues/367">this issue</a> there seemed to be an intention to split the functionality entirely.

I suppose that the limited functionality of ad/hosts blocking in uMatrix is meant to appease those who don't care about element hiding (but also don't want to install another extension), but I cannot help but be curious if the attitude toward separating them has been steadfast or waned recently. Any perspective on the topic would be appreciated!

**Comment by gorhill** [comment]
Both tools can be used alone or combined. It is assumed that whoever use these tools will figure by themselves how to use them best together -- this is especially true that uMatrix is made for advanced users, so they can figure how to set up things themselves.

**Comment by mailinglists35** [comment]
> unchecking malware-related hosts files in uBlock is suggested to avoid unneeded overlap.

hi,

what exactly must be unchecked (what should be unchecked in umatrix and what should be unchecked on ublock origin), please?

using umatrix and ublock origin from chrome store.

thank you

**Comment by CrisBRM** [comment]
@mailinglists35 Select all lists on uMatrix. Uncheck all lists that you checked on uMatrix, on uBlock.

**Comment by berrythesoftwarecodeprogrammar** [comment]
inspect the lists you are using and if any of them are hosts files then uncheck them and use them in umatrix instead. and use ublock only for non-hostsfile lists. *imo*

**Comment by mailinglists35** [comment]
on umatrix:
 Peter Lowe’s Ad server list‎ (yoyo.org): 992 used out of 2,422purge cache

on ublock:
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 2,422 used out of 2,422purge cache

which one should be disabled?
