### ISSUE TITLE
Can you please also sign the uMatrix (Dev) on the same way as uBlock Origin?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#321]
Now, with the new Fx 40, there is a warning - at least for the dev version from the URL https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/ ... because it's not signed.

Can you please also open a separate Dev Channel within AMO?

Kind regards!

**Comment by gorhill** [comment]
The dev channel is only available to fully reviewed extensions:

> Beta channels are only available to fully-reviewed add-ons [[source](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance)]

uMatrix is currently awaiting full review.

**Comment by Alpengreis** [comment]
Ok, all right, thanks!

**Comment by gorhill** [comment]
uMatrix has now been fully reviewed on AMO. I can now upload dev build to AMO, and I did upload the latest build, 0.9.2.2b1.

**Comment by Alpengreis** [comment]
So good, cool!
