### ISSUE TITLE
Possible to force a site to use HTTPS?

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uMatrix#323]
With noscript I can specify that all connections to reddit should occur over https. Reddit will default to non-https otherwise. Is there a configuration within uMatrix that gives me similar capability?

**Comment by CrisBRM** [comment]
No. There's https everywhere for that.

**Comment by vdcbb** [comment]
which involves installing a whole other extension, just to filter one or two sites.

**Comment by yupi2** [comment]
@vdcbb For Reddit - https://ssl.reddit.com/prefs/security/
Your answer is to use HTTPS Everywhere (and others) since uMatrix doesn't provide that.

**Comment by CrisBRM** [comment]
uMatrix's job is not to rewrite URLs for websites that support https.

**Comment by gorhill** [comment]
> There's https everywhere for that.

That is the answer.
