### ISSUE TITLE
the lock icon to save setting for current site could be changed into something more intuitive

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#326]
i find a checkmark sign instead to be a better visual representation of a "save matrix" action.
many times i hit the eraser instead of the lock

**Comment by mailinglists35** [comment]
what does 'invalid' mean here?

**Comment by CrisBRM** [comment]
It means he disagrees and, to be fair, so do I. It's too subjective and doesn't make a difference. Locks > disquettes.

**Comment by mailinglists35** [comment]
what does "disquettes" means? do you mean floppy disk in french?
i never suggested a floppy disk icon, even if that appears to be more widespread.
a checkmark would be way more intuitive than a lock.

**Comment by mailinglists35** [comment]
also if he disagrees, then have the balls to tag it as "won't fix" instead. this is definitely not 'invalid'.
