### ISSUE TITLE
Please document 3rd Party request handling by uMatrix

### ISSUE THREAD

**Issue by ghling** [gorhill/uMatrix#327]
I'm wondering how uMatrix handles requests from 3rd party sites but couldn't find any information about this.
As far as I understand it, when I visit a.com, allow it to load stuff from b.com and b.com wants to load further elements from c.com, the requests to c.com are added to the list of the current site (a.com) so I can allow them or not.
Does uMatrix respect global rules (e.g. if a rule allows requests from b.com to c.com, does it allow those as well when they originate from visiting a.com)?
Coming from RequestPolicy, I find it a bit unclear to see if requests to c.com are made from a.com or b.com in this scenario. In RP, requests from b.com would result in a new tab where requests for b.com can be handled.

Could you please document this request handling and maybe think about a site-based blocking theme (if b.com has requests on it's own, add a separate tab to handle those).

Thank you already, I'm really liking uMatrix.

**Comment by gorhill** [comment]
The 1st-party is the base domain extracted from the URL of the page.

All direct or indirect network requests made by the page which do not match the base domain of the URL of the page are considered 3rd-party.
