### ISSUE TITLE
Updated hosts files shown as outdated

### ISSUE THREAD

**Issue by woky** [gorhill/uMatrix#328]
![](http://i.imgur.com/NQdk4yo.png)

After I manually update hosts files, their entries are still listed  as _outdated_. It's either a bug or confusing terminology.

**Comment by gorhill** [comment]
Use the logger and see if the requests to fetch the remote hosts files are blocked by uMatrix.

**Comment by 5t3f4n** [comment]
I get this too but only for ` hpHosts’s Ad and tracking servers‎` but it seems the site is having issues.

>Service Unavailable
>HTTP Error 503. The service is unavailable.

Not a uMatrix issue. At least not in my case.

**Comment by ldgbc** [comment]
Can the "date' of it been last updated be add? It would give detail on how outdated, is "outdated".
