### ISSUE TITLE
umatrix and uBlock not displayed correctly in Firefox

### ISSUE THREAD

**Issue by drm200** [gorhill/uMatrix#331]
In Firefox, in the about:config,  I set the:
     "browser.display.use_document_fonts" = 0
in order to provide a little more privacy (this is a recommended firefox security setting).   However, setting this feature to zero breaks both uMatrix and UBlock a little bit.

When this  entry is set to zero, both uMatrix and UBlock fail to display properly when you click on the icon in the toolbar..... Upon clicking the icon you will see all of the graphics is missing.

This is not a big issue ... but I think you should be aware of the interaction and consequences of setting "browser.display.use_document_fonts" = 0

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/issues/605>.

**Comment by drm200** [comment]
I missed that.  Thanks.
