### ISSUE TITLE
Best practices guidance for allowing XHR and Frames?

### ISSUE THREAD

**Issue by vdcbb** [gorhill/uMatrix#332]
I was hoping for some guidance (or direction on where I can go) to learn the safest way to configure uMatrix for dealing with XHR and Frames. Is it safe to allow 1st party Frames on reputable sites (e.g., duckduckgo.com), or is it generally best practice to always block them even for 1st party? 

A Frame is indicated by uMatrix here: https://duckduckgo.com/?q=test&ia=meanings. Yet the page looks the same whether the Frame is allowed or blocked. Is there a way to discover what the Frame is? Will this help me know whether I should allow it or nor?

I have similar questions on the safest way to configure for XHR, like if I should be leery of allowing it for 3rd party sites or whether I should treat it similarly to Scripts (e.g., if I allow Scripts, always allow XHR).

**Comment by gorhill** [comment]
> Is it safe to allow 1st party Frames on reputable sites

1st-party frames are not blocked with default settings, because if you already connected to the site, so blocking 1st-party frames are assumed safe.

> Is there a way to discover what the Frame is?

Logger.

**Comment by vdcbb** [comment]
Yes, the Logger shows https://duckduckgo.com/post2.html but I don't know what that is/means. Is there a way to see/identify where the Frame is on the page to try to understand its purpose?
