### ISSUE TITLE
Firefox wyciwyg-scheme questions

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uMatrix#334]
Go here: http://marry-mind.deviantart.com/art/Faceless-Void-Death-Prophet-556598001

These are my current rules:
![umatrix](https://cloud.githubusercontent.com/assets/930620/9550974/04d09952-4d74-11e5-89a5-9fc77bad25db.png)

Try clicking on the download button in the top-right corner. A blank window opens with nothing displayed and umatrix shows a weird `wyciwyg-scheme` I've never seen before.
![umatrix2](https://cloud.githubusercontent.com/assets/930620/9551070/8433883a-4d74-11e5-8b81-d5c49385b3ba.png)

Reading a little more into this it seems to be part of firefox's cache but I'm wondering if it's safe to add `matrix-off: wyciwyg-scheme true` to my rules?

**Comment by CrisBRM** [comment]
https://en.wikipedia.org/wiki/WYCIWYG

**Comment by gorhill** [comment]
Fixed with e8136cb6679d.
