### ISSUE TITLE
Auto reload page after dismissing uMatrix

### ISSUE THREAD

**Issue by dllud** [gorhill/uMatrix#337]
After changes were made in the matrix, it would be handy if the page was automatically reloaded when we dismiss uMatrix (by pressing Esc, clicking outside the matrix or hovering out if #336 gets implemented). Please check [NoScript](https://noscript.net/) for a working example.

This would spare us from clicking the reload icon. Such might seem irrelevant but one has to take into account that uMatrix is heavily used when in the default "blacklist all by default" mode (I have to tweak it for almost any new website I visit). Thus, by the end of the day, this accounts to a relevant number of clicks/time spent by the user. Coming from NoScript, which has this feature, I can immediately see the extra time I spend to use uMatrix.

**Comment by vdcbb** [comment]
This is on purpose. See here: http://www.wilderssecurity.com/threads/umatrix-the-http-switchboard-successor.369601/page-15#post-2489046

**Comment by dllud** [comment]
Thanks for the info.

> 1. Code was too complicated for what I consider a non-essential feature, compromising uMatrix's stability (my main goal).
> 2. The code relied in part on behavior specific to Chromium.
> 3. After using uBlock for weeks, months, I now favor having the user reload on his own when he decides so. I like it this way personally.
> 4. The matrix can be stickied in the logger, rendering auto-reload irrelevant.
> 5. The auto-reload code was buggy anyways, it did not always accomplish its purpose (because point 1. and 2. above)

Could you please elaborate on point 3? When using uBlock I had the exact opposite experience, I missed the auto-reload. For uMatrix I see little advantage on forcing the user to reload manually. The most common use case is to open the matrix, enable some domains and reload. Closing the matrix without reloading is a rare event (I've never done it).
But you could always add this as optional, though it seems most users would benefit from it. Were there any scenarios where auto-reload hindered usability?

If we consider Firefox alone point 1, 2 and 5 shouldn't be an issue. You can go to NoScript and cherry-pick their code which seems stable (both projects are GPL). 
Point 4 seems irrelevant here. If a user opens the logger she is certainly not looking for a quick use case, thus no problem on not auto-reloading.

**Comment by orklah** [comment]
@dllud I had a few experiences where a sensible page was useless because some content was blocked when using another addon which force auto refresh. When refreshing the page, a token must have been used and I couldn't use the page correctly.

However, I'm in favor of implementing the same functionnality as uBlock when disabling the addon for a page: a big refresh button easy to reach.

**Comment by Havokdan** [comment]
There should be an option, which came off by default, which auto-reload the page to close the popup of the icon.
