### ISSUE TITLE
allowing samedomain.com->samedomain.com automatically acts as if samedomain.com->1st-party is enabled

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#339]
i dont want to allow cookies and images for *.facebook.com on facebook.com but even if i block 1st-party cookies and images on facebook.com, and then allow only facebook.com images and cookies, all other subdomains automatically turn green as if 1st-party is allowed. the only solution so far seems to be to block each of the other subdomains individually.

image: https://my.mixtape.moe/gvjows.png

**Comment by gorhill** [comment]
> if i block 1st-party cookies and images on facebook.com, and then allow only facebook.com images and cookies, all other subdomains automatically turn green as if 1st-party is allowed

By design. Rules for a hostname will propagate to descendant hostnames.
