### ISSUE TITLE
feature request: allow My Rules whitelist to override 3rd party host files

### ISSUE THREAD

**Issue by jayarmstrong** [gorhill/uMatrix#341]
I'm trying to allow a domain (googleadservices.com) and have whitelisted it under My Rules but uMatrix continues to block the domain until I disable all 3rd party host files.

my line in My Rules: 

    * googleadservices.com * allow

results: when clicking on google shopping ads from a google search page, it loads [chrome-extension://ogfcmafjalglgifnmanfmnieipoejdcf/main-blocked.html?[...]] (a tab) with the following message:

uMatrix has prevented the following page from loading:
http://www.googleadservices.com/[...]

As soon as I disable all the hosts files, I am able to load the page normally.

**Comment by gorhill** [comment]
Your rule does not override existing rules for `www.googleadservices.com`. Just override the existing blacklisting of `www.googleadservices.com` (in Dan Pollck's, MVPS, hpHosts) using `* googleadservices.com * allow`.

**Comment by jayarmstrong** [comment]
excellent. Thank you for the explanation and the great addon.
