### ISSUE TITLE
uMatrix panel not respecting vertical taskbar

### ISSUE THREAD

**Issue by PatchyKnowly** [gorhill/uMatrix#342]
OS: Vista x64
Browser: Pale Moon x64

Might be specific to my setup, but very inconvenient nonetheless; I have my taskbar on the right-hand side of my screen, and when I click on the uMatrix button, the panel is only bounded by the desktop edge, causing it to be obscured by the taskbar. Behaves this way with both unmaximized and maximized windows.

![ui](https://cloud.githubusercontent.com/assets/8378762/9711896/ea57dca2-553e-11e5-9d3a-41fcf3bbeba0.png)

**Comment by vzjrz** [comment]
Just tried it on windows 7 and works for me.

**Comment by gorhill** [comment]
The popup position is controlled by the browser, not uMatrix -- this is true for all platforms. If you think the popup position is incorrect, you should report this to Pale Moon developers.

**Comment by PatchyKnowly** [comment]
Ah, thanks for letting me know. I'll go see what Pale Moon devs say then.
