### ISSUE TITLE
Adding a site row

### ISSUE THREAD

**Issue by ltcomdata** [gorhill/uMatrix#343]
Hello:

Thanks for an amazing utility!

I wish you would add a "site-only" row, just as you have a "1st party" row.  The reason for this: maybe I want to white-list all the elements of the website _useful.example.com_, but not necessarily give full rights to the domain _example.com_.  Currently white-listing "1st-party" automatically white-lists the domain, and therefore white-lists all its sub-domains as well.  So, for instance, white-listing 
_example.com_ would not only automatically white-list _useful.example.com_ - which is desired - but also _junk.example.com_ - which might be undesired.

Yes, I am aware that I don't have to white-list the 1st party by default, and I can simply white-list the actual website row when I open the site.  But then, assuming I want  these rules to persist, I would need an entry in the uMatrix rules for every website I find useful, whereas if a "site-only" row existed, then I would only need a single rule - much like the "\* \* 1st-party allow" which is the initial default.

An example where this makes a real difference is in Gmail.  When I open Gmail I want several rights automatically given to _mail.google.com_, but I don't necessarily want to give these same rights to _talkgadget.google.com_, or to _plus.google.com_, or to _play.google.com_.

Again, thank you for the amazing utility!

**Comment by vzjrz** [comment]
If you're gonna trust any link you click on to allow certain requests then I don't see the point in only allowing from the exact site you're on and not its other subdomains. If you have reasons to suspect google's other subdomains then by all means go ahead and block those.
