### ISSUE TITLE
Sync only working per browser (not uploading)

### ISSUE THREAD

**Issue by eduardoeae** [gorhill/uMatrix#345]
Using latest git version.
With sync enabled I can only download the rules previously uploaded from that browser.
With uBlock's sync, when I click to upload my rules I see immediate outgoing network traffic. With uMatrix this doesn't happen. So I conclude nothing is being uploaded.

**Comment by gorhill** [comment]
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You are not providing the necessary details for the issue to be handled.

> Using latest git version

If you are using a Chromium-based browser, syncing won't work when merely installing the uMatrix `zip` package. The steps to make it work are detailed at that link: <http://stackoverflow.com/questions/29726604/how-do-i-test-the-sync-feature-of-the-chrome-extension-during-development>. In short, you need to create a `crx` package and install the resulting package on various computers for syncing to work.

**Comment by eduardoeae** [comment]
Sorry. I forgot.
Using Firefox. I build the extension with your script in the tools folder in git.
uBlock's sync works OK.

**Comment by gorhill** [comment]
Fix is in latest dev build.
