### ISSUE TITLE
Umatrix doesn't appear to be working in Chrome 45.0.2454.85 m

### ISSUE THREAD

**Issue by jrynd** [gorhill/uMatrix#348]
I'm not sure what I did, but after the latest Chrome update, umatrix doesn't have any effect any more (everything loads unconditionally). Clicking on the uMatrix button does not bring up the matrix. Right-clicking on it gives me the popup menu with "Options", "Remove from Chrome", and "Hide Button".

Windows 7 64-bit, Chrome 45.0.2454.85 m

**Comment by CrisBRM** [comment]
Looks like a problem on your end. Go to %appdata%\Local\Google (if I'm not mistaken), and delete the application folder. Then install it again.

I don't have Windows installed anymore, but I can confirm it's working normally for me (Chromium 45.0.2454.85 / Gentoo).

**Comment by gorhill** [comment]
> Clicking on the uMatrix button does not bring up the matrix

Looks like you have a dud installation. The browser is the one bringing up the popup, so if it does not come up, something is wrong with your uMatrix installation.

**Comment by CrisBRM** [comment]
@gorhill Sometimes it's the browser's installation. Updating without deleting the 'application' folder would occasionally break my installation, namely the font rendering of some UI elements as well as the rendering of the matrix itself (it would be completely blank).

If you didn't push a uMatrix update to the chrome store, then the browser update is the only differing factor.

**Comment by jrynd** [comment]
Removed umatrix and deleted the applications directory. Redownloaded Chromesetup.exe and ran it. No umatrix obvious.y Redownloaded umatrix and it's been hung on "Adding to Chrome..." for over an hour.

**Comment by gorhill** [comment]
> Redownloaded Chromesetup.exe

From where?

**Comment by jrynd** [comment]
From https://www.google.com/chrome/

**Comment by gorhill** [comment]
Whatever the issue is, it's unrelated to uMatrix. You will have to find solutions somewhere ([example](https://www.reddit.com/r/chrome/comments/39mupa/downloads_not_finishing_0_secs_left/)), there is clearly something with your system which interferes with the proper functioning of the browser.
