### ISSUE TITLE
"report-uri" regex doesn't cover all cases

### ISSUE THREAD

**Issue by tomaszzielinski** [gorhill/uMatrix#349]
Gmail's Content-Security-Policy header ends with "`;report-uri /mail/cspreport`". 

The [existing regex](https://github.com/gorhill/uMatrix/blob/2224ece1a5af8e40df590c59e5bc2c656651a8f0/src/js/traffic.js#L406) doesn't recognize it as it expects a trailing semicolon:

```
> ';report-uri /mail/cspreport'.match(/report-uri[^;]*;\s*/)
null
> ';report-uri /mail/cspreport;'.match(/report-uri[^;]*;\s*/)
["report-uri /mail/cspreport;"]
```

The following regex seems to work:

```
> ';report-uri /mail/cspreport; ;report-uri /mail/cspreport'.match(/report-uri.*?(;|$)/g)
["report-uri /mail/cspreport;", "report-uri /mail/cspreport"]
```

You can also add "\s*" directly after the semicolon if that part is needed (it's present in the current regex).

**Comment by gorhill** [comment]
Thanks for reporting.

Looks like I spotted this when code-reviewing for uBlock, but forgot to backport the change to uMatrix.
