### ISSUE TITLE
feature request: allow sets

### ISSUE THREAD

**Issue by dhiltonp** [gorhill/uMatrix#352]
Use case:

To allow embedded youtube videos on a new site, I need to select specific permissions 3-5 times with a reload between each change.

It would be nice if I could create a 'youtube' set of permissions, which could then be enabled/disabled in one or two actions.

**Comment by hotdogman** [comment]
https://github.com/gorhill/uMatrix/wiki/Very-bare-walkthrough-for-first-time-users
You're looking for the global scope (*).

**Comment by dhiltonp** [comment]
Ah, thanks :)

David

**Comment by gorhill** [comment]
Duplicate of #30.

Hopefully One day I will find the courage to undertake this.
