### ISSUE TITLE
[Question] prevent websites from knowing my language preferences

### ISSUE THREAD

**Issue by Krysisx** [gorhill/uMatrix#354]
Hi,

is there any way to make uMatrix prevents websites from knowing my language preferences.

Thanks

**Comment by CrisBRM** [comment]
If you're using firefox, go to about:config and set ````intl.accept_languages```` to ````en-us,en````, and the ````general.useragent.locale```` to ````en-us````.

**Comment by Krysisx** [comment]
ok, is there any way to do the job in one click (something like a switch button, maybe using an extension)?

**Comment by zummuz** [comment]
@Krysisx try HeaderControlRevived it can change referrer, user agent and language for all sites and create rules for particular sites. Its for firefox. Or look for extensions which change http headers.

**Comment by Krysisx** [comment]
Thanks I'll try that, but I will search for a open source extension like uMatrix that does that.
I'd like this feature to become a uMatrix feature. What do you think? Is it possible?

**Comment by zummuz** [comment]
@Krysisx https://bitbucket.org/Torvin/headercontrolrevived/src (https://bitbucket.org/Torvin/headercontrolrevived/issues?status=new&status=open - link from firefox AMO), looks like that addon is open source.

**Comment by Krysisx** [comment]
Thanks, I also found this: https://github.com/dillbyrne/random-agent-spoofer
I think it's good and has features that I think could also be added in uMatrix.

**Comment by 2glops** [comment]
Krysisx,

There is also Modify Headers:
http://www.garethhunt.com/modifyheaders/

**Comment by zummuz** [comment]
I think language preferences can't be very helpful in user tracking as long as you don't request rare African dialect or something like that. Insecure things like cookies, caches, referrer, UA, etc uMatrix can handle, so I doubt that gorhill would approve this feature but who knows.
It's better to discuss suggestions in the subreddits and keep github for problems/issues:
https://www.reddit.com/r/ublockorigin
https://www.reddit.com/r/uMatrix

**Comment by Krysisx** [comment]
Ok thanks

**Comment by anewuser** [comment]
You can use this simple extension to change it quickly: https://addons.mozilla.org/firefox/addon/quick-accept-language-switc/

**Comment by Roman-Nopantski** [comment]
There are too many "leaks" can that give away your language: such as locale/time-zone (eg NZST = New Zealand Standard Time = probably English), date/currency formats (eg saturday vs samedi (french) vs sabato (italian) etc), keyboard hardware fingerprints and events, font enumeration - to name but a few. I haven't confirmed it, but I suspect that even the `gecko.buildID` (which reveals the build date and time down to the second) could be used to determine if the build/bundle used is English, German, French etc.

Hopefully, the Tor Uplift Project will incorporate time-zone/locale/language spoofing in the future, as they have done with screen/window metrics. It's not something that can be comprehensively handled by some preferences - the rabbit hole goes too deep.

https://wiki.mozilla.org/Security/Tor_Uplift/Tracking

**Comment by anewuser** [comment]
@Roman-Nopantski If you are paranoid to the point of thinking that websites are using your build ID and comparing it against a chart to know your language and that's somehow a problem to you, you should really just use just Tor and similar tools to browse the web.

**Comment by gorhill** [comment]
Anti-fingerprinting is best handled as a separate extension.
