### ISSUE TITLE
More Tools not react immediately when show the number of distinct requests on the icon is activated

### ISSUE THREAD

**Issue by Zitronella** [gorhill/uMatrix#356]
Steps to reproduce (uMatrix 0.9.2.1 and Firefox 40.0.3)
-New Firefox Profile
-Install uMatrix (from AMO)
-go to uMatrix Dashboard->Settings-> enable "show the number of distinct requests on the icon is activated"
-shrink/minimize Firefox, so that you can see at the top on the right "More tools..."
-load (reload) a webpage
-click on "More tools.." 
The Button "More tools" do not show the popup. You must click 2x more again, bevore it shows more tools.

You can see the behavior in an animated gif on http://mozhelp.dynvpn.de/dateien/forum/ff-uMatrix-Bug.gif

Edit: it seems the same bug is also in uBlock

**Comment by one23** [comment]
This was most likely due to [a bug in Firefox affecting icons with badges](https://bugzilla.mozilla.org/show_bug.cgi?id=1029937). If so, it should be fixed with Firefox 42.
