### ISSUE TITLE
Synchronization with a remote server (using the access rights 766, 644)

### ISSUE THREAD

**Issue by Misque** [gorhill/uMatrix#360]
want to sync feature has been implemented with any remote server \ site of http- protocol for users and groups, you can do that?

for example: «rwx r-- r--»
where the owner has every right to file: read, write, and execute it, and all the other users only read privilege

Sorry for my English, I'm using google

**Comment by Misque** [comment]
not idea? :(

**Comment by gorhill** [comment]
I don't plan to implement a sync feature which does not relies on whatever framework is provided by the browser.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
