### ISSUE TITLE
Option request: auto-close UI/matrix after Reload

### ISSUE THREAD

**Issue by Gittyperson** [gorhill/uMatrix#361]
Being on a 1680x1050 resolution, most of the times (about 8/10) I need to click Reload to check on how a website works/looks after matrix changes, I also have to close the UI because it takes up screen space and hides a large part of the page.

So, it might be useful to have an option for that, or perhaps an extra button (reload & close UI) if you think it might be possible. Thanks.

(could also apply to uBlock0)

**Comment by scosist** [comment]
This would be nice to have, or at least a config setting to enable/disable the behavior.

**Comment by gorhill** [comment]
Click <kbd>Escape</kbd> to dismiss the popup.

**Comment by Gittyperson** [comment]
Thanks gorhill. I knew about this and pressing Esc is definitively better than using the mouse for closing the UI, but it can still become a very repetitive task at times.

**Comment by ramschel** [comment]
I would love to see something along the lines of an option to enable auto-reload after a matrix change click.
