### ISSUE TITLE
[SeaMonkey] uMatrix popup is transparent

### ISSUE THREAD

**Issue by 5t3f4n** [gorhill/uMatrix#362]
Screenshot:
![uMatrix](https://cloud.githubusercontent.com/assets/11399326/10046317/6046076a-6208-11e5-8282-792807199bf8.png)
Same screenshot with increased saturation to highlight the issue:
![uMatrix edited](https://cloud.githubusercontent.com/assets/11399326/10046329/70e97d04-6208-11e5-8c9a-6b71487386d1.png)
I found a workaround and that is to toggle "Reduce transparency" in Accessibility preferences, but this is not needed for any version of Firefox that I have tried so far (39, 40 and 41).
![transparency](https://cloud.githubusercontent.com/assets/11399326/10046471/29d02f02-6209-11e5-9359-843943ccb9fc.png)
Note: This also affects uBlock Origin in the same way but it's less prominent because of the narrower popup (unless advanced mode is toggled).

`uMatrix 0.9.2.1`
`uBlock Origin 1.1.1`
`SeaMonkey 2.35`
`OS X 10.10.5 (14F27)`

**Comment by gorhill** [comment]
Does this affect other addons? (If so, it's a browser thing.)

**Comment by gorhill** [comment]
Someone with dev skills could try to add `opacity: 1;` in [`popup.css`](https://github.com/gorhill/uMatrix/blob/master/src/css/popup.css#L9), then create a local package and install it in SeaMonkey and see if this helps.

**Comment by 5t3f4n** [comment]
>Does this affect other addons?

I don't know. uMatrix and uBlock Origin are my only extensions that have popups.

>Someone with dev skills could try to add opacity: 1; in popup.css, then create a local package and install it in SeaMonkey and see if this helps.

I'm no expert but I tried this and it had no result. But perhaps I repackaged it wrong or something.

>By the way, I don't have access to an OSX install, so I can't investigate OSX-specific issues.

Would you consider installing OSX in a VM?

**Comment by gorhill** [comment]
> I don't know. uMatrix and uBlock Origin are my only extensions that have popups.

Try Ghostery, it has an HTML-based popup. That will be much easier for you to install Ghostery than for me to figure a way to obtain and run OSX.

**Comment by 5t3f4n** [comment]
>Try Ghostery, it has an HTML-based popup.

Alright I tried with Ghostery (version 5.4.8.1) and it has no transparency.

>That will be much easier for you to install Ghostery than for me to figure a way to obtain and run OSX.

Of course. I didn't mean you should go through the trouble solely for this issue but figured it might be valuable for you to have the ability to test-drive your extensions on OS X in general. I could hook you up with remote access to an actual Mac if you're interested but don't want to fiddle with VMs.

**Comment by gorhill** [comment]
Where would I find a version of OSX installable in a VM if ever I want to try OSX?

**Comment by gorhill** [comment]
I added `opacity: 1` rules in [latest dev build of uBlock](https://github.com/gorhill/uBlock/releases). Can you see if this helps?

**Comment by 5t3f4n** [comment]
>Can you see if this helps?

Using `uBlock Origin 1.1.2b1` I see no visible difference. Transparency is still there.

>Where would I find a version of OSX installable in a VM if ever I want to try OSX?

This is a fairly popular thing to do so simply search the web using your preferred search engine for "yosemite [name-of-VM]" e.g. https://startpage.com/do/search?q=yosemite+virtualbox

**Comment by 5t3f4n** [comment]
Just letting you know that the problem still occurs as of `uMatrix 0.9.2.2b5`.

**Comment by 5t3f4n** [comment]
I sometimes see this in error console. Is it related to this in any way?

`Error: TypeError: matrixSnapshot.userSettings is undefined`
`Source File: chrome://umatrix/content/js/popup.js`
`Line: 76`

**Comment by gorhill** [comment]
I will no longer support legacy Firefox and browsers based on legacy Firefox -- I don't have the time for such a low adoption extension on lower adoption browsers.
