### ISSUE TITLE
[SeaMonkey] Too many behind-the-scene requests

### ISSUE THREAD

**Issue by 5t3f4n** [gorhill/uMatrix#363]
First things first: I believe this is closely related to this: https://github.com/gorhill/uBlock/issues/211
However, that was for [Firefox] and supposedly fixed long ago, but I guess the fix didn't affect SeaMonkey so I'm creating a new issue instead of bumping that one.

I'm also not only seeing `css` in b-t-s as the other issue mentions but `xhr`, `other` and possibly more that I believe shouldn't be there. Although `css` is perhaps most peculiar since it frequently appears both in b-t-s and regular requests.

uMatrix and uBlock Origin also seem to categorize stuff differently.
For example, a .webm video is categoriezed as `media` in uBlock Origin while it's categorized as a b-t-s `other` in uMatrix.

STR: Same as other issue except using SeaMonkey.

`uMatrix 0.9.2.1`
`uBlock Origin 1.1.1`
`SeaMonkey 2.35`
`OS X 10.10.5 (14F27)`

**Comment by gorhill** [comment]
So far I haven't found a way to investigate this:

- there is no debugger for add-ons
- For some reasons using `console.log` does not work

**Comment by requiredregistration** [comment]
what about this? https://addons.mozilla.org/en-US/firefox/addon/tiny-javascript-debugger/

**Comment by 5t3f4n** [comment]
Someone posted a link to https://addons.mozilla.org/firefox/addon/tiny-javascript-debugger here but the post has since been removed for whatever reason. Reposting the link in case it's of any help.

**Comment by bayun** [comment]
Same on Linux,  SeaMonkey 2.38, uBlock Origin 1.1.1, RequestPolicy

It seems to depend on order in which extensions are initialized, as sometimes after restarting seamonkey It was working... till next restart.

If you need anything that not-very-good-with-JS programmer can do - I will be happy to help, this bug annoys me to no end.

**Comment by gorhill** [comment]
I will no longer support legacy Firefox and browsers based on legacy Firefox -- I don't have the time for such a low adoption extension on lower adoption browsers.
