### ISSUE TITLE
Strange Twitter cookie requests after going to an another site in the same tab

### ISSUE THREAD

**Issue by Kangou** [gorhill/uMatrix#368]
1) Go to Twitter, login
2) Inside the same tab, go to https://parano.be from a click to the bookmark
3) The matrix and the uMatrix log show blocked cookie requests from Twitter.

Parano.be don't do any request to Twitter when I'm going to it from a new tab.
Also, It don't do this weird thing when I'm already logged to parano.be before going to it, only when I have no session cookie from it.

My rules:

```
* * * block
* * cookie block
* * css allow
* * frame block
* * image allow
* * plugin block
* 1st-party css allow
* 1st-party image allow
* 1st-party other allow
* 1st-party xhr allow
twitter.com 1st-party cookie allow
twitter.com 1st-party frame allow
twitter.com amp.twimg.com frame allow
twitter.com amp.twimg.com other allow
twitter.com amp.twimg.com xhr allow
twitter.com pbs.twimg.com other allow
twitter.com twimg.com script allow
twitter.com twitter.com script allow
twitter.com video.twimg.com other allow
www.parano.be www.parano.be cookie allow
```

(Plus others not related to twitter nor parano.be)

Firefox 41.0, uMatrix 0.9.2.2b4, OS X Yosemite. Firefox is set to "Only allow first-party cookies".
I can also reproduce it on some other websites.
![umatrix_et_paranoiaque](https://cloud.githubusercontent.com/assets/26610/10122730/77c8b394-6521-11e5-8f37-67f3f7e3a39a.png)
![umatrix_log](https://cloud.githubusercontent.com/assets/26610/10122731/7e2a5bc0-6521-11e5-922d-33fc859e4a02.png)

**Comment by vzjrz** [comment]
Yeah really strange also got the same thing. The url you used though was: http://www.parano.be/v15/desktop.php

**Comment by Kangou** [comment]
Yep sorry, obviously my bookmark is going to https://www.parano.be/v15/desktop.php, not the root (then redirecting to login.php since i'm not logged).

**Comment by CounterPillow** [comment]
I've got a similar issue. When opening the site http://overviewer.org/~agrif/sigsample/ in a tab in which previously twitter was open, uMatrix shows fake requests for all twitter cookies. When opening the site in a new tab, those requests aren't there. The requests don't show up in the network console though, so they're not "real".

**Comment by gorhill** [comment]
This occurs because a network request to `twitter.com` is sent **after** the page has unloaded and the other page has started loading. uMatrix is told the network request to `twitter.com` was fired in the context of the new page:

![a](https://cloud.githubusercontent.com/assets/585534/16667739/ff146a04-445b-11e6-9cf2-21d5cb27dac3.png)
