### ISSUE TITLE
Blocked cookies can still be read with JavaScript

### ISSUE THREAD

**Issue by lunboks** [gorhill/uMatrix#370]
Hello! I've been using uMatrix as a cookie whitelist, and I noticed that sites with client-side cookie handling (`document.cookie`) are still able to access cookies even when they're supposed to be blocked.

I'm not sure if this is intended behavior, but I definitely didn't expect it.

Repro:
1. Go to http://www.whatarecookies.com/cookietest.asp
2. Enable scripts and disable cookies
3. Site is still able to read and write cookies

**Comment by gorhill** [comment]
> I'm not sure if this is intended behavior

Yes. This is explained in the UI of uMatrix:

> Blacklisted cookies are not prevented by uMatrix from entering your browser. However they are prevented from leaving your browser, which is what really matters. Not blocking cookies before they enter your browser gives you the opportunity to be informed that a site tried to use cookies, and furthermore to inspect their contents if you wish.

**Comment by 5t3f4n** [comment]
@lunboks: In the uMatrix Dashboard, you can go to the Privacy tab and toggle "Delete blocked cookies". This behavior may or may not be more in line of what you were expecting. Make sure you click the `(?)` button to reveal and read the info first though.

**Comment by CrisBRM** [comment]
Just to clarify: the 'delete blocked cookies' option makes it so that blacklisted cookies are immediately deleted upon entering the browser and being accounted by uMatrix.

**Comment by gorhill** [comment]
@CrisBRM Yes, except remove "immediately": it's done in a lazy way. Cookie deletion is an asynchronous operation.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I find doing that breaks websites very fast, so what I do is enable them for the sites than really want them and use self-destructing cookies to supplement umatrix.
