### ISSUE TITLE
add more domain suffixes

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#372]
are ALL domain suffixes included in umatrix (and maybe ublock?) only from publicsuffix.org? i realised that a lot of tor proxies should probably treated as suffixes. e.g:
```
onion.cab
onion.city
onion.direct
onion.link
onion.lu
onion.nu
onion.sh
onion.to
tor2web.blutmagie.de
tor2web.fi
tor2web.org
torstorm.org
```
some of those may be outdated now but you get the point. are there currently any custom suffixes in umatrix/ublock which some of these could be added to? or do i need to contact the site owners and get them to submit to publicsuffix.org

edit: also is the list updated in umatrix/ublock whenever publicsuffix updates their list?

**Comment by gorhill** [comment]
> are ALL domain suffixes included in umatrix (and maybe ublock?) only from publicsuffix.org?

Yes. I make absolutely no exception, whatever is in the list or not decide what is a suffix or not. If you think the above suffixes should be in there, submit to the maintainers of the Public Suffix List.
