### ISSUE TITLE
Installed latest release, still have the old one

### ISSUE THREAD

**Issue by Krysisx** [gorhill/uMatrix#374]
Hi,

I have just installed the latest version 0.9.3.0rc1, but it says that I still have the 0.9.2.3.
Is it normal or not?
I have firefox 41.0.1 and Linux Mint 17.2.

Thanks

**Comment by Snapy** [comment]
It's normal : gorhill didn't change the [version number](/gorhill/uMatrix/blob/master/platform/chromium/manifest.json#L5) but you should have the latest version.

**Comment by gorhill** [comment]
I had changed it but forgot to commit the change.

**Comment by Krysisx** [comment]
great, thanks
