### ISSUE TITLE
white list option for http referrer spoofing [enhancement]

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [gorhill/uMatrix#375]
Hi there, I would really dig an option like this. I don't know if there are extensions out there to do this or if it's even possible but if so I think it would be great for issues like https://github.com/gorhill/uMatrix/issues/358

Thanks again for your hard work on this extension gorhill.

**Comment by gorhill** [comment]
I don't understand what "white list option for http referrer spoofing" means.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
You have a Spoof HTTP referrer string of third-party requests option in uMatrix, I'm asking if it's possible to exclude sites such as googlevideo/youtube from this feature while keeping it on for most other things. 

Is it fesable and or possible to make this a feature? Or if you could suggest an extensions capable of this that would be great to supplement uMatrix, thanks!

**Comment by vzjrz** [comment]
I use https://addons.mozilla.org/en-us/firefox/addon/referrer-control/ and it works great.

**Comment by gorhill** [comment]
You can turn referrer spoofing on a [per-site basis](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches), but I don't plan to have a column in the matrix just for referrer spoofing.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
fair enough thanks
