### ISSUE TITLE
some images are shown even if images are blocked 

### ISSUE THREAD

**Issue by ksumesh21** [gorhill/uMatrix#378]
my rules contain
- - \* block
- - image block

But on doing a google search some images are shown .

And  google image search also shows some top most result , even though uMatrix rules are set to  block images globally

**Comment by gorhill** [comment]
Confirm these images are not blocked through the logger. uMatrix blocks network requests, it won't block inlined resources through `data:` or resources present in the memory-based browser.

**Comment by gorhill** [comment]
No feedback from user. assuming `data:` URIs, which are inlined in the source code.
