### ISSUE TITLE
mc.yandex.ru cookie

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#379]
0) Enable "Block 3-rd party cookie" in [Chromium win64](http://chromium.woolyss.com/download/) settings
1) Enable hpHosts’s Ad and tracking servers‎ (which contains `127.0.0.1 mc.yandex.ru`)
2) Install [this](https://chrome.google.com/webstore/detail/musicsig-vkontakte/hanjiajgnonaobdlklncdjdmpbomlhoa) extension
3) go to http://www.kinopoisk.ru
4) mc.yandex.ru somehow installed a cookie

**Comment by gorhill** [comment]
> Blacklisted cookies are not prevented by uMatrix from entering your browser. However they are prevented from leaving your browser, which is what really matters. Not blocking cookies before they enter your browser gives you the opportunity to be informed that a site tried to use cookies, and furthermore to inspect their contents if you wish.

**Comment by mikhaelkh** [comment]
So any ad server which uMatrix supposedly blocks can install cookies?

**Comment by gorhill** [comment]
> If network requests are cancelled before they leave the browser, how can a site install a cookie?

Hmm yes, this should not happen. Let me try to reproduce.

**Comment by gorhill** [comment]
I can't reproduce. I visited `http://www.kinopoisk.ru`, and there was not a single network request to `mc.yandex.ru`.

**Comment by gorhill** [comment]
Ok, I visited a link from the from page of the site, and finally got blocked network requests to `mc.yandex.ru` for a `script` resource. However, no cookies were installed from that domain. So I can't reproduce.

**Comment by mikhaelkh** [comment]
It turns out you need to install [this](https://chrome.google.com/webstore/detail/musicsig-vkontakte/hanjiajgnonaobdlklncdjdmpbomlhoa) extension to reproduce the problem.

**Comment by gorhill** [comment]
> It turns out you need to install this extension to reproduce the problem

Unfortunately, Chromium was changed in such a way that uMatrix can no longer see and process network requests which originate from other extensions. See #338.

**Comment by mikhaelkh** [comment]
I know that, privacy now allows crappy extensions to what they want;(

**Comment by gorhill** [comment]
Actually, uMatrix may at least be able to delete these cookies even if it is unable to intercept network requests from other extensions. uMatrix's cookie management also act as a cookie janitor and whatever cookies are stored in the browser, uMatrix will regularly process them and see if they need to be deleted -- if the option to delete cookies is checked.
