### ISSUE TITLE
Add support for installation on Thunderbird

### ISSUE THREAD

**Issue by Big--Mike** [gorhill/uMatrix#380]
Hi, I'm very happy with uMatrix on my Firefox Browser and tried to install this addon on my Thunderbird, too - but got the error, that this isn't supported.

The reason for installing this addon in Thunderbird is, that I'm using Thunderbird as RSS reader and therefore am also watching web sites inside Thunderbird. 

It would be nice to add Thunderbird support if this doesn't need to much code changes. :)

**Comment by CrisBRM** [comment]
You can use uBlock Origin in the meantime.

**Comment by Big--Mike** [comment]
Thank you for the hint, but I get the same error about Non-compatibility for uBlock Origin - it seems not to be compatible with Thunderbird, too.

**Comment by CrisBRM** [comment]
Did you try the latest version from github? It does have basic thunderbird support https://github.com/gorhill/uBlock/commit/7501447cace6832ee8b8423689ac989cc914bcdc

**Comment by Big--Mike** [comment]
No, I tried the version from addons.mozilla.org. I'll wait, until it's officially updated there.

**Comment by gorhill** [comment]
There is a beta version in the [dev channel of uBlock Origin on AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta) -- you can install from there.
