### ISSUE TITLE
Add legacy toolbar button on firefox

### ISSUE THREAD

**Issue by eduardoeae** [gorhill/uMatrix#382]
uBlock already have this, could you add it to uMatrix as well?
I use vimperator and the normal button on the vimperator's toolbar doesn´t open the menu. For now I can circumvent this issue, but it adds another problem.

**Comment by Raziel-23** [comment]
I can answer your question, because for me it was also the issue. uMatrix has already this feature, but you have to manually add extensions.umatrix.forceLegacyToolbarButton entry as boolean type and set it to true. After restarting firefox it should works, for pentadactyl it works.

**Comment by eduardoeae** [comment]
I love you!
It would be nice to have that preference shown by default in about:config though. But good enough for me.
