### ISSUE TITLE
Visual glitch when hostname is too long

### ISSUE THREAD

**Issue by user65478** [gorhill/uMatrix#383]
Hi,

some hostnames are too long for uMatrix. Then they will not entirely fit into the table and will partially leak into the neighboring areas, like the following screenshot demonstrates: (notice the black spots between some cells):
![Image](http://fs5.directupload.net/images/151017/6ngsqwg9.png)

My browser: Firefox 41

Steps to reproduce (example):
1. Visit [focus.de](http://www.focus.de/)
2. Open uMatrix panel

**Comment by gorhill** [comment]
Duplicate of #46.
