### ISSUE TITLE
dns-bh.sagadc.org error

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#388]
Error downloading `Long-lived malware domains‎ ` from http://dns-bh.sagadc.org. Maybe other [mirror](http://www.malwaredomains.com/?page_id=29)?

**Comment by gorhill** [comment]
Works from here. In any case, I can't keep changing the URL every single time there is one failure. If this is a longer term breakage I will change it.

**Comment by mikhaelkh** [comment]
This webpage is not available. Again.

**Comment by mikhaelkh** [comment]
Now I can't update Malware Domains (and long-lived) from http://malwaredomains.lehigh.edu/.
