### ISSUE TITLE
Script targeting uMatrix in order to spoof and disable

### ISSUE THREAD

**Issue by Kalthorn** [gorhill/uMatrix#391]
I was curious why thepiratebay was suddenly showing images in Firefox Nightly.  The UI for uMatrix was just empty, no 1st Party rows or anything.  I then found and updated to the uMatrix dev channel and the matrix UI appeared again.

The location was spoofed to be "blank.about-scheme" so glanced in the source and see this in my page head:

```
<script id="umatrix-ua-spoofer" type="text/javascript"> ;(function() { 
     try { 
         /* https://github.com/gorhill/uMatrix/issues/61#issuecomment-63814351 */ 
         var navigator = window.navigator; 
         var spoofedUserAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0"; 
         if ( spoofedUserAgent === navigator.userAgent ) { 
             return; 
         } 
         var pos = spoofedUserAgent.indexOf('/'); 
         var appName = pos === -1 ? '' : spoofedUserAgent.slice(0, pos); 
         var appVersion = pos === -1 ? spoofedUserAgent : spoofedUserAgent.slice(pos + 1); 
         Object.defineProperty(navigator, 'userAgent', { get: function(){ return spoofedUserAgent; } }); 
         Object.defineProperty(navigator, 'appName', { get: function(){ return appName; } }); 
         Object.defineProperty(navigator, 'appVersion', { get: function(){ return appVersion; } }); 
     } catch (e) { 
     } 
 })();</script>
```

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think that code is inserted by umatrix if you have the useragent spoofing enabled. there isnt any evidence that the page location was spoofed? might just be another issue with the nightly

**Comment by gorhill** [comment]
That's code uMatrix injects when user agent-spoofing is enabled -- so that the `navigator.userAgent` matches the one used to spoof the `User-Agent` header.

**Comment by Kalthorn** [comment]
Ha, yeah, that obvious possibility didn't even occur to me.  After berry's comment I did some more testing and it seemed to be an intermittent problem with Nightly.  Thanks.
