### ISSUE TITLE
Blocked all cookies, still site manages to set a cookie.

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uMatrix#392]
![Screenshot 1](https://i.imgur.com/LO2hBFm.jpg)
![Screenshot 2](https://i.imgur.com/G5aVSpL.jpg)

uMatrix 0.9.2.1
Firefox 41.0.2
Windows 8.1 Pro 64 bit

**Comment by benoit-pierre** [comment]
This is normal, see the help text for the **Delete blocked cookies** option:

> Blacklisted cookies are not prevented by uMatrix from entering your browser. However they are prevented from leaving your browser, which is what really matters. Not blocking cookies before they enter your browser gives you the opportunity to be informed that a site tried to use cookies, and furthermore to inspect their contents if you wish.

**Comment by gorhill** [comment]
By design. The same way uMatrix blocks outbound network requests, it blocks outbound cookies.
