### ISSUE TITLE
Referrer spoofing

### ISSUE THREAD

**Issue by seafox** [gorhill/uMatrix#393]
Re my [first observations](https://addons.mozilla.org/en-US/firefox/addon/umatrix/reviews/757866/).

The core ideology of uMatrix is the total control over the security leaks. To consciously allow something and deny unknown by default. That gives the best security. The big question is could a user with uMatrix cope with constant overhead of adding rules as he surf? Note, uBlock Origin doesn't even contain the feature, for exactly this reason!

Let's take youtube videos embedded on so many pages. Its very frustrating experience to add the rules for each site containing videos like youtube, as it would require disabling referrer spoofing on per site basis. All the trouble just to see the embedded videos. We need a smart way to code dynamic rules, such as "if page contains youtube.com links, assume it has built-in video frames, thus disable referrer spoofing for the page". But how can we know the site to load contains youtube links prior to calling it from the browser when it has to decide whether spoof the referrer or not? If anyone knows the solution, then great, its doable!

So if we can't get the info prior to parsing the page, the best remaining workaround would be just marking the video to open in its own "home" page (like www.youtube.com for youtube) and simply wrapping it inline to the special placeholder space or icon with the link to click. That would be different from the current two options for blocked items, when very small arrow up with link address shown or just the entire part is hidden altogether. Or, maybe iframe wrapper with \* youtube.com allow global permission will work better?

Thoughts?

**Comment by 5t3f4n** [comment]
I think your first paragraph hits the nail on the head. uMatrix is not for everyone. For everyone else, there's uBlock Origin. I can only speak for myself of course, but I use uMatrix to have complete control. I don't want it to do any guesswork.

As for your suggestion, I believe it would be ultimate pointless. YouTube links/embedded videos are so extremely common that you might as well just leave spoofing off by default…

The better solution IMHO is to edit the list of UAs you're spoofing to only include UAs close to your own. Yes, this will make it slightly less random but you'll still be reporting a false browser version and/or operating system while making sure the site serves you content that will work with your browser.

For the site rules (whether to allow scripts, xhr, frames etc.) simply change your scope to `*` while unbreaking the site and it should work on most other sites as well.

**Comment by ebugusey** [comment]
Is this related to #405 ?

**Comment by seafox** [comment]
@ebugusey yes, all #320, #358, #393, #405 have the same root. Am I getting it right the issue is not present on Chrom(ium) and is FF specific?

**Comment by ebugusey** [comment]
@seafox as you can see from #405 in 0.9.3.1 referrer spoofing for Origin field has been disabled. So, it's not a problem now. You don't need to disable this feature for youtube.

**Comment by seafox** [comment]
Seems like in 0.9.3.1 there is more strict/different rules than current devel. version rc2.
I had not touched the rules except enabling referrer spoofing in rc2 - it worked OK.
After installation of 0.9.3.1 release and enabling referrer spoofing YT videos work, but on some sites I do not see youtube background embedded images (i.e. the picture shown on youtube video canvas before playing video) in current FFox release. I see only the vidio title, big play icon in the center on black background. Example: http://censor.net.ua/video_news/359001/vstan_kogda_ya_s_toboyi_razgovarivayu_ya_lider_partii_gpu_i_sbu_pokazali_film_o_zaderjanii_korbana_video

**Comment by gorhill** [comment]
> on black background

I see the placeholder image fine if allowing `s.ytimg.com`, more specifically if allowing scripts for `s.ytimg.com`.

> than current devel. version rc2

There is no current dev build, 0.9.3.1 is the last build.

**Comment by seafox** [comment]
@gorhill 
I have global domain * level YT enabled: www.youtube.com + frames AND s.ytimg.com + scripts.
See screenshot: http://i63.tinypic.com/5yeo1y.jpg
Note: after browser restart it's 100% reproducible black background, but after some manipulations it might start to show the normal image background!

**Comment by gorhill** [comment]
@seafox Yes, I can reproduce with FF. The logger says the image, located at `https://i.ytimg.com/vi_webp/i3l9jxAoUp8/hqdefault.webp` is not blocked. I fix the issue by disabling UA spoofing for the site. You can also keep UA spoofing enabled, but use only Firefox-related UA strings -- this is a good idea in general.

**Comment by seafox** [comment]
Yes, removing all UA strings with AppleWebKit fixes that. But then we have only 2 options for FF UAs - more required! Related thought: why not to make random UA selector to choose only FF containing strings automatically, w/out the need for users to hash them manually? Also, looks like all those problems are FF related as Chrome works fine also with AppleWebKit strings.

**Comment by ebugusey** [comment]
>But then we have only 2 options for FF

See https://github.com/gorhill/uMatrix/wiki/Latest-user-agent-strings#firefox-39
>Chrome works fine also with AppleWebKit strings
Because it is a webkit based browser.

**Comment by seafox** [comment]
@gorhill
1. Thanks for extra UA strings. Bad that they are excluded from _any_ updates. Would you consider a chekbox option to keep (either restore or include) default UA strings to the existent user config?
2. New included string "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0" doesn't work with latest FF release on Win7 - check the same [link above](https://github.com/gorhill/uMatrix/issues/393#issuecomment-153306741)

**Comment by the8472** [comment]
> Let's take youtube videos embedded on so many pages. Its very frustrating experience to add the rules for each site containing videos like youtube

I think that's not a problem specific to referrers. It's a problem of nesting.

Essentially a youtube-embed on a 3rd party site is one atomic item that you want to allow. With all the sub-items not being related to the embedding site but to the embedded site due to CORS-isolation.

In other words, there are two different concerns

a) is site A allowed to make a specific type cross-origin request to site B (e.g. embed a youtube iframe)
b) if a site B resource is cross-origin embeded in any site then allow it to load X, Y and Z.

Note that an embed is distinct from a top-level load. E.g. if you load youtube on the top level you may want to let it access google.com and send cookies so you get your youtube-login. But when you embed it on a 3rd party site you only want to allow the minimal amount of requests necessary to make it work.

I outlined similar thoughts in #318

**Comment by the8472** [comment]
Or to put it even more strongly, the permissions granted currently are to coarse-grained.

Let's expand the scenario:

* nytimes.com links to a youtube.com video
* nytimes also embeds google ads
* let's hypothetically assume the youtube.com video is some sort of sponsored thing that *only* works if youtube can play ads, thus has a dependency on google ads
* youtube.com also has a depdendency on googlevideos.com

what the user wants to allow:

nytimes.com -> youtube.com -> googlevideos.com
nytimes.com -> youtube.com -> ad.doubleclick.net [we're not happy about this one, but at least we strip cookies here]

what the user does not want to allow:

nytimes.com -> ad.doubleclick.net
nytimes.com -> googlevideos.com
youtube.com -> nytimes.com

or any other combinations that might possible by the current rules.


Ideally this would be represented as a path along a directed graph. But I think we can get away with specifying specific edges. I already suggested the embedded submatrix in #318, another option would be adding new scopes specifically for embedded content. That way one could allow the embed with one rule in the top level scope and just manage all the dependent requests in the subscope, once for all sites that embed that subscope.

![scopes for embedded content](http://i.imgur.com/Gt7KNgu.png)

**Comment by seafox** [comment]
@the8472,
Looks like you are essentially proposing changing uMatrix to uCube...

**Comment by the8472** [comment]
@seafox, well, we already have at least 2 matrices anyway, through the scopes. My suggest is either adding more or embedding one matrix into a larger matrix as already suggest in #318:

 ![embedded matrix](https://camo.githubusercontent.com/939631396332bf1390025cb55393f655a4f519ca/687474703a2f2f692e696d6775722e636f6d2f6f7051584d58582e6a7067)


Like I said above. ideally we would describe a graph, but in light of usability and the "matrix" branding I'm considering some reductions. I think the UI issues are definitely solvable.

**Comment by deathtrip** [comment]
Embedding another matrix into the default one, like in the image above, will just make the interface clogged and unintuitive.

**Comment by the8472** [comment]
Offering some link to jump from the embedding-point to a new matrix would also be an option.

I think the UI-aspect can be solved, how exactly may be down to individual preferences, I'm just trying to demonstrate that it is possible.

**Comment by johnswolter** [comment]
If I can learn all the jargon, browser issues, discover my browsers' & uMatrix's theory of operations, problem descriptions, and solutions I might gain some useful information.   Oh wait.....I need to make money and get some sleep too..[wink, wink,...]

**Comment by johnswolter** [comment]
How would I override for one viewing this doubleclick monster,  this discussion reads like it could be relatyed to this issue..
https://googleads.g.doubleclick.net/aclk?sa=l&ai=C60uYDE0vWMmyH5aNmQTMiLLoC5-g-KNHkozMyPACwI23ARACIOP7kwMoAmDJvquJkKToD6ABhd-Z2wPIAQGoAwGqBJ4BT9Cp8dcASA8fSNslD2tadyK9-u9Jmdk6Os5-nM224clCkp7TzXxArh3a6l-Xrvo_XTSgMkc1g5dkU-ARxlSJuBPFHPI_WHXUYNF8hx9fO53LdBjoFc99t2LWm7supO9c1VMv4hxg47h8Fd4ViQ__knm4JAGTKGMaprD8O1DTS2xdmoJqjBAexQp0uHTMw1M3ViA8ldLCDMX2XEcfle2gBhrIBrv0s-vhAYAH46DmJKgHpr4b2AcB0ggFCMBhEAG4E-gB&num=2&cid=CAASSeRoz9i-cBUHZblMyzAAS7fubyYD7pn5RzTwiFxtNk1nZhVITVCY9tBFNxi7rCYgbYY3p8rycOLCNVAhqeoJakF_EXBycihspNQ&sig=AOD64_2oUkfNshBz5u_95VJeivl590yBlg&ctype=21&video_id=lm3JsPibKB4&client=ca-pub-6219811747049371&adurl=http://www.youtube.com/watch%3Fv%3Dlm3JsPibKB4

**Comment by gorhill** [comment]
Time passed and I am no longer sure what the specific issue is for me to fix. So closing as _wontfix_, and if there was anything I missed here, which is focused, specific and actionable, the please open a new issue about it.

Just in case, re-writing the core filtering code is not something I will consider, so no point opening an issue for this.
