### ISSUE TITLE
Cloud Storage?

### ISSUE THREAD

**Issue by Jokler** [gorhill/uMatrix#397]
I noticed the cloud storage functionality in uBlock Origin a while ago.
Now i wondered if you couldn't implement the same for uMatrix as I have most of my rules in that.

**Comment by user65478** [comment]
![SRSLY](http://www.threadbombing.com/data/media/4/Srsly.jpg)
It's already implemented. You only have to look at the release page.
--> https://github.com/gorhill/uMatrix/releases

**Comment by Jokler** [comment]
http://www.nooooooooooooooo.com/
