### ISSUE TITLE
3rd party filter, NOR: Norsk adblockliste‎ no longer exists

### ISSUE THREAD

**Issue by grrrrr** [gorhill/uMatrix#398]
The 3rd party filter `NOR: Norsk adblockliste‎` located at http://home.fredfiber.no/langsholt/adblock.txt  no longer exists.

I can find one [forum post](https://forums.lanik.us/viewtopic.php?t=22993) that makes mention of it no longer existing and links to a [year old mirror](https://github.com/ytakano/adchecker/blob/master/adblock.txt) of the list on github

**Comment by gorhill** [comment]
uMatrix does not use this filter list. You meant to open an issue for uBlock?

**Comment by grrrrr** [comment]
*facepalm* yes I did
