### ISSUE TITLE
Faded green/red cells should be the same color in all scopes

### ISSUE THREAD

**Issue by pjvandehaar** [gorhill/uMatrix#401]
These colors tell me whether requests were allowed or blocked:
<img width="532" alt="screen shot 2015-10-29 at 6 30 57 pm" src="https://cloud.githubusercontent.com/assets/862089/10833864/7154b0a4-7e6b-11e5-9885-3dfb9f8755c1.png">

These colors do not:
<img width="532" alt="screen shot 2015-10-29 at 6 24 35 pm" src="https://cloud.githubusercontent.com/assets/862089/10833863/715485e8-7e6b-11e5-92d9-5fa75ccee3db.png">

**Comment by gorhill** [comment]
> Currently, it's deceiving.

There is nothing deceiving: the global scope shows you what happens to network requests when evaluated against the global scope, and the local scope shows you what happens to network requests when evaluated against the local scope. Without this, it would be impossible to visually create rules for a specific scope without the scope providing a visual feedback of the rules.

**Comment by pjvandehaar** [comment]
Thanks for explaining that.

It seems odd that I set `* 1st-party * allow`, a global-scope rule, but it is only evaluated by the site scope.  If this makes sense in the implementation, that's fine I guess.

Anyways, thanks bunches for uBlock/uMatrix.

**Comment by gorhill** [comment]
> It seems odd that I set `* 1st-party * allow`, a global-scope rule, but it is only evaluated by the site scope

Yes, however its presence in the global scope is necessary, just for the sake of being able to create _default_ `1st-party` rules.

**Comment by CrisBRM** [comment]
An easy way to interpret the matrix is to view everything as an aggregate of transparent, hierarchical layers that inherit properties from the top down — everything you do to the global scope is inherited by the local scope without overwriting existing local rules. Conversely, what you do to the local rules does not affect the global scope because it's a narrower scope, at the bottom of the hierarchy.

**Comment by pjvandehaar** [comment]
Alright, this makes sense now.
