### ISSUE TITLE
uMatrix not detecting elements and breaking Youtube History

### ISSUE THREAD

**Issue by EgorkaSanyok** [gorhill/uMatrix#402]
I have tested this using Firefox 41.0.2 as well as Chrome 46.0.2490.80 with uMatrix 0.9.3.0rc2. This was my initial matrix, which only affects the Youtube History function (namely, the videos I watch don't put themselves in the list):

![...](http://i.imgur.com/lLAQcIU.png)

After enabling and disabling a few features, and trying to find a matrix combination for which the history would work, I have narrowed it down to this combination:

![...](http://i.imgur.com/ku2zlv4.png)

Namely, after enabling the image elements AND the cookie elements of s.youtube.com (which is globally blacklisted by default), the History function works again. If you disable one of them, the History breaks again, which means that there is a weird dependence between them.

This leads to my question. Is uBlock not detecting that there is a cookie that activates this function which belongs to s.youtube.com or does it run deeper than that? And how come those two object types are dependent on eachother?

If it is of any concern, I have disabled Referrer spoofing specifically for youtube.com (it is globally on), hyperlink auditing attempts are blocked, delete local storage content set by hostnames is on, and it is clearing cache every 60 minutes.

**Comment by DjogaRo** [comment]
Sounds like what I'm/was experiencing. I made it a topic here:
http://forum.palemoon.org/viewtopic.php?f=26&t=10032

Don't know about chrome, but could it be that you find that in FF settings (url: about:config) which start with "browser.history.allow" are set to false? If so, for me worked prohibiting XHR for youtube. Same goes for google and for github within projects. Though the work-around doesn't work for the latter completely.

**Comment by EgorkaSanyok** [comment]
I haven't tried setting those values to false, but blocking XHR for youtube prevents expanding the menu on the left using the menu button. Even if it could work on youtube, I'd rather not have this tradeoff :smile:

**Comment by DjogaRo** [comment]
Never recognized that menu there. :) This workaround isn't a good solution for me either. My point was more about finding out, if those settings break it for you - or to rule that out, thus gaining information.

**Comment by CrisBRM** [comment]
This is hardly a uMatrix bug.

**Comment by gorhill** [comment]
> Namely, after enabling the image elements AND the cookie elements of s.youtube.com (which is globally blacklisted by default), the History function works again. If you disable one of them, the History breaks again, which means that there is a weird dependence between them.

There is no bug. The fact that no cookies are reported in the matrix for `s.youtube.com` means that there are no cookies with the specific domain `s.youtube.com`, but this does not mean that no cookies are sent in the `Cookie` header of network requests to `s.youtube.com`: some cookies are designed to also be sent to subdomains, and I an guessing it is the case here.
