### ISSUE TITLE
0.9.2.1 stopped working between Nightly 2015-10-19 and 2015-10-20

### ISSUE THREAD

**Issue by aleksejrs** [gorhill/uMatrix#403]
Everything is green and allowed, no "1st-party" row.

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1a157155a4fe0074b3d03b54fe9e466472c2cd56&tochange=f7b746b4e91307448cb0746a41f677bfc23908b0

**Comment by gorhill** [comment]
Can I see a screenshot of your matrix for a web page where the issue occurs?

**Comment by aleksejrs** [comment]
![umatrix-broken-green-yandex](https://cloud.githubusercontent.com/assets/1025861/10866110/f5a4ec0c-8032-11e5-844e-ef4d4b22e5bb.png)

**Comment by aleksejrs** [comment]
good 2015-10-19-03-02-27-mozilla-central-firefox-44.0a1.ru.linux-x86_64
bad  2015-10-20-03-13-17-mozilla-central-firefox-44.0a1.ru.linux-x86_64

**Comment by gorhill** [comment]
There is nothing wrong: matrix filtering is turned off in your screenshot.

**Comment by aleksejrs** [comment]
Maybe (enabling filtering makes it look normal), but
1. Where is "1st-party"?
2. Why does it start with Firefox Nightly 2015-10-20?

**Comment by gorhill** [comment]
Do you have uBlock Origin installed? If so, can you see if you get the same problem with it with the dynamic filtering pane?

**Comment by gorhill** [comment]
You may want to confirm this also happens with the [dev build of uMatrix](https://github.com/gorhill/uMatrix/releases), which is also available for on AMO, in the developer channel.

**Comment by aleksejrs** [comment]
Ah, I hadn't really read that paragraph.  0.9.3.0rc2 seems to work properly with the nightlies.

**Comment by gorhill** [comment]
>  0.9.3.0rc2 seems to work properly with the nightlies.

Ok, I think it's time for me to officially release this one, it has been _release candidate_ forever now.

**Comment by aleksejrs** [comment]
As for uBlock Origin, its UI seems to differ enough that I can't immediately tell if anything is wrong.

**Comment by aleksejrs** [comment]
> I think it's time for me to officially release this one

Yes, it's also a problem with Firefox Dev Edition.
