### ISSUE TITLE
The matrix skips 2nd-Level Domain [Pale Moon & Firefox]

### ISSUE THREAD

**Issue by DjogaRo** [gorhill/uMatrix#404]
Hi there,

after uMatrix' update from 0.9.2.1 to 0.9.3.0, I recognized that the row for githubusercontent.com is missing:
<Here two screenshots were meant to be. Cannot upload as png nor as jpg nor as gif! It's just saying
"Something went really wrong, and we can’t process that file. Try again.">

As could have been seen above, on `https://github.com/*` I get rows for `*.githubusercontent.com`, but the one for `githubusercontent.com` is not shown. And I just noticed it's the same for `github-cloud.s3.amazonaws.com` - for the higher domains there aren't rows in the matrix.

My matrix let me deduce having a filter `github.com githubusercontent.com image allow`, which I indeed can find in the dashboard. Since I can't recall, writing filters by hand, I then thought, this bug is new - which is why I haven't looked back too far, if there's already an issue on this -, but further testing in parallel to writing this suggests otherwise. So I must have added saif filter manually - I guess.
(And I already had a feeling this issue isn't new to me. I hadn't bothered that much, it seems.)

Reproduced on (with new profiles):
```
PM 25.7.3          - uM 0.9.3.0              - but here with my everyday profile
PM 25.7.3          - uM 0.9.2.1 & 0.9.3.0rc2
FF 40.0.3 & 41.0.2 - uM 0.9.3.0
FF 24.8.1esr       - uM 0.9.2.1 & 0.9.3.0
```
**Edit**: on Windows 7 x64 - PM is x64, too

If you cannot reproduce this, feel free to tell me where in the code to look. It's not that pressing to me and I'm after something else right now, but sooner or later I'd investigate.

BTW, you do wish not to see feature requests on the issue tracker. Where would those go, then? I'd have three of them. :)

**Comment by vzjrz** [comment]
githubusercontent.com and s3.amazonaws.com are all in the Public Suffix List: https://publicsuffix.org/list/

**Comment by DjogaRo** [comment]
I see. Didn't know about that list. Thank you.
Not an issue then.
