### ISSUE TITLE
uMatrix 0.9.3.0 doesn't load youtube videos when spoof http referrer is enabled

### ISSUE THREAD

**Issue by mooglestiltzkin** [gorhill/uMatrix#405]
uMatrix 0.9.3.0 (which i updated to today) doesn't load youtube videos when spoof http referrer is enabled

Disabling this feature "Spoof HTTP referrer string of third-party requests." restored youtube function.

never had this issue with 0.9.2.1

**Comment by Snapy** [comment]
Duplicate of #358 (see [this comment] (/gorhill/uMatrix/issues/358#issuecomment-147205686)).

**Comment by mooglestiltzkin** [comment]
to be fair those were rc1, this is final release :X ty for the link i can see whats going on. apparently it wasn't resolved still :{ unfortunately.

**Comment by gorhill** [comment]
I pushed a new release, 0.9.3.1 -- in which spoofing of the `Origin` header is removed for now.
