### ISSUE TITLE
Save Page As w/o disabling

### ISSUE THREAD

**Issue by grumpygeek** [gorhill/uMatrix#407]
I want to be able to use "Save Page As" to save a page I'm viewing to HDD without having to disable uMatrix to do so.   (It's not easy to tell from the icon when it is disabled so I sometimes forget to re-enable.)  I admit I could have overlooked a rule regarding this, but I did check and didn't see anything obvious.  If possible I'd like it to just be for user initiated action, not something a web page script could do without me noticing, but that is secondary.

**Comment by gorhill** [comment]
You are not providing much details, I don't even know which browser you are using. See [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by grumpygeek** [comment]
Waterfox 40.0.2 at the moment.  If I knew of any specific relevant details, I would add them.  But I assumed it was probably something easy I had overlooked.

**Comment by grumpygeek** [comment]
Here's a little more: enabling "Other" for the site allows saving to work.   This "Other" category is a bit vague to me so I'd prefer a global setting to specifically just allow saving page if that is possible.  I hope that's clear.

**Comment by berrythesoftwarecodeprogrammar** [comment]
do you have behind-the-scene connections blocked? i was doing experimenting yesterday with `behind-the-scene * * block` and it seems any kind of download falls under `other`, even images etc. if you're saving something it falls under `other` and its origin is `behind-the-scene`. not sure if its the same with saving pages but im guessing it is

**Comment by gorhill** [comment]
https://github.com/gorhill/httpswitchboard/issues/407#issuecomment-54474067

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah i figured

**Comment by berrythesoftwarecodeprogrammar** [comment]
OP shouldnt be having this problem though unless they blocked behind-the-scene requests

**Comment by grumpygeek** [comment]
I don't know if I blocked everything, but I guarantee you I tried. :)  That's what I use these addons for.  Same with NoScript and RequestPolicy, which I can now do without if I get uMatrix setup right.  Then I reenable just what I want as I come to it.   That's why uMatrix suits me better than uBlock Origin.   I can live with this if I have to.  BUT, there is no danger and no reason to block saving a page, that's a basic function of browsing.  (Yes, I read the explanation, nut that just explains why it's not working right.  It's Mozilla's fault; I never did like the way that worked.  Saving a page should use the file that is already in the cache, not download another copy; then it's just a simple local file copy process and no concern with internet protocols.)  I may see if I can an addon to give me the cache file name (that was built in to Opera years ago) and then just copy that file to the right folder - even a bigger pain but I'll be beating them at their own game.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i try to do the same. this is the base of what im working with:
```
https-strict: * true
matrix-off: about-scheme true
matrix-off: behind-the-scene false
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: opera-scheme true
referrer-spoof: * true
* * * block
* 1st-party css allow
* 1st-party image allow
behind-the-scene * * block
behind-the-scene * image allow
behind-the-scene * other allow
```
(then a bunch of behind-the-scene allows to allow addon updating etc etc)
had to allow images for behind-the-scene to prevent breaking favicons. i couldnt find a way to allow favicons through only.
and i was allowing ocsp servers with `other` but then i just allowed `other` in `behind-the-scene` altogether because of the file downloading issue
