### ISSUE TITLE
Can't get YouTube Upload to work

### ISSUE THREAD

**Issue by zappe** [gorhill/uMatrix#408]
Using FF 42 and uMatrix 0.9.3.1 and when I press Upload button on the main page it tries to open something and then redirects back to  the main page.
Am I missing something that I need to whitelist?
I've pretty much whitelisted everything except ads.

**Comment by gorhill** [comment]
uMatrix will break things, it's the default expected behavior. I emphasize it's for advanced users because they will know how to un-break things. The repo here is to file issue/bug, i.e. unexpected behaviors.

**Comment by gorhill** [comment]
I am trying to open a thread on [Mozilla's Discourse](https://discourse.mozilla-community.org/c/add-ons/add-on-support) to take care of user support. Will post the link if/when the thread is accepted.

**Comment by gorhill** [comment]
https://discourse.mozilla-community.org/t/support-umatrix/5131
