### ISSUE TITLE
Chrome Sync doesnt work between two Computers

### ISSUE THREAD

**Issue by garack666** [gorhill/uMatrix#411]
I have 0.9.3.1 on both Win10 Machines installed on latest Chrome32. I have both Chrome Browsers synced and connected to my Account. Sync Feature works on two Computers but seperatly: I can upload myRules and download it again from one Computer. But i have to sync the rules between two Computers. When i upload my Rules i cant download them with the other Computer. It only donloads the Rules i uploaded on this specific Computer.

**Comment by gorhill** [comment]
> But i have to sync the rules between two Computers.

I don't understand this one sentence. What do you mean exactly?

**Comment by gorhill** [comment]
Ok, I guess what is happening is that the extension id on both computers is different, as you installed uMatrix manually on both computer. Sync won work across different extensions, and the extension id is what distinguish extensions. I need to push the updated version to the Chrome store, and you need to install that version on both your computers.

**Comment by garack666** [comment]
There is a new Sync Feature in Umatrix with Version 9.3.0. I can upload MyRules to the Google Account. I wanted to use this Feature, because i have two Computers. This Computers both Have Latest Chrome Browser installed with the same Google Account and Google Sync is active.
In this way i can sync for example My Bookmarks between two Computers.

The same Sync i wanted for Umatrix. SO i installed latest UMatrix 0.9.3.1 on both Chrome Browsers. I enabled Sync on both. Now When i upload My Rules to the Google Cloud with PC1 and dowload it with PC1 all works fine. 

But when i upload my Rules with PC1 and download it with PC2 nothing happens. PC2 dont get the Rules, the rules on PC2 just stays the same.

**Comment by garack666** [comment]
OK nice, push it ro Chrome store, i really like Umatrix, Best Blocker ever (would be even better to block specific Ressources from one URL) , i assume it takes some time, cause Google have to check the addon?

**Comment by gorhill** [comment]
It's now available in the Chrome store. I think the delay for review is reserved for extensions with a sizable user base.

**Comment by garack666** [comment]
Wow very nice! Many thinks and i wish you success with this extension. I and many others reccomend this in it tech forums often, hope it helps!
