### ISSUE TITLE
content policy throwing exceptions

### ISSUE THREAD

**Issue by the8472** [gorhill/uMatrix#413]
I'm seeing the following in the browser console: `TypeError: contextWindow is null frameModule.js:156:14`

Firefox Nightly, Build ID 	20151112030238
uMatrix	0.9.3.0rc2

**Comment by gorhill** [comment]
I am still using Nightly 44.0a1 (2015-10-18). Is your version 45?

**Comment by the8472** [comment]
yes

**Comment by gorhill** [comment]
I reverted fix #390 as you suggested, so I am hoping this will make the issue here disappear.

**Comment by gorhill** [comment]
Can you tell me whether the last dev build (here) fix the issue?

**Comment by the8472** [comment]
Your link is broken, but I tested with https://github.com/gorhill/uMatrix/releases/tag/0.9.3.2b0

The exception still occurs, inspecting `frameModule.jsm` with the debugger `this.modernFirefox` is false in the content policy.

**Comment by gorhill** [comment]
> `this.modernFirefox` is false in the content policy

Fixed in latest dev build. Note that I still do not have the latest Nightly, so I can't tell whether bug #390 is back or not with the changes.

**Comment by the8472** [comment]
works. no content policy calls and requests are properly categorized.
