### ISSUE TITLE
How to share rule sets with others?

### ISSUE THREAD

**Issue by bonanza123** [gorhill/uMatrix#419]
I'm already using this awesome plugin for a while and want to install it also e.g. on the PC of my family and girl friend. To avoid that they get frustrated to early (because they have to configure all their favorite websites upon first visit) I would like to share my rule set with them (some kind of rule subscription, not only blacklists). Is that already somehow possible? If not, that would be an awesome enhancement (at least for me) :-)

**Comment by gorhill** [comment]
You can export the rules to a file and then import and append from a file, in the _My rules_ pane.

**Comment by bonanza123** [comment]
ahh okay. But some URL-based subscription method for this doesn't exist yet, right?

**Comment by gorhill** [comment]
> But some URL-based subscription method for this doesn't exist yet

No. I do not intend for subscription-based model for rules, the point of these rules is that they are completely decided by the users themselves -- they override the static filters which are usually decided by someone else.

**Comment by bonanza123** [comment]
Okay, despite I would like that feature I also fully understand your point. Thanks for your extremely fast response.

**Comment by LaxrMediumWas** [comment]
I do not explicitely ask for subscriptions but is there any other way to automate rules updating among family members' browsers?
