### ISSUE TITLE
Embedded maps don't disply properly (PaleMoon & Firefox)

### ISSUE THREAD

**Issue by ltcomdata** [gorhill/uMatrix#421]
In some websites, embedded maps do not display correctly.
For example: https://accessdane.countyofdane.com/050912233328.
Even if the initial map display correctly (and not only halved), when you zoom out, a half of the map is lost.  And I am pretty sure that the highlighted portion doesn't correspond to the map.
I don't know if the problem exists on Chrome.

**Comment by gorhill** [comment]
marking as invalid. See <https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md>.
