### ISSUE TITLE
how to whitelist a domain which is in a host file without allowing all of its requests everywhere

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#422]
i tried to see if there were issues related to this already. maybe:
https://github.com/gorhill/uMatrix/issues/203
https://github.com/gorhill/uMatrix/issues/86
but i couldnt find anything exact

i came across this link on facebook http://bzfd.it/1LMi3Bd
which then redirects to https://ad.atdmt.com/c/go;p=11042208151161;ev.a=1;idfa=;idfa_lat=;aaid=;aaid_lat=;cache=/?h=http://www.buzzfeed.com/h1/fbmd/citidoublecash/meals-that-taste-just-as-good-the-second-time-around?utm_term=4ldratp
which is blocked by umatrix

i have an addon called Redirector so i made a redirect from `https?:\/\/ad\.atdmt\.com\/[^\?]+\?h=([^\?]+).*` to `$1` which would just go straight to the proper urls and bypass `ad.atdmt.com`. but the problem is that umatrix catches the url before redirector does

the only solution i could find was to add this to the matrix `* ad.atdmt.com * allow`. but thats a problem since i dont want all requests to that site to be allowed everywhere. i just want the document to load and have all of its resources subject to filtering. but umatrix doesnt have a document option like ublock does. is there no other way to prevent a domain listed in a host file from being completely blocked and having it only subject to my rules matrix?

sorry if this is a duplicate.
Firefox 41.0.2
uMatrix 0.9.3.2
uBlock 1.3.4

**Comment by berrythesoftwarecodeprogrammar** [comment]
also i saw some issues about stripping the urls and having an option to let the user proceed to the redirect url, but how umatrix wont get in the business of url modifying. i understand.

also the issue about temporary whitelisting domains. i guess that could work in this case, but if its a domain which one clicks on often, i doubt having to click 'temporarily allow' every time would be a good solution.

from what i understand, the current way umatrix works with hosts file domains is like ublock's strict blocking except it cant be disabled. am i wrong? if not, is there any plan to change this?

**Comment by gorhill** [comment]
`* ad.atdmt.com doc allow`?

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh my god perfect. i tried 'document' didnt know there was a doc. thanks.
is there a list of  all the request types?

**Comment by gorhill** [comment]
Only in the code so far: <https://github.com/gorhill/uMatrix/blob/master/src/js/matrix.js#L61>.

The `doc` is a hidden column in the matrix -- it would not be very useful to display it as there is only one `doc` request per page/frame.

There is a hidden rule `* * doc allow`. Had to come to this (hiding it) as often users just wiped out all the rules to start from scratch -- which meant the browser would cease connecting anywhere -- as if the connection was lost -- and issues would be opend about this.

**Comment by berrythesoftwarecodeprogrammar** [comment]
oooh yeah that makes sense.

now that i know this, i dont mind manually adding in doc allow rules if sites are blocked in hosts files. but maybe on the block pages, there could be a button which would add a doc allow? might make it easier for people who want to 'whitelist' websites which appear in hosts files they use

**Comment by gorhill** [comment]
> maybe on the block pages, there could be a button which would add a doc allow

Issue #203.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@gorhill so for dynamic rules in umatrix, the following content types can be used:
```
*
doc
cookie
css
image
plugin
script
xhr
frame
other
```

how about with ublock? could you link me to a list or some code with a list in it? i found different pieces of code but couldnt figure out which ones were actually for dynamic rules

**Comment by gorhill** [comment]
In uBO, the dynamic filtering pane reflects you what types can be blocked: `all`, `image`, `1p-script`, `inline-script`, `3p-script`m `3p-frame`.

For static filters, refer to ABP's doc regarding types, and uBO-specific filter options.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thanks!
but  thats not exactly true for ublock and dynamic filters right? because the logger shows things like `image`, `xhr`, `other` etc but when added as dynamic filters they disappear. only static filters i guess

**Comment by gorhill** [comment]
I said "dynamic URL filtering".

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh right sorry
