### ISSUE TITLE
Feature idea: Modify rules from popup window

### ISSUE THREAD

**Issue by pkillnine** [gorhill/uMatrix#424]
This would make it easier to allow top-level domains for scopes. For example, many websites get CSS and scripts from cloudfront, and cloudfront uses esoteric subdomains to supply this content e.g. "d22r54gnmuhwmk.cloudfront.net".

It would be a lot simpler to be able to modify a rule in the popup window as one makes it, rather than by going into the settings, editing the rules and then finding the particular rule for the particular website and changing it.

This could be implemented by allowing one to modify the specific rule associated with the matrix entries by right clicking on the entry and then showing a box with the rule in it, which you could then modify.

**Comment by ldgbc** [comment]
This is also useful for situation such as 
avatars1.githubusercontent.com
avatars2.githubusercontent.com

There isn't a way for you to quickly do 
*.githubusercontent.com

**Comment by ndavidow** [comment]
Perhaps a more elegant solution would be to show second level domains for any subdomains, even if there is no content loaded from the parent domain. Some exceptions should probably be made for certain expansive second level domains; eg the country TLD .uk has .gov.uk, .co.uk, etc, and it would not make sense to provide those in the matrix.

**Comment by phanimahesh** [comment]
That would work, but the ability to modify rules directly from the popup gives a much greater flexibility.

**Comment by migueldemoura** [comment]
I've stumbled upon this, precisely with cloudfront. @ndavidow's idea seems reasonable.
