### ISSUE TITLE
Browser does not remember options on Youtube

### ISSUE THREAD

**Issue by Krysisx** [gorhill/uMatrix#426]
Hi,
I have Firefox 42.0.
My issue is that if I change some settings on `Youtube` website like volume, annotations on/off, autoplay on/off etc... and then open a new video, all my settings go back to default.
I have both `uMatrix` and `uBlock` and in `uMatrix` I have enabled all the following options:
![istantanea_2015-12-03_12-19-24](https://cloud.githubusercontent.com/assets/4366877/11559316/2c33e04a-99b8-11e5-86e9-a535e59aa65e.png)
![istantanea_2015-12-03_12-19-40](https://cloud.githubusercontent.com/assets/4366877/11559317/2c651c82-99b8-11e5-9689-4a183176b303.png)
Is it an issue or a normal behaviour according to the `uMatrix` options I have enabled? In this last case, what feature does it make that behaviour?

Thanks for your great work.

**Comment by gorhill** [comment]
See the [big warning on the front page](https://github.com/gorhill/uMatrix#warnings).

GitHub is for issues with uMatrix itself, not issues arising from the use of uMatrix. I can't possibly assist everyone about issue arising from blocking stuff, that would no longer be a hobby.
