### ISSUE TITLE
Default placeholder background takes too long to display (FF ESR 38, Linux)

### ISSUE THREAD

**Issue by dev-random** [gorhill/uMatrix#429]
When page contains too many blocked elements, my browser (Firefox ESR 38 on Linux) becomes extremely slow (each frame takes *seconds* to draw). It seems to be the result of combining linear-gradient and background-repeat in extensions.umatrix.placeholderBackground. Replacing the gradient with a data-uri-encoded png fixes the issue for me. Using -moz-repeated-linear-gradient instead of repeating the gradient with background-repeat works as well.

**Comment by Magister** [comment]
This is very annoing - scrolling is very slow because of this...
@dev-random did you managed to fix that locally? Now Firefox wants signed addons, so modifying it is not an option...

**Comment by dev-random** [comment]
@Magister 

about:config

extensions.umatrix.placeholderBackground

url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAAAAACoWZBhAAAABGdBTUEAALGPC/xhBQAAAAJiS0dEAP+Hj8y/AAAAB3RJTUUH3wwIAAgyL/YaPAAAACJJREFUCFtjfMbOAAQ/gZiFnQPEBAEmGIMIJgtIL8QEgtoAIn4D/96X1KAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTUtMTItMDhUMDA6MDg6NTArMDM6MDAasuuJAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE1LTEyLTA4VDAwOjA4OjUwKzAzOjAwa+9TNQAAAABJRU5ErkJggg==") repeat scroll #fff

**Comment by Magister** [comment]
@dev-random Thanks a lot!

**Comment by wu5oeDah** [comment]
@dev-random 

I've been waiting a long time for this too.
Thank you.

**Comment by tsuflux** [comment]
I would love to see @dev-random's solution merged.
