### ISSUE TITLE
Youtube Fullscreen Disabled - until I disable uMatrix Addon

### ISSUE THREAD

**Issue by HarryStottle** [gorhill/uMatrix#431]
been using uMatrix with Chrome for a few months and Firefox for a month. Think I know my way around it but this morning hit a problem with youtube videos which no amount of uMatrix tweaking would fix. I tried enabling everything, regardless. I tried disabling uMatrix for the youtube "scope". Nada. Only disabling the addon altogether re-enabled the full-screen option. 

The behaviour is repeatable, even after system reboots. (Win 8.1. Firefox 42)

As nothing else (that I'm conscious of) has changed on my system, since yesterday morning, and I've been watching youtube videos with appropriate uMatrix permissions for a few weeks without difficulty, I can only surmise that some uMatrix update in the past 24 hours has borked the system.

However, I don't see any other mention of it elsewhere in the issues list so perhaps I'm the only sufferer.

Suggestions?

**Comment by gorhill** [comment]
I can play Youtube fullscreen just fine with uMatrix enabled. Your issue is somewhere, you will have to investigate. Did you try disabling UA spoofing?

**Comment by HarryStottle** [comment]
Hole in one squire!
Disabling UA spoofing fixed it.

Grateful for the fix, but bemused at "what changed overnight"  (possibly for me only?) to make the fix necessary? 'snot like I switched UA spoofing ON. (That's the default, it's always been on, so far as I know)

Still, that's not your problem. You've improved the human condition enough for one day!

**Comment by drm200** [comment]
I had the same problem.  I am using Chrome in  ubuntu.  I was unable to get YouTube to go full screen.
If I unload the umatrix extension in chrome the problem goes away.
If I reload the umatrix extension in chrome then the problem returns.
If I disable umatrix filtering for the youtube scope ... the problem remains .... 

Disabling UA spoofing fixed the problem.  I only post this here to help anyone else who was struggling to find the solution.
