### ISSUE TITLE
Feature: Disable/Enable matrix should also toggle Privacy stuff

### ISSUE THREAD

**Issue by defkev** [gorhill/uMatrix#432]
Mainly User agent and referer spoofing.

**Comment by CrisBRM** [comment]
Close this, it has already been requested before and the response was negative—rightfully so, although I do think disabling/enabling them should toggle the padlock and remain temporary unless the padlock is clicked on.

**Comment by defkev** [comment]
Sorry but i am not following that logic.
Disabling/Enabling spoofing (User agent, referrer) already triggers the padlock.
Since you can configure this as a rule (per domain, sub domain) anyway:
```
ua-spoof: github.com false
referrer-spoof: github.com false
```
So imho it would just make sense that enabling/disabling the whole matrix should (temporarily) disable this as well: 
```
matrix-off: github.com true
```

But you caught me for not searching the closed issues.
Shame on me..yada yada

**Comment by gorhill** [comment]
Those extra switches are not part of matrix filtering, hence they are not affected by the matrix-filtering switch. One could disable matrix filtering while still enforcing strict HTTPS, or referrer spoofing. I do not intend to change this.

**Comment by defkev** [comment]
I work with a lot of different admin panels, to many and to fast paced that i care about whitelisting everything, so i just disable the matrix globally temporary.
Since i am not bothered about my privacy nor have to deal with advertising here because i am usually the one running them.
On one of these i noticed that the logon session is somewhat tied to the user agent, thus kicking me out every five minutes the user agent changes, which is annoying.

It of course depends on the situation the user is dealing with. Considering that uMatrix is meant to be used on the internet instead of a intranet it makes no sense to sacrifice privacy for usability.
Point taken.
