### ISSUE TITLE
[feature request] allow syncing preferences between different browsers

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#433]
I use multiple browsers on multiple computers.
For various objective reasons it is impossible to use only firefox or only chrome.
It would be **awesome** if someday umatrix could sync it's settings independent of browser (github maybe?)

**Comment by gorhill** [comment]
> if someday umatrix could sync it's settings independent of browser

I don't plan to ever implement this, this would require this project to have a central server with sync infrastructure. I don't intend to do this. Exporting/importing through a backup file is the workaround.

**Comment by mailinglists35** [comment]
> Exporting/importing through a backup file is the workaround

Can this be performed programatically without user intervention? The people who are using the browser with umatrix don't have the ability to export/import the rules.

**Comment by mailinglists35** [comment]
> I don't plan to ever implement this

But would you accept patches if someone else works the entire third party server syncing?

**Comment by gorhill** [comment]
I don't accept patch which add features.

**Comment by mailinglists35** [comment]
>  Exporting/importing through a backup file is the workaround.

is there any chance you could add ability to sync to the external file automatically, without the user having to interact with import/export buttons?
That way I could handle sending and receiving the file to the users' computer and umatrix would handle syncing with that file.

**Comment by gorhill** [comment]
uMatrix already supports cloud storage. You are asking me for a custom feature as if I was a dev for hire.

**Comment by mailinglists35** [comment]
> uMatrix already supports cloud storage

that is partially true (only when using the addon in the same type of browser)
the subject is about supporting cross-browser syncing.

> You are asking me for a custom feature as if I was a dev for hire

I'm sorry if that is your perception. English is not my mother tongue so maybe some translations you might have interpreted as a personal inquiry. I'm only asking nicely for a new feature.

**Comment by gorhill** [comment]
> I'm only asking nicely for a new feature.

I declined -- I wish my choice of declining would be respected, not debated. Whatever I decline, I may or may not change my mind in the future.
