### ISSUE TITLE
[feature request] allow global exceptions to "Strict HTTPS" 

### ISSUE THREAD

**Issue by mailinglists35** [gorhill/uMatrix#434]
With [x] Strict HTTPS option enabled, I can't view images on some sites that load their jpegs over regular http.

I wish I had a way to add exceptions to "strict https" mode - like allowing jpegs over unencrypted http for all websites - thus effectively hijacking the name "strict" into something softer like "prefer https" :D

**Comment by mailinglists35** [comment]
in another words, make it a per-site feature instead of a global one :)

**Comment by gorhill** [comment]
It is a [per site feature](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches#strict-https). The checkbox in the _Privacy_ pane is to pick a default global setting.

**Comment by mailinglists35** [comment]
> It is a per site feature. The checkbox in the Privacy pane is to pick a default global setting.
I'm sorry, but I don't understand how this could be setup so for every site I visit, strict https to be enabled with the exception of .jpg urls?

**Comment by mailinglists35** [comment]
same feature requested in a comment in issue #67 https://github.com/gorhill/uMatrix/issues/67#issuecomment-67506083

**Comment by gorhill** [comment]
Strict HTTPS implicitly applies only to passive contents (like images), not to active content (like scripts), because the browser will refuse in the first place to pull non-HTTPS active content resources from within a HTTPS document.

**Comment by mailinglists35** [comment]
oh, thank you so much for the clarification! :)
