### ISSUE TITLE
no scope for a single domain level?

### ISSUE THREAD

**Issue by 360up** [gorhill/uMatrix#435]
Lets say I'd like to allow xhr on github.com to write this report:
github.com github.com xhr allow

doing so I've automatically invited all sublevels to the xhr party:
api.github.com
assets-cdn.github.com
live.github.com

... and I have to manually block them again.

Is there no way to provide a scope for a single domain level w/o sublevels?

**Comment by gorhill** [comment]
> Is there no way to provide a scope for a single domain level w/o sublevels?

No.

**Comment by 360up** [comment]
>> Is there no way to provide a scope for a single domain level w/o sublevels?

> No.

@gorhill
Is that something you think about changing? If not why not?
