### ISSUE TITLE
Chrom(ium/e) keyboard shortcuts not implemented in Firefox 

### ISSUE THREAD

**Issue by j1my3p1x** [gorhill/uMatrix#438]
Steps to reproduce: 
Install uMatrix in Firefox through Github or the addons.mozilla.org
Open the addons menu in Firefox (ctrl-shift-a) 
Click "Extensions" on the left hand side. 
No "Shortcuts" button is present, while there is one in Chrome.

Proposed solution: 
Add a "Shortcuts" tab in the uMatrix Dashboard for Firefox.

Example Chrome image: http://i.imgur.com/rksZTZU.png

How to access the Chrom(ium/e) Shortcuts: 
Press the "Hamburger" menu in the top right of Chrome and select "Extensions" ( http://i.imgur.com/UnkTszA.png ) 
Scroll down all the way in the window that opens, and press "Keyboard Shortcuts" on the bottom mid-right. http://i.imgur.com/6Lo2FAd.png

**Comment by gorhill** [comment]
> Add a "Shortcuts" tab in the uMatrix Dashboard for Firefox.

FF is moving toward WebExtensions, so it's just a matter of when I "convert" uMatrix to use WebExtensions, which reportedly [already support the commands API](https://wiki.mozilla.org/WebExtensions#List_of_supported_APIs).

**Comment by j1my3p1x** [comment]
Sounds good. I appreciate the response. I'll mark this as closed.

**Comment by qazip** [comment]
How is this going? I thought UMatrix was already ported to WebExtension..
