### ISSUE TITLE
Icon keeps getting removed

### ISSUE THREAD

**Issue by handy1957** [gorhill/uMatrix#444]
Hello,  I'm using Pale Moon 25.8.1 with Windows XP Pro SP3 and uMatrix 0.9.3.1  and keep losing my Icon after customizing it to the icon bar.  It will stay for some reboots and others it will be gone.  Only way to get it back is to re customize.  It seems to be working even though the icon disappears.

**Comment by gorhill** [comment]
See if this happens using the latest [dev build](https://github.com/gorhill/uMatrix/releases).

**Comment by handy1957** [comment]
I will give it a test drive and see what happens.  Thank you

**Comment by 5t3f4n** [comment]
I had the same issue with SeaMonkey, icon also disappearing seemingly at random. Does uMatrix have a way to "force legacy toolbar button" like uBlock Origin does?

**Comment by alex-theoto** [comment]
For seamonkey this happens when you start private session

**Comment by gorhill** [comment]
Legacy Firefox and derivatives no longer supported.
