### ISSUE TITLE
[Feature request] Add setting to disable the display of the main-blocked.html page

### ISSUE THREAD

**Issue by Offnfopt** [gorhill/uMatrix#446]
I have a minor feature request, the request is to add a option on the settings page to disable the display of the main-blocked.html page (i.e. when a site is blocked, give no notification that the site was blocked).

I attempted to create a greasemonkey/tampermonkey userscript to accomplish this, but Chrome doesn't allow extensions to make changes to other extension URLs, so this is something that couldn't be accomplished with a 3rd party userscript which is why I'm making the feature request.

Should just need to add a new variable to be used on the settings page with the relevant HTML then modify the `traffic.js` page where it currently has:
 
`vAPI.tabs.replace(tabId, vAPI.getURL('main-blocked.html?details=') + query);`

Thanks for your time at looking at my request, really appreciate your uMatrix extention makes browsing the web so much more pleasant and faster.

**Comment by gorhill** [comment]
Add `no-strict-blocking: * true` in _My rules_ pane in the dashboard.

**Comment by Offnfopt** [comment]
I think you misunderstood my request. I don't have any problems with sites that are blocked, I just want a option to hide the main-blocked.html instead of displaying it. So the logic would be a option in settings that allows you to hide the main-blocked.html page i.e. if a site is blocked, instead of displaying main-blocked.html it would just be quietly blocked without notification to the user via main-blocked.html page.

**Comment by gorhill** [comment]
> quietly blocked without notification to the user via main-blocked.html page.

You mean the browser would display whatever page it displays when a page can't be fetched?

**Comment by Offnfopt** [comment]
No, I meant the page would be blocked like usual but there would be no indication to the user. Say a page did a pop-up/under and the domain was blocked, instead of showing main-blocked.html it wouldn't show anything, so basically the blocked page would be closed and there would be no indication to the user. I'm asking for this feature because I spend time closing a bunch of tabs that show the main-blocked.html page, but if there was a setting to not show blocked pages (the main-blocked.html page) and just quietly block the sites then I wouldn't spend any time having to close these pages.
