### ISSUE TITLE
Page looks differently in Firefox and Opera

### ISSUE THREAD

**Issue by LaxrMediumWas** [gorhill/uMatrix#450]
www.kasparov.ru looks like it misses CSS in Firefox. Opera renders it correctly with the same configuration. My settings are block user-agent, strip http headers, https only; only 1st party css and images are allowed. No subscriptions.
It should be noted, that I type www.kasparov.ru. with the dot at the end, because the site is banned in Russia.

**Comment by gorhill** [comment]
You will have to make the case that there is an issue is with uMatrix itself. I will re-open if you provide all the information substantiating that there is an issue with uMatrix.

**Comment by LaxrMediumWas** [comment]
ok then, I don't know how I do that. Just letting you know.
