### ISSUE TITLE
How do I manually add a custom rule for e.g. 192.16.*.*

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uMatrix#451]
Because now each time you enter any Twitch channel, uMatrix blocks chat, and you have to manually click on each and every IP address listed in uMatrix to unblock chat and to connect to it, and do that each time you enter a different Twitch channel.

So it would be nice if you could add rule for 192.16.*.* or something like that instead of full IP.

I'm on Firefox.

**Comment by vzjrz** [comment]
You can just do `www.twitch.tv 192.16 other allow`

**Comment by gorhill** [comment]
Be specific, what is the rule exactly you are trying to create?

**Comment by gorhill** [comment]
Yes, as @vzjrz answered.
