### ISSUE TITLE
Feature request: optionally deny cookies  completely (do not accept cookies at all)

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uMatrix#452]
I've read the wiki and the tooltip information about blocking cookies in uMatrix, I *think* I understand the rationale behind letting cookies in but not out in blocking mode (they will not  be read by their original sender (*or any other third party?*) and you can assess which sites have been setting which cookies) yet I still believe that an option to deny cookies entirely, preventing them to enter the browser altogether, should be available.

There are a number of situations in which having cookies stored inside the browser in blocking mode could somehow lead to a privacy leak/concern: 
* first of all I would consider user error, what if one clicks on the wrong place of the matrix by mistake, or somehow alters some setting without noticing
* unpredictable interaction of uMatrix with other extensions
* possible bugs/regressions in uMatrix 

for added peace of mind, and considering the strong focus of uMatrix on privacy/security, I definitely think that an option to not set cookies at all would make sense.

Having identifying data stored -even temporarily- inside the browser doesn't look to me desirable in principle: if it is there, it may or may not be accessed, but if it isn't there, there's nothing to access -end of story.

**Comment by 5t3f4n** [comment]
>an option to deny cookies entirely, preventing them to enter the browser altogether, should be available

It's already available, in your browser settings. There is no reason for uMatrix to duplicate this feature IMHO.

**Comment by gorhill** [comment]
> I still believe that an option to deny cookies entirely, preventing them to enter the browser altogether, should be available.

This is what the early versions of HTTP Switchboard did. That does not work, for many reasons:

1. It becomes impossible to report the number of cookies in the matrix, and it becomes impossible to report them in details in the logger (name/type).
1. Cookies can be set through javascript: there is no way to block the creation of cookies, the APIs to deal with cookies are asynchronous.

The most sensible way to deal with them is to delete them afterward, that covers all the cases, and is compatible with asynchronous APIs. There is a setting in the )Privacy_ pane in the dashboard for this.
