### ISSUE TITLE
Impossible to use Livefyre commentary widget

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uMatrix#454]
Both uMatrix and uBlock block Livefyre widget. I disabled both and still cannot post a comment in this page: http://massivelyop.com/2016/01/09/massively-ops-guide-to-choosing-an-online-arpg/#comments

When clicked Post Comment As... it popups a blocked page by uMatrix even though the matrix filtering is disabled.

Even when you enable All in site it still lists Livefyre in red and need to enable each and every Livefyre URL.

Seems like a legit commenting system used by a legit website and don't see why it should be so blacklisted and blocked.

**Comment by gorhill** [comment]
3rd-party filter list issue. Use the logger. Mind the prominent warning on the front page of uMatrix.
