### ISSUE TITLE
User agent spoofing doesn't cover all methods of getting the user agent

### ISSUE THREAD

**Issue by Roman-Nopantski** [gorhill/uMatrix#455]
Forgive me if I lack the correct terminology here. Two different methods of obtaining the information are used (in the example given) and return two different results - one spoofed, one actual. To test you can use the site https://whoer.net/ where two methods' results are shown under the "Browser" section: Headers and Javascript.

To reproduce. First of all, no other UA manipulation is being used. The browser (FF) reports it's UA correctly as is. Zero other manipulation. In uMatrix's scope for whoer.net, allow user agent spoofing (I will assume you have a bunch of agents listed under options - in my case it is a mixture of win32/win64 FF versions that are consistent with my browser and platform, one of which is my actual UA).

Result: unless you are "unlucky" enough to randomly spoof your actual user agent, you should see that whoer.net detects and flags your user agent as suspicious activity, because it can detect two different results.

I'm dead keen on using this feature in uMatrix. Until now I have simply spoofed my UA as the latest FF ESR version (but whitelisted sites such as Mozilla). However, I am increasingly of the opinion that it is better to hide in the noise and be unique with randomization. But I would want to make sure that whatever method is used, the same result is given.

**Comment by gorhill** [comment]
I actually plan to remove the spoofing of `navigator.userAgent`, only the HTTP header will be spoofed. Spoofing `navigator.userAgent` was a mistake and does more harm than good, as this really accomplishes nothing given all the bits of info which can be extracted through javascript.

**Comment by Roman-Nopantski** [comment]
No problems. Mark as closed/resolved/wontfix :)

**Comment by ebugusey** [comment]
> whoer.net detects and flags your user agent as suspicious activity, because it can detect two different results

What?
![my ip 2016-01-13 12-34-46](https://cloud.githubusercontent.com/assets/8318227/12289013/59c903c8-b9f2-11e5-9bda-0c4a31404dbe.png)
It's consistent for me.

Only two problems with UA spoofer that I see is this:
![my ip 2016-01-13 12-38-50](https://cloud.githubusercontent.com/assets/8318227/12289130/1682f4ce-b9f3-11e5-8f21-aa122df6c997.png)
and this:
![screenshot 2016-01-13 12 40 43](https://cloud.githubusercontent.com/assets/8318227/12289136/20265d54-b9f3-11e5-9498-b1eefabca6b3.png)

**Comment by gorhill** [comment]
> Only two problems with UA spoofer that I see is this:

As said, only disabling javascript will properly foil a large swat of fingerprinting techniques -- UA is just one source of bits of data, there are many more, so in the end it's placebo to only spoof UA on javascript level. Best is to disable javascript -- something uMatrix does out of the box for all 3rd parties (these are the most likely to try to fingerprint you, especially the ubiquitous ones). For an even better protection, there is the Tor browser.

**Comment by SkySkimmer** [comment]
Incomplete UA spoofing with JS enabled makes some sites complain, eg https://www.cmso.com/ makes the following alert:
>ERROR: Possible problem with your *.gwt.xml module file.
>The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8). Expect more errors.

I don't remember what the uMatrix defaults are, but if they enable UA spoofing and 1st party JS people will get that error.
Maybe UA spoofing should be enabled only if the specific request would be blocked were it a javascript request? ie if some site has JS enabled for 1st party but not 3rd parties you get UA spoofing for the 3rd party requests only.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think its better to leave useragent spoofing to addons specifically designed for such a thing
for firefox you can use either:
[Random Agent Spoofer](https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/)
or 
[UAControl](https://addons.mozilla.org/en-us/firefox/addon/uacontrol/) with [User-Agent JS Fixer](https://addons.mozilla.org/en-US/firefox/addon/user-agent-js-fixer/)

**Comment by Roman-Nopantski** [comment]
@berrythesoftwarecodeprogrammar Indeed. I use UAControl with User Agent Overrider (I haven't looked for a while, and there are bound to be dozens them) - would be nice if one addon did both headers and JS (there probably is one, I'm just being lazy today - and no, I do not want RAS).

**Comment by berrythesoftwarecodeprogrammar** [comment]
User-Agent JS Fixer which i linked, complements other addons including UAControl, by changing the javascript useragent to the same one as the header

**Comment by Roman-Nopantski** [comment]
@berrythesoftwarecodeprogrammar Excellent. Thanks. Works as advertised :) One less thing to maintain and worry about.

**Comment by crssi** [comment]
Idea of a User-Agent JS Fixer is a good one... but unfortunately it doesn't work completely and is a half measure.
Most completed is Random Agent Spoofer, which has also other problems.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@crssi works fine here. I use Random Agent Spoofer + UAControl + User-Agent JS Fixer. RAS chooses a random useragent profile for all sites by default and I use UAControl for when I want to use a specific useragent for a site. It is able to override RAS. The JS Fixer then just writes the same values from UAControl into the javascript objects. You can test it here, http://browserspy.dk/browser.php . I just tested with the latest versions and it's still working.

**Comment by crssi** [comment]
I am on Win 8.1 x64., FF 45 ESR, uMatrix, User-Agent JS Fixer and NoScript in Allow JS mode.
Spoofed UA on uMatrix: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36
Going to: http://browserspy.dk/os.php
Results:
Operating System: Linux/Unix
OS detected via jQuery: win
OS detected via platform: Win64 - Windows 64bit
OS CPU detected via JavaScript:	Windows NT 6.3; Win64; x64 

See the discrepancies here... and we can go on.
I dont really know what exactly does work on your side, but you might have missed something, or I am?

**Comment by Roman-Nopantski** [comment]
@crssi The thread is about alerting gorhill that the two methods of getting the user agent (headers, JS) were not both covered by uMatrix. With JS fixer, this issue is no longer an issue.

The fact that the user agent contains OS info, means that as an end user, you need to be smarter with your OpSec. That has nothing to do with uMatrix. The same goes with trying to spoof, for example, your time zone - you need to make sure locale, date/currency formats, languages and a dozen more items are all plausible, otherwise all you do is create a unique fingerprint. This is because there are a huge amount of ways to get information about your browser etc, including redundancies. Here's one that definitively determines you are using FF ( https://thehackerblog.com/dirty-browser-enumeration-tricks-using-chrome-and-about-to-detect-firefox-plugins/index.html ). How about navigator.buildID which reveals the built time of your version down to the second. And there are ways to determine exact or rough estimates of your browser make and model based on internal changes and responses.

TBB struggles to get all this right. An unpatched FF has no hope. Your best defense of course is to control JS. Worse case scenarios, you need to be plausible, and follow good OpSec. Don;t pretend to be chrome or safari when you are not. Don't pretend to be linux when you aren't. Surely 64bit FF on Win8 is a pretty common subset. Stick to that as your options, just change the version numbers.

**Comment by crssi** [comment]
I have sad that here mentioned workaround using "User-Agent JS Fixer" to fix the problem wont work.
Now you are talking about other things and you are deviating out of focus here.
The browser enumeration tricks to detect browser you can be remediated with https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/
and test it over https://www.browserleaks.com/firefox before and after.

So I really dont understand the struggle here and finding all king of excuses... I know that there are other stuff, but lets focus only to UA spoof here.

I think it would be really easy to implement for someone like gorhill into uMatrix to get the whole UA spoof sollution... in the chrome://umatrix/content/dashboard.html#privacy under UA list, if there would be and option (after some sort of separation in the same line) to enter the following preferences (there might be some too many and some missing):
gecko.buildID
gecko.mstone
general.appname.override
general.appversion.override
general.buildID.override
general.oscpu.override
general.platform.override
general.useragent.vendor
general.useragent.vendorsub

So when uMatrix changes the "general.useragent.override" it can at the same time change also the upper preferences if listed and with that the end-user could set-up this thing and get better control.

**Comment by crssi** [comment]
@berrythesoftwarecodeprogrammar 
It works for you because you are using Random Agent Spoofer, which is working correctly. ;)

**Comment by Roman-Nopantski** [comment]
@crssi JS Fixer works perfectly as described. It matches the header to JS. End of story. That is it's purpose. It is not broken.

Gorhill has said he not going to do this (i.e match JS to headers, which is what this issue was about). And now that we are aware of this, regardless of the extension we use to spoof, we can at least marry the two with JS Fixer if need be. The issue is closed. The topic is "... methods of getting the user agent".

The topic is NOT "how to make all the fingerprinting and information leaks in your browser match random user strings". You're twisting it all on its head. What I am trying to explain to you is that you are almost asking for the impossible. I haven't checked in on RAS for a while, but this is exactly the sort of thing they are trying to do. But you'll still fail to plug it all. There is no way you can hide your browser or operating system (and more) from the truly determined.

I already gave you a couple of examples that cannot be blocked (assuming you have to allow the JS) that determine your browser as being Firefox. There are even more ways to work this out. There are multiple ways to determine your OS. Forget about all those about:config entries - that's just the tip of the iceberg. For example, even if you block flash and disable downloaded fonts, and don't allow web pages to choose their own fonts etc - JS can still determine some (or even all?) of the fonts on your system, and from that, work out your OS.

You will never defeat fingerprinting (assuming you have to allow JS to run). There are just way too many holes, and if they were all plugged, the internet would mostly break for you. The best you can do is limit it (by reduce entropy (being very common), or even by raising it by randomzing everything all the time (always being unique)). If the choice is to reduce entropy, they you need to use good OpSec.

If you want to ask gorhill to patch/cover all the methods of getting the information displayed in user agents, then politely ask him in a new issue and read his response :)

**Comment by crssi** [comment]
OK... got it. I would like to deeply thank you for your explanation and your time to answer me.

Have a nice weekend
cheers
