### ISSUE TITLE
.co.uk not recognized as a TLD

### ISSUE THREAD

**Issue by pointyointment** [gorhill/uMatrix#456]
`.co.uk` is effectively a TLD, regardless of the official structure of domain names. uMatrix should recognize it as one. To see the undesired behavior, just go to bbc.co.uk and look at what's listed in the matrix.

**Comment by vzjrz** [comment]
I see nothing wrong with this: 
![asdfasdfadfasdfasdfadfsdf](https://cloud.githubusercontent.com/assets/930620/12252691/32b6f7a8-b89f-11e5-838f-68d1639d4760.png)

**Comment by gorhill** [comment]
I went to bbc.co.uk and all is fine.

[CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md)

**Comment by pointyointment** [comment]
Cannot reproduce. `bbc.co.uk` seems to have been redirected to `bbc.com` today, so I can't go there to take a screenshot of what I saw. Therefore I agree with closing this.
