### ISSUE TITLE
User Agent spoofing doesn't seem to work (according to about:support)

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uMatrix#457]
I'm seeing that checking the random user agent spoofing in uMatrix 0.9.3.1 doesn't seem to do anything according to the *about:support* page in Firefox 43 : I only see the default (real) user agent there, even using a handful of ua strings that apparently work when used with User Agent Switcher extension.

In other words, when changing the user agent manually using User Agent Switcher I can see the ua string changing accordingly in *about:support*, whilst if using  uMatrix  with the same  ua strings, nothing changes in *about:support* (the real user agent is displayed) .

Is that expected behavior?

**Comment by gorhill** [comment]
The HTTP header `User-Agent` is changed live before leaving the browser -- it's not changed in any browser settings.

**Comment by acrobat1** [comment]
Thanks for explaining that: I'm sorry for having opened this issue based on just what I saw by looking at *about:support*.
It is true that websites read the proper user agent string once this option is enabled, even if nothing is changing visually in *about:support*.

I can see that your extensions may be somehow different from average ones, as they actually do something even when it looks like they aren't.
