### ISSUE TITLE
Questions about user interface

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uMatrix#458]
I hope this is the right place to ask, I was wondering if someone could please clarify the UI for me.

1) Using default settings, I don't understand what is the meaning of the dark green block below frame.
I understand, all 1st party is allowed, then what does the dark green square do?
2) What are the triangles in top left corner of some blocks?
![um1](https://cloud.githubusercontent.com/assets/13304436/12291463/ba37df50-b9e7-11e5-9822-7c5df090d2da.jpg)

3) if I click at the lower half of the frame block, it turn light red with a dark red triangle. What is that?
![um2](https://cloud.githubusercontent.com/assets/13304436/12291474/c7725268-b9e7-11e5-829a-a993463b249c.jpg)

Thanks

**Comment by Havokdan** [comment]
I am interested in knowing the answers to these questions too, if there are no answers on the wiki, it would be nice to add them later.

**Comment by AdKiller** [comment]
"CLOSED"

0_O

**Comment by gorhill** [comment]
Read the doc, do not use the issue tracker as if it was a forum. An excerpt from page of the project:

> [HTTP Switchboard's documentation](https://github.com/gorhill/httpswitchboard/wiki) is still relevant, except for [uMatrix's differences with HTTP Switchboard](https://github.com/gorhill/uMatrix/wiki/Changes-from-HTTP-Switchboard).

**Comment by AdKiller** [comment]
Thank you very much. All clear now.

**Comment by Havokdan** [comment]
Maybe this answer: https://github.com/gorhill/httpswitchboard/wiki/The-matrix-cells

**Comment by dragetd** [comment]
This issue could be treated as a request for better documentation. I was reading through the documentation and could not magically forsee that this information is hidden within a chapter about differences to another plugin I have not used before.

Would you accept PRs regarding improving the documentation of these things?

**Comment by sleek22** [comment]
@dragetd,

Thank you for your comment.

It answered a lot of questions that I had also.
