### ISSUE TITLE
Cannot save 'hosts files' list on Seamonkey

### ISSUE THREAD

**Issue by alex-theoto** [gorhill/uMatrix#459]
Umatrix was on seamonkey's addons but for some reason, it is removed.

However, I'll post this bug.
Seamonkey 2.39
Umatrix 0.9.3.1 (I tested even the dev version)

When you update the hosts list, everything works fine. But if you close the browser and open it again and go to dashboard - hosts files, there are no blocklist hostnames and there is no update option (it is gray).

**Comment by gorhill** [comment]
Can't reproduce.

See if there are errors in the browser console.

**Comment by alex-theoto** [comment]
Ops, I'm sorry. Something messed up on seamonkey's local files.
I removed user's config files and now seamonkey and umatrix works fine.
Now I can see it ai their addons.
