### ISSUE TITLE
Graphical glitch when domain name is exceptionally long

### ISSUE THREAD

**Issue by ledti** [gorhill/uMatrix#46]
In the attached image, under ```metric.gstatic.com```, is a long domain name which causes a graphical glitch in the white area in-between the cells.

Similar long domain names show up on some youtube videos.

[Example link](http://www.youtube.com/watch?v=hOmNWxx4Cwo). With default uMatrix settings whitelist ```googlevideo.com``` and ```s.ytimg.com```, and a long domain name shows up for me.

![umatrix_graphical_glitch](https://cloud.githubusercontent.com/assets/526445/4930062/c6241232-655d-11e4-8d95-9c25f5a93944.png)

**Comment by SergeiShir** [comment]
New user of uMatrix
Noticed the same cosmetic issue
![example](https://cloud.githubusercontent.com/assets/17823400/19017302/b78ee080-883d-11e6-8a0c-c03c3e107132.png)
