### ISSUE TITLE
How to set a domain to be globally allowed?

### ISSUE THREAD

**Issue by NastyLarryDargan** [gorhill/uMatrix#461]
Hi there

Sorry for my bad english.

I browse a lot of websites. Recently, I installed uMatrix, and I kinda love it, but it kinda pain in the ass when it comes to enable popular domains on many websites.

For example, my english is rather poor, so often I help myself by translating websites through Google Translate addon (for Chrome). But that of course requires translate.googleapis.com to be allowed on every new website. So I have to enable this domain everytime. 
But there are worse examples, just like youtube, ohhh man, I have to enable youtube.com, refresh, then ytimg.com, refersh, then googlevideo.com. This is madness! I have to do it on every new website.

How to set domains like translate.googleapis.com or googlevideo.com to be allowed on every website?

Thanks in advance for your help.

**Comment by CrisBRM** [comment]
```* translate.googleapis.com * allow``` probably

**Comment by Havokdan** [comment]
https://github.com/gorhill/uMatrix/wiki/Very-bare-walkthrough-for-first-time-users

**Comment by gorhill** [comment]
@NastyLarryDargan The scope in which a rule is create when you click is the one shown in the top-most, left-most box. By default the domain of the current page is the scope. Select `*` to select the global scope. Doing so means that each rule you create will be in the global scope, i.e. apply everywhere. Don't forget to select back the local scope when you are done creating global rules.
