### ISSUE TITLE
[Firefox] [Bug] target-attribute confuses uMatrix

### ISSUE THREAD

**Issue by SINE** [gorhill/uMatrix#462]
Short explanation:
uMatrix Firefox get's confused if you click on a link with the HTML-attribute ```target="_blank"```
For example: ```<a href="http://google.com" target="_blank">LINK</a>``` would open a new tab, when you now go back to the tab where you clicked the link, then click on uMatrix, it will show you the configuration screen for the page of the link, not of the page you are still on.

Demo-HTML file:
[umatrix-bugreport.zip](https://github.com/gorhill/uMatrix/files/92775/umatrix-bugreport.zip)

Reproduce by:
1. Open the HTML file in the ZIP archive
2. Click the first link with left-click - > everything works as expected
3. Click the first link with middle-mouse click -> new tab opens, close it -> back on old tab everything looks as expected
4. Click the second link with left-click -> new tab opens, close it -> back on old tab with the bugged uMatrix state
5. Click the uMatrix button to open it's quick-menu, the domain displayed will show the domain of the link you clicked on before.

**Comment by gorhill** [comment]
What version of uMatrix was this? That issue is fixed in the dev build 0.9.3.2 -- available on AMO in the dev channel.

**Comment by SINE** [comment]
Jesus, sorry, I forgot the most important info. Indeed, it is the version 0.9.3.1 on AMO - I will make sure to test the dev channel now.

**Comment by gorhill** [comment]
I just pushed a release version of 0.9.3.2 this morning. It's pending review.

**Comment by SINE** [comment]
Issue seems to be fixed.

I would like to add a big thank you for your great work.
Have a good one.
