### ISSUE TITLE
Hosts files list is emptied on SeaMonkey when the browser is not started on startup

### ISSUE THREAD

**Issue by KlipperKyle** [gorhill/uMatrix#463]
If the browser is not the first component to start when SeaMonkey launches, then uMatrix's list of hosts files will be emptied.

![screenshot_2016-01-18_21-31-12](https://cloud.githubusercontent.com/assets/6385218/12410536/04f3cfa8-be2b-11e5-97c3-d1bf555b6aed.png)

To reproduce:
1. Install uMatrix on SeaMonkey (I am on version 2.39.)
2. Go to the uMatrix dashboard.  Confirm there are items listed in the Hosts files tab.
3. Edit > Preferences > Appearance.  Uncheck Browser and check Mail & Newsgroups.  (This will tell SeaMonkey to launch the Mail/News client on start instead of the browser.)
4. Restart SeaMonkey.  Go to the uMatrix dashboard.  The list of Hosts files is empty like in the screenshot above.

Additional notes: If you set a master password (e.g. to protect your email passwords), then SeaMonkey will prompt you for the master password _before_ the Browser is started, even if you have Browser checked in the Appearance preferences panel.  This also has the side effect of wiping uMatrix's hosts list.

**Comment by KlipperKyle** [comment]
I should probably post some version numbers:

- uMatrix 0.9.3.2 (from addons.mozilla.org)
- SeaMonkey 2.39
- Arch Linux x86_64

**Comment by gorhill** [comment]
I could reproduce.

**Comment by umatrix-user** [comment]
New, prospective user of uMatrix here - planning to move from NoScript + RequestPolicy + ABP.

uMatrix looks to be the extension making the other 3 obsolete, you have been doing an excellent job, Raymond!

I do have a related problem here on SeaMonkey 2.40, settings are not saved/remembered between sessions at all. Whenever I start the browser, it just comes up with all default settings. Not only hosts files are forgotten, but everything. Yes, I do have a global password set up in SeaMonkey.

With OP over 2 months ago, do you need a hand with this, perhaps?

**Comment by gorhill** [comment]
I will no longer support legacy Firefox and browsers based on legacy Firefox -- I don't have the time for such a low adoption extension on lower adoption browsers.
