### ISSUE TITLE
Allow per-site user-agents

### ISSUE THREAD

**Issue by Stebalien** [gorhill/uMatrix#464]
Currently, one can either send random a random user agent or send the correct user agent. It would be nice if one could send custom values per-site.

```
ua-spoof: youtube.com chrome # Send chrome UA.
ua-spoof: youtube.com true # Random
ua-spoof: youtube.com false # Don't spoof
```

Where `chrome` is defined elsewhere, e.g. in another rule (`ua: chrome "some UA"`). The UA could also be specified in-line however, defining aliases is quite a bit more usable and would also allow user agent selection to be better integrated into the UI.

My current use case is, as the example suggests, telling youtube that I'm running chrome (it fixes some video playback issues I'm having on youtube).

**Comment by gorhill** [comment]
The switches' state are encoded on two bits -- "chrome" and whatever else browser exist or may arise does not fit the current implementation, and I really do not plan on rewriting all this from the ground up. Declined.

**Comment by Stebalien** [comment]
Would you be consider accepting a patch if I find time?

**Comment by gorhill** [comment]
To implement this would require to over-complicate the code -- beyond what I find acceptable for such a narrow purpose. Best is such case is to completely disable UA spoofing in uMatrix and install a mroe specialized extension.

**Comment by Stebalien** [comment]
That's reasonable.
