### ISSUE TITLE
[Not an issue] Permanent global rules

### ISSUE THREAD

**Issue by pipebomb** [gorhill/uMatrix#468]
Is there a way to add certain domains to permanent whitelist, like youtube and all kinds of cdn so I don't need to re-add youtube every time because a website embedded a video?

**Comment by gorhill** [comment]
Use the scope selector to pick in what scope the rules are created. Scope selector is top-left cell.

**Comment by pipebomb** [comment]
Wow, I didn't know about this! 

Thank you for the hasteful reply and for amazing work! Cheers.
