### ISSUE TITLE
Just blocks everything suddenly.

### ISSUE THREAD

**Issue by DarkAlchy** [gorhill/uMatrix#470]
I use this on a domain that must have your number because it seems to know I am using you and will block all pages.  I have tried turning it off but that doesn't work so I have to remove the entire chrome directory and let chrome rebuild it when I restart (without your plugin) before the pages will be served to me again but as soon as I install Umatrix it will stop me cold.

I wish I could just have umatrix allow all (shows * * * allow in the rules) so I never get a single pink url in it again BUT block all frames and other then maybe that would work.

**Comment by gorhill** [comment]
[Front Regarding broken sites](https://github.com/gorhill/uMatrix#regarding-broken-sites).

**Comment by DarkAlchy** [comment]
I don't think you are getting it or maybe you don't wish to but this site knows when umatrix is being used and even has gone so far as to inject a special cookie when used.  I guess it can't stealth or basically it is like adblockers when the website does a popup saying you are using one.
--------------------------------------------
On Mon, 1/25/16, Raymond Hill <notifications@github.com> wrote:

 Subject: Re: [uMatrix] Just blocks everything suddenly. (#470)
 To: "gorhill/uMatrix" <uMatrix@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>
 Date: Monday, January 25, 2016, 7:11 AM
 
 Front
 Regarding broken sites.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by DarkAlchy** [comment]
I also would like to know about this part because this is the part that always confused me...

uMatrix can be set to work in allow-all/block-exceptionally mode with a single click on the all cell in the global scope *, if you prefer to work this way. This will of course break less sites

I have it set up like that but the site is still broken but why?  Here is another one, as I mentioned but was skimmed over, but if I turn off umatrix would think it wouldn't matter but once a site is broken it stays broken as long as umatrix is installed regardless of the on/off button or the allow all.  Why is that?  I mean does it not really get out of the way when turned off?
--------------------------------------------
On Mon, 1/25/16, Raymond Hill <notifications@github.com> wrote:

 Subject: Re: [uMatrix] Just blocks everything suddenly. (#470)
 To: "gorhill/uMatrix" <uMatrix@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>
 Date: Monday, January 25, 2016, 7:11 AM
 
 Front
 Regarding broken sites.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by gorhill** [comment]
That sort of issues being open is really tiresome. Only proved bugs/issues should be opened here, not request for support. I do warn that uMatrix is **definitely for advanced users** on the front page.

> Why is that?

An advanced user would have already investigated all this on his own, especially using the logger. And even if I was accepted requests for support, the issue is [completely lacking basic efforts](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md) to make it easy to handle.

Please do your home work, this sort of filed issues is a burden on any project.
