### ISSUE TITLE
Allow single script only?

### ISSUE THREAD

**Issue by Symbai** [gorhill/uMatrix#472]
In the GUI (firefox) I can only forbid or allow scripts of a specific domain. But there are 4 scripts loaded and I just want to forbid a single script. 

I can see the url in the log window but I haven't found a way to block only single scripts by their URL. Is there a way?

**Comment by adrienbeau** [comment]
>  Is there a way?

No. uMatrix works at the domain-level.

**Comment by Havokdan** [comment]
Would it not be possible to lock the items in the matrix via logger? I refer to the items individually.

**Comment by gorhill** [comment]
> Is there a way?

No, uMatrix's rules are hostname-based at most.
