### ISSUE TITLE
Please correct site "https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix"

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#473]
@gorhill 

I know, I wrote a incorrect section there. I WOULD correct the text, but editing is disabled ...

So, PLEASE edit this site!

**Comment by gorhill** [comment]
Page deleted. There is nothing to say really: whoever is advanced enough to use uMatrix is able to understand where uBlock Origin and uMatrix overlap, and decide how to configure both extensions in such case.

**Comment by Alpengreis** [comment]
That's good - thank you!!
