### ISSUE TITLE
[Feature Request] Blacklist or whitelist individual cookies

### ISSUE THREAD

**Issue by TheLoneWolfling** [gorhill/uMatrix#474]
(This is either a feature request, or a discoverability failure - either it does not exist or I could not find it.)

I'd like to be able to whitelist or blacklist individual cookies (preferably by regex on the cookie name). Currently there's no way to, for instance, allow a cookie that sets a yes/no preference while also blocking the user tracking cookies on the same domain.

**Comment by gorhill** [comment]
I do not intend to turn uMatrix into a full blown cookie manager. There are specialized extensions out there for this.
