### ISSUE TITLE
Possible to improve image placeholders? Sometimes they are just too tiny (1px).

### ISSUE THREAD

**Issue by AtTheGates** [gorhill/uMatrix#479]
First thank you very much for your outstanding extension. I really begin to love it (I'm a Policeman user). It seems more lightweight on CPU and memory usage compared to Policeman. Plus it's more actively developed.

I use uMatrix with just CSS allowed. So images are blocked. On some sites the image placeholders are simply too hard to see. They have just 1px. See the placeholders on this screenshots compared to Policeman:

http://www.hardwareluxx.de/community/f211/zeigt-euren-linux-desktop-434887-58.html#post24189962

Policeman:
![placeholder_policeman](https://cloud.githubusercontent.com/assets/9346225/12708978/eaced3d0-c8a6-11e5-8cd1-dfd2348e6388.png)

uMatrix:
![placeholder_umatrix](https://cloud.githubusercontent.com/assets/9346225/12708989/0b7fe8ee-c8a7-11e5-8e2b-0cf924245020.png)

Another feature request: Would it be possible to load images with right click context menu, like Policeman?

![loadimages_policeman](https://cloud.githubusercontent.com/assets/9346225/12709042/ecbedaf4-c8a7-11e5-985b-e865f86f35e2.png)

Thank you very much in advance. :-)

**Comment by Nojevah** [comment]
I was quite sure I already asked for this (some years ago unfortunately) but I can't find it. I asked the same thing: a better placeholder (the one for chrome, which is used by uBlock) and a contextual menu to temporarily display image.

**Comment by gorhill** [comment]
> some years ago unfortunately

Locking issue due to noise.
