### ISSUE TITLE
Script not detected on cgit commit page

### ISSUE THREAD

**Issue by Q3CPMA** [gorhill/uMatrix#485]
[Example](http://git.musl-libc.org/cgit/musl/commit/?id=869a9df5b5f7da57ebd86d146e25f78450678eeb&context=5&ignorews=0&dt=0)
The "diff options" don't work without enabling scripts for git.musl-libc.org, but the script column is empty.

**Comment by coffeemakr** [comment]
I think the reason why the script column is empty is because the JavaScript code is embedded in the HTML code and not an external resource which was blocked. 
In this case uMatrix prevents the execution of the script but does not block a resource.

**Comment by gorhill** [comment]
uMatrix will count all the embedded scripts as one script.

**Comment by gorhill** [comment]
Works fine on my side with FF 47/Chromium 50, with a blocked script column -- there is no script for that page.

**Comment by gorhill** [comment]
I see, we are talking about the drop-down lists under the _diff options_ section -- thought it was about the _diff_ pane itself.

**Comment by gorhill** [comment]
Though uMatrix will count take into account script tags, the case here is that there are no script tags, however there are embedded event handlers, which are not taken into account: `<select name='h' onchange='this.form.submit();'>`. uMatrix needs to look for these too.

**Comment by gorhill** [comment]
Ultimately, there is a missing API browser-side for uMatrix to account reliably of any sort of inline script code on a page. Without such API, it's impossible to guarantee that uMatrix will always report 100% of the time that inline javascript is being executed on the page.

NoScript uses `report-to`/`report-uri`, and this is a good idea to solve the problem. This would allow uMatrix to report 100% reliably when inline script code is trying to execute on a page. However for this to work there needs to be a fake URL to which the report is sent, and one has to worry that such fake URL requests do not end up leaving the browser, and I rather avoid such a questionable detour for what is merely a one bit of information in the case of uMatrix. This also creates "noise" on the webRequest API handlers of other extensions.

With an API such as `webRequest.onCSPViolationOccurred`, there would be no need to such a complicated detour to simply access a trivial piece of information.
