### ISSUE TITLE
Generate useragents instead of using lists

### ISSUE THREAD

**Issue by KOLANICH** [gorhill/uMatrix#486]

**Comment by mbme** [comment]
sounds great, but how should uMatrix guess actual browser versions?

**Comment by KOLANICH** [comment]
of course from repos:
https://github.com/mozilla/gecko-dev/blob/master/dom/base/Navigator.cpp
https://chromium.googlesource.com/chromium/src.git/+/master/content/common/user_agent.cc
https://chromium.googlesource.com/chromium/src.git/+/master/components/version_info/version_info.cc
https://trac.webkit.org/browser/trunk/Source/JavaScriptCore/Configurations/Version.xcconfig


PS I don't think it is a good idea to change useragents because it is possible to detect browser engine in another way and if the useragent and the detected engine mismatch, this means that the user uses this feature. The share of users using such features is small which means that this is information-rich fingerprintable parameter.
