### ISSUE TITLE
How to get uMatrix to block sites in the background.

### ISSUE THREAD

**Issue by sleek22** [gorhill/uMatrix#487]
uMatrix will give me the following message:

uMatrix has prevented the following page from loading:
http://syndication.exoclick.com/splash............

The original web page disappears and is replaced by the above message. I can always go back by clicking the "Go Back" button. Is there a way to do this blocking silently in the background without losing the page that I am on?

**Comment by a13ph** [comment]
@sleek22 use one of many unloading addons instead, like "Auto Unload Tab", which is probably the most powerful/bloated one, or any other one from bartab/unload families

in **Auto Unload Tab** you can set auto unloading to be really low timeout, though not less than a minute. 
Probably more precise would be to set **maximum of loaded tabs to 1**.
There are lots of options, so see for yourself

**Comment by gorhill** [comment]
> Is there a way to do this blocking silently in the background without losing the page that I am on?

I can't make sense of this feature request. If uMatrix prevent navigation to a site, the user won't have any clue why this is the case. That page is there to inform of why the navigation is being blocked.
