### ISSUE TITLE
"Delete blocked cookies" seems to be broken

### ISSUE THREAD

**Issue by rkoe** [gorhill/uMatrix#489]
I've enabled "Delete blocked cookies". However, some "blocked" cookies are not deleted; instead, uMatrix tries to delete non-existing cookies.

Used versions: uMatrix 0.9.3.2, Firefox 38.6.0 (iceweasel) on Linux

Details / Steps to reproduce:

1. Remove all cookies (Firefox -> Edit -> Preferences -> Privacy -> Show cookies... -> Remove all)
2. Enable uMatrix-log
3. Open some sites, here: ebay.de, ebay.com, youtube.com, google.de.
    All these sites set cookies.
4. Look which cookies exist. Here, only cookies from ebay.de, ebay.com, youtube.com, google.de exist.
    (Firefox -> Edit -> Preferences -> Privacy -> Show cookies...)
4. Wait about 2-3 minutes.
5. Now, the youtube.com-cookie is gone, but the ebay.de-/ebay.com-/google.de-cookies are still there.
6. Look into the uMatrix-log. It says:
   - "cookie deleted: http://youtube.com/..." (OK)
   - cookies for ebay.de, ebay.com, google.de are not deleted (bug)
   - And I get a whole bunch of "cookie deleted"-messages for non-existing cookies / for cookies which existed a few hours ago, e.g. "cookie deleted: https://twitter.com/..." (I've been on twitter some hours ago.) (bug)
7. Wait some more (e.g. 10 minutes) -- no "cookie deleted" messages occur in the log.
8. Open youtube.com -- a new cookie is set.
9. Up to 2 minutes later, the youtube-cookie is correctly deleted ("cookie deleted: http://youtube.com/...").
10. 2 minutes after the "cookie deleted: http://youtube.com/..." entry, a whole bunch of additional "cookied deleted:"-messages of non-existing cookies occur in the log (but of other domains than at point 6; twitter.com is not listed, but others which were not listed at point 6, are).

This looks like the cookie-tracking in uMatrix is broken: It does not correctly track existing cookies, but thinks that there are cookies, which do not exist.

**Comment by gorhill** [comment]
You do not provide any details about your rules -- I can't even start to investigate without this.

**Comment by rkoe** [comment]
My rules in short are: Block all cookies (and nearly all scripts). 3rd-party cookies are forbidden.
I could also create a cut-down-version with minimal rules (and then post the whole rules or even send you the firefox-profile), if this would be helpful.

Rules: mainly
* * * block
* * other block
* * script block
* 1st-party css allow
* 1st-party frame allow
* 1st-party image allow
plus several cross-site-css/-image entries ("... ... css allow", "... ... image allow")

3rd-party cookies: "Accept third-party cookies: Never"

**Comment by gorhill** [comment]
I try to reproduce and see nothing wrong. I would like that you find exact repro steps that focuses only with one site. Provide the ruleset for that one site + the cookie-related settings in uMatrix.

**Comment by gorhill** [comment]
I tested the _Remove all_ button in Firefox's _Preferences_ page, and I confirm uMatrix does not clear its internal database of cookies. I will need to add code to do so. Looking at the code, it looks like this is also an issue for the Chromium port.

**Comment by acrobat1** [comment]
By any chance, could this be somehow related to what I've tried to describe [here] (https://github.com/gorhill/uMatrix/issues/83#issuecomment-177041474)

>I've indeed used some of these specific cookie manager extensions long with uMatrix, and I've sometimes noted that the logger sees cookies even after they should have been blocked/deleted according to the cookie management extension

or is this something else entirely?

**Comment by gorhill** [comment]
Looks like it's probably the same issue.

**Comment by gorhill** [comment]
An interesting observation concerning Firefox's cookie settings... If one select _"Keep until: I close Firefox"_, then **all** cookies become session cookies, including cookies which intended purpose is to be persistent.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@gorhill is the fix for this in any way related to https://github.com/gorhill/uMatrix/issues/385 ? i dont completely understand what the fix does but i updated and im watching my logger to see if it still deletes non blocked cookies which i have

**Comment by berrythesoftwarecodeprogrammar** [comment]
yes seems like its fixed and both `Delete blocked cookies` and `Delete non-blocked session cookies` do their jobs properly now.

**Comment by gorhill** [comment]
My mistake: e9e1f7e631c96c23a8ca1061f714eeec0a2da830 solves #385, not this one here. I still need to make uBO aware of cookies removed by some external methods.
