### ISSUE TITLE
Nobbs Question's 

### ISSUE THREAD

**Issue by Droyk** [gorhill/uMatrix#492]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

Hey @gorhill First of all I want to thank you for making two good extensions 1st is ublock & 2nd is umatrix 
and now I want you to give me some helpful answers 

So @gorhill 1st question is I am already an advanced user of ublock.... but now I want to be an experienced user in umatrix why you guys didn't made a wiki like you guys did in ublock case?

2nd I don't want to use any other ad blockers can I do that if I am using umatrix and remove every ad blocker will I see any ads at all?

3rd If I really have 2 have another ad blocker for ad blocking for e.g. ublock+umatrix how much memories these 2 extensions are going to capture and after using umatrix for 1 day straight I have to say that my page’s load slow sometimes I don't know why though .............they shouldn't be right :(....and plz tell me how much cpu power they will take too?

4th why you guys didn't add element picker in umatrix ...like you did in ublock

5th after using umatrix for the whole day ...I have to say that it breaks the pages a lot ..so if a user need's to fix that user have to turn the script button green this thing fixes almost 70% of pages and now for the remaining 30% of the pages that breaks after enabling the script option I have to enable  XHR,OTHER , and sometimes iframe too...............by doing this I have to say that it's a tedious task I browse 100 to 200 websites a day....and by enabling and testing these options almost takes some seconds too some minutes now multiply whole testing thing by number of websites I visit everyday
so the answer would be it takes away too much time. even if I use the lock option to save my setting's there is no guarantee that I am going to see the site again .... Every day I browse 50 to 60 new sites for some of college project's....................So in conclusion is there is any way to make script, XHR and other a default enables on every website Plz tell me there is a way to do that 

6th So I wanted to replace my ublock to umatrix but there aren't many host's in the umatrix so what I did is add custom url's from ublock to umatrix 
The below written hosts I added into the umatrix.... plz tell me I did the correct thing and if there are any missing host that I didn't add plz tell me

```
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/badware.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/filters.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/privacy.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/unbreak.txt
```

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Please do not use issue trackers as replacement for a forum.

**Comment by Droyk** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [Feb 18, 2016, 4:37 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/492#issuecomment-185450381 "2016-02-17T23:07:04Z - Replied by Github Comment Enhancer"):
> Please do not use issue trackers as replacement for a forum.

I cant post on the support forum every time i want to reply to your linked topic its says https://imgur.com/JE2Txby ............you are not permitted to view the requested resource
plz just tell me these questions

**Comment by Droyk** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [Feb 18, 2016, 4:37 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/492#issuecomment-185450381 "2016-02-17T23:07:04Z - Replied by Github Comment Enhancer"):
> Please do not use issue trackers as replacement for a forum.

I commented on the forum plz answer me there thanxx and sorry for inconvenience 
https://discourse.mozilla-community.org/t/support-umatrix/5131/6](https://discourse.mozilla-community.org/t/support-umatrix/5131/6

**Comment by Droyk** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [Feb 18, 2016, 4:37 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/492#issuecomment-185450381 "2016-02-17T23:07:04Z - Replied by Github Comment Enhancer"):
> Please do not use issue trackers as replacement for a forum.

@gorhill  I am really sorry to post here.....but nomatter what i write on the forums The spam filters  Akismet hide my reply to you I tried to msg Mods but they didn't answer at all.....plz @gorhill  help me

**Comment by Droyk** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [Feb 18, 2016, 4:37 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/492#issuecomment-185450381 "2016-02-17T23:07:04Z - Replied by Github Comment Enhancer"):
> Please do not use issue trackers as replacement for a forum.

Hey @gorhill  Sorry I should have posted it there but now i posted it plz tell me answers i want thanxx
here is the link  https://discourse.mozilla-community.org/t/support-umatrix/5131/7
