### ISSUE TITLE
Atleast answer me on the forum 

### ISSUE THREAD

**Issue by Droyk** [gorhill/uMatrix#493]
Sorry @gorhill I know it's annoying for you but I am waiting for you to answer those questions for almost 2 days now. You said discussion are only for forums so I write down all the question's down there but now you are not even answering the damn questions...Plz answer my questions here 
https://discourse.mozilla-community.org/t/support-umatrix/5131/6

**Comment by gorhill** [comment]
Anybody can answer, it does not have to be me.
