### ISSUE TITLE
Tell me the answers of these questions

### ISSUE THREAD

**Issue by Droyk** [gorhill/uMatrix#495]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

Hey @gorhill First of all I want to thank you for making two good extensions 1st is ublock & 2nd is umatrix 
and now I want you to give me some helpful answers 

So @gorhill 1st question is I am already an advanced user of ublock.... but now I want to be an experienced user in umatrix why you guys didn't made a wiki like you guys did in ublock case?

2nd I don't want to use any other ad blockers can I do that if I am using umatrix and remove every ad blocker will I see any ads at all?

3rd If I really have 2 have another ad blocker for ad blocking for e.g. ublock+umatrix how much memories these 2 extensions are going to capture and after using umatrix for 1 day straight I have to say that my page’s load slow sometimes I don't know why though .............they shouldn't be right :(....and plz tell me how much cpu power they will take too?

4th why you guys didn't add element picker in umatrix ...like you did in ublock

5th after using umatrix for the whole day ...I have to say that it breaks the pages a lot ..so if a user need's to fix that user have to turn the script button green this thing fixes almost 70% of pages and now for the remaining 30% of the pages that breaks after enabling the script option I have to enable  XHR,OTHER , and sometimes iframe too...............by doing this I have to say that it's a tedious task I browse 100 to 200 websites a day....and by enabling and testing these options almost takes some seconds too some minutes now multiply whole testing thing by number of websites I visit everyday
so the answer would be it takes away too much time. even if I use the lock option to save my setting's there is no guarantee that I am going to see the site again .... Every day I browse 50 to 60 new sites for some of college project's....................So in conclusion is there is any way to make script, XHR and other a default enables on every website Plz tell me there is a way to do that 

6th So I wanted to replace my ublock to umatrix but there aren't many host's in the umatrix so what I did is add custom url's from ublock to umatrix 
The below written hosts I added into the umatrix.... plz tell me I did the correct thing and if there are any missing host that I didn't add plz tell me

```
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/badware.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/filters.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/privacy.txt
https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/unbreak.txt
```

**Comment by CrisBRM** [comment]
Stop being a fucking nuisance.

**Comment by benoit-pierre** [comment]
How about you stop spamming the tracker and read the actual documentation?

**Comment by Droyk** [comment]
[**@benoit-pierre**](https://github.com/benoit-pierre) commented on [Feb 20, 2016, 12:55 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/495#issuecomment-186368432 "2016-02-19T19:25:24Z - Replied by Github Comment Enhancer"):
> How about you stop spamming the tracker and read the actual documentation?

I am not spamming I just want to know the answers of some questions that's all Tell me where in documentation written the answers of these questions 
> 3rd If I really have 2 have another ad blocker for ad blocking for e.g. ublock+umatrix how much memories these 2 extensions are going to capture and after using umatrix for 1 day straight I have to say that my page’s load slow sometimes I don't know why though .............they shouldn't be right :(....and plz tell me how much cpu power they will take too?

> 4th why you guys didn't add element picker in umatrix ...like you did in ublock

> 5th after using umatrix for the whole day ...I have to say that it breaks the pages a lot ..so if a user need's to fix that user have to turn the script button green this thing fixes almost 70% of pages and now for the remaining 30% of the pages that breaks after enabling the script option I have to enable XHR,OTHER , and sometimes iframe too...............by doing this I have to say that it's a tedious task I browse 100 to 200 websites a day....and by enabling and testing these options almost takes some seconds too some minutes now multiply whole testing thing by number of websites I visit everyday
> so the answer would be it takes away too much time. even if I use the lock option to save my setting's there is no guarantee that I am going to see the site again .... Every day I browse 50 to 60 new sites for some of college project's....................So in conclusion is there is any way to make script, XHR and other a default enables on every website Plz tell me there is a way to do that

> 6th So I wanted to replace my ublock to umatrix but there aren't many host's in the umatrix so what I did is add custom url's from ublock to umatrix 
> The below written hosts I added into the umatrix.... plz tell me I did the correct thing and if there are any missing host that I didn't add plz tell me

> https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
> https://easylist-downloads.adblockplus.org/easyprivacy.txt
> https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
> https://easylist-downloads.adblockplus.org/easylist.txt
> https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
> https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/badware.txt
> https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/filters.txt
> https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/privacy.txt
> https://raw.githubusercontent.com/gorhill/uBlock/master/assets/ublock/unbreak.txt

**Comment by CrisBRM** [comment]
https://github.com/gorhill/uMatrix/wiki

Also, reported.

**Comment by Droyk** [comment]
[**@CrisBRM**](https://github.com/CrisBRM) commented on [Feb 20, 2016, 1:03 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/495#issuecomment-186370398 "2016-02-19T19:33:14Z - Replied by Github Comment Enhancer"):
> [https://github.com/gorhill/uMatrix/wiki](https://github.com/gorhill/uMatrix/wiki)
> 
> Also, reported.

I have already seen that it didn't have my answers that's the reason i am asking

**Comment by CrisBRM** [comment]
Gorhill should have just blocked you from accessing the bug tracker.

**Comment by Droyk** [comment]
[**@CrisBRM**](https://github.com/CrisBRM) commented on [Feb 20, 2016, 1:07 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/495#issuecomment-186371577 "2016-02-19T19:37:24Z - Replied by Github Comment Enhancer"):
> Gorhill should have just blocked you from accessing the bug tracker.

I Can make another account easily...i just want want some answers if i din't get the answer i will not go from here

**Comment by Droyk** [comment]
[**@CrisBRM**](https://github.com/CrisBRM) commented on [Feb 20, 2016, 1:07 AM GMT+5:30](https://github.com/gorhill/uMatrix/issues/495#issuecomment-186371577 "2016-02-19T19:37:24Z - Replied by Github Comment Enhancer"):
> Gorhill should have just blocked you from accessing the bug tracker.
Its the Developer fault entirely. if he just answered my question on forum I would have never come here to ask the question again

**Comment by ethus3h** [comment]
@Droyk if you expect people to be on hand to answer your questions all the time, maybe you should be using an app that has a support contract. Duh.

**Comment by vgturtle127** [comment]
@Droyk 

1. uMatrix already has a [Wiki](https://github.com/gorhill/uMatrix/wiki), but you can also check [the docs directory](https://github.com/gorhill/uMatrix/tree/master/doc) for more information.

2. There will always be more ads, and nothing will block all of them.

3. That depends on many factors, like what kind of system you are running, web browser you are using, websites you visit, and other factors. Nobody can tell you exact numbers, but you should be fine, it is probably something else on your computer slowing things down (extensions, antivirus, etc.).

4. uMatrix isn't really meant to be used like that, therefore the element picker doesn't make a whole lot of sense.

5. It sounds like you should uninstall uMatrix and just use uBlock and call it a day.

6. Again, my recommendation would be to just use uBlock and remove uMatrix. No offense, but I think uMatrix is a little too in-depth and complex for you to use if you browse a lot.

Also, based on how the other developers are reacting, I would say that you need to try and be more patient and perhaps more respectful since this is given to you for free and Gorhill works on it in his spare time.

I don't know where you are from, but we would appreciate it if you would try and learn more etiquette and manners for English speakers.

This isn't meant to offend you, I give this same advice to anybody trying to attain help from another country or region.

**Comment by Hout** [comment]
@vgturtle127 Respect! :+1:
