### ISSUE TITLE
Switch protocol for pgl.yoyo.org to https

### ISSUE THREAD

**Issue by mdPlusPlus** [gorhill/uMatrix#496]
The hosts file on pgl.yoyo.org does support https now: http://pgl.yoyo.org/adservers/#https

So you can change the URL to
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext (oh and btw, you seem to load the URL with the parameter showintro=1, which only works because you're using the mimetype=plaintext, you should switch it to showintro=0)

or
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0

**Comment by phanimahesh** [comment]
Fixed in 0031a477217c74d89cf7806155b1446780768542. Can be closed
