### ISSUE TITLE
Can't start LiveChat despite uMatrix way deactivated for the source web-site

### ISSUE THREAD

**Issue by gooly** [gorhill/uMatrix#497]
Hi,
I wanted to start a chat: [http://www.softlayer.com/support](url).
Despite I deactivated uMatrix for this url I get:
```
uMatrix hat das Laden der folgenden Seite verhindert:
https://sales.liveperson.net/hc/12703439/?cmd=file&file=visitorWantsToChat&site=12703439&SESSIONVAR%21skill=Sales-SL-WWW-English&referrer=http%3A//www.softlayer.com/support&SESSIONVAR!launch-page=http%3A//www.softlayer.com/support 
```
I  would prefer to be able to see a button or any other option to establish a chat communication!!

**Comment by gorhill** [comment]
You say you deactivated uMatrix for `softlayer.com`, so why would you expect uMatrix to also be deactivated for `sales.liveperson.net`? Just also deactivate uMatrix for `sales.liveperson.net` (or preferably figure the ruleset to make it work).
