### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS  on answers.microsoft.com

### ISSUE THREAD

**Issue by garack666** [gorhill/uMatrix#500]
On all  answers.microsoft.com sides i get this erroe, for example try this:

https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj4vtOrt4nLAhWEJQ8KHUz1BZoQFgggMAA&url=http%3A%2F%2Fanswers.microsoft.com%2Fen-us%2Fwindows%2Fforum%2Fwindows_10-networking%2Foffice-2016-airspacechannel-event-log-error%2Fb76775e3-3b41-4ff9-a77f-a8a8c489415f%3Fpage%3D2&usg=AFQjCNExfvEpebURN5XdcG0AX1uC2pbgEQ

Copy this link in Edge f.e. adn it works. 
Switch off umatrix did not work for me only disable the extension.
Running latest Chrome32

**Comment by adrienbeau** [comment]
No problem using Firefox 44.0.2 and uMatrix 0.9.3.2. Your link displays the Microsoft page.

I already had a one Microsoft rule: microsoft.com aspnetcdn.com * allow

Also collector.githubapp.com and googleanalytics.com were on my blacklist.

**Comment by gorhill** [comment]
Front page of the project:

> [Do] not file issues to report broken sites when the sites are broken because uMatrix does its job as expected.
