### ISSUE TITLE
Umatrix possibly conflicts with Session Manager addon in Firefox beta 45.0

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uMatrix#501]
This has been happening as soon as the update to Firefox beta 45 came out: the browser hangs for a long time on exit, then finally crashes.

After trying again and again, I suppose it is down to a possible conflict/issue with the Session Manager addon, because neither Umatrix or Session Manager alone apparently trigger the issue, instead it happens only with both enabled and also kinda randomly, often times it will crash repeatedly on exit, but occasionally it won't.

This is what I see in a terminal:

```
WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"SessionStore: flushing all windows","state":{"total":1,"current":0},"filename":"resource:///modules/sessionstore/SessionStore.jsm","lineNumber":1456,"stack":["resource:///modules/sessionstore/SessionStore.jsm:ssi_onQuitApplicationGranted:1456","resource:///modules/sessionstore/SessionStore.jsm:ssi_observe:652","chrome://global/content/globalOverlay.js:goQuitApplication:69","chrome://browser/content/browser.xul:oncommand:1"]}] Barrier: quit-application-granted
FATAL ERROR: AsyncShutdown timeout in quit-application-granted Conditions: [{"name":"SessionStore: flushing all windows","state":{"total":1,"current":0},"filename":"resource:///modules/sessionstore/SessionStore.jsm","lineNumber":1456,"stack":["resource:///modules/sessionstore/SessionStore.jsm:ssi_onQuitApplicationGranted:1456","resource:///modules/sessionstore/SessionStore.jsm:ssi_observe:652","chrome://global/content/globalOverlay.js:goQuitApplication:69","chrome://browser/content/browser.xul:oncommand:1"]}] At least one completion condition failed to complete within a reasonable amount of time. Causing a crash to ensure that we do not leave the user with an unresponsive process draining resources.
[3122] ###!!! ABORT: file resource:///modules/sessionstore/SessionStore.jsm, line 1456
[3122] ###!!! ABORT: file resource:///modules/sessionstore/SessionStore.jsm, line 1456
```

Firefox 45.0b6  	build ID 20160215141016
uMatrix	0.9.3.2 
Session Manager	0.8.1.10

**Comment by gorhill** [comment]
> instead it happens only with both enabled

That is absolutely not an indication there is something wrong with uMatrix. A good case need to be made first, and the issue not occurring when disabling uMatrix is not a good case -- a timing issue could be involved. Currently I see this as sending me on a quest to prove that uMatrix is not the issue.

**Comment by acrobat1** [comment]
Well I reckon it looks like that and I apologize for that matter, however that's really all I have for now: I've been using basic troubleshooting practices such as selectively disable addons, start in safe mode, try different versions of the browser and that's all I can say for now.

It's not like I've not been trying and putting some time in it, unfortunately that's all my limited knowledge allows me to do: I can say for sure that with the same combination of addons Firefox 44 doesn't crash on exit whilst Firefox 45 does, and Umatrix along with SessionManager seems involved in this - but I could be wrong, of course.

I'm not pretending a solution, if there's anything else that I can do, like maybe running Firefox from a terminal with some specific debugging variables, I'll do it.

**Comment by Radagast** [comment]
@acrobat1 - check your crash reports, your issue may be related to [1187196] (https://bugzilla.mozilla.org/show_bug.cgi?id=1187196) - [1248489] (https://bugzilla.mozilla.org/show_bug.cgi?id=1248489) - [1187196] (https://bugzilla.mozilla.org/show_bug.cgi?id=1187196) - [1206393] (https://bugzilla.mozilla.org/show_bug.cgi?id=1206393)

**Comment by acrobat1** [comment]
Yes, I've read some of the  bugs you've linked above: definitely looks like the issue I'm talking about.

Once again, apologies for pointing towards uMatrix, I was tricked into thinking it possibly was uMatrix fault because, as I've said, for some reason disabling it apparently cured the issue.
OTOH, I kinda assumed that such a bug wouldn't have gone trough all these beta releases uncaught (and it's still happening in the current beta as I'm writing this) : so I 
was lead to believe *it had to be* some weird addon compatibility issue.
