### ISSUE TITLE
Add a "settings" icon to the menu

### ISSUE THREAD

**Issue by gitgetgot** [gorhill/uMatrix#506]
So users can *quickly* go to the dashboard.

Example from uBlock Origin:
![screenclip](https://cloud.githubusercontent.com/assets/974980/13375296/c8a6a800-dd9b-11e5-9514-3fb88bcb321a.png)

**Comment by gorhill** [comment]
You can already go to the dashboard by clicking that bar.

**Comment by gitgetgot** [comment]
not very intuitive, but ok if you know it... 8-)

**Comment by polyzen** [comment]
It would be very appreciated if there could be an option to choose whether the entire bar is clickable. The amount of times I've accidentally clicked the bar instead of the reload button is "too damn high" :p

Should I open a separate issue to see if someone is interested in implementing this?

**Comment by gorhill** [comment]
> Should I open a separate issue 

No, I would decline and close the issue. There is such a thing as settings bloat, and this would qualify.

**Comment by polyzen** [comment]
Perhaps a bigger gap between the buttons and the bar, then?
