### ISSUE TITLE
extend option: Show the number of distinct requests on the icon

### ISSUE THREAD

**Issue by gitgetgot** [gorhill/uMatrix#507]
![screenclip](https://cloud.githubusercontent.com/assets/974980/13375333/6aa3aa18-dd9c-11e5-8e32-c638ad2be0dd.png)

The information shown on the icon is not meaningful, imho.

Users only know: wow, a lot of things happen to be on that page.

I, personally, am interested only in scripts, so

I'd like to suggest more granulation from the users side:
like, let the user chose, what he/she likes to be counted

i.e.
```
[x] Show the number of distinct requests on the icon
    [ ] cookie
    [ ] css 
    [ ] image
    [x] plugin
    [x] script
    [ ] xhr
    [ ] frame
    [ ] other
```

Now, the user knows Ok, there are n scripts/plugins on that page. 
It would save the clicks to open the menu.

**Comment by gitgetgot** [comment]
no reason?
wouldn't you think its useful for the user?

**Comment by gorhill** [comment]
The idea is appealing. But then I considered:

- the overhead required to obtain that granular information each time the icon badge has to be updated;
- user settings creep.
