### ISSUE TITLE
uMatrix doesn't show the actually used hosts file if you middle click the link to it

### ISSUE THREAD

**Issue by towlie** [gorhill/uMatrix#509]
In this case you can see that uMatrix always shows an outdated version.
uMatrix
![umatrix](https://cloud.githubusercontent.com/assets/6986141/13396441/cd898f40-def4-11e5-8a88-06ef48ce5ea7.jpg)

uBlock Origin
![ublock](https://cloud.githubusercontent.com/assets/6986141/13396444/d5e0de96-def4-11e5-9fa4-11076e0ebf33.jpg)

Note: It shows the updated host file only when you left-click the link.
Firefox 44.02
uMatrix 0.9.3.2
uBlock Origin v1.6.2

**Comment by towlie** [comment]
Logger: 
![logger](https://cloud.githubusercontent.com/assets/6986141/13396623/f69b675e-def5-11e5-98df-6064e5facab3.jpg)
It looks like it downloads it but still falls back to the files you stored in assets.

**Comment by gorhill** [comment]
How did you open the list, lef-click or middle-click?

Left-click will cause uMatrix to see the resource through the asset viewer, while with middle-click Firefox bypass uMatrix's JS code and open the nominal link under the mouse.

**Comment by towlie** [comment]
Oh I see. I middle clicked/ draged the link to a new tab. Just left-click shows the uddated list

**Comment by towlie** [comment]
Hm shall I reopen? Because this is a different bahaviour compared to ublock

**Comment by gorhill** [comment]
Sure, just change the title to reflect the real issue, the current title might cause unneeded worries.
