### ISSUE TITLE
Feature request: support allow/deny based on uri scheme (e.g. https:)

### ISSUE THREAD

**Issue by Chaz6** [gorhill/uMatrix#515]
I would like to be able to create rules based on url scheme, for example:-

* bootstrapcdn.com https script allow

This would provide some extra security by helping block mitm attacks that can occur with unencrypted protocols.

**Comment by Chaz6** [comment]
That bulletpoint should be a "*" (thanks, Markdown).

**Comment by gorhill** [comment]
This would required a complete refactoring of the core filtering code, while adding complexity to it. I will pass on this.
