### ISSUE TITLE
Referer option conflicts with Privacy Badger extension in Chrome

### ISSUE THREAD

**Issue by semente** [gorhill/uMatrix#517]
![2016-03-08_14 14_838x358](https://cloud.githubusercontent.com/assets/29862/13609592/5eb1e406-e538-11e5-9705-f8ffff965aac.png)

**Comment by gorhill** [comment]
That's a chrome API limitation (which makes sense), only one extension is allowed to modify a specific header entry. You will have to pick one or the other.

**Comment by semente** [comment]
I would use uMatrix referrer spoofing because I don't know how it works in Privacy Badger (do you?). If it is the same behavior I will do that. Otherwise I think I should report Privacy Badger to add a option to disable this from their extension.

**Comment by semente** [comment]
@gorhill do you know how Privacy Badger's referer spoofing works?

**Comment by Atavic** [comment]
It's not the same behaviour, umatrix always enforces its settings, while PB acts only on the third party sites it sees as trackers.

When PB blocks cookies from being read or created, it will also block the referer header.

**Comment by semente** [comment]
For those with the same problem, you can check the following issue pages on Privacy Badger project: 
https://github.com/EFForg/privacybadger/issues/855
https://github.com/EFForg/privacybadger/issues/1314
