### ISSUE TITLE
[Feature Request] Add support for wildcard subdomains in My rules

### ISSUE THREAD

**Issue by itschytoo** [gorhill/uMatrix#519]
Hi.
To make (e.g.) youtube work, you have to allow xy.googlevideo.com, where xy can be many different values.
The rule
  youtube.com *.googlevideo.com other allow
does not work. It seems wildcards are not evaluated in the subdomain part.

Regards,
Gerrit

**Comment by Snapy** [comment]
Subdomains are included by default so googlevideo.com is sufficient. Read the doc and search for similar issues next time.

**Comment by gorhill** [comment]
Use `youtube.com googlevideo.com other allow`. Subdomains implicitly inherit rules from broader rules, you don't need to use `*.`.

**Comment by itschytoo** [comment]
Thank you both. Sorry for the bother!
