### ISSUE TITLE
Can't figure out some broken sites rules

### ISSUE THREAD

**Issue by aspera7** [gorhill/uMatrix#521]
I have following issue. From time to time I encounter sites which doesnt work properly. Even with all scripts allowed or disabled matrix filtering the site is still not working properly. I have to either go into addon page and disable uMatrix or to switch to another browser. Example site: [http://www.mirrorsedge.com/beta?intcmp=opm_merch_MEcatalystBeta]

Can someone help me resolve this?

**Comment by gorhill** [comment]
Please, as stated on the [front page of the project](https://github.com/gorhill/uMatrix), this is not the place for this:

> Keep Github issues for bugs. User support is [Mozilla's add-on-support](https://discourse.mozilla-community.org/t/support-umatrix/5131).
