### ISSUE TITLE
whitelisted about-scheme problem

### ISSUE THREAD

**Issue by N4melessGitter** [gorhill/uMatrix#524]
RE: https://github.com/gorhill/uMatrix/issues/523

I wanted to respond to your reply but you had already closed it.

I didn't know that there's an "about-scheme" scope and it only showed "addons.about-scheme" in the scope panel.
`about-scheme * * allow` does indeed what I want to accomplish.
Maybe add "about-scheme" to the scope panel while in "addons.about-scheme", if possible.
I think it would also be good to change the default config.
Replace `matrix-off: about-scheme true` with `about-scheme * * allow`, because it does basically the same thing but better IMO.

Thank you sir for some awesome addons btw!!

**Comment by berrythesoftwarecodeprogrammar** [comment]
if you just want to avoid the `about:addons` page connecting to google analytics just do this:
```
matrix-off: about-scheme true
matrix-off: addons.about-scheme false
addons.about-scheme mozilla.net * allow
```
(only turn the matrix on for `about:addons` and whitelist only `*.mozilla.net`. doesnt seem like it needs to connect to any other domains)

**Comment by N4melessGitter** [comment]
yeah that would be another way to achieve the same, with a bit more control.
But just in case there are other "about-scheme"-s now or in the future which connect to blocked domains, it's not the best solution IMO.
I would still prefer replacing `matrix-off: about-scheme true` with `about-scheme * * allow`,
since it's the closest replacement in behaviour AND filtering bad domains everywhere.
And in only one line too. KISS

It's also possible to set this in Firefox to control "about:addons":
`user_pref("extensions.webservice.discoverURL", "about:blank");`
But that "clears" the whole addons search content and only leaves the search bar.
