### ISSUE TITLE
Don't change location on blocked domains

### ISSUE THREAD

**Issue by dag** [gorhill/uMatrix#527]
I made a bookmarklet to look up the current domain in hpHosts:

```
javascript:location.href%20=%20'http://hosts-file.net/default.asp?s='%20+encodeURIComponent(document.location.hostname)
```

The idea was that when I visit a domain uMatrix blocks, I can quickly go look up why (assuming it's in hpHosts).  Problem is, uMatrix changes the current location to `chrome://umatrix/content/main-blocked.html?details=[...]` so the bookmarklet doesn't work.

If at all possible, I would like `document.location` to remain the original location that uMatrix blocked, rather than uMatrix's block notice page.  That would also be more in line with what browsers do for failed or blocked pages, I think (such as for broken certificates or phishing sites).

**Comment by berrythesoftwarecodeprogrammar** [comment]
and maybe show which hosts file the offending domain resides in? or maybe this has been requested many times before and its not possible after the lists are merged

**Comment by dag** [comment]
Agreed.  I'll add that idea to #526.
