### ISSUE TITLE
uMatrix toolbar icon randomly removes itself (fx-nightly 48) 

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#529]
I've noticed when using the most recent nightly builds of firefox, the uMatrix toolbar icon is randomly removed and placed in the 'Additional Tools and Features' section of Customise. From what I've seen so far, it happens following a restart of the browser, but it is random, moreover it is the only toolbar icon seemingly affected (uBlock, HTTPS Everywhere and SDC are all fine)

**Comment by gorhill** [comment]
uMatrix version please.

**Comment by Radagast** [comment]
Apologies. Version is 9.3.4. As mentioned in my earlier post, this happens when restarting the browser, i.e., with (<shift f2> restart) or following a browser update.

**Comment by Rukachan** [comment]
I can confirm it with Firefox esr 45.0.1 and used as well to happen with Iceweasel 44.
The version is 0.9.3.3.
It does not happen only when restaring the browser but completely randomly (unlike what the previous poster claims). I think it usually happens when visiting some sites sometimes.
To me it is not getting placed to "Additional Tools and Features" but it disappears completely.

The way I fix it is to either disable and re-enable the addon or if it doesn't work restart the browser.

**Comment by gorhill** [comment]
Do you have the `about:config` option `extensions.umatrix.forceLegacyToolbarButton` set to `true`? If so, reset the value to `false`.

**Comment by Rukachan** [comment]
@gorhill I do not have this option at all.

**Comment by Radagast** [comment]
I also don't have `extensions.umatrix.forceLegacyToolbarButton` in about:config. However, for me the issue seems to have corrected itself, although I have no idea why...

**Comment by h1z1** [comment]
Can confirm this on Palemoon 26.2.2, it randomly disappears.  Restarting the browser, cycling the plugin or re-adding it to the toolbar restores the icon.  

uMatrix: 0.9.3.5
uBlock: 1.7.6

**Comment by grumpygeek** [comment]
"uBlock, HTTPS Everywhere and SDC are all fine) "

SDC has been having and causing this instability problem for years.   Ghostery does too.  And a few others I don't recall, all restartless, and all/most place their button at the right edge, always starting on the nav toolbar, and are not stable when moved anywhere else.  It's based on an old, underlying flaw in Mozilla's code which is not likely to ever be fixed.

uMatrix is mostly stable (for me) in the default position at the right edge of nav bar, without SDC or Ghostery installed.  But occasionally uMatrix will disappear after installing a new extension that tries to take that spot.

**Comment by Cerberus-tm** [comment]
@grumpygeek That's strange. For me, the icons of Pushbullet, Redirector, and Self-Destructing Cookies also disappear often after a browser restart. What is more, the add-ons also don't work at all when that happens! For example, I can't send anything through Pusbullet when that happens, nor receive anything. And Redirector doesn't redirect.

So you say this is a problem inherent in Firefox. Would there be any way to prevent this from happening manually, or some kind of work-around?

**Comment by grumpygeek** [comment]
I think there is zero chance of Mozilla fixing it, unless it also affects the new web extensions.  It's been happening longer than I can recall, maybe 2.0.  Also affects SeaMonkey, but not as bad, and every other Mozilla browser I've tried (not counting K-Meleon, which used to have plenty of its own problems).  And may be one of the causes relating to the profile becoming irrevocably corrupt once you have around 4-5 dozen extensions installed.  I've been through that process too many times.  The new SDC alternative for PM, Crush Those Cookies, is also badly affected (maybe Gorhill could give him some tips on what he did).

**Comment by Cerberus-tm** [comment]
@grumpygeek Hey, I somehow never saw your reply. I'm glad to see that Crush Those Cookies was fixed. Do you still experience this issue? I must say I haven't seen it happen in a long while. Perhaps it stopped happening once I started to always force-close Firefox: that seems to have helped. And is the issue still present in Firefox 57, that you know? I'm still on an older version.
