### ISSUE TITLE
setting get reset (randomly?) at the after some firefox launches

### ISSUE THREAD

**Issue by rezad1393** [gorhill/uMatrix#530]
after updating firefox to 45.0.1 setting of umatrix gets reset almost randomly between firefox launches.

**Comment by gorhill** [comment]
uMatrix uses FF's SQlite API, so something wrong on your computer -- quite possibly a corrupted uMatrix's SQlite db. I suggest you back up your settings, delete `[your Firefox profile]/extension-data/umatrix.sqlite`, then restore your backup.

There were issues opened in the past about corrupted SQlite db, look for them here and in uBO project for insights on how to avoid such corruption.

**Comment by rezad1393** [comment]
that is what I actually done so that I don't have to set my rules from scratch.
but it happened 2 times after that two.
right now I don't know what triggers it.
I just know that the first time it happened and it happened the first time just after updating to firefox 45.0.1
