### ISSUE TITLE
incorrect displaying of subdomains (com.au)

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#532]
so this issue was quickly fixed (i dont know what happened), but i thought i would open up an issue anyway in case you knew what caused it or can produce it again.

steps:
1. visit http://dev.bentechsolutions.com.au/
2. whitelist some things e.g. first party scripts, css/js on third party cdns (while on the `bentechsolutions.com.au` context)
3. restart browser (with restart button in menu)
4. now it shows the matrix like this:
![bentech](https://cloud.githubusercontent.com/assets/6548571/13976821/6750b91c-f117-11e5-8c6c-68933f312791.png)

it wouldnt show the base domain, it would show `com.au` instead, even though it was fine the first time. i then opened the website in a new tab and it was fixed, but that had me confused for a bit and not sure what caused it. its now 'fixed' but the fact that it happened might be a problem.

**Comment by berrythesoftwarecodeprogrammar** [comment]
woops forgot to add:
Firefox 45.0.1 (updated today)
uMatrix 0.9.3.3

**Comment by gorhill** [comment]
Duplicate of #56.
