### ISSUE TITLE
Cookie incorrectly blocked when denied in * scope but allowed in site/domain scope.

### ISSUE THREAD

**Issue by Mikachu** [gorhill/uMatrix#535]
This is sort of weird, but I was losing the ncr cookie on google.com intermittently (the one that says don't redirect to .whatevercountry) that you get by visiting google.com/ncr. I finally figured out this only happens if I have default block of cookies, and allow on the site or domain scope, but it's fine if I default on in the global scope. Also weirdly all other cookies appear to be fine, I stay logged in on google.com and I haven't noticed any problems on any other sites.
It also works for "a while" after visiting /ncr, then after maybe 5 minutes or so the next visit will forget and redirect to the country domain.

**Comment by Mikachu** [comment]
Well, it seems like I was wrong even though I tested for a few days before reporting; I just got redirected with default whitelist cookies on google.com... And this time it took 9 hours to break apparently.

**Comment by Jalkion** [comment]
I think I found the problem, when you got to youtube.com it wants to access your google cookies and when it doesn't find them because you have blocked access it just writes a new NID cookie which resets your preferences.

**Comment by Mikachu** [comment]
Like I said, this happened when I had all cookies on all sites globally default to whitelisted, so youtube.com was already allowed to access my google.com cookies when I encountered the issue the final time. I also just checked that I don't have any relevant "cookie block" lines either.

**Comment by Jalkion** [comment]
Yeah I forgot that part when I found out how to reproduce it.

If you open the uMatrix logger and filter by "cookie google" and go to youtube.com with cookie block on for google.com it should show this [https://i.imgur.com/WjQL3rv.png](url)

**Comment by gorhill** [comment]
Closing: old issue, no exact repro steps (1., then 2., then 3., etc.), no relevant information provided (browser, version, ruleset, etc.), no evidence provided (example, logger output stating that such and such cookies were deleted). I will re-open when the case is **clearly made** there is an issue with uMatrix.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
