### ISSUE TITLE
[Feature Request] crunch "If-None-Match" header

### ISSUE THREAD

**Issue by N4melessGitter** [gorhill/uMatrix#537]
It would be a great privacy feature for people who have cache enabled, to be able to hide "If-None-Match" headers for all non-blocked requests. (ie prevent E-Tags tracking)
I looked at the source and I think all it would need is a new checkbox in the settings panel and one more IF clause in traffic.js after the ua-spoof:

```
if ( µm.tMatrix.evaluateSwitchZ('if-none-match', pageStore.pageHostname) ) {
        details.requestHeaders.setHeader('if-none-match', '');
}
```

Maybe it would fit better in uBlock as it doesn't make sense to have this enabled on a scope-level.

Privoxy can do this already but only for http and Modify Headers add-on doesn't see what you call behind-the-scene requests.

I tried to implement this in my local copy of the .xpi but couldn't get a proper repack done,
so I would greatly appreciate it if you would add this feature to either uBlock or uMatrix.

Thx

**Comment by gorhill** [comment]
Use "Clear browser cache every [...] minutes" to take care of etag-based tracking.
