### ISSUE TITLE
CSP rule breaks site unless 1st party scripts are allowed

### ISSUE THREAD

**Issue by afontenot** [gorhill/uMatrix#538]
[This page on archlinux.de](https://www.archlinux.de/?page=PackageStatistics) uses no scripts, but uMatrix adds (or modifies) the content-security-policy header and breaks the (same domain) CSS. CSS is allowed in uMatrix, scripts are not. I see the following security errors

    Content Security Policy: Couldn't parse invalid host 'unsafe-inline'script-src
    Content Security Policy: The page's settings blocked the loading of a resource at self ("style-src https://www.archlinux.de https://www.archlinux.de"). 

If I allow 1st party scripts on uMatrix, the CSS is no longer blocked by CSP. But I shouldn't have to enable scripts to use a site that doesn't have any scripts. 

Tested in Firefox 45.0.1 on Archlinux.

**Comment by gorhill** [comment]
There is a specific code path for which the CSP directive created by uMatrix is malformed.

**Comment by gorhill** [comment]
I uploaded 0.9.3.5rc0 with the fix in the dev channel on AMO.
