### ISSUE TITLE
TabContext.onGC has bad scalability on FF

### ISSUE THREAD

**Issue by the8472** [gorhill/uMatrix#540]
I've obtained the following profile on a FF session with µMatrix and many tabs.

![profiler output](http://i.imgur.com/OXU9mmW.png)

As you can see the `onGC` function spends many seconds in `indexFromBrowser`. I think this might be because [tabbrowser.browsers](http://mxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#2868) does some XUL and proxy object hocuspocus which then leads to a very inefficient `indexOf`

I think simply keeping a `WeakMap` of \<browser\> => ID and a `Map` of ID => [weakreference](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.getWeakReference)(\<browser\>) should reduce the need for cleanup.

All that would be left would be scrubbing of IDs that map to nulled weak references.

**Comment by gorhill** [comment]
Thanks for the investigation/insight, I didn't know about `Components.utils.getWeakReference()` -- that would solve the issue I was facing not being able to iterate through a WeakMap. However there is [this part in the doc](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.getWeakReference):

> just because get() succeeds doesn't mean your object is valid. It might simply not have been garbage collected yet

So the way I understand this, I would have to double-check whether the weak browser reference is really valid by looking up <browser> => ID?

**Comment by the8472** [comment]
This probably refers to weak references simply not being aware of any internal lifecycle that an object might have. I.e. they don't get nulled magically just because you close/invalidate/shutdown some object that supports such things.

Whether that's actually a problem depends on downstream consumers of the object returned from the weak reference. It's no different from fishing some old dom node that has long been detached or a channel that has been closed out of some javascript variable.

**Comment by the8472** [comment]
Ah, I looked at the code. In addition to the weakmap/ref stuff [this check](https://github.com/gorhill/uMatrix/blob/4336c5c7c48e6b88f594151fce80e72a07bef385/platform/firefox/vapi-background.js#L1092-L1095) could be replaced with something else that doesn't need the index operation.

Checking whether the `<browser>` is still attached to the DOM might be the most efficient way.

Alternatively there is `browser.ownerDocument.defaultView.top.gBrowser.getTabForBrowser(browser)`, but I don't know whether that's any more efficient, I think it might also iterate internally.

**Comment by gorhill** [comment]
If this works well, I will import the changes into uBO as well.

**Comment by the8472** [comment]
Looks good. Haven't seen any more hangs on  0.9.3.5rc1

**Comment by sheepdestroyer** [comment]
Running the RC with this fix since release, no pb. Is is still planned to port that fix to uBO?
