### ISSUE TITLE
Port websocket filtering from uBlock

### ISSUE THREAD

**Issue by TheRyuu** [gorhill/uMatrix#543]
Since I use both uBlock and uMatrix I don't/can't use dynamic filtering in uBlock (since only one can be used to block scripts) so it would make sense to have it in both(?) provided it can be done so they don't interfere with each other.

I know your general feelings on pull requests so I'm just starting with this instead.  Since they both use a similar vAPI backend hopefully it shouldn't be difficult to port it over provided the design itself has shown to be sound (since it's something of a workaround for Chromium based browsers).

**Comment by gorhill** [comment]
Already in there since a while, reported in `XHR` column.
