### ISSUE TITLE
with docs.google.com (FF45-46 et uMatrix 0.9.3.3)

### ISSUE THREAD

**Issue by babyblue69** [gorhill/uMatrix#545]
With uMatrix 0.9.3.3 it is impossible to reach the Google pages docs, which I share with the members of my guild (information: list Stuff and Cap-Stats in game).
Only solution to solve the problem, it is the deactivation of the extension in the administrator of Firefox 45.0 or 46.0

**Comment by gorhill** [comment]
What else did you try aside "deactivation of the extension"?

**Comment by babyblue69** [comment]
All, one after the other one.
....
EverSync
Ext. Download manager tweak
Facebook Disconnect
FEBE
Gestionnaire de session
T - Google Translator for Firefox
Speed Dial [FVD]
Stylish
uBlock Origin
WhatsApp Desktop
WOT

**Comment by CrisBRM** [comment]
Gorhill is asking if you tried to fix it using the scopes/toggles.

**Comment by babyblue69** [comment]
yes

**Comment by babyblue69** [comment]
yes

**Comment by babyblue69** [comment]
yes

**Comment by babyblue69** [comment]
Yes, I also made that.

I made a screenshot jpg and png 1024x718 409k but " Attach rows " do not want it, even the File was converted in PDF.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by babyblue69** [comment]
Thank ......
Easy to close the post instead of solving the problem

browser version/ublock version   >   Fact 
these settings, these filter lists, these custom filters.   >   Fact
do this.
open this exact URL.   >   Fact    https://docs.google.com/spreadsheets/d/1o2jMQCxbto-fdEb7qGoIcesml6J7j7GF8tP_O7HDcQk/edit#gid=703121560
do this.
observe this.   >   Fact
click this.   >   Fact
observe such and such issue   >   Fact
see screenshot   >   Fact :

![screenshot 27-04-2016](https://cloud.githubusercontent.com/assets/7869009/14886577/bb53d200-0d51-11e6-90cc-7b33165345b6.jpg)

**Comment by gorhill** [comment]
Did you try disabling the per-site switches?

**Comment by babyblue69** [comment]
YES

**Comment by gorhill** [comment]
> YES

Sorry can't help you.

**Comment by babyblue69** [comment]
Well, OK
I am going to return on less good NoScript, but it works with everything sites

**Comment by babyblue69** [comment]
Anyway, thanks for your help.
If to find you the solution, made the I to know.

**Comment by gorhill** [comment]
After you changed the rules, did you force a refresh the page using uMatrix's own button?

**Comment by babyblue69** [comment]
Uninstall, reinstall, reset (setting default) and there it works, thank you for the help(assistant) that you brought me, good continuation.
