### ISSUE TITLE
Rename "Long-lived malware domains‎" to "Malware domains (long-lived)‎"

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uMatrix#546]
Rename "Long-lived malware domains‎" to "Malware domains (long-lived)‎" and place next to "Malware domains‎" to show that these two lists are from the same site and one is essentially the subset of the other. Also, the corresponding filter in uBO is named "Malware domains (long-lived)‎".

**Comment by gorhill** [comment]
This file is not longer part of the project.
