### ISSUE TITLE
Changes to wiki

### ISSUE THREAD

**Issue by SRGOM** [gorhill/uMatrix#548]
Can you please add the following to the wiki page:  "Very bare walkthrough for first time users"
I tried but I don't have permission to edit wiki

---

Lets get the easy stuff out of the way first: the bottom rows in dark red are blacklisted websites. Websites are blacklisted based on the "Hosts File" in settings (small gear icon in the top left). A website being blacklisted means that by default no content will be loaded from it. 

> Strict blocking (dark red) trumps strict everything else, including strict allowance (dark green). If any row or column header is dark-red, any cell in that row or column will have to be individually changed to allow content. 

Coming to the third-party websites then which are in light red by default. Notice how all the columns in these rows are light red except css and image which are light green. As you may have guessed, it means that the only third party content that's allowed is css and images. In the top row (the row header for which is `all`), you see css and images in dark green which says allow for `all`, css and images. If you wish to by default block `all` css which cannot be overridden by any general rule (read rule enforced by clicking row header) then make the `all` css cell dark red. Notice that now for all first party websites, the respective css cell is light red. 

> To change a header/cell color, clicking on its upper half changes to and from green, clicking on its bottom half changes to and from red. 

You can try changing the row header to any color and yet the cells will remain light red. This proves the previous point about how strict blocking trumps everything else. Now we can make a guess about the default rules:  (which are in settings -> user-rules)
- Cookies: Allow only first party
- CSS: Allow all 
- Images: Allow all
- Plugins, script, XHR (ajax): Disable all
- Frames: Strictly disable all, allow first party
- Others: Disable all

Its easy to see that this exactly matches the rules in settings -> user-rules. The default out-of-the-box rules (as of this writing) are: 

```
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
```

The asterisk in the first column corresponds to the fact that these rules are global and not site specific. To create a site-specific rule, replace the asterisk in the first column with the website address. The second and third columns refer to the row and column respectively. Row values can be 1st-party or \* (meaning all websites) and column values can be css/frame/image/script/xhr etc. 

Say you've made a lot of temporary changes but wish to go back to the original "default" state, hit the rubber button, third from the right in the top-right row. If you want to make these changes permanent, hit the lock button. You'll see that when you hit the lock button, the newly created filters get a small triangle on the upper left side.

Say you wish to temporarily enable all scripts from all websites- make the script column header dark-green. 

Say you wish to disable everything from a certain third party website- make the row for that third-party website dark-red.

> You may need to refresh the page to allow changes to take effect

---

**Comment by SRGOM** [comment]
@gorhill  Sorry I don't mean to bother repeatedly but bringing this to attention again in case there is some change you want me to make to this before you can commit this to the wiki...

**Comment by gorhill** [comment]
I have created more documentation lately, so hopefully this address the issue.
