### ISSUE TITLE
Allow #starting comments in rules

### ISSUE THREAD

**Issue by SRGOM** [gorhill/uMatrix#549]
There should be an option to end a rule with a string starting with \#, e.g.: 

> * google.com frame allow \#For captcha 

So that I can comment all my rules and I know why a rule's there

**Comment by TripleCxx** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by gorhill** [comment]
The rules are a view on uMatrix internal database -- there can't be comments, they would be discarded whenever a rule is removed through a mere click on a cell in the popup panel.
