### ISSUE TITLE
Ability to​  modify HTTP_ACCEPT headers ​

### ISSUE THREAD

**Issue by gorhill** [gorhill/uMatrix#55]
Through email:

> For further anonymization, and because User agents are, for most people (not me since I am always on the latest version of Chromium x64​, very identifiable​), obsolete​ (unless they use a nightly or obscure browser)​, it​ is​ important to​ have the ability to​ modify HTTP_ACCEPT headers​ (especially for people who live in smaller countries), assuming this is possible​. Though having the option of cycling it from a list every n minutes would be great as well.
> 
> ​I would recommend the following to be the default, to more effectively crack down on the usage of fingerprinting tools:
> "accept_encoding":"gzip,deflate,sdch",
> "accept_default":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8",
> "accept_lang":"en-US,en;q=0.8",

Will have to think carefully about this. Just a single whitespace, missing or not, is enough to make one browser stand out among others. I don't have access to any stats regarding strings in widespread use, so it is a bit difficult here to work in blind mode.

My earlier thoughts on this is that the HTTP_ACCEPT header should be tightly coupled with the UA string, and to support the ability to add a suffix string to the candidate UA strings, which suffix, if present, would be used for the HTTP_ACCEPT header.

**Comment by CrisBRM** [comment]
@jankkm Whilst I can't confirm the veracity of your initial statement (though it does seem suspicious), HTTP_REQUEST headers are not browser dependant and constitute an enormous privacy risk for tech literate people from smaller countries.
