### ISSUE TITLE
Umatrix dialog goes under taskbar

### ISSUE THREAD

**Issue by floggle** [gorhill/uMatrix#550]
Palemoon - Version: 26.2.1 (x64)
uMatrix: 0.9.3.3
Windows 7

I have my Windows taskbar on the right side of the screen. When I open the uMatrix dialog to alter the settings for a specific site, much of the the dialog is under the taskbar. It seems the plugin is assuming the width of the screen is where it should put the right-most-bounds of its dialog rather than using the width of the browser window (which is regular full-screen and doesn't go under the taskbar).

**Comment by gorhill** [comment]
Browser issue -- out of control of uMatrix.
