### ISSUE TITLE
[Firefox] Cookies are not blocked even using "* * cookie block"

### ISSUE THREAD

**Issue by Lvl4Sword** [gorhill/uMatrix#553]
1. Install uMatrix
2. Go to chrome://umatrix/content/dashboard.html#user-rules
3. Add the following to your permanent rules: * * cookie block
4. Go to the following website: https://www.wikipedia.org/
5. Go to about:preferences#privacy and in History set Remember History to Use custom settings for history
6. Click "Show Cookies..."
7. Cookies from wikipedia are shown, even though they should be blocked for every site.

Regardless of cookie settings in about:preferences#privacy this still occurs.

**Comment by byte-jra** [comment]
You really should inspect the chrome://umatrix/content/dashboard.html#privacy tab ...

**Comment by Lvl4Sword** [comment]
@byte-jra I don't believe I'd call that a "fix". There's still bad conveyance, and everything else works. Why should cookies be any different? If there's a technical reason behind this, worst case scenario is at least letting the user know.
