### ISSUE TITLE
Blanket-allowing cloudfront.net still blocks some of the random named xxx.cloudfront.net

### ISSUE THREAD

**Issue by Kyamon** [gorhill/uMatrix#555]
I have blanket-allowed `* cloudfront.net * allow` and it still blocks a few of the randomly named things.

![shark_sonic_duo_infomercial_-_vidme_-_mozilla_fi_24-05-2016_107](https://cloud.githubusercontent.com/assets/15200348/15522869/c5313aac-21d2-11e6-8891-297e55a42f19.png)

**Comment by gorhill** [comment]
Because these appears in one of the blacklist. This is how uMatrix works.
