### ISSUE TITLE
Facebook Settings

### ISSUE THREAD

**Issue by dmiranda12** [gorhill/uMatrix#556]
Hi Cris.  Thanks for your work on this.  I installed this extension and ublock origin last night, and after getting rid of adblock plus and noscript, I have started playing around.  As https://github.com/gorhill/uMatrix/wiki/Examples-of-useful-rulesets, you touch briefly on facebook. I managed to make it work fully, including videos from FB and youtube (have not ried yet with googlevideo) with the following settings.  I wonder if they could be further constrained.  Please note that I am blocking all the FAMA + Yahoo and Google by default.  Thanks for your work in this!

* facebook.com * block
* facebook.net * block
facebook.com akamaihd.net * allow
facebook.com facebook.com * allow
facebook.com facenet.net * allow
facebook.com fbcdn.net * allow
facebook.com staticxx.facebook.com frame allow
facebook.com www.facebook.com frame allow
facebook.com youtube.com * allow
facebook.com youtube.com frame allow
facebook.com ytimg.com * allow

**Comment by gorhill** [comment]
Who's "Cris"?

Anyways, closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by dmiranda12** [comment]
Sorry about that.  Chris is the name that appears in the wiki, I thought.
I posted the same suff plus some google rules in the wilders security forum
Thanks.
