### ISSUE TITLE
Extension doesn't work on chrome.google.com

### ISSUE THREAD

**Issue by PaulBags** [gorhill/uMatrix#557]

**Comment by berrythesoftwarecodeprogrammar** [comment]
this issue is going to be closed since you haven't provided any details at all

**Comment by PaulBags** [comment]
The details are that the extension does nothing in the chrome webstore, chrome.google.com. http://chrome.google.com, extension does nothing there. Cannot use uMatrix in the chrome webstore. I can't think of any other ways to say it, or any other details to add - i t   j u s t   d o e s n ' t   w o r k   o n   c h r o m e . g o o g l e . c o m.

**Comment by berrythesoftwarecodeprogrammar** [comment]
so its not blocking anything? what browser? what version of the addon? what do you see in the matrix?

**Comment by berrythesoftwarecodeprogrammar** [comment]
ok i can reproduce this with the url https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf?hl=en

doesnt happen in firefox. happens in google chrome with any `chrome.google.com` url. the matrix shows as empty and nothing appears in the logger for those tabs

Chromium 52.0.2739.0 (64-bit)
uMatrix 0.9.3.3

**Comment by berrythesoftwarecodeprogrammar** [comment]
the same happens with ublock on chromium it seems

**Comment by PaulBags** [comment]
Latest Chrome, 0.9.3.3, screenshot: http://iforce.co.nz/i/uppmbkel.wvp.png

**Comment by gorhill** [comment]
No extensions work on `chrome.google.com`.
