### ISSUE TITLE
Allow * in hyperlink rules, e.g. fbcdn-*.net to allow fbcdn-a.net and fbcdn-b.net

### ISSUE THREAD

**Issue by SRGOM** [gorhill/uMatrix#560]
There are some sites which use the format xyz-a.something.com, akamaihd.net being one. Is it possible to allow xyz-*.something.com to consider xyz-a.something.com and xyz-b.something.com both so that the rule list can be smaller?

**Comment by gorhill** [comment]
That would require a whole new UI and core implementation.
