### ISSUE TITLE
Custom rules reset after each browser restart (Seamonkey)

### ISSUE THREAD

**Issue by figvam** [gorhill/uMatrix#561]
Hello,
Thanks for another excellent extension!

My custom rules are always reset after each browser (Seamonkey 2.40/Linux) restart, uMatrix 0.9.3.3.
I checked umatrix.sqlite, apparently custom rules are saved in "userMatrix" setting. I looked at this setting before and after the restart, and it's exactly the same. But going to the dashboard after the restart, all I see is the default rules. When I edit something and commit, the "userMatrix" row in the sqlite file is updated.

There are also some uMatrix related errors in the console when I open the rules tab, see the attachment.
(I have a strong feeling of deja vu... see case 1034 in the uBlock project. Such is a fate of us Seamonkey users...)
![scr-umatrix](https://cloud.githubusercontent.com/assets/316709/15677141/0d878860-275a-11e6-8d39-0526391f08a5.png)

**Comment by figvam** [comment]
Here are all umatrix entries from the startup log:
`JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 687: TypeError: win is null
JavaScript strict warning: chrome://umatrix/content/js/cookies.js, line 499: ReferenceError: reference to undefined property vAPI.cookies
JavaScript error: chrome://umatrix/content/js/cookies.js, line 499: TypeError: vAPI.cookies is undefined
JavaScript error: chrome://umatrix/content/js/assets.js, line 131: TypeError: vAPI.lastError is not a function
JavaScript error: chrome://umatrix/content/js/assets.js, line 131: TypeError: vAPI.lastError is not a function
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1400: TypeError: getTabBrowser(...) is null
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1400: TypeError: getTabBrowser(...) is null
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1400: TypeError: getTabBrowser(...) is null
.....
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1400: TypeError: getTabBrowser(...) is null
Document chrome://umatrix/content/dashboard.html loaded successfully
JavaScript strict warning: chrome://umatrix/content/js/messaging.js, line 586: ReferenceError: reference to undefined property vAPI.cloud
JavaScript error: chrome://umatrix/content/js/messaging.js, line 586: TypeError: vAPI.cloud is undefined
`

**Comment by gorhill** [comment]
Please use the latest version of uMatrix, which is 0.9.3.4, and see if this works. If not, could you try the dev version (available on AMO) 0.9.3.5?

**Comment by byte-jra** [comment]
0.9.3.5rc1 user here - same story. Just wanted to say that I've become used to disabling and immediately re-enabling uMatrix (and another extension) after starting Seamonkey, else it won't work (or in uMatrix case load its settings).

**Comment by figvam** [comment]
Interesting. Looks like AMO still has 0.9.3.3?
Anyway, updated to 0.9.3.5rc1 but no luck. The log follows:

```
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 687: TypeError: win is null
JavaScript strict warning: chrome://umatrix/content/js/cookies.js, line 499: ReferenceError: reference to undefined property vAPI.cookies
JavaScript error: chrome://umatrix/content/js/cookies.js, line 499: TypeError: vAPI.cookies is undefined
JavaScript error: chrome://umatrix/content/js/assets.js, line 131: TypeError: vAPI.lastError is not a function
JavaScript error: chrome://umatrix/content/js/assets.js, line 131: TypeError: vAPI.lastError is not a function
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1416: TypeError: getTabBrowser(...) is null
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1416: TypeError: getTabBrowser(...) is null
....
JavaScript error: chrome://umatrix/content/js/vapi-background.js, line 1416: TypeError: getTabBrowser(...) is null
JavaScript strict warning: chrome://umatrix/content/js/vapi-background.js, line 896: ReferenceError: reference to undefined property details.popup
Document chrome://umatrix/content/dashboard.html loaded successfully
JavaScript strict warning: chrome://umatrix/content/js/messaging.js, line 586: ReferenceError: reference to undefined property vAPI.cloud
JavaScript error: chrome://umatrix/content/js/messaging.js, line 586: TypeError: vAPI.cloud is undefined
Document https://github.com/gorhill/uMatrix/issues/561 loaded successfully
JavaScript error: chrome://umatrix/content/js/vapi-client.js, line 43: NS_ERROR_NOT_INITIALIZED: 
JavaScript error: chrome://umatrix/content/js/messaging.js, line 586: TypeError: vAPI.cloud is undefined
JavaScript error: chrome://umatrix/content/js/vapi-client.js, line 43: NS_ERROR_NOT_INITIALIZED: 
```
