### ISSUE TITLE
option to keep cookie intact when cookie are blocked?

### ISSUE THREAD

**Issue by tx9191** [gorhill/uMatrix#563]
On many websites blocking fisrt-party cookie makes the login records in cookie get overwritten. That forces me to enter the password again to relogin after I revoke the cookie blocking, which increase the risk of leaking the passwrod when that happens on a non-https website.

**Comment by crssi** [comment]
That's normal, since you get rid of the cookies upfront already.
If you visit 1st party page with cookies allowed that would not happen.
I have 1st party cookies allowed and I am using then "Self-Destructing Cookies" extension, which deals with the cookies and other sort of super-cookies really good.

**Comment by gorhill** [comment]
> On many websites blocking fisrt-party cookie makes the login records in cookie get overwritten. That forces me to enter the password again

Don't block these 1st-party cookies if you do not like the side effects of blocking 1st-party cookies.

**Comment by tx9191** [comment]
@crssi uMatrix doesn't block any cookie in the http responses(i.e. Response Cookies) sent from the websites, it blocks cookies by preventing the cookies data be sent to the website. So far uMatrix hasn't offered a way to block cookies on the reponse end. 

It's common for a website to set new cookies for a browser when it find there is no cookie data in the http request from that browser, and that new cookies are very likely to overwrite the login information that is set earlier.

Unnecessarily browsing websites after login allows them establish a link between your browsing behaviour and you accounts. And deleting the cookies forces you to enter your passwords again when you need to login, which may give someone more chances to catch them on theirs route to the website servers when the communications are not encrypted.

I think it's useful for umatrix to get the ability to  block the Response Cookies, allowing me to "log in"/"log out" by allow/block the cookies with just one click, without concern of entering password

**Comment by gorhill** [comment]
I can't make sense of your request here: on a site which requires cookies to log in, you want to be able to login without cookies being exchanged.

**Comment by tx9191** [comment]
My scenario: 
1.to log in a website to check if there is any new massage sent to my account.
.
2.After finishing the checking, I'd like to read some news or other stuff which don't require login and cookie on the same website. And I don't want the website to collect my browsing behaviour and link it to my account/e-mail/phonenumber or other information I store on that site. So I block the cookie for the site,along with 'Delete local storage content set by blocked hostnames' enabled, so that the website deem me as a new user to it. 
(Simply loging out doesn't do the trick as there's very likely to be some information for recognizing me in the cookie even after logging out.)

3.At the next time when I want to check message in my account, I revoke the cookie blocking for that site. Because the cookie that records the login information has been overwriten now, I have to enter my id/password again - in some cases I have to go through the boring 2-step login again and again, in some other cases I send my password in plain text over the internet several times a day.

4.If uMatrix can block the Response Cookies to keep the cookies that contain my login information intact, I can simply revoke the blocking temporarily and the site will immediately treat me as a logged-in user without requiring my id/password again.
