### ISSUE TITLE
Spoof user-agent string at the end of the session instead

### ISSUE THREAD

**Issue by mindstormer12** [gorhill/uMatrix#565]
By default uMatrix spoofs the user-agent string every 5 minutes. Spoofing user-agent string is an attempt to obscure your identity and reduce your fingerprint. This is way too frequent and makes your fingerprint more unique--no average user would change his user-agent string this often and this unusual behavior will identity you as part of a very small group of paranoid people. This is one of the legitimate criticisms of the Random Agent Spoofer addon.

Instead of (or in addition to) spoofing at such a frequent interval, why not spoof at the end of the session for the next? It will also be consistent with clearing cookies at the end of the session, which many people do. 

On an unrelated-note, does uMatrix spoof JavaScript variables as well in addition to spoofing user-agents? If they are not spoofed as well, spoofing user-agents is almost pointless because many sites use JavaScript and its variables can be checked as a form of fingerprinting. If it's the case that both are not spoofed, then tracking companies can easily know your failed attempt at spoofing and you are therefore exposed and unique.

**Comment by Superbest** [comment]
@gorhill Out of curiosity, why did you decline this? Do you feel that 5 minute setting to be a sane default, or did you already have a different improvement planned?
