### ISSUE TITLE
Custom referrer spoofing

### ISSUE THREAD

**Issue by dangranos** [gorhill/uMatrix#568]
While it's nice to be able to disable and enable referrer spoofing per scope, i would like a way to set own referrer string for a scope. For example, when i go to site X from any other site and i have custom referrer for X, it will spoof the referrer to Y, which i set for it.

This is required because some sites use referrers to access some pages (damn adwalls) and disabling all spoofing just for those sites is a bit uncomfortable (and for some reason just disabling it for that scope didn't work, or maybe i just messed up).

Edit: Don't worry, per-scope spoofing toggle works. Just checked that yet again. It was just that site used a redirect in case of spoofed referrer.

**Comment by anewuser** [comment]
@dangranos Please close this issue if you've solved your problem.

**Comment by anewuser** [comment]
Now I understand the issue. I've disabled spoofing for `solvemedia.com`, but when I open [this URL](http://www.emuparadise.me/Atari_2600_ROMs/A-Team,_The_(AKA_Saboteur)_(05-08-1984)_(Atari,_Jerome_Domurat,_Howard_Scott_Warshaw)_(CX26133)_(Prototype)/91171-download), it still spoofs the referrer while requesting `solvemedia.com` scripts unless I disable it for `emuparadise.me` too, even though there's no redirect in place.

**Comment by berrythesoftwarecodeprogrammar** [comment]
just use the Refcontrol addon
