### ISSUE TITLE
Forced to disable extension to be able to watch videos on twitch and in some cases other sites as well.

### ISSUE THREAD

**Issue by PerfyNormal** [gorhill/uMatrix#569]
There's an issue with watching streaming videos on Twitch and some issues with sites such as Hugefiles and similar, where capcha will not work even if you turn off or let all scripts through.
Every time I want to watch Twitch video I am forced to disable uMatrix or it will not work, I've got no clue how to work around this.

**Comment by gorhill** [comment]
Read carefully: <https://github.com/gorhill/uMatrix#warnings>.
