### ISSUE TITLE
What happened to subdomain rules? Can I opt-out?

### ISSUE THREAD

**Issue by Forkest** [gorhill/uMatrix#570]
On sub.example.com I no longer have sub.example.com row, but only *.example.com

Scripts and other elements from upper domains may be used not for usability, but for tracking purposes only. More scripts than minimally needed may hurt performance. All in all I'd like to have the rules separated.

I guess the change was done for simplicity, but why reducing capabilities without a switch?

**Comment by gorhill** [comment]
There was no change. If you want the subdomains visible, expand using the expand/collapse button on the _all_ cell.

**Comment by Forkest** [comment]
Oh, thanks! Probably clicked it accidentally. Sorry for the inconvenience.
