### ISSUE TITLE
Allow dom storage but deleting it periodically, like cache or cookies?

### ISSUE THREAD

**Issue by rieje** [gorhill/uMatrix#573]
I couldn't find much information on the setting "Delete local storage content set by blocked hostnames," but enabling it means dom storage is disabled whether or not cookies are blocked in uMatrix and disabling the setting means dom storage is allowed only when cookies are allowed--is this correct? "Deleting local storage content" implies that dom storage is enabled and dom data is written though, doesn't it?

Anyway, how about a feature to allow dom storage (perhaps treat it separately from cookies) and and be able to specify an interval to delete it periodically like what is capable for cache and cookies?

**Comment by gorhill** [comment]
Whether the local storage is cleared or not depends on the "cookie" column in the matrix, and whether the setting to cleared local storage is enabled.

> how about a feature to allow dom storage (perhaps treat it separately from cookies) and and be able to specify an interval to delete it periodically like what is capable for cache and cookies?

The cache is a browser-wide operation. Cookies and local storage is a per-site rule, reflected by the "cookie" cell in the matrix.

**Comment by rieje** [comment]
I don't understand--so if I have that option checked and some of the cookies are enabled while the rest are disabled under the cookies column, you said they are deleted, implying that some dom data is stored at some point (which allows some sites that require it to function). So when does it delete the dom storage? Or do you mean that the dom storage is completely disabled and no dom data is stored ever?

**Comment by gorhill** [comment]
- A web page loads
- uMatrix checks whether cookies are blocked/allowed for the page
    - if cookies are blocked, then uMatrix checks if the setting to delete local storage is enabled
        - if the setting is enabled, the content of localStorage/sessionStorage is cleared

**Comment by rieje** [comment]
Last question--is dom storage cleared along with cookies at the specified interval that cookies are deleted?

**Comment by gorhill** [comment]
> is dom storage cleared along with cookies at the specified interval

Not along with cookies, and not a interval: it's done once at page load time, using a content script, because `window.localStorage`/`sessionStorage` can be accessed only using same-origin policy.
