### ISSUE TITLE
Finer-grained script & plugin control

### ISSUE THREAD

**Issue by agentxray** [gorhill/uMatrix#574]
It would be great if we could (dis)allow individual plugins and script types independently from one another rather than just lumping them all together. For example, I want to disallow scripts except for canvas, because I think adding noise to canvas fingerprints is far better than blocking them.

**Comment by CrisBRM** [comment]
You can do this with uBlock. Disable a specific url, in this case, ending in .js, on a given hostname.

**Comment by gerg5c42g542g2c54g52c** [comment]
That requires installing two addons for one thing, increases attack surface etc. Why not make one addon that does all an advanced user may need? It's just a matter of adding few small features to uMatrix for it to become one.
