### ISSUE TITLE
uMatrix toolbar icon missed after Seamonkey 2.40 restart or creating new window

### ISSUE THREAD

**Issue by dymn** [gorhill/uMatrix#576]
uMatrix toolbar icon missed after Seamonkey 2.40 restart or creating new window
Gentoo x64, Seamonkey 2.40, Umatrix 0.9.3.6

I'm trying set the about:config option extensions.umatrix.forceLegacyToolbarButton to true and false, but not helped.

**Comment by gorhill** [comment]
I will no longer support legacy Firefox and browsers based on legacy Firefox -- I don't have the time for such a low adoption extension on lower adoption browsers.
