### ISSUE TITLE
Inexplicable interference with Github features

### ISSUE THREAD

**Issue by rheber** [gorhill/uMatrix#577]
Despite any of the following rules:

    matrix-off: github.com true
    * github.com * allow
    github.com * * allow

emoji don't appear correctly, the edit button for repository descriptions doesn't work, and even as I  write this issue I find that the buttons for previewing or adding quotes or code don't work. I'm using Pale Moon 26.3.

**Comment by gorhill** [comment]
You did not list other per-site settings which can also affect web pages: Strict HTTPS, User agent spoofing, referrer spoofing.

**Comment by byte-jra** [comment]
@rheber You also need to allow `githubusercontent.com` in order to fully use GitHub. But a more thorough look at the matrix or the log should have told you so.

**Comment by gorhill** [comment]
Alright, I am going to close this as _invalid_: you do not make the case that there is an issue with uMatrix code (there is no word on whether you investigated the per-site switches). Also, you do not provide any specific URL where the issue can be immediately seen. Make the case there is an issue with uMatrix, and if so, provide easy to repro steps -- never assume I have a handful of bookmarks where your specific issue can be immediately seen (as in no need to log in).
