### ISSUE TITLE
No Resource URI Leak Addon breaks dashboard

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uMatrix#578]
Block Web-exposed subset of chrome URIs, makes chrome://umatrix/content/dashboard.html an empty page with only header tabs.

**Comment by gorhill** [comment]
Please report to the addon causing the issue, not the one suffering from it.

**Comment by gorhill** [comment]
To be clear, there is no web-exposed resources in uMatrix or uBlock Origin.
