### ISSUE TITLE
Menu doesn't open without navigation bar (Firefox)

### ISSUE THREAD

**Issue by z33ky** [gorhill/uMatrix#580]
I've put the uMatrix Button in Vimperator's statusline and disabled the navigation bar (`:set toolbars=nonavigation`). The button is highlighted when I hover the cursor over it, but pressing the button doesn't open the menu, although it stays pressed (background getting darker).
When I reenable the navigation bar the menu works (`:set toolbars=navigation`), but whenever it is disabled, the menu stops popping up.

Another addon where the menu works even without the navigation bar is HTTPS Everywhere (version 5.1.10).

I use Firefox 47.0, Vimperator 3.14.0 and uMatrix 0.9.3.6.

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/issues?q=is%3Aissue+vimperator+is%3Aopen
