### ISSUE TITLE
Site rules do not correctly inherit global rules

### ISSUE THREAD

**Issue by La-Li-Lu-Le-Lo** [gorhill/uMatrix#582]
Using Pale Moon with umatrix 0.9.3.6. I used this webpage to test out my cases:
https://www.reddit.com/r/videos/comments/43wsdi/history_of_japan/

To make it easier to understand what's going on, I made a video. see:
https://www.youtube.com/watch?v=EuXkSV1u8aY&feature=youtu.be

Let me outline what's going on the in the video.
In the beginning, I take a look at the temporary rules. The youtube video is not working because I made temporary changes that make it not show up.
these 2 lines are responsible for that:
{
reddit.com embedly.com frame inherit
reddit.com embedly.com script inherit
}

So then I revert the temporary changes I made and reload. Now the youtube video is working again. Looking through the rules, you can see I removed the temporary rules.

Now I redo the steps I did again to make the video not show up.

example that breaks the rules:
1: start at global tab
2: go to site tab
embedly.com site rule ON
embedly.com script + frame OFF
embedly.com site rule OFF
3: go to global tab and toggle the global permissions just in case
embedly.com script + frame OFF
embedly.com script + frame ON
4: go back to site tab to see the site permissions are still turned off
5: go to chrome://umatrix/content/dashboard.html#user-rules to see that 2 rules have been added as temporary rules
{
reddit.com embedly.com frame inherit
reddit.com embedly.com script inherit
}

These are the same rules that made the youtube video not work at the beginning of the video.

Next, I revert the temporary changes again, then reload the page. youtube video is working again

So in conclusion, there seems to be a problem when the global tab -> site rule that adds inherit rules. Removing the inherit rules manually fixes my problem.

Misc details below. Optional to read if you need more clarification:
During the testing of umatrix, I found out that changing cdn.embedly.com in the global rules does not change cdn.embedly.com in the site rules. I wondered about why this was happening. Something was off, so I decided to go to my user rules to see what was wrong.
chrome://umatrix/content/dashboard.html#user-rules
For some reason, the inherit rules were mixed in here or something, but they weren't correctly inheriting the global rules. After removing the embedly site rules, for some reason, there were still rules to inherit the parent rules like this:
{
- embedly.com frame allow
- embedly.com script allow
  reddit.com embedly.com frame inherit
  reddit.com embedly.com script inherit
  }

However, it looks like inheritance doesn't work. Removing these inheritance rules makes the site work again
{
- embedly.com frame allow
- embedly.com script allow
  }

this is a copy of a working rule set:
{
    matrix-off: about-scheme true
    matrix-off: behind-the-scene true
    matrix-off: chrome-extension-scheme true
    matrix-off: chrome-scheme true
    matrix-off: localhost true
    matrix-off: opera-scheme true
    \* \* \* block
    \* \* css allow
    \* \* frame block
    \* \* image allow
    \* 1st-party \* allow
    \* 1st-party frame allow
    \* embedly.com frame allow
    \* embedly.com script allow
    \* googlevideo.com plugin allow
    \* redditstatic.com script allow
    \* youtube.com plugin allow
    \* youtube.com script allow
    \* ytimg.com plugin allow
    \* ytimg.com script allow
    pricezombie.com www.youtube.com frame allow
    reddit.com \* script inherit
    reddit.com embedly.com xhr inherit
    reddit.com imgur.com frame allow
    reddit.com imgur.com script allow
    reddit.com reddit.com script allow
    reddit.com www.redditmedia.com frame allow
    reddit.com www.youtube.com frame allow
}

Once I add these 2 inherit rules, the youtube video stops showing up.

example that proves my rules are working fine:
1: start at site tab
2: go back to global tab and toggle embedly.com site rule
3: go back to site tab to see the rule has been toggled

**Comment by gorhill** [comment]
I looked carefully at the content of your video, and all is working as expected. You are creating two "graylist" rules ( `inherit`) to override the global whitelist rules for `embedly.com`. These graylist rules tells uMatrix to inherit the rules from the X and Y axes of the matrix, and being explicit rules, they cancel inheritance from the Z axis -- thus the global rules for `embedly.com frame` and `embedly.com script` are no longer taken from the broader scope (the global one in the current instance), but only from the local hostname and type. I am not sure to understand what you did expect to happen.

**Comment by La-Li-Lu-Le-Lo** [comment]
I see now. I guess that's not the issue then.

There is still the problem that comes at `0:40 - 0:47` of the video
When I uncheck the "`embedly.com`" site rule in the `site scope` (I don't know a better term for that. see: http://i.imgur.com/cP0vUje.png) It does NOT delete the inherit rule. I would assume that unchecking that rule would delete this rule, but at `0:52` you can see that after I refresh umatrix's page, the inherit rules are still there. Even though I clearly **unchecked** the "`embedly.com`" site rule.

Now, once this happens, if you go to 1:17, you'll see that I'm trying to toggle the embedly.com script and embedly.com frame rules in the global scope, but it doesn't change anything in the site scope. I see now that I can't because of the graylist rules. However, there would have been no way for me to know a graylist rule was created because I assumed **unchecking** the "`embedly.com`" site rule would completely **remove** the graylist rule.

So really the big problem is that that the graylist rule is being created without being deleted after I uncheck the "`embedly.com`" site rule as in `0:40 - 0:47` in the video.

**Comment by gorhill** [comment]
> It does NOT delete the inherit rule

It comes down to the fact that uMatrix can't read mind. It's not a given that an explicit inherit rule should be removed automatically: one may have toggled the global rule by accident, or just want to remove the global rule temporarily. At time of implementation, I did ponder whether I should remove narrower rules which may have become relevant, but that is just guessing, uMatrix can't know for sure what is the intent of the user. At most, uMatrix could offer an _Optimize_ button in the _My rules_ pane, but it can't do this autmatically and silently. This was also [brought up in the past](https://github.com/gorhill/uMatrix/issues/13#issuecomment-60520652).

**Comment by La-Li-Lu-Le-Lo** [comment]
Okay, I see what you're saying. It would be hard to tell whether you should remove an inherited rule or not if you were to remove a global rule. This is a complicated issue to deal with.

The thing is with the way things are now, you can delete the `global` rule while `inherit` rule is in place. Then both the `global scope` and the `local scope` won't have any rules for the graylist rule to inherit from.

Since there's the issue of accidentally deleting an inherit rule without the user meaning to, then how about this? You should only delete `inherit` rules if the parent rule that created it is deleted as well **AND** if inherit rule is **temporary**. You do not delete any `inherit` rules that are in the `permanent` rules. You wouldn't want to mess with any permanent rules. This way, if the user previously added `inherit` rules and saved it, they wouldn't be deleted. That's the best suggestion I can come up with at the moment. Although again, this is just guessing at the user's behaviour patterns.

For example, these are the Temporary rules umatrix has created before a commit:
```
reddit.com embedly.com script inherit -> added
-- inherit rule is created by umatrix for one reason or another and not committed yet
* embedly.com script allow -> deleted
-- this global rule has been deleted by the user. 
```
The `inherit` rule is still here even though the `global` rule has been deleted. Therefore at this time, the `inherit` rule has nothing to inherit from and is unneeded. So you remove an inherited rule when the user hasn't committed changes for the `temporary` rule.

If all else fails, an _optimize_ button in the My Rules pane would be nice.

As referenced in the other issue thread #13, 

> "I am trying to come up with a slight visual hint that a cell is explicitly graylisted -- there is currently none. I will be experimenting with some ideas of visual, as currently this can lead to confusion."

As for this, maybe you could add a filter with 80% opacity to indicate graylisted cells. At least some kind of visual hint would be good to avoid confusion in the future.

**Comment by gorhill** [comment]
> the inherit rule has nothing to inherit from

There is no such thing as "has nothing to inherit from" in uMatrix. A cell **always** inherit from another cell (the exception being the _all_ cell) -- this is the essence of uMatrix. When a cell has no explicit rule (implicitly graylisted) or is explicitly graylisted, uMatrix will walk-up the inheritance paths until it finds the first explicit rule.

The fact that some seemingly pointless _inherit_ rules can be left behind is completely a trivial issue, not worth adding code upon code to try to deal with this, using a _guessing_ approach at that.
