### ISSUE TITLE
about issue #584 and your behavior, gorhill

### ISSUE THREAD

**Issue by requiredregistration** [gorhill/uMatrix#585]
i will begin with your 'GPL, fork, etc.' comment. the free software movement is not about open source code software only. it is about many things. read carefully everything that richard stallman has written and everything that he writes.

now, about the issue and your behavior.

you declined the request and closed the issue without understanding exactly what is being requested. you locked the issue because you became upset. you talked about logic and then you proceeded to become irrational. you mentioned 'ublock', its 'dynamic URL filtering', and 'trust', things that are completely irrelevant to what is being requested.

WTF has happened to you gorhill? you are not the same gorhill i talked with in the past. maybe you forgot who i am ([my umatrix issues](https://github.com/gorhill/uMatrix/issues?q=is%3Aissue+author%3Arequiredregistration+is%3Aclosed) and [my httpswitchboard issues](https://github.com/gorhill/httpswitchboard/issues?q=is%3Aissue+author%3Arequiredregistration+is%3Aclosed)). you have closed another issue of mine in the past. you were wrong then and you happen to be wrong again now.

you became hostile from your second comment in issue #584. i am not a newbie. i am not requesting crazy and useless things, nor i am requesting things that can be done with other add-ons and extensions already.

it is true, you need a vacation, https://github.com/gorhill/uBlock/commit/dce5487fc0bcb1ad6d9408766d94c47cbae9af25.

what we do not need is you jumping to conclusions, you being dishonest, and you locking issues for nonsense, because it becomes impossible to comment once an issue is locked.

**Comment by gorhill** [comment]
I disagree with the need to implement your suggested feature, I marked it "decline", but you keep harping about how I am wrong disagreeing with you. How much text of wall and time to write them will it requires before it can be accepted that I won't implement a suggested feature?

**Comment by gorhill** [comment]
Let me comment on this:

> then you proceeded to become irrational

What is irrational to me is to unduly worry that you connected even **once** to `piwik.gitlab.com` **after** you explicitly said to uMatrix you were all fine with connecting to `gitlab.com`. This makes absolutely no sense. You do not want `piwik.gitlab.com`, just block it explicitly, then you will be fine _forever_ afterward, it will still be blocked if ever you decide for whatever reasons to toggle the _all_ cell to "allow", or toggle the _script_ cell to "allow", etc. With your suggestion, the use of the _all_ and type cells become weird, nonsensical, and things become even weirder if working in allow-all/block-exceptionally mode.

**Comment by bananamous** [comment]
I just requested to the admin that that user up there, the one that keeps causing shit on Github, gets permanently BANNED.
Also, Umatrix is one of the reasons I actively DO use the internet.  Umatrix ROCKS, and I have told all of my friends/family/people I meet in grocery stores about it.  Thank you, Umatrix developer, and keep up the marvelous work!!!

Cheers!

**Comment by reitzig** [comment]
@requiredregistration FWIW, blacklisting the offending subdomain globally has the effect you intend. There are several tracker/logger subdomains on the default blacklists, e.g. for Disqus. Blacklisted rows are not overwritten by vertical inheritance.

Flaming the author in another issue is certainly no way to handle the situation. OS devs have no obligation to derivate from their vision for their project.

**Comment by Penguin-Guru** [comment]
None of my business here but I believe objective assessment of how reported issues are handled is a worthy issue to improve a technical project. In this case, perhaps not objective, but please do not report users for trying to improve a project. The project admin has the power to close issues and should be able to handle problematic users at their discretion. If somebody told me to take a vacation, I would certainly not take offense at it.

**Comment by Atavic** [comment]
That wasn't a tentative to improve anything.

**Comment by hukkay** [comment]
@requiredregistration Stop your drama / harassing
