### ISSUE TITLE
UI got glitched

### ISSUE THREAD

**Issue by jonnyrobbie** [gorhill/uMatrix#587]
I'm on uMatrix 0.9.3.6 for FF Nightly(50.0a1 (2016-07-12)) (I'm actually not sure if it's the github or mozilla version, but I'd guess it's the mozilla version) and the UI got glitched like this:

http://i.imgur.com/fzolmLI.png

The problem is it I'm not aware of any recent uMatrix change, so it might have been caused by something else. The only thing that comes to my mind is the recent kde/plasma 5.7 update. But since I have no problems anywhere else/addons or not, I'd guess it has to be caused at least partially by uMatrix. It might also be caused by some recent Nightly update.

**Comment by vlaszlo** [comment]
I've seen a similar kind of UI corruption two or three days ago, too, with the same uMatrix version in Firefox Nightly on Windows 10. A browser restart made it go away and I haven't seen it since.

**Comment by debiangirl** [comment]
Im pretty sure is the browser configuration and the DE, not uMatrix, Im using Firefox in Debian with Stylish and seems like this: [](http://imgur.com/a/GDaEE)

**Comment by debiangirl** [comment]
@gorhill or anybody can close this issue? Its already solved.

**Comment by thewaywest** [comment]
NOT fixed. installed uMatrix now, FFX 48.0 running Ubuntu 14.04 clone (elementaryOS). With first click, it renders one-half the panel, vertically. Moving the cursor down into the panel and sliding back and forth renders the missing pieces.

Clicking, then moving the mouse directly right along the FFX icon bar seems to allow it to resolve -- but when I have the uMatrix icon to the far right, as desired, I have nowhere to go to do this.

**Comment by jonnyrobbie** [comment]
@debiangirl It's never been solved. It's just been worked around with browser restart. The underlying issue is still there.

@thewaywest what happens when you restart ff?

**Comment by thewaywest** [comment]
I saw no improvement with a restart, so didn't mention it. Enough flavors of browser + Linux, assume there is some CSS/LESS tweak required. Works fine on my Windows box.

**Comment by jonnyrobbie** [comment]
Weird, I've had this issue only once when I created this thread, which was worked around with ff restart and it's been fine ever since then. Latest ff nightly 51.0a1.

When I click the uMatrix icon, it usually manages to sort itself out to proper size.

**Comment by thewaywest** [comment]
But notice -- I am on packaged FFX 48.0 distributed Ubuntu 14.04 clone
(elementaryOS)... so maybe the only solution is to manually install the
nightly build...

For a production product, though, you can't expect users to do this.
Hope there is a solution. Most sites I am able to wiggle the mouse and
the panel renders, but some are difficult. May have to go back to
NoScript :/

**Comment by dragon788** [comment]
@thewaywest If you install Google Chrome/Chromium on the same machine do you get similar artifacts with uMatrix in that browser?

Also I'm not sure what classifies this as a "production product"? You paid nothing for it, it is freely available, the source code is also fully accessible, there is no option for a paid support contract and the author works on it in his free time.

**Comment by dragon788** [comment]
So I've seen this occasionally if you change the global zoom level in Chrome or your browser gets confused between HiDPI and non-HiDPI screens, but it doesn't appear to happen consistently. Sometimes changing the zoom from 100% to 150% and restarting Chrome/Chromium causes it, other times it doesn't. It would probably take a Selenium or other UI test to take snapshots and toggles through all the zoom levels to accurately reproduce.
