### ISSUE TITLE
Is there a way to disable javascript in local file:// for firefox?

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uMatrix#589]
Just noticed that javascript runs on local html files. My rules:

```
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: opera-scheme true
* * * block
* * cookie block
* * frame block
* * plugin block
* 1st-party css allow
* 1st-party image allow
```

Noscript does seem disable local js.

**Comment by Snapy** [comment]
Remove `matrix-off: localhost true`.

**Comment by vzjrz** [comment]
@Snapy I tried removing that rule but it still runs js. I even removed everything except `* * * block` and still nothing.

**Comment by debiangirl** [comment]
Why you just dont try modify the **javascript.enable=false** preference inside the **about:config** ?

**Comment by vzjrz** [comment]
@debiangirl Yeah that would disable javascript everywhere but it wouldn't allow me to quickly control it on a case by case basis like I do with umatrix.

**Comment by Roman-Nopantski** [comment]
What does `file-scheme file-scheme script allow` do?

**Comment by gorhill** [comment]
uMatrix/uBO inject a content security policy ("CSP") directive in response headers to prevent inline script tag from executing. I verified that with Chromium/Firefox, their respective handler for response headers is not invoked -- hence no CSP can be injected.

**Comment by Atavic** [comment]
@vzjrz addons like maone's no script can block/unblock JS with an icon.

**Comment by gorhill** [comment]
@Atavic: that does not work with NoScript 10, which is webext-based like uMatrix.

**Comment by Atavic** [comment]
Ajjj... Right. What about [policy-control](https://github.com/schomery/policy-control)

[AMO](https://addons.mozilla.org/en-US/firefox/addon/policy-control/)

**Comment by Thorin-Oakenpants** [comment]
@gorhill : quick question (semi related i think, please don't shoot me). See [ghacks-user.js issue](https://github.com/ghacksuserjs/ghacks-user.js/issues/134), [Bugzilla 1368682](https://bugzilla.mozilla.org/show_bug.cgi?id=1368682) etc. No one is sure yet if this is a problem in web content, but it certainly can be done manually eg entering `C:\$MFT\foo` - anyway to block this in uM or uBo?

**Comment by gorhill** [comment]
> anyway to block this in uM or uBo?

This would need to be tried -- see what the logger reports. If the logger reports it, then it should be blockable. I don't have Windows, so I can't try.
