### ISSUE TITLE
Columns for Fonts and Media

### ISSUE THREAD

**Issue by waqas** [gorhill/uMatrix#590]
Just like Policeman.

**Comment by reitzig** [comment]
Is there a particular reason for declining this? Fonts, in particular, would be useful to allow without having to allow anything else.

**Comment by gorhill** [comment]
Fonts are evaluated using the _css_ column, media are evaluated using the _image_ column (which I plan to renamed appropriately).

**Comment by reitzig** [comment]
I see. For my sensibilities (which allow for CSS and images from all not-blacklisted sources), that's okay. Thanks for clarifying.

> Also, space is limited, I can't just keep adding columns.

Out of curiosity: what restricts space? On my desktop screen there's plenty of room left, and it's not as if uMatrix had a particularly slim interface even now. ;)

**Comment by gorhill** [comment]
> what restricts space?

Chromium does. I think there is even an issue opened about this somewhere. If you use a large page zoom enough in the Chromium settings, the popup panel will no longer fit horizontally, the browser limit the max width.

**Comment by CrisBRM** [comment]
https://github.com/gorhill/uMatrix/issues/263 seems like a better alternative and actually justifies the existence of the My Rules panel.

**Comment by kirill9000** [comment]
Columns could be made narrower if their headers contain abbreviations or icons instead of wide labels (like "cookie"). Then there will be place for more columns.
