### ISSUE TITLE
How is pornhub bypassing uM and uBO?

### ISSUE THREAD

**Issue by h1z1** [gorhill/uMatrix#593]
At the risk of being judged. title says it all.  Something I've noticed a lot lately are sites being able to load 3rd party requests (read: ads but also more nefarious resources) - neither uM nor uBO have any record of such requests.  I don't care so much about the requests themselves but I am concerned neither addon has any record of it.

Pornhub is an interesting case because it's one of a few sites advertisers target with new crap.   For example

http://ws.00zasdf.pw/json

uBO identifies it as 3rd party and blocked but ONLY in the log.

uM identifies it as other and permitted, again ONLY in the log.

The source is fairly fortified somehow (view source doesn't directly work), however there are ways.  When you do, you'll see it's a websocket callback from trafficjunky.

There are _no_ exceptions in either uM or uBO. 

My only solutions at this point have been to block sites like trafficjunky entirely through dns zone spofing and avoiding sites entirely that utilize such moronic things.   PH is honestly just a smoke test of how BAD sites can get.

Is this normal?

**Comment by gorhill** [comment]
I don't understand the reported issue -- can't answer. Be very specific please, with URL, explain what is wrong, what is expected, etc.

**Comment by h1z1** [comment]
Don't think posting links to porn are wise on Github.

The problem 
- sites are able to make requests that are not handled properly by uMatrix or uBlock.   Pornhub was the example, specifically the URL I gave (http://ws.00zasdf.pw/json)

- uBlockOrigin identifies it as 3rd party and blocked but ONLY in the log.

- uMatrix identifies it as other and permitted, again ONLY in the log.


Expected behaviour 
- the request gets first noticed on the dashboard
- the request shows up in the logger
- correct disposition is selected based on filters

I don't know what causes it nor do I have a repeatable test case.

Versions: 
- Browser: Palemoon 26.2.2
- uM: 0.9.3.5
- uBO: 1.7.6
- ** Noscript / adblock are not installed **

**Comment by gorhill** [comment]
It's not helpful.

> sites are able

Provide a list of such sites, not generalities. I can't investigate "sites", I investigate pages at specific URLs.

> uBlockOrigin identifies it as 3rd party

uBO works all fine. The network request `http://ws.00zasdf.pw/json` was properly blocked by uBO using default filter lists, and it was also properly reported in the dynamic filtering pane of the popup panel (what I assume you call "dashboard").

> uMatrix identifies it as other and permitted, again ONLY in the log

The network request was labeled as behind-the-scene by uMatrix. It appears I forgot to import a fix I made in uBO -- specifically for Pale Moon a long while ago -- to find exactly from which tab the network request originated. This is now fix in 8464e3d594592c0410680c59d13c6ca630d0cd63.

**Comment by h1z1** [comment]
What the fuck?   I gave you the site and URL...  My questions if it was normal or not.  Thanks, I think.

**Comment by gorhill** [comment]
I can't answer because as said I didn't see any "bypassing" -- or I have no clue what you mean by "bypassing". As opposed to what you said, uBO filters properly `http://ws.00zasdf.pw/json`. Maybe somebody else will understand better.

**Comment by d-kr** [comment]
According to the spec there is one way they could do it: https://www.w3.org/TR/CSP2/#source-list-paths-and-redirects

In short when they redirect(http response code 301) cross origin then csp ignores them :/ .

**Comment by gorhill** [comment]
The most important thing missing in this bug report was to substantiate _"blocked but ONLY in the log"_, to make the case using the Network pane in dev tools. This is what I used to confirm that whatever uBO reports as blocked in its logger was confirmed being blocked in the Network pane.

**Comment by Raavizz** [comment]
> @h1z1 : What the fuck?

Stop your drama / insulting / vulgar words / negativity.
