### ISSUE TITLE
object object, aditional dialogs

### ISSUE THREAD

**Issue by RobertVisser** [gorhill/uMatrix#594]
Awesome plug-in. Thanks for making it available.

Thia afternoon on eBay I'm now receiving pop-ups which require I click. Once clicked the pop-up disappears and page is no-longer grayed-out. Have received three different variants. Screenshots of all three are attached.

It is, of course, possible this results from Firefox's own, pop-up blocker: Preferences > Content > Pop-ups > Block pop-up windows which I have checked.

Given uMatrix is the only Ad/Content blocker I have installed, I thought I'd check if the issue might originate w/ uMatrix before contacting Mozilla Support.

Running Firefox Developer Edition 49.0a2.

Thanks.

![Uploading 20160720_object_aditional-dialogs-2.png…]()
![Uploading 20160720_object_object.png…]()
![Uploading 20160720_object_aditional-dialogs.png…]()

**Comment by gorhill** [comment]
Your screenshots are not available.

**Comment by RobertVisser** [comment]
Raymond, Hi. It may have been eBay, itself. Issue is no longer present.
Thanks. Rob
