### ISSUE TITLE
setting matrix-off: behind-the-scene false breaks SSL

### ISSUE THREAD

**Issue by h1z1** [gorhill/uMatrix#595]
I was hesitant to create this but for any future reference, setting "matrix-off: behind-the-scene false",  will break SSL in a magically annoying way.   You will not be able to add certificate exceptions, the button remains grey.  There's absolutely no indication from anything as to why either.

**Comment by gorhill** [comment]
[Behind the scene requests](https://github.com/gorhill/httpswitchboard/wiki/Behind-the-scene-requests):

> If you choose to block wholly or partially behind-the-scene requests, you are responsible for any potentially negative side-effects.

**Comment by h1z1** [comment]
Ah my little napoleon complex friend..  It's not invalid, there's NOTHING indicating why one can't accept the certificate.   That is the bug.   Why I opened this - warn anyone else who might run into it.

**Comment by jjohns71** [comment]
I know it's not productive, but fuck off on snapping on his reasons.

**Comment by h1z1** [comment]
Snapping?  Hardly,  I'm amused.  Honestly thought he would update the wiki or something to warn others. Not just close it as invalid.   I have no idea what switchboard is/was.

Didn't say any code change was required, quite simply that it happens.  He did the same thing with my other bug, ironically enough had he said websockets aren't really filtered it would have been more productive.  Looking at other tickets I can see he just closes most of them.   Closed issues do not show up by default, I had nfi and still don't, what the relationship between UBM and SSL is.  I can say I spent the lesser part of two weeks trying to narrow it down.

Only people snapping are you two.

**Comment by gorhill** [comment]
> had he said websockets aren't really filtered it would have been more productive

You previous issue was "pornhub bypassing uM and uBO": I verified that this was not the case, hence closed as invalid. You failed to make the case. I checked again: the logger reports `http://ws.plmokn.pw/json` as being blocked, and this is confirmed by the output of the Network pane in Pale Moon's dev tools.

**Comment by gorhill** [comment]
> thought he would update the wiki or something to warn others

I do warn about blocking behind-the-scene network requests, I even quoted it above. I won't make a list of all that can break specifically and for each browser, the generic warning about important functions of the browser starting to not function properly is enough.

What I could do however is to create a default rule such that the behind-the-scene scope works in allow-all/block-exceptionally by default. So if someone turns on matrix filtering for the behind-the-scene scope, I would expect the browser has better chance of functioning properly. Still, in the end users are responsible to understand the consequences of the rules they create/remove.

**Comment by Raavizz** [comment]
> @jjohns71 : fuck off

Stop your drama / insulting / vulgar words.

**Comment by hukkay** [comment]
@jjohns71 stop your drama / vulgarity / insulting
