### ISSUE TITLE
IPv6 password form submission fails

### ISSUE THREAD

**Issue by dd23** [gorhill/uMatrix#597]
**My setting:**
I have a Brother MFC-L8650CDW printer that has a web interface, which I can reach via IPv4 and IPv6 through https. It has a self-signed certificate and thus my browser shows a warning, which I chose to permanently ignore (I don't know if this last part is relevant, though).

The web interface offers an admin login to unlock several management features.
Here's a HTML snip from the website of the login box:

```
 <div class="SetBox" id="SetBoxAuthRight">
 <div id="SetBoxAuthLeft">
 <form method="post" action="/general/status.html">
 <div>Login
 <input type="password" id="LogBox" name="Ba01" />
 <input type="hidden" name="loginurl" value="/general/information.html?kind=item"/>
 <input id="login" type="submit" value="&nbsp;" />
 </div></form></div></div>
```

**My problem is the following:**
Using the printer's IPv4 address, the login works fine in all cases. Using its IPv6 address, the login fails. There's no error message. The same website just reloads when I submit the password.

This happens only in Firefox 47.0 when uMatrix 0.9.3.6 is activated with default settings. Everything works fine when I manually deactivate the filter for that particular website (IPv6 address).

The problem does not occur in Chromium 51.0.2704.103 (64-bit) with uMatrix 0.9.3.3.

Let me know if you need more info.

**Comment by gorhill** [comment]
What did you try to identify the issue? Did you open the logger?

**Comment by dd23** [comment]
I can reproduce the issue when I enable uMatrix entirely for this domain. The problem disappears when I disable uMatrix for this domain.
See the following picture:
![umatrix](https://cloud.githubusercontent.com/assets/630500/17181956/34f2e4f4-5422-11e6-913a-29cc044b39a4.png)

When the login does not work, I can see several entries in the log (Firefox's web console, opened with Ctrl+Shift+K) like this one:
`Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src 'unsafe-eval' *").`
These entries are not there, when the login works.

**Comment by gorhill** [comment]
Logger?

**Comment by dd23** [comment]
Sorry, wasn't aware that there is a logger in uMatrix. But here we go: Upper half is the correctly working login, lower half fails.
![umatrix2](https://cloud.githubusercontent.com/assets/630500/17183597/90277ad2-5428-11e6-8ea4-506acfc45eaa.png)

Apparently scripts are blocked, even though this is not supposed to happen.
The IPv6 addresses are identical in all lines.

**Comment by gorhill** [comment]
Is the IP address of the blocked script _exactly_ the same as the IP address of the document pulling these scripts?

**Comment by dd23** [comment]
Yes, I have double-checked. Blocked and non-blocked IPs are exactly the same. 
I copied the logger output to a text editor and did a quick Ctrl-F for the IP and all lines were highlighted.

**Comment by gorhill** [comment]
Ok, I will look into this. I can't remember if [this uBO issue I fixed in Firefox](https://github.com/gorhill/uBlock/issues/1276) was also fixed for uMatrix.
