### ISSUE TITLE
Script blocking in Speeddial Extension

### ISSUE THREAD

**Issue by allo-** [gorhill/uMatrix#598]
I tried if i can replace NoScript with uMatrix (currently using both), but when i disabled noscript, scripts blocking in the [SpeedDial Extension](http://speeddial.uworks.net/) while creating thumbnails did no longer work.
As the thumbnailer probably runs all scripts and accepts cookies and so on it would be good if it's blocked as well. I would have said it's a problem of this extension, but NoScript manages to be active when this extension creates thumbnails, so it should definitely be possible and the hook needed for this may be useful for a lot of other extensions rendering pages in the background as well.

My Testcase is https://slashdot.org/, which shows "Slashdot Top Deals" on the right with colorful images, when you allow XHR for api.stocksocial.com and does not show it with uMatrix default config.
Using the default config and the Speeddial-Extension you see this ad.

**Comment by gorhill** [comment]
Looks fine to me, I removed all the rules from uMatrix, so that even CSS and images won't be loaded, and this is clearly working as per thumbnails, and logger:

![a](https://cloud.githubusercontent.com/assets/585534/17280023/90743ce0-5753-11e6-873d-bc111239344d.png)

**Comment by gorhill** [comment]
With uMatrix's default rules, this is what I get for slashdot.org:

![a](https://cloud.githubusercontent.com/assets/585534/17280049/3b99b046-5754-11e6-80f0-939567f13fcf.png)

**Comment by allo-** [comment]
I guess i need to test on a profile with less addons ...
What i currently changed was to set NoScript from "allow main domain" to "allow global", to test if i get the (almost) same behaviour with uMatrix alone without reloading twice per Temporary-Allow action.

With NoScript active i do not see this box at all. But the strange thing is, i see that the tile has an option "allow javascript", which is disabled here. I am not sure what possibly interferes there and what exactly causes the box there / to be removed

NoScript allow main domain:
![NoScript disabled](http://i.imgur.com/BIlp0W3.png)

NoScript allow global
![NoScript disabled](http://i.imgur.com/ExvnHnM.png)

No Box when loading slashdot via clicking on the screenshot. Allowed:

- All Images
- All CSS
- (www.).slashdot.org
- (a).fsdn.com

everything else disallowed.

**Comment by allo-** [comment]
With a fresh profile with only speeddial and uMatrix i get your thumbnail.

**Comment by allo-** [comment]
As the slashdot poll now looks a bit broken like in your screenshot and i can reproduce this in a tab by disallowing all scripts on slashdot.
I guess NoScript took over the whole scripting in the thumbnailer allowing the main domain and disallowing everything else, while now the javascript is disabled, because of the checkmark in the settings for this speeddial tile.

So it seems:
- NoScript + uMatrix active + Javascript disabled for the thumbnail: No Box at all.
- NoScript allow global + uMatrix active + Javascript disabled for the thumbnail: Scripts are running.
- uMatrix active + Javascript disabled for the thumbnail: Scripts are not running, no box is shown.
- uMatrix active + Javascript enabled for the thumbnail: Scripts are running**(*)**, box is shown, but images are not loaded.

**(*)** Maybe the box is hidden by another addon. I suspected uBlock, but i cannot reproduce loading it in a tab without allowing other scripts than the main domain, even when i disable uBlock (via its button, not in the addon manager)

Thank you for helping to debug with a whole other addon.
When it works with NoScript uninstalled i am happy, as i wanted to replace it. Now i look into configuring if i can make sure that all plugins are click-to-play even when hidden first and then i will have the features i used from NoScript.

**Comment by allo-** [comment]
is there some option to block HTML5-Video by default? Setting ``* * plugin block`` doesn't prevent it.

**Comment by gorhill** [comment]
> is there some option to block HTML5-Video by default?

For the latest uMatrix stable release, HTML5 videos are reported in the `other` column. In the latest dev build, they are reported in the `image` column.
