### ISSUE TITLE
Unable to login on bing.com

### ISSUE THREAD

**Issue by vanowm** [gorhill/uMatrix#600]
Hello.

I'm unable to login at bing.com. The page refreshes and it shows as I'm not logged in.

Nothing blocked shows in the list
![](http://i.imgur.com/UT7LdM4.png)
(including at logger list) and disabling uMatrix on that website does nothing.

However once uMatrix is disabled in addons manager then I can login with no problem.

Any ideas?

**Comment by gorhill** [comment]
Did you also try to play with the per-site switches? (referrer spoof, etc.)

**Comment by vanowm** [comment]
Found what caused it: referrer spoofing.

Apparently disabling uM on particular website doesn't disable the additional 3 toggles?

**Comment by gorhill** [comment]
There is no feature to disable uMatrix for a site, the power button is to disable matrix filtering.

**Comment by gorhill** [comment]
I plan on adding a badge for the per-site switches icon so as to remind users how many of the switches are turned on for the current site.

**Comment by vanowm** [comment]
I see that now. It's confusing (although what isn't in uM? ;) )
Perhaps instead of power switch icon _(which ultimately suggests disable of the addon on that website and not just part of it_) it should be something like crossed off filter icon?
Badges would help _(although I have no idea what the badge at filter power button represent without going through the manual)_ and definitely would be a great help if button changed (color) when everything is disabled in there.
