### ISSUE TITLE
uMatrix popup gets cropped while desktop composition is disabled on Windows 10?

### ISSUE THREAD

**Issue by Ectoplasm** [gorhill/uMatrix#601]
![untitled](https://cloud.githubusercontent.com/assets/1444556/17469116/2e4a1b30-5cfc-11e6-9fec-37705221a18b.png)

If you use a workaround* to get WIndows 10 working with desktop composition (dwm.exe) disabled if you so wish, the uMatrix popup gets cut off. It will appear normal the first time you open it, but is cut off for the remainder of the session. This is not a problem with uBlock.

*To do this:

1. kill explorer.exe
2. suspend winlogon.exe
3. kill dwm.exe
4. while the screen is black, run explorer.exe

**Comment by gorhill** [comment]
I don't have Windows, let alone Windows 10. This will have to be investigated by someone else.

By the look of the screenshots, it does appear that the popup panel is properly sized, just not properly displayed. Likely a Firefox issue, the panel is plain HTML/CSS/JS code. Does uBO display fine when the dynamic filtering pane is opened in the popup panel?

**Comment by Ectoplasm** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1444556/17490734/518f71dc-5d72-11e6-85de-11737e168bc9.png)

Looks like the dynamic filtering pane on uBlock Origin does the same thing, but only the dynamic filtering pane. The main popup appears normal until you open the dynamic filtering pane, and returns to normal when you collapse it.

**Comment by gorhill** [comment]
Please submit the issue to Windows or Firefox, as said, uBO's amd uMatrix's popup panel use plain legit HTML/CSS -- it's rendered by the browser.
