### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by ghajini** [gorhill/uMatrix#602]
![screenshot 34](https://cloud.githubusercontent.com/assets/20338483/17486414/5668375c-5dae-11e6-8e7f-527a057d65d7.png)
![screenshot 35](https://cloud.githubusercontent.com/assets/20338483/17486413/5665cf9e-5dae-11e6-938c-4d1b4cfaf52a.png)

iam new to this extension,i don't know how it works...when i want to watch youtube videos it shows blank page,i can't click play-which is unavailable

**Comment by ghajini** [comment]
here upload not work when umatrix is active

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
