### ISSUE TITLE
GooglePlay or ChomeStore broken with uMatrix

### ISSUE THREAD

**Issue by alexara** [gorhill/uMatrix#603]
##### About my system
* FF 48.0
* uMatrix 0.9.3.6
* ~~uBlock 1.8.4~~

##### Settings
* all host lists selected
* else default

##### URLs
`https://play.google.com/store`
`https://chrome.google.com/webstore/category/apps`

##### Issue
uMatrix breaks the web pages listed above -- even if deactivated on the pages above. Compare screenshot.
After deactivating uMatrix I emptied the browser caches and reloaded the pages.

##### Work around
The issue is gone when the uMatrix addon is completely disabled.

##### Screenshot of the issue
![umatrix_googleplay_broken](https://cloud.githubusercontent.com/assets/13819719/17588197/8891e342-5fcd-11e6-8f40-fc66465b2659.png)

##### Logger
Nothing blocked as expected.

**Comment by gorhill** [comment]
Did you also check referrer-spoofer, agent-spoofer, strict https?

**Comment by alexara** [comment]
> Did you also check referrer-spoofer, agent-spoofer, strict https?

Forgot about that, though I thought it's disabled as well if I turn it off for a certain page.

**Soltution:** The **agent-spoofer** caused it somehow!

**Comment by gorhill** [comment]
I just pushed a new dev build which should help not forget about these switches.
