### ISSUE TITLE
Add localStorage category / have a way to undo all effects of Firefox's `network.cookie.cookieBehavior=2`

### ISSUE THREAD

**Issue by sjamaan** [gorhill/uMatrix#607]
Currently, cookies can be blocked by uMatrix, but sites can still leave personally identifiable information in localStorage (and probably other html5 features like indexedDB and such).

I used to surf with cookies disabled globally in the general Firefox preferences, which can then still be allowed by uMatrix for selected sites. However, this "cookies" setting (which maps to `network.cookie.cookieBehavior=2` in `about:config`) also affects localStorage! Some sites will still need localStorage, which means those sites end up broken with uMatrix. So my only recourse is to re-enable cookies globally in Firefox, but this means that sites I don't trust as much will still be able to make use of localStorage (but of course only if JS is enabled for the domain).

Steps to reproduce:
- Open Firefox Preferences screen, click "privacy" and disable the checkbox `accept cookies from sites`
- Visit http://html5demos.com/storage and enable script for the domain `html5demos.com` in uMatrix.
- Type something in either box
- Refresh
- The box should contain the typed text, but it doesn't.

Repeat the steps with `accept cookies from sites` enabled, and you'll notice that the demo will work.

For example, surfing with `accept cookies from sites` disabled breaks hard on any site that uses an older version of Modernizr, which does feature detection by "touching" localStorage, which then throws an exception because localStorage isn't enabled. This is how I found out about this unexpected mismatch in behaviour; I expected to be able to undo **all** the effects of disabling `accept cookies from sites` using uMatrix.

So I guess localStorage should be added as a separate category, or simply treated under the `cookies` control. I don't think it's really necessary to distinguish between the two (Firefox doesn't either, in its settings at least), as they're both ways of storing arbitrary site-specific data on your computer.

**Comment by gorhill** [comment]
Just check the option _"Delete local storage content set by blocked hostnames"_ in the dashboard -- it actually lookup cookie rules to wipe clear or not `localStorage`/`sessionStorage`.

**Comment by sjamaan** [comment]
Thanks for your quick response! So if I understand it correctly, if I enable JS for site X, but disable cookies, uMatrix will wipe localStorage along with the cookies set by the site when I close the browser?

**Comment by gorhill** [comment]
uMatrix prevents cookies from reaching the remote server. Optionally, if you check the relevant options in the dashboard, uMatrix will wipe the blocked cookies and localStorage/sessionStorage when you visit the site.

**Comment by sjamaan** [comment]
Thanks for the explanation.

You say uMatrix prevents the cookie from reaching the remote server, but can it guarantee that if the cookie is not `httponly`?  Then the JS code could just read it and send it in some other request (either XHR or insert an element with a `href` or `src` that communicates the data to the server). The same is true for localStorage of course..

**Comment by gorhill** [comment]
Just check the _"Delete blocked cookies"_.
