### ISSUE TITLE
[feature request] allow exceptions to "Strict HTTPS" like scripts

### ISSUE THREAD

**Issue by Tronic69** [gorhill/uMatrix#609]
Many websites and companies use images in newsletters which are hosted without HTTPS. Hence I cannot see this images in my webmail due to "HTTPS Strict" is activated and per default it should be activated.

At the moment I have two possible solutions:
1) I leave "HTTPS Strict" atcive and still have some unreadable newsletters.
2) I disable "HTTPS Strict" for my webmailer domain => I see all images, but every other content could be delivered via HTTP through webmailer into my browser. NOT GOOD ;-)

Both option are not really satisfying. What about an option to allow HTTP from just one domain to another like scripts, frames and other things?

At the moment I can make a ruleset like this:
```
https-strict: webmailer.tld false
webmailer.tld external.tld * allow
webmailer.tld external.tld frame allow
webmailer.tld external.tld script allow
```

What about someting like this?
```
webmailer.tld external.tld * allow
webmailer.tld external.tld frame allow
webmailer.tld external.tld script allow
webmailer.tld external.tld http allow
         or
webmailer.tld images.external.tld http allow
```

In this case HTTP is just alloewd for trusted sites/domains and HTTPS will be still forced for the rest of the web.

Thanks in advance, 
Tom

**Comment by gorhill** [comment]
I do not plan to rewrite the core filtering engine, which such feature would require.

**Comment by migueldemoura** [comment]
@gorhill, sorry to revive this, but what are your thoughts on redirecting such http requests to https instead of blocking them? I can see an obstacle with this, as some sites redirect back to http, but it would address OP's annoying issue.

Does something like this require a considerable change on the arquitecture?

**Comment by Tronic69** [comment]
@migueldemoura 
Redirections have to be done on server side and not on clients. I never saw a server redirecting https to http (only http to https, like I do it for all requests on my servers) and if you do this on a client you will get just 404s for you client side redirections (IMHO in at least 95% of requests).

**Comment by migueldemoura** [comment]
@Tronic69 
> Redirections have to be done on server side and not on clients.

Why? Ideally, all web services would be served as https only, and redirect http to https. While I agree it should be the job of sys admins to ensure this, you can't really rely on it. After all, browsers interpret malformed html syntax for this same reason. The server provides access to content; the client chooses how to display it - the entire premisse of uBlock and uMatrix.

> I never saw a server redirecting https to http (only http to https, like I do it for all requests on my servers)

If you don't support https, it is wise to perform such redirect to reduce bounces. This is easily observed in the wild on, for example, a few news websites:

https://www.huffingtonpost.co.uk
https://www.bbc.co.uk

> if you do this on a client you will get just 404s for you client side redirections (IMHO in at least 95% of requests)

Setting aside that such percentage is likey overblown, how is that worse than what you have now? If the resource doesn't have a https version, it isn't displayed like with the current implementation. If it does, you now have a less or non-broken website.

The only issue I see with this suggestion is potentially increasing complexity. Other than that, I believe it is reasonable, isn't feature creep and addresses a real issue.
