### ISSUE TITLE
"Preferences" in about:addons should lead to the preferences

### ISSUE THREAD

**Issue by reitzig** [gorhill/uMatrix#612]
Clicking "Preferences" in about:addons leads to the addon description, but it _should_ lead to the preferences.

I honestly thought there were no preferences until I noticed the small gear in the corner just now.

**Comment by grumpygeek** [comment]
Do you mean "Options"?  (Or, maybe you are using a different browser.)  There are other extensions that do the same thing, usually because there are some settings on the "More" page.

**Comment by reitzig** [comment]
I'm on Firefox:


![screenshot from 2016-09-12 18-15-15](https://cloud.githubusercontent.com/assets/1488534/18443383/f482f072-7914-11e6-8bc8-2b6ed63c0abd.png)

That button "Preferences" does not lead to preferences but to the addon description.

**Comment by grumpygeek** [comment]
OK, I understand, the addon description is also what you get by clicking "More" link.  The button has always been labelled Options for me on Windows, but I think there are some differences on others OSes in menu labels so maybe that is why one of us sees Options and the other sees Preferences.  Anyway we'll have to let gorhill decide if the Options/Preferences button which is part of the browser should open Dashboard (i.e., the tab with uMatrix "preferences") or just open the description page ("More") which does have a button to open Dashboard.  I'm fine either way.  Also FWIW, you may already know, you can click on the black title bar in the Matrix to get to Dashboard.

**Comment by gorhill** [comment]
This used to work like this. However the current behavior [was implemented to support Firefox for Android](https://github.com/chrisaljoudi/uBlock/commit/2b60436ecea7eb05d35dae4fb8026694e2a95b8c#diff-7d802932847c7520529520631685fb0f). I do not intend to have a separate uBO extension just for Android.
