### ISSUE TITLE
Import from RequestPolicyContinued 1.x

### ISSUE THREAD

**Issue by powerman** [gorhill/uMatrix#613]
Please add support for importing RPC 1.x rules (see https://github.com/RequestPolicyContinued/requestpolicy/issues/342). Or maybe just provide a hint how to convert it's user.json into something what can be imported into uMatrix.

**Comment by gorhill** [comment]
Rule syntax: <https://github.com/gorhill/uMatrix/wiki/Rules-syntax#directive-rule-syntax>.

**Comment by powerman** [comment]
Thanks. Here is oneliner to convert (require Perl and JSON::XS perl module installed):
```sh
cat ~/.mozilla/firefox/*.default/requestpolicy/policies/user.json | 
    perl -0777 -MJSON::XS -nE '
        for (decode_json($_)->{entries}{allow}->@*) {
            s/\A\*\.//, s/\A\z/*/ for $_->{o}{h}, $_->{d}{h};
            printf "%s %s * allow\n", $_->{o}{h}, $_->{d}{h};
        }
    ' >requestpolicy-umatrix.txt
```
