### ISSUE TITLE
Global block or allow

### ISSUE THREAD

**Issue by Misque** [gorhill/uMatrix#614]
hi guys, tell me how globally block or allow javascript, frame, or XHR 
(for example:
 globally allow script for ajax.googleapis.com
globally allow s.ytimg.com
 globally block... etc )
I was trying to understand syntax, but have not found where :(
write an example syntax plz

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
