### ISSUE TITLE
Cannot defend against SVG-based keylogger with images enabled

### ISSUE THREAD

**Issue by liamwhite** [gorhill/uMatrix#615]
I'm not sure if this is actually possible to defend against in any meaningful way in uMatrix itself, but when images are enabled, inline SVG using `<set>` can be used to create a keylogger that bypasses the content security policy restrictions that are in place. It doesn't work when using SVG in an `<img>` tag, however.

Example: https://html5sec.org/keylogger/

This makes requests to "evil.com" even when scripts/XHR are restricted, as it doesn't use either. It only stops working when images are disabled (or CSP has restrictions on img-src, something I tested), but I find that disabling images may be too much of a stretch for me.

**Comment by h1z1** [comment]
I don't see XHR but I do see images and they are blocked.  Then again I have first party blocked by default.

* 1st-party image block
* 1st-party other block

That is a pretty evil  page either way.  Why is it even possible?

**Comment by d-kr** [comment]
My chrome console says: "SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead." Maybe we just have to wait a few releases?

**Comment by gorhill** [comment]
> Cannot defend against SVG-based keylogger with images enabled

Yes you can: don't enable images for 3rd parties.

It's up to you to set up your defense the way you wish, according to your own prerogative. If you worry about 3rd party images used for bad, just do not allow them: just remove the `* * image allow` rule.
