### ISSUE TITLE
Latest UA strings

### ISSUE THREAD

**Issue by debiangirl** [gorhill/uMatrix#616]
Im collecting the latest UA to update the strings, in the wiki page the UA strings are old and there are problems with watching videos or alerts in the browser asking to update the browser version.
Can you provide the following UA strings?
Safari in Mac OS El Capitan
Chrome in Mac OS El Capitan
Chrome in Windows 10
Edge in Windows 10
Opera in Windows 10

**Comment by gorhill** [comment]
I changed the wiki to point out where to get new strings from 3rd parties.
