### ISSUE TITLE
"waiting for extension [uBlock|uMatrix]" when load Google Chrome

### ISSUE THREAD

**Issue by VanguardLH** [gorhill/uMatrix#618]
- Load Google Chrome.
- See "Waiting for extension uMatrix ..." in the status bar.
- Nothing happens in web browser (blank window, blank chrome).  Stays that way indefinitely.
- Have to kill chrome.exe processes and reload Google Chrome.

Have seen the same problem when using uBlock Origin which was removed because it kept crashing Google Chrome (both work okay in Firefox).  I've seen Gorhill's responses claiming Javascript cannot cause the crash of Google Chrome.  Yet the web browser doesn't crash with his extensions disabled.  I and other users have encountered the crashing or hanging with his extensions enabled in Google Chrome.  When extension not there (or disabled): no crashes or hangs.  When extension is there (enabled): sometimes crashes or hangs but a reload gets web browser working again. 

The following extensions were installed by me and are enabled (there are some more but they are disabled for now):

Context Menu Search
Empty New Tab Page  <-- could this be conflicting?
Nimbus Screenshot and Screencast
OneTab
Tabs to the Front
uMatrix (uBlock Origin is disabled)

The Empty New Tab page not only opens blank new tabs (and with nothing in the address bar, not even about:blank) but also loads a blank new tab when Google Chrome is loaded.  Could uMatrix be waiting for something to load as a document before it will disengage and let the web browser continue to load successfully?  I can disable that extension and leave uBlock Origin and uMatrix enabled for a testing period (until encountering the next crash or hang) but I really am not going to leave Google Chrome pushing out the equivalent of Opera's speed dial "most visited" anti-privacy feature or wasting resources and bandwidth since it is rare that I ever load the web browser to go back to where I visited previously (that's what bookmarks are for).  With that extension disabled, I will have Google Chrome configured for a home page using about:blank to, at least, eliminate that waste of resources when first loading the web browser.

I first encountered crashing and hangs when using uBlock Origin.  Later I added uMatrix.  I grew weary of the crashes and hangs (status = "waiting") with uBlock Origin so I disabled it and relied solely on uMatrix.  However, since then several times the web browser hangs with a "waiting" status on the uMatrix extension. 

Only seen this happen when loading Google Chrome (i.e., when it starts), not when the web browser has already successfully loaded and while navigating to various sites or their pages.  On what is the web browser waiting for uMatrix to do?

With the web browser hung (stuck on "waiting" status for the uBlock or uMatrix extension), I'm not sure how I could do anything to track down the problem.  The web browser is unresponsive (not even the tabs or addressbar are shown - empty chrome) so it's not like I could go into a console to check on errors.

Google Chrome 53.0.2785 64-bit (same problems back in v52)
Windows 7 Home x64 SP-1

uBlock Origin 1.9.4 (currently disabled)
uMatrix 0.9.3.3 (enabled - will probably disable it, too)

**Comment by VanguardLH** [comment]
I disabled the New Tab extension just in case it was modifying the document and results in uBlock Origin and/or uMatrix jamming on trying to detect or use a non-existing document.  Both uBlock Origin and uMatrix were enabled.  I hit another error on loading Google Chrome.  Again, this was on initially loaded the web browser, not after it was successfullly loaded.

- Load Google Chrome (to about:blank or to any URL).
- Get error on chrome.exe loading (Google Chrome shows empty chrome & window - it did not load).
- Reload Google Chrome and go into Developer tools.
- Select the Console tab.
- Shows the errors:
    Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
      https://ssl.gstatic.com/support/content/images/sprites/social-mobile-<hexnum>.png
    Failed to load resource: net::ERROR_BLOCKED_BY_CLIENT
      https://www.google.com/generate_204

It appears uBlock Origin and/or uMatrix are blocking a resource that Google Chrome expects to be available when that web browser initially loads and even when about:blank is configured for the default home page.  The resource blocking means the web browser won't load (gets hung or errors) and probably why the chrome is blank (no tabs, no addressbar, no toolbar).

The error does not specify WHICH client is doing the blocking, and I'm assuming "client" means an extension (not where client means the web browser itself).

Or this could be a different symptom (blocked resource) in addition to the crashing or hanging (status = "waiting") problems.  I can't be sure the console log is showing errors from the prior crash of chrome.exe or errors on the next load of the web browser (which loads okay) but incurs internal errors on trying to get at resources that are getting blocked by uBO or uMatrix.

**Comment by gorhill** [comment]
> When extension not there (or disabled): no crashes or hangs

I cannot reproduce any hand or crash. If the browaser crash, report to Chromium devs, you probably have a tainted Chrome installation.

**Comment by gorhill** [comment]
> Google Chrome 53.0.2785 64-bit (same problems back in v52)
> Windows 7 Home x64 SP-1

<https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html>
