### ISSUE TITLE
SVGs not interact properly if scripts are blocked (though it says 0 scripts in the page)

### ISSUE THREAD

**Issue by Fanolian** [gorhill/uMatrix#621]
Affected files:
https://r12a.github.io/maps-east-asia/images/ten-kingdoms.svg
https://r12a.github.io/maps-east-asia/svg/CE_944.svg
([source](http://rishida.net/blog/?p=1776))

Extension: uMatrix 0.9.9b2
Browser: Firefox 48.0.2, current Nightly
OS: Windows 10 AU

Steps to reproduce:
0. In a new profile, install uMatrix 0.9.9b2
1. Visit affected svg. You should be able to interact with the graphs now.
2. Block scripts from r12a.github.io. Reload the page. (see attachment below)
3. Try to interact with the graphs again.
![umatrix_svg](https://cloud.githubusercontent.com/assets/771216/18510991/d22bed1c-7ab3-11e6-904f-ffcc2e2865f5.PNG)

Result:
I cannot interact with the graphs after disabling scripts.
I don't know how svg works. But if it requires enabling scripts to interact properly, it should be stated in the matrix, i.e. not showing 0.

Thank you for the extension.

**Comment by gorhill** [comment]
I can reproduce.
