### ISSUE TITLE
Not all Cookies are prevented from reading by blacklisted Sites

### ISSUE THREAD

**Issue by Hobbybyte** [gorhill/uMatrix#623]
Tested Systems
  uMatrix 0.9.2.1 / 0.9.3.0 / 0.9.3.6 / 0.9.9.b2
  Firefox ESR 45.3 , Firefox 48.0.2 , Palemoon 26.4.1
  Windows XP-32, XP-64, WIN-7-32, Win-7-64

Example 
  http://www.whatarecookies.com/cookietest.asp

Settings
`* * cookie block`
`whatarecookies.com whatarecookies.com cookie block`

Cookie can be stored - OK
Cookie should not be read , but could be read - Issue

 - thanks for spending time in this great extension

**Comment by gorhill** [comment]
Please, read the built-in doc about cookies.

**Comment by Hobbybyte** [comment]
I read the whole Documentation and all Infos I could
found about uMatrix/Cookies **before** writing this
and making all the tests :

I did it twice, but it doesn't change anything.

Manual :
So, if you block cookies by uMatrix, a server which has set a
cookie cannot read the cookie again -- and so, the cookie is blocked.

But the Server **can** read the complete Cookie under some circumstances.

**Comment by gorhill** [comment]
> read the whole Documentation and all Infos

![a](https://cloud.githubusercontent.com/assets/585534/18615243/aac1501e-7d6f-11e6-959c-65a5286dfe5a.png)

**Comment by Hobbybyte** [comment]
First thanks for your answer.

If you don't delete the local Cookie, the site can read the old value :
![test_1809161340](https://cloud.githubusercontent.com/assets/22267146/18615561/0faeb77a-7daa-11e6-8558-9f0bfbaf18d4.jpg)
If you manipulate the local Cookie :
![test_1809161405](https://cloud.githubusercontent.com/assets/22267146/18615576/2a60b276-7daa-11e6-9560-f080de03c4cd.jpg)
This indicates for me, that teh server **can** read the cookie

**Comment by gorhill** [comment]
> This indicates for me, that the server can read the cookie

Not the server, the javascript code of the page.

**Comment by Hobbybyte** [comment]
That makes clear our different Point of View.

I wanted to know, how google can identify me with complete 
blacklisted Cookie Function in uMatrix until the Cookie is deleted : 

if e.g. google reads the Cookie in local Javascript, obfuscate it
mathematically reversible and translate it into a Bitmap or JS Url 
and loads the Url, then the Google Server gets the contents of the 
local ID Cookie without any problems until the Cookie is deleted.

So i agree with you , its not a direct Issue of uMatrix, its an
generally Problem of the way, how uMatrix handles the blocking
of Cookies.

Its useful for some circumstances to give the local Javascript code
the allowance to read the Contents of a Cookie, but then there are 
several ways to transfer the Cookie indirect to the Server without
uMatrix have a Chance to block this in the existing manner.

sorry for misinterpreting the sentence : 
`Cookies are prevented from leaving your browser`
I saw the opposite and wanted to know why

Thank you for spending time on this.

**Comment by gorhill** [comment]
> its an generally Problem of the way, how uMatrix handles the blocking of Cookies.

There is no problem. You forget the part where you can ask uMatrix to delete the blocked cookies.

**Comment by leafcutterant** [comment]
> There is no problem. You forget the part where you can ask uMatrix to delete the blocked cookies.

How quickly does uMatrix delete the cookie after it was set?
