### ISSUE TITLE
[Feature request]: Activate/deactivate add-ons per site visited ruleset

### ISSUE THREAD

**Issue by flyingzebras** [gorhill/uMatrix#624]
HTTPS Everywhere use rulesets for which sites is should be active/inactive on.

What do you think about the idea to make it possible to activate/deactivate defined add-ons on site visited basis?

Example: Disable Greasemonkey for tv4play.se only.

**Comment by gorhill** [comment]
The matrix filtering button applies to the current scope, so you can disable it on a per-site basis.

**Comment by flyingzebras** [comment]
@gorhill My idea was to enable/disable _any_add-on_ (not just uMatrix) per site-basis.

**Comment by gorhill** [comment]
> Do you understand?

I have no idea why you think uMatrix should become an add-on manager.

**Comment by elypter** [comment]
it would make sense in a greater "per site settings" management addon that manages everything from cookies, plugins, ads, site optimization, redirects and so on but such an addon unfortunately doesnt exist. if you find developers then tell them the idea.

**Comment by flyingzebras** [comment]
@elypter I agree with you. Such add-on need a lot of permission though. Perhaps this mission could be something for the Firefox developers.

**Comment by elypter** [comment]
unfortunately i dont think they will do such a thing. youre more likely to find someone developing for palemoon or vivaldi to implement this in their browsers. firefox has become way too big and rigid to incorporate new ideas
