### ISSUE TITLE
Media and image unmerging

### ISSUE THREAD

**Issue by kirill9000** [gorhill/uMatrix#626]
I think merging them is bad from security perspective. Audio and video are much more complex formats than images, and their parsers are more likely to contain various vulnerabilities (see libstagefright for example). So I want to decide whether to allow images and media separately.

@gorhill could you please roll back your decision to merge them?

**Comment by gorhill** [comment]
And when one allows _other_, it allows much more than just media resources. Why would having these in _other_ be of any help? At least with _image_ (which I plan to rename _media_) you know what you are allowing in.

**Comment by kirill9000** [comment]
>it allows much more than just media resources

Websockets? I don't see how they could be more dangerous than media.

**Comment by kirill9000** [comment]
>At least with image (which I plan to rename media) you know what you are allowing in.

Details about what types of resources column controls could be placed in it's tooltip.

**Comment by hrj** [comment]
> And when one allows other, this allows much more than just media resources.

How about having more columns? One each for `image`, `media`, `websockets` and `others.

/no-sarcasm-intended

**Comment by gorhill** [comment]
`websocket` can be merged with `xhr`. For `media`, I am still willing to consider adding one more column, this will require a lot of work in popup though, and further delay publication of a newer version, and time is short on top of that.

**Comment by gorhill** [comment]
There is now a specific column for media.
