### ISSUE TITLE
uMatrix stuck on fixed size view with other oddities as well as fixed count

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [gorhill/uMatrix#629]
I have just noticed that uMatrix 0.9.3.6 on Firefox 49 has just suddenly started:

a) It shows this on every site whether this is true or not and I can't get it to shake it:

![umatrix_fixed_56](https://cloud.githubusercontent.com/assets/11575271/18852082/c72719c8-8436-11e6-8caa-2fbc9cd4b6e7.png)

b) The view's height and width are fixed on too small values for the data to be displayed, and on most sites I cannot move down the list (in c I can, but not proper, and it does not allow changing the width):

![umatrix_too_small](https://cloud.githubusercontent.com/assets/11575271/18852122/fa8fb144-8436-11e6-82c2-97ec1282fe64.png)

c) On some specific pages for some reason there is a scroll bar, though as you can see from this screencast it behaves very strangely (it's an mp4 file but I had to zip it up so that I could upload it here):

[uMatrix_Strange_Scroll_Bar.mp4.zip](https://github.com/gorhill/uMatrix/files/494137/uMatrix_Strange_Scroll_Bar.mp4.zip)

I am running Ubuntu GNOME 16.04.1 with GNOME 3.20. It was fine earlier on in the browser session, I only noticed it when I exited a fullscreen program I had been watching on the BBC iPlayer website. And it has made uMatrix practically unusable.

After restarting my browser the issue seems to have fixed itself and gone away, but if this issue comes again too often it will be really annoying to have to keep restarting my browser to fix it.

**Comment by gorhill** [comment]
Probably the browser console contained errors providing clues. Next time, please report any error reported in the browser console (Ctrl-Shift-J).

**Comment by johnswolter** [comment]
I'm seeing the same issue in Ggl Chrome(54.0.2840.99 m) & Chrome-64(54.0.2840.99 m) but it appears to be the blacklist area most times..  Usually, not always, only one line is displayed indicating a blacklist exists.  When expanded that list is not visible if the non-blacklist is near the tab's bottom.

Could you respond with directions as how to generate the debug info you need
