### ISSUE TITLE
Wildcard doesn't include iframes

### ISSUE THREAD

**Issue by vibrasphere** [gorhill/uMatrix#630]
E.g. I want to allow YouTube in all sites. So you go with `* youtube.com * allow`, it allows all scripts and etc. except iframes. So then you have to add duplicate line with `* youtube.com frame allow`, which, I think, is very impractical and now like that I need to add multiple lines for each website.

Also I got another question. I want to include `asdasdasd.cloudfront.net` in a site so I add this rule `twitch.tv cloudfront.net * allow`, but it doesn't work. I tried `.cloudfront.net` and `*.cloudfront.net`. The idea is to somehow skip the `asdasdasd.` subdomain part so that rule would allow all with whatever comes before `.cloudfront.net` because those subdomains aren't static, so we can't each time add a new rule everyday.

I read the documentation, but it's too complicated, I don't think I found the area about subdomains and a general rule for both, all and iframes.

Cheers

**Comment by gorhill** [comment]
> So then you have to add duplicate line with `* youtube.com frame allow`, which, I think, is very impractical and now like that I need to add multiple lines for each website.

That's just how uMatrix works. If you do not want frames to be blocked globally, just remove the rule enforcing this (`* * frame block`), then you won't need to override it.

> so I add this rule `twitch.tv cloudfront.net * allow`, but it doesn't work.

I just checked, and it does work.

**Comment by vibrasphere** [comment]
Can you test with .trade domain? E.g. poe.trade It has the subdomain.cloudfront.net called

**Comment by gorhill** [comment]
`poe.trade cloudfront.net * allow` won't work because `d3pkae9owd2lcf.cloudfront.net` is blacklisted by one of the filter list. That's how uMatrix works: narrower rules win over broader ones. You choose how you want to override the blacklisted hostname:

Cancel blacklist status of `d3pkae9owd2lcf.cloudfront.net` everywhere:

    * d3pkae9owd2lcf.cloudfront.net * allow

Allow all from `d3pkae9owd2lcf.cloudfront.net` on `poe.trade` only:

    poe.trade d3pkae9owd2lcf.cloudfront.net * allow

Allow only script from `d3pkae9owd2lcf.cloudfront.net` on `poe.trade` only:

    poe.trade d3pkae9owd2lcf.cloudfront.net script allow

**Comment by vibrasphere** [comment]
Why it's blacklisted? Which filter?

**Comment by gorhill** [comment]
I don't know why. Looking up the hostname in the filter lists you have activated, and then ask whoever maintains that list.

**Comment by vibrasphere** [comment]
So then how do you know it is even blocked by any blocklist at all

**Comment by gorhill** [comment]
> So then how do you know it is even blocked by any blocklist at all

Well, if you did not block it yourself, then one of the list did?

Look, I do warn up front that uMatrix is for advanced user, I just do not have the time to assist users in diagnosing web site breakage etc., uMatrix is expected to break site, it's default settings is to block active content from 3rd-party servers by default.
