### ISSUE TITLE
Menu fills the whole screen

### ISSUE THREAD

**Issue by k-h** [gorhill/uMatrix#632]
The menu I get when I click on the umatrix icon tends to grow sideways until it's larger than the screen.

It starts out at normal width and then gets gradually larger until it's way larger than my screen.
umatrix 0.9.3.6 Firefox 48 Macos 10.11.6

![Uploading Screen Shot 2016-10-01 at 2016 Oct 1, 11.56 18 AM.png…]()

**Comment by k-h** [comment]
![screen shot 2016-10-01 at 2016 oct 1 11 56 18 am](https://cloud.githubusercontent.com/assets/724426/19011058/18f14602-87cf-11e6-9cd1-ed873244e472.png)

**Comment by gorhill** [comment]
I can't reproduce with FF 49 and the uMatrix icon in the default toolbar.

What is this bar at the bottom in which I see the uMatrix icon?

**Comment by k-h** [comment]
status-4-ever (an extension)

**Comment by gorhill** [comment]
Do you have the issue if uMatrix icon is in the default toolbar at the top?

**Comment by k-h** [comment]
It seems the window gets wider with each use and eventually wraps back to the correct size.  I can't of course see this except when it's smaller than my screen.  Firefox 49 runs too slow so I went back to 48.  Could that be a cause?

**Comment by gorhill** [comment]
Do you have the issue you disable all other extensions, then restart Firefox?

**Comment by k-h** [comment]
I made a copy of my profile and disabled all addons but: Status-4-evar, stylish, tab mix plus, tree style tab, ublock origin and umatrix and it still occurs:
![screen shot 2016-10-03 at 2016 oct 3 12 17 47 am](https://cloud.githubusercontent.com/assets/724426/19020845/6e045612-88ff-11e6-8273-918fed32608d.jpg)

I will disable the rest and see.

**Comment by k-h** [comment]
This is the next time I clicked it.
![screen shot 2016-10-03 at 2016 oct 3 12 18 18 am](https://cloud.githubusercontent.com/assets/724426/19020862/f5a662ea-88ff-11e6-916f-df0d610d7dcb.jpg)

**Comment by k-h** [comment]
Disabling all add-ons and restarting, still have the problem.

**Comment by gorhill** [comment]
> Disabling all add-ons and restarting, still have the problem

You have a screenshot?

**Comment by k-h** [comment]
>You have a screenshot?

It looked the same.

I just went back to  firefox 49 and it doesn't exhibit this problem.

**Comment by gorhill** [comment]
> It looked the same.

The same as what? I asked you yo try uMatrix without any other extensions. So far, you have followed up with two screenshots showing me uMatrix still with other extensions. You are making it difficult to investigate by resisting providing the information requested, i.e. try uMatrix **without** your _status-4-ever_ extension.

**Comment by k-h** [comment]
Here is a screenshot of the second click:
![screen shot 2016-10-04 at 2016 oct 4 10 37 08 am](https://cloud.githubusercontent.com/assets/724426/19057884/f2212310-8a1e-11e6-961d-cf54b0c17358.jpg)

And the third click:
![screen shot 2016-10-04 at 2016 oct 4 10 37 33 am](https://cloud.githubusercontent.com/assets/724426/19057892/01c435fa-8a1f-11e6-8955-9bfcab6604cc.jpg)

Firefox 48 with umatrix the only extension

**Comment by gorhill** [comment]
Do you have user styles?

**Comment by k-h** [comment]
I use an extension "Stylish" for that and it was disabled.

**Comment by Atavic** [comment]
@k-h So you had Firefox 49 and then you went back to 48. 

Did you modify the GUI on Firefox 49? Did you add/remove icons/toolbars?
Maybe the FF 49 GUI settings aren't working well on FF 48.

**Comment by bizaff** [comment]
For what it's worth, I've seen this from time to time - not the whole screen full, but a large amount of white space to the right of the "other" column.

**Comment by Atavic** [comment]
I had similar problems caused by removed addons that left some errors into my toolbar. A new profile corrected it.
