### ISSUE TITLE
CPU-intensive forbidden image replacement

### ISSUE THREAD

**Issue by kirill9000** [gorhill/uMatrix#633]
Current background: linear-gradient replacement causes a significant lag when scrolling page with multiple forbidden images on older CPUs in Firefox. It would be better with something simple like RP's flag picture.

**Comment by gorhill** [comment]
uMatrix version?

**Comment by kirill9000** [comment]
Latest from AMO - 0.9.3.6.

**Comment by gorhill** [comment]
This was fixed in that version, see 09cf683e1a81c5d09f6b36c2212b02365a08679c.

**Comment by kirill9000** [comment]
Thank you.

**Comment by gorhill** [comment]
Be sure it's not overridden by the setting `extensions.umatrix.placeholderImage` in `about:config`.

**Comment by kirill9000** [comment]
I've tried on a new profile - works good. Yeah, there were leftovers in these prefs on my old profile.
