### ISSUE TITLE
Useragent randomization improvements

### ISSUE THREAD

**Issue by Mattk50** [gorhill/uMatrix#634]
I'd been looking for a good useragent randomizer for awhile when to my joy i saw it was already in umatrix. However, the implementation has room to improve, the current system doesn't provide much to people who are trying to anonymize their activity across multiple websites and i would even argue it doesn't do much as is. Here are my suggestions to improve this functionality.

- The option to use a random user agent per website rather than for the whole browser would prevent cross website tracking for when your randomized useragents intersect. This is the big one in terms of effectiveness, i believe.
- Option to automatically populate the list with browser specific common user agents every time the browser goes up a version, perhaps even using a similar "lists" system to the adblock lists already used in ublock origin and hosts lists in umatrix
- Alternatively, automated useragent generation depending on some input parameters would allow a much bigger variety for each user.
- Randomized spoofing options for more than useragent, including the canvas fingerprint, webgl fingerprint, and if technically possible in an extension, the system fonts and plugin reporting (though i realize enabling these options would break many websites, the option would be enjoyed).

Thanks for the excellent extensions and effort you've put into them, gorhill.

**Comment by Atavic** [comment]
There are some other addons for this specific purpose, as Random Agent Spoofer or UAControl that let you choose the User-Agent on a per-site basis.

**Comment by Atavic** [comment]
There's [randomua](https://github.com/LeoTindall/randomua) as Webextension.
