### ISSUE TITLE
Chrome vs Firefox Functionality - Handling a blocked site

### ISSUE THREAD

**Issue by jjohns71** [gorhill/uMatrix#637]
When 'uMatrix has prevented the following page from loading:' the functionality is different in Chrome vs Firefox.

In Chrome, it is possible to override the block by setting the blocked domain to allow from within the quick panel and refreshing the page. In Firefox however, the blocked domain doesn't show up at all from the panel.

I think the way Chrome handles this is a better way because it at least gives the user an easy way to override the hosts entry that is blocking access by clicking on the blocked host name and turning it "green" from the quick panel. In Firefox, it's not possible to do this without first going into the 'My Rules' tab from within the Dashboard settings and manually entering in an override rule. Is it possible to get the same functionality how Chrome handles a fully blocked site in the Firefox version so we can manually override an errant block like in the case below? It seems like the Chrome quick panel is more user friendly.

Chrome Options: 
![chrome](https://cloud.githubusercontent.com/assets/6795795/19161558/45097cd6-8bc2-11e6-9b4c-4867b67f4175.png)

Firefox Options: 
![ffx](https://cloud.githubusercontent.com/assets/6795795/19161568/4f44825e-8bc2-11e6-9aad-bc61af0fa918.png)

Thank you!

**Comment by gorhill** [comment]
No URL? Transcribing from the screenshot is going to be tedious.

**Comment by jjohns71** [comment]
Sorry the URL is http://www.indystar.com/story/news/crime/2016/10/04/state-police-raid-indy-office-growing-voter-fraud-case/91540816/

It seems like the host might be down right now, but this was how the block was working when I took the screenshots yesterday, indystar is a news site so most likely it is an errant block in a hosts list.

**Comment by jjohns71** [comment]
Now when I tried this today, the indystar URL did load in my Firefox uMatrix quick panel so maybe it was just a temporary bug that was not allowing it to display yesterday. Seems weird, sorry if this is a false bug report, I will close, seems functionality is the same between Chrome & Firefox.
