### ISSUE TITLE
About list of all blockable objects 

### ISSUE THREAD

**Issue by lstar4ever** [gorhill/uMatrix#641]
Hi,
For the UBlock, ou  have listed all the 7 tytpes of elements that can be blocked with UBlock, e.g. image, 3p-frame...etc
However, the same lists of things I cannot located in the uMatrix wiki,
May you please add this list to the wiki, or where can I locate these information?
Thanks.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
