### ISSUE TITLE
only if https

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uMatrix#642]
Hi!
It's feature request.
I want to make such rules:
```
* * script block
* 1st-party script allow (but only https)
```
I think that's will be great and helpful for potential MitM-attack.

**Comment by gorhill** [comment]
Just be sure to use an encrypted connection to download a web page, your browser will now allow scripts from non-encrypted connections to run on the page.

**Comment by jhsagl4a** [comment]
Not all sites have https. I want allow scripts only from https-sites.

**Comment by gorhill** [comment]
Downloading a page from a non-encrypted connection is incompatible with worrying about MitM.

**Comment by jhsagl4a** [comment]
MitM-active-attack is exactly a replacement of scripts.

**Comment by gorhill** [comment]
> Not all sites have https

Then your rule `* 1st-party script allow (but only https)` would not accomplish anything.

**Comment by jhsagl4a** [comment]
This rule allows 1st-party scripts only through https.
And first rule block all scripts
`* * script block`
