### ISSUE TITLE
Question .svg

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uMatrix#643]
Why .svg files count like plugins but not images?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by jhsagl4a** [comment]
I want to block flash but allow svg. Can I do that with uMatrix?
It might be a feature request.

**Comment by gorhill** [comment]
There is no repro steps.

**Comment by jhsagl4a** [comment]
.svg and .swf both count as plugins.
and if I use
`* * plugin block`
both are blocked
I want to block swf and don't block svg
