### ISSUE TITLE
Feature request: More options to reduce fingerprinting and improving privacy

### ISSUE THREAD

**Issue by tonowoe** [gorhill/uMatrix#644]
Hello guys. Thank you for your great plugin.

I have a couple of ideas to improve privacy and reducing the fingerprinting of the browser.

- spoofing screen and resolution related information (such as width, height, outer and innerheight, contrast, pixel and color depth and such)
- spoofing hash of the canvas fingerprint (canvas related information)
- spoofing hash of the WebGL fingerprint (WebGL related information)
- spoofing date/timezone
- spoofing language
- spoofing system related information (like platform and oscpu)
- spoofing fonts
- spoofing plugins, MIME-types
- spoofing HTTP-ACCEPT headers
- spoofing Do Not Track choice
- spoofing audio related information (like via DynamicsCompressor, AudioContext, OscillatorNode and such)

There are other types of fingerprinting too which are done e.g. by BlueCava, but I'm not sure what all these are and are they "spoofable":

- CLSIDs, ActiveX
- MSIE Security Policy
- Mouse gesture, keystroke timing and velocity patterns, and accelerometer readings (ondeviceorientation) 
- AJAX implementation
- Math constants

**Comment by gorhill** [comment]
Foiling fingerprinting is best left to another specialized extension.

**Comment by rEnr3n** [comment]
This may not be enough but it's a good start https://github.com/snyderp/web-api-manager

**Comment by ArchangeGabriel** [comment]
If using Firefox, look at `privacy.resistFingerprinting`.
