### ISSUE TITLE
Filter based on requesting site, not just scope

### ISSUE THREAD

**Issue by bizaff** [gorhill/uMatrix#645]
I poseted this a while ago - https://superuser.com/questions/1117768/firefox-plugins-umatrix-vs-policeman - and got no response there.

If it's not already there, is this something that could be added to uMatrix?

**Comment by bizaff** [comment]
I'll assume it's not currently capable of this - any reason this won't/can't be done?  Could it be done with minimal UI support, just through the rules page?  I think it's a solid feature, and I'm willing to help..

**Comment by gorhill** [comment]
Just create global allow rules for auxiliary hostnames, than create a local rule for `youtube.com` when you want to allow Youtube on a site, the other related rules in the global scope will then take effect.
