### ISSUE TITLE
Feature Request - Wildcard within destination hostname

### ISSUE THREAD

**Issue by BanisterJ** [gorhill/uMatrix#646]
So that I could write a rule like

`* *.cloudfront.net * allow`

Personally, I wouldn't care if the * character was used, if /\w+/ or something else is preferable.

**Comment by gorhill** [comment]
Wildcard is implicit.

**Comment by gorhill** [comment]
Seriously considering closing the issue tracker for a while with all issues opened with no respect with regard to [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
