### ISSUE TITLE
User Agent Spoofing Disturbs Firefox Sync

### ISSUE THREAD

**Issue by EMLVIRUS** [gorhill/uMatrix#648]
User Agent spoofing sometimes makes Firefox Sync judges current device as a new one and requires another Email confirmation.

**Comment by gorhill** [comment]
You allowed UA spoofing in behind-the-scene scope?

**Comment by EMLVIRUS** [comment]
I believe I didn't add any per-scope rules
on chrome://umatrix/content/dashboard.html#privacy, i simply tick everything but Strict HTTPS: forbid mixed content.

**Comment by gorhill** [comment]
> I believe

What are your rules?

**Comment by gorhill** [comment]
Actually I realize that uMatrix doesn't have default rules to prevent spoofing in the behind-the-scene scope. This is a mistake. Add these rules manually, commit, and see if this help

    referrer-spoof: behind-the-scene false
    ua-spoof: behind-the-scene false
    https-strict: behind-the-scene false

**Comment by EMLVIRUS** [comment]
Yep, that would work. Could you fix that on next update?
