### ISSUE TITLE
strange interaction with gab.ai

### ISSUE THREAD

**Issue by atomGit** [gorhill/uMatrix#652]
gab.ai is a new social media site - very strange interaction with uMatrix apparently where the background changes color and you are redirected to github

i can reproduce by:

1) disable JS in uM globally
2) go to https://gab.ai/
3) click anywhere near the white box in the lower left
4) background changes color (pale yellow) and you are redirected to a uMatrix support req. on github: `https://github.com/gorhill/uMatrix/issues/61#issuecomment-63814351`

uMatrix 0.9.3.6
Firefox 49
Linux

**Comment by Atavic** [comment]
maybe the browser went back to the previous page?

**Comment by atomGit** [comment]
nope - wasn't on that page, didn't comment there and don't recall ever seeing it before
