### ISSUE TITLE
IPv6 not supported

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [gorhill/uMatrix#653]
Visit [http://[2607:f740:d::f77]/](http://[2607:f740:d::f77]/), [http://[2001:470:1:18::125]/](http://[2001:470:1:18::125]/), [http://[2001:470:1:18::119]/](http://[2001:470:1:18::119]/) to test.

**Comment by Atavic** [comment]
http://relay.mx/ works here.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Steps for reproduce:
1. Connect to an IPv6 internet.
2. Start Firefox and create a new profile.
3. Install uMatrix.
4. Open the page http://[2001:470:1:18::125]/ or http://[2001:470:1:18::119]/ (IPv6 address of ipv6.test-ipv6.com).
5. Open uMatrix menu.
6. Try to allow the scripts and not see the proper permits cells (as in https://web.archive.org/web/20170227031554/https://dump.bitcheese.net/images/tyvadut/Firefox:_uMatrix:_IPv6_%D0%BD%D0%B5_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82_0.png).

**Comment by Atavic** [comment]
You should give info as Firefox version... 
Is this related? https://github.com/gorhill/uMatrix/issues/667

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Tested on Firefox 51.0.1 (64 bit, release), OS Linux, uMatrix 0.9.3.6.
#667 is very similar. #597 is a bit like.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Also tested on Firefox 52 (64 bit, release). Reopen the bug, please.

**Comment by gorhill** [comment]
> uMatrix 0.9.3.6

This was key information not provided in the original bug. This was fixed a long time ago in 83b342d4e4d768d57f1c982d9bf6b673ad35526e. Fix is in dev build, available in development channel on AMO.
