### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by robinhood2014** [gorhill/uMatrix#655]
This is not an "issue" per se as much as a request, but, since this extension is cross-browser already (Firefox, Opera and Chrome), why not build a version for Microsoft Edge? You're already working on uBlock Origin for the same browser, so for "power surfers" who want to exercise more control over scripts and the like, uMatrix seems only natural to be an extension candidate for Edge.

**Comment by anewuser** [comment]
The author of this project doesn't even use Windows. Please close this issue and ask somebody else to do it for you.

**Comment by Nojevah** [comment]
It's a request, and I think it is the right place to ask. If Edge extensions were to work nearly like Chrome/Firefox, it could be supported too. In the end, the main developer will choose what to do.

**Comment by gorhill** [comment]
Whoever is proactive is free to make a port just like this was done for uBO.
