### ISSUE TITLE
Missing reload button

### ISSUE THREAD

**Issue by Tanath** [gorhill/uMatrix#658]
The Firefox version is missing the reload button after the eraser button. Is there a way to get it back? I didn't see a setting for it.

**Comment by Tanath** [comment]
I've tried reinstalling uMatrix and there was no change. I also noticed the revert all and logger buttons are also missing. Here's a screenshot:  
https://imgur.com/a/HiFdU

It's the same on any site. That area is empty.

I'm using Firefox 49.0.2 on Linux.

**Comment by Tanath** [comment]
Er, not sure if I somehow missed this before or something changed, but the buttons are actually there, they're just invisible. Hovering does show the tooltip. I was sure I moused over them before.

**Comment by gorhill** [comment]
You have any user styles?

**Comment by Tanath** [comment]
I don't appear to.

**Comment by gorhill** [comment]
I can't reproduce such issue. There are no other report of such issue. So far this means there is something specific on your side causing this. Only you can investigate to find out what is causing this on your side.

**Comment by p42n3** [comment]
I can confirm this, i've just learned about these invisible buttons because of this github issue, i didn't miss them before... :)

@Tanath : i'm using a light-colored text on dark background theme on my desktop, maybe you too?

**Comment by Tanath** [comment]
Yes, I am. I've switched my theme a few times recently, so it's not any particular theme.

**Comment by Tanath** [comment]
Well, I just tested with a dark on light theme and the buttons are visible. I won't use such a theme as it's harsh on my eyes, but the info is useful for troubleshooting. It is notable this problem does not occur on the Chrome version.

**Comment by gorhill** [comment]
> it's weird it only affects some buttons and not others.

The buttons left of the reload one have a different style applied to them. The first two are colored according to the currently selected scope (to emphasize they apply to the current scope), while the two others are dimmed if there are no temporary rules. So some themes styles are overriding uMatrix ones.

**Comment by p42n3** [comment]
"some themes styles are overriding uMatrix ones" -no, probably not, as far as i can observe it, it's that developers/designers often define only foreground color but not background, or the other way round. So, the theme style changes the undefined color, but does not change (not override) the defined color.
Probably the same here?

**Comment by gorhill** [comment]
> So, the theme style changes the undefined color, but does not change (not override) the defined color.
> Probably the same here?

This is uMatrix's style for the button:

    body .toolbar button {
        ...
        background-color: white;
        color: black;
        ...
    }
