### ISSUE TITLE
* mask as a part of domain name?

### ISSUE THREAD

**Issue by rhazor** [gorhill/uMatrix#659]
Something like `* akamai*.net * allow` does not work.
So I need to add both:
`* akamai.net * allow` and
`* akamaihd.net * allow`

And like that for all the 'cdn' domains, and there are hundreds of those. And it all would be solved if something like:
`* *cdn.com * allow` worked, or
`* cdn*.com * allow`

But now you have to add one by one each time and every day.

**Comment by rhazor** [comment]
wow

**Comment by gorhill** [comment]
Fork and try rewrite the core filtering code, it will become obvious why I declined.
