### ISSUE TITLE
Flickering dropdown menu, wtf?

### ISSUE THREAD

**Issue by foxx** [gorhill/uMatrix#660]
So this has been driving me a bit nuts for a while, sometimes when you click on uMatrix the dropdown box will "flicker", it's been happening since the day I started using it (almost 2 years ago), only just thought to report it.

Here's a screencast showing the bug;

https://www.dropbox.com/s/tfgvzuewiqc4p8e/wtf.mov?dl=0

```
Browser: Chrome 54.0.2840.87 (64-bit)
OS: MacOS Sierra 10.12.1 (16B2555)
```

**Comment by gorhill** [comment]
The popup panel is just normal HTML/CSS/JavaScript, and the frame containing it is under control of the browser. The only explanation I can see is that you have a relatively slow CPU.

**Comment by foxx** [comment]
@gorhill Macbook has a pretty powerful CPU, and happens on fresh install. Even so, I'm not sure how that would result in the frame being half hidden, surely if it was CPU related then it would be a laggy render rather than a totally broken one?

**Comment by foxx** [comment]
Also note that this problem only happens with uMatrix extension, and no other extensions (such as Audio EQ, which has a similarly sized popup)

**Comment by foxx** [comment]
Also related to https://github.com/gorhill/uMatrix/issues/423

**Comment by gorhill** [comment]
> Also note that this problem only happens with uMatrix extension, and not other extensions 

The matrix is dynamically build, so the popup the size of the popup (which is not under uBO's control) may change as the matrix is built.

**Comment by foxx** [comment]
Any idea what the fix for this might be? Even if just a rough guess? Seems quite a few other people have been hit by this one too.
