### ISSUE TITLE
Method of allowing a domain across all scopes

### ISSUE THREAD

**Issue by fourquarts** [gorhill/uMatrix#662]
It would be nice to be able to specify that a domain can be used by any site (scope) instead of just the current site. For example, I'm not concerned about sites loading an embedded version of Google Maps. It would be very rare for me to want that blocked. If I didn't want it on a particular site, I could just block it within that scope.

If this already exists, please let me know. I can't seem to find it if it does. Thanks.

**Comment by d-kr** [comment]
On the left side of the popup click on the blue region with the url and select '*' like in this wiki page https://github.com/gorhill/uMatrix/wiki/Very-bare-walkthrough-for-first-time-users.
