### ISSUE TITLE
"1st-party allow" overrides IP range block

### ISSUE THREAD

**Issue by argiopetech** [gorhill/uMatrix#665]
* 192.168.100.1 * block
    * 1st-party * allow

blocks access to 192.168.100.1 with "uMatrix prevented the following page from loading: http://192.168.100.1". However, an IP range such as "192.168.100" as in

    * 192.168.100 * block
    * 1st-party * allow

does not prevent the page at http://192.168.100.1 from loading.

Is this intended behavior?

**Comment by argiopetech** [comment]
Some extra platform info:

$ google-chrome-stable --version
Google Chrome 54.0.2840.90 
$ uname -sr
Linux 4.4.21-gentoo

Tested against uMatrix 0.9.9b2 loaded as an unpacked extension and 0.9.3.6 from the Chrome web store. uBlock Origin is installed but disabled, uBlock Origin Websocket is installed and operational.

**Comment by gorhill** [comment]
> Is this intended behavior?

Yes, because the rule `* 1st-party * allow` overrides `* 192.168.100 * block`. The first rule overrides the second one because it is more specific. This is key in uMatrix: narrower rules always override broader ones.

**Comment by argiopetech** [comment]
I agree that `* 192.168.100.1 * block` should override `* 192.168.100 * block` since 192.168.100.1 is more specific, but my intuitive feeling is that the interaction with `1st-party` in this case should work like subdomains. `* google.com * block` also blocks e.g., `calendar.google.com`.

As it is, it takes three records

    * 192 * block
    192 1st-party * block
    192 1st-party frame block

to block a /8 block given the default uMatrix settings, but only one (`* google.com * block`) to block a domain and all its subdomains.

Would you consider amending this behavior?

**Comment by gorhill** [comment]
> Would you consider amending this behavior?

No. I consider any one specific IP address to be 3rd-party to any other IP address.

> `* google.com * block` also blocks e.g., `calendar.google.com`

Bad example. What you are asking is rather like:

`* com * block` also blocks e.g., `google.com`

If you want this behavior, remove the rule `* 1st-party * allow`, you will get what you want without the need to introduce arbitrariness in how rules are evaluated in uMatrix.

**Comment by gorhill** [comment]
I believe what you actually want is this:

    192.168.100 1st-party * block
    192.168.100 1st-party frame block

You can override global `1st-party` rules in narrower scopes.
