### ISSUE TITLE
uMatrix/uBlock Origin conflict with each other and cause extension error randomly

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uMatrix#669]
### Describe the issue

uMatrix/uBlock Origin conflict with each other and cause extension error over a CSP responsive header.

### One or more specific URLs where the issue occurs

outlook.com (4 times so far)
pornhub.com (2 times so far)

### Screenshot in which the issue can be seen

https://i.gyazo.com/9c3114cdbb16601fbf6e840c4eaa6b62.png

### Steps for anyone to reproduce the issue
1) Remove all cached data and web storage for live.com, outlook.live.com and outlook.com
2) Close Chromium
3) Open Chromium and browse to outlook.com (you will need a microsoft account to login outlook mail)
4) An orange notification icon should popup in the extreme right corner of the screen, click on it and you will be sent to chrome://extensions page which will display this warning - https://i.gyazo.com/9c3114cdbb16601fbf6e840c4eaa6b62.png

PS - This happens randomly, so it wont happen 75 % of the time, but if follow the steps and try to re-create it after some time, it will happen. Run uBO with uMatrix for 3-4 days if you want to experience it yourself without recreating it.

### Your settings
uMatrix - Default
uBlock- Default
- Browser/version: Chromium 56
- uBlock Origin version: 1.9.16
- uMatrix version  - 0.9.3.6

I enabled and disabled a lot of uMatrix settings to no avail. I even changed the installation order, still the issue happens. So far, the race condition is caused where uMatrix reaches first for a CSP response header.

Is there anything you can suggest/do to make it go away and not appear ?

**Comment by gorhill** [comment]
This is a browser behavior, by design. Only one extension can modify one request/response header.

**Comment by uBlock-user** [comment]
So what should I do ? Remove uMatrix ?

**Comment by gorhill** [comment]
> Also why does it happen randomly

uBO modfies the CSP header to block websocket/inline script according to filters/rules. uMatrix modifies CSP header to block 1st-party script according to rules, consequently use the loggers of both uBO/uMatrix find out what modified the CSP header.

**Comment by uBlock-user** [comment]
and then whitelist blocked resources from one of the extensions to avoid this ? Will that work ?

**Comment by gorhill** [comment]
> Will that work ?

Sure. Not blocking 1st-party script with uMatrix would be best, since uBO can both block inline script if needed **and** websockets where needed.

**Comment by uBlock-user** [comment]
Forget to add, I have ||$websocket in uBO. Can that be the cause ?

**Comment by gorhill** [comment]
I could experiment with pushing new CSP header rather than modifying the existing one. As per CSP spec, new CSP policies intersect with existing ones. Would still need to modify existing one to remove `report-uri` stuff. Anyway, worth experimenting.

**Comment by gorhill** [comment]
> Can that be the cause ?

yes.

**Comment by uBlock-user** [comment]
Reinstalled uMatrix. These are my saved rules - http://pastebin.com/raw/hu0pTPx5

Let me know if you need anything else. Also if ||$websocket is causing it, I can't really remove it as I enjoy the benefits of all websocket connections being blocked by default and I don't  have to worry about adding websites everytime I find some websocket sending some ads, so is there any alternative around that ?

**Comment by gorhill** [comment]
Your `* * frame allow` is causing uMatrix to change CSP headers of loaded frames: the `iframe` is allowed to load, but no script is allowed to run in the `iframe`.

**Comment by uBlock-user** [comment]
Removing that would cause 3rd party video players to be blocked, that's why I have allow them. Case in point, couchtuner hosts 3rd party video players and without that rule, they won't load or appear, so that's the issue.

**Comment by gorhill** [comment]
The sensible solution is to use narrow global rules for where the players are hosted:

    * thevideo.me * allow
    * thevideo.me frame allow

Now this issue is turning into a support issue. I expect advanced users to understand how to use uMatrix and be able to come up with the proper set of rules.

**Comment by uBlock-user** [comment]
Well with the lack of recommended rules documentation for websites, I had to come up with something that won't bother me every now and then as that host and many others are used on several websites also my key question is can this be fixed with a tweak in rule set/settings ?

**Comment by Rimmer7** [comment]
Things like recommended rulesets is something we the users should work on, so that gorhill can focus on getting actual work done.

**Comment by uBlock-user** [comment]
>Things like recommended rulesets is something we the users should work on

That's your opinion, I disagree. The actual work you talk about has already been done, there's nothing left and uMX is already a full working extension.
