### ISSUE TITLE
Strict HTTPS feedback

### ISSUE THREAD

**Issue by my-password-is-password** [gorhill/uMatrix#67]
Chrome's built in mixed content blocker seems to only block scripts and gives a warning for other types of requests.

![chromemixedcontent](https://cloud.githubusercontent.com/assets/6408935/5153416/d7521f82-71dc-11e4-93d9-a8e5add8716e.PNG)

uMatrix's strict HTTPS blocks all types of requests.

![umatrixstricthttps](https://cloud.githubusercontent.com/assets/6408935/5153420/0371e4c6-71dd-11e4-9e0c-ed0fb2f1878d.PNG)

Heres Microsoft's Mixed Content test page, https://ie.microsoft.com/testdrive/browser/mixedcontent/assets/woodgrove.htm

Not reporting this as a bug just feedback after reading the wiki.

This site seems to be a better test page for comparing mixed content blocking, https://www.bennish.net/mixed-content.html

The built in blocker allows media (images, audio, video) requests.

**Comment by privatebob** [comment]
Strict HTTPS doesn't seem to be blocking the http link in the src of HTML5 <video> tag.

Example: 
https://www.dailymotion.com/video/x2fzmkz_game-of-thrones-season-4-making-of_shortfilms
In network monitor:
Path: http://proxy-04.nyc.dailymotion.com/video/918/887/147788819_mp4_h264_aac_2.mp4?
auth=1232432434-5675-9dfsdwen-345jlkjsdf9f7lswer080lkjljsdf6zxcyvt45b
Method: GET
Status: 206 Partial Content
Scheme: http
Type: video/mp4
Initiator: Other

**Comment by gorhill** [comment]
Fixed in 0.9.0.0: uMatrix now blocks itself the non-secure requests, rather than relying on a CSP policy.
