### ISSUE TITLE
Enabling uMatrix on a Per-Site Basis

### ISSUE THREAD

**Issue by ThisIsAlanB** [gorhill/uMatrix#671]
Given the nature of uMatrix and other extentions like it, I wanted to know if it'd be possible to have uMatrix be disabled by default, manually enabling it for the sites that the user wants to be blocked. That way, sites will almost always work, and the sites that need filtered can when manually enabled.

Thank you!

**Comment by uBlock-user** [comment]
This comes close to what you want - `* * * allow`

That's allow all/block exceptions model.

**Comment by ThisIsAlanB** [comment]
Alright. Thank you very much!
