### ISSUE TITLE
Can Javascript inside PDFs be blocked?

### ISSUE THREAD

**Issue by hrj** [gorhill/uMatrix#672]
When I open [this PDF](https://hal.inria.fr/hal-01399482/document) in Chromium 53 + uMatrix, a print dialog is automatically shown. This is [apparently](http://superuser.com/questions/263842/) because of some embedded javascript in the PDF.

Is it possible for uMatrix to block this embedded JS?

FWIW, NoScript in Firefox seems to block it.

**Comment by gorhill** [comment]
Not possible, you are dealing with Chromium PDF plugin there. Even trying to block javascript using Chromium's site settings does not work. Browser issue.
