### ISSUE TITLE
mail.com + uMatrix cause Firefox to completely hang or almost crash

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uMatrix#674]
It's been about a week that I can not use Mail.com when uMatrix filtering is enabled. (I know it is a crappy service and I am going to stop using it, but I thought to report this issue so that it might lead to improving uMatrix)

The aforementioned combination causes prolonged unresponsiveness in Firefox to the point that I have to kill firefox.exe

Tried with a brand new Firefox profile, and uMatrix as the only addon, filters updated to the latest version. 

When I turn off uMatrix filtering, mail.com works.

Firefox message:

> A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
> 
> https://img.ui-portal.de/pos-cdn/mailcom/core/latest/poseidon-814a8194.min.js:6

[poseidon-814a8194.min.js.txt](https://github.com/gorhill/uMatrix/files/622595/poseidon-814a8194.min.js.txt)

![mail com error 1](https://cloud.githubusercontent.com/assets/13304436/20765015/f2822f90-b730-11e6-8ca4-8c0b50019a8b.jpg)
![mail com error 2](https://cloud.githubusercontent.com/assets/13304436/20765019/f7420fa0-b730-11e6-866e-a26650fa6939.jpg)
![taskmgr firefox](https://cloud.githubusercontent.com/assets/13304436/20765020/f9c69534-b730-11e6-8c0e-347841eda351.jpg)

Firefox 50.0.1
uMatrix 0.9.3.6
Windows 10 Pro v1511

**Comment by gorhill** [comment]
There is no issue in uMatrix. Sometimes web sites may break as result of blocking network requests. This is an instance of this.

**Comment by AdKiller** [comment]
It is not limited to the usage of the said website. It brings down the whole Firefox browser, surely that is not intended purpose of uMatrix?!

**Comment by gorhill** [comment]
It's not uMatrix's code doing this, it's the site's code.

**Comment by uBlock-user** [comment]
Cannot reproduce. Disable all other addon. No issue with the website.
