### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by AlexPoulsen** [gorhill/uMatrix#676]
I used to use HTTP switchboard on Chrome; Now I use Safari (because of distrust for google).
Are there any technical limitations preventing this from being a Safari Extension too?

**Comment by gorhill** [comment]
Duplicate of #96.

**Comment by will1818** [comment]
@AlexPoulsen please also see https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/93 for safari issues, you are better off sticking with chromium

**Comment by AlexPoulsen** [comment]
I will look into deleting those automatically, thanks. I would consider using chromium, but never chrome.
