### ISSUE TITLE
Different second screen resolution effects uMatrix menu

### ISSUE THREAD

**Issue by diseq** [gorhill/uMatrix#679]
With a different second screen resolution, elements in the uMatrix menu are not at expected positions. i.e. mouse cursor postion and button do not match. happens on second scree. i guess it translates positions from first screen.

Chrome Version 54.0.2840.99 m (64-bit)
Windows 10.0.14393
UMatrix on chrome:  0.9.3.6
1.screen res: 1920x1080
2.screen res: 2560x1440

![umatrix_problem](https://cloud.githubusercontent.com/assets/6008785/21072479/890294e2-bec4-11e6-9bdc-07723e5b0ec8.gif)

**Comment by gorhill** [comment]
uMatrix does not make use of x,y coordinates in its code, it just uses mouseenter/mouseleave events. This means there is a bug in the browser, you need to report to Google Chrome devs.

**Comment by gorhill** [comment]
I believe this would be the related Chromium issue: <https://bugs.chromium.org/p/chromium/issues/detail?id=426656>.
