### ISSUE TITLE
Incomplete CSS when Editing Temporary Rules

### ISSUE THREAD

**Issue by ewhac** [gorhill/uMatrix#680]
In the My Rules tab, when clicking on the Edit button to edit the Temporary Rules, the resulting pane does not completely specify the CSS to render the pane.  More specifically, the `color` element is not specified, meaning that the text in the `textarea` will inherit the default foreground color.  For people who use "dark" desktop themes, this means the text is rendered in white or near-white, making it near-illegible against the light blue.

To fix this: Go to `user-rules.css` around line 141 to the declaration for `#diff textarea`, and add the element: `color: black;`

**Comment by gorhill** [comment]
Can't reproduce with latest version.
