### ISSUE TITLE
Youtube History not work

### ISSUE THREAD

**Issue by Flowex** [gorhill/uMatrix#682]
Hello,

my problem is that the Youtube History not work with uMatrix.
The Reason is that the Hosts Files Blocked the History, but u can not disable the Hosts file for a Site.
Any way that i can Disable the Hosts Files for one Site ? 
I want use the YT History but not disable the Hosts Files.

Sorry my English is not the best, i hope u know what i mean :) 
And Thanks for uMatrix, is a very nice Plugin :)

**Comment by gorhill** [comment]
> Any way that i can Disable the Hosts Files for one Site ?

No.

Just override the block rule with your own rule. Example: `youtube.com s.youtube.com * inherit`, or broader `* s.youtube.com * inherit`.
