### ISSUE TITLE
Config Window too big for screen - Chromium

### ISSUE THREAD

**Issue by Saucermote** [gorhill/uMatrix#683]
This has come up before in issue #483 and #571 and was fixed for Firefox I believe, but the same fix does not apply to Chromium based browsers.

I'm currently using Vivaldi (latest snapshot) which is based on Chromium 55.0.2883.92 and uses the Chrome webstore and extensions, and there is no scroll bar available to use when the number of hosts exceeds the screen space.  I'm using a 1920x1080 monitor, so my vertical screen space isn't tiny, but this still happens with surprising frequency.

Ublock Origin recently introduced a small workaround with their [new advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) allowing the users to set the font size.

---

I'm wondering if we could please get the scroll bar and/or the font size setting? 

The same screen shots would apply that apply from the above issue number.

**Comment by lonkamikaze** [comment]
Same problem here on Chromium Version 56.0.2924.87 (64-bit).

It might be worth mentioning that my screen has 160 DPI and chrome renders things accordingly. I.e. I'm not using some fake DPI that causes everything to be tiny.

**Comment by lonkamikaze** [comment]
Maybe some details are in order. The problem is not that there is no scroll bar, the problem is that the uMatrix window is too big and cut off in the bottom.

Given enough items in the table a scroll bar will show up, but of course you cannot scroll further than all the way down, so you never get to see the bottom most items.

The impression that the scroll bar is not working comes from the case when the uMatrix window is to big to fit into the Chrome window, but is big enough to contain the whole table without scrolling. This happens surprisingly often.

![2017-03-07 chromium-umatrix-small](https://cloud.githubusercontent.com/assets/5013682/23651812/0122961a-0327-11e7-954d-3ee2457988f7.png)

**Comment by gorhill** [comment]
> the problem is that the uMatrix window is too big and cut off in the bottom

The browser decide max size of popup panels, extensions have no control/knowledge of this. There is an open chromium issue somewhere about popup panel extending beyond screen size.

**Comment by Saucermote** [comment]
I think there is some sort of bug going on however, because frequently it isn't displaying all of the columns to let me pick what type of content to allow as the window is way too small; randomly the XHR, frame, other column get cut off completely.   It takes reopening the webpage, refreshing, tab switching to finally get the window to show me all the options I need to get the page to open correctly.  Then it is a 50/50 shot if I'm able to scroll down far enough to see all the rest of the options without something being cut off.   Most of the time it works correctly, but some random sites it will just cut everything off at the bottom and right, or it will just display a gear when I hit the button.

**Comment by ddraws** [comment]
I understand your frustration but a bug is a bug https://bugs.chromium.org/p/chromium/issues/detail?id=428044

**Comment by gorhill** [comment]
> as the window is way too small

There is a separate known issue which affects MacOS + Chrome users. Are you on MacOS?

**Comment by Saucermote** [comment]
I'm on Win 7 x64, no idea what they are on.

**Comment by Saucermote** [comment]
I think I actually figured out what is causing the issue on my end, it is the UI scaling. Anything other than normal UI scaling causes the popup window to randomly not display correctly.  Normally I run with a smaller UI, which you would think allow more space for the window to display, not less, but resetting the chromium/vivaldi UI to the default size causes the config window to display correctly, at least for now.
