### ISSUE TITLE
How to block just 1 script from a domain? 

### ISSUE THREAD

**Issue by gab854** [gorhill/uMatrix#687]
Hello.
Is there a way to disable just 1 script?
This website has 3 scripts, if I block all the 3, the site doesn't work. The issue is that one of these scripts is a VERY annoying popup script that shows an ad every other click with NSFW content.

As I see it, I can only block all 3 scripts or allow all 3.
I've used the logger and pinpointed the script I would like to block.
Is this possible?
Thank you.

**Comment by gorhill** [comment]
> Is there a way to disable just 1 script?

No.

**Comment by sleek22** [comment]
If you have uBlock Origin, you can try using Inline Script Tag Filtering.

I wanted the Forbes print article page without the print pop-up. I wrote the following filter in uBlock Origin to block it:

forbes.com##script:contains(print)

The reference page to Inline Script Tag Filtering is here:

https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering

**Comment by uBlock-user** [comment]
> If you have uBlock Origin, you can try using Inline Script Tag Filtering.

That only works for Firefox, not all browsers, so not a worthy of being suggested as a generic solution.

**Comment by elypter** [comment]
unless there wont be any other developer for ublock/umatrix i dont think gorhill wont find the time to implement any major features toumatrix
