### ISSUE TITLE
blocked content is now displayed as grey box, instead of previously red conspicuous box

### ISSUE THREAD

**Issue by 400thecat** [gorhill/uMatrix#688]
In earlier versions (such as in the featured video: Chrome: uMatrix - Das wichtigste Addon), the blocked content box is nice, conspicuous red-striped area.

In the current version, it is grey, unconspicuous area.

Has this been changed intentionally?
Is there a simple way to revert it back on my side ?

PS: many thanks for this great extension

**Comment by grumpygeek** [comment]
See if you accidentally checked "Color Blind Friendly" on the settings tab of Dashboard.

**Comment by 400thecat** [comment]
No, "Color Blind Friendly" is not checked

**Comment by xofe** [comment]
This was removed quite a while ago (with commit https://github.com/gorhill/uMatrix/commit/44f1a61c42fb3c0357774ea176ef0ea6a9591642).

The new background style can be changed, though I don't know the procedure for Chrome/Chromium. In Firefox, it is set using `extensions.umatrix.placeholderBackground` about:config preference.
