### ISSUE TITLE
uMatrix Popup UI gets unresponsive randomly

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uMatrix#689]
### Describe the issue

uMatrix's popup UI becomes unresponsive randomly and gets screwed up. This has been happening since yesterday.

### Screenshot in which the issue can be seen

https://i.gyazo.com/37e8b73132a2555329c6f3bac485ab32.png

https://i.gyazo.com/b1d0f19bae034763505f21c19340558d.png

### Settings

- Browser/version: Chromium 57
- uMatrix version : 0.9.3.6

**Comment by uBlock-user** [comment]
It occurs randomly, so you won't be able to reproduce immediately, you will have to browse for a while and keep opening popup UI and click anything on it to see it's responsive or not. Also can you check `popup.js` and `popup.html` files ? The issue appears to be stemming from there.

**Comment by jjohns71** [comment]
I also have this issue sometimes, the most common set of repeatable events for me are using Firefox with espn.com website. If you open the panel, make some changes, refresh the page, the panel will _sometimes_ crash and show as blank. I haven't been able to determine a set of 100% repeatable steps to reproduce however so I hadn't opened a ticket myself.

**Comment by uBlock-user** [comment]
Mine started happening since I updated Chromium from `57.0.2960.0` to `57.0.2970.0`. It's completely random, so it becomes very difficult to catch. For me, it happens when I open the panel and click on anything. Either it becomes unresponsive or the entire CSS of the panel gets fucked up like in the first pic I posted.

**Comment by uBlock-user** [comment]
Closing this as this issue has reached an impasse.

**Comment by uBlock-user** [comment]
Closing this as the issue has reached an impasse.

**Comment by hukkay** [comment]
> @uBlock-user : fucked up

@uBlock-user Stop your vulgarity
