### ISSUE TITLE
[Feature Request] Save Rules permanent & Auto-Reload

### ISSUE THREAD

**Issue by Goldich** [gorhill/uMatrix#691]
Hi,
I just started using uMatrix due to the lack of good alternatives in Chrome. I figured quit fast, that I have to allow each request and the extension is not remembering anything. In the configuration I saw that a temporary rule set and a permanent rule set exists, but current changes are not automatically stored in the permanent rules. 

Can you implement a setting to save rules on purpose to the permanent rule set? 

The second topic is the page reload. It's really annoying if you have to reload each time manual, when you approve a rule. What’s about if a rule changed and the user clicks into the tab, the page reloads automatically? 

Best Regards,
Oliver

**Comment by Goldich** [comment]
Sorry, but closing without explanation is really unfriendly.

**Comment by jjohns71** [comment]
@Goldich Please read my [post](https://github.com/gorhill/uMatrix/issues/685#issuecomment-268620190) on issue #685  which should teach you how to save temporary changes one of two different ways.

@gorhill Is there any possibility you would use the above instructions I posted on #685  within the wiki? (New bullet point perhaps?) I think a lot of user issues are very similar and just stem from misunderstanding of functionality of the plugin and hoping the walk through I posted for global rule setting is helpful as it shows how to set global and non global rules and permanently save them.
