### ISSUE TITLE
Apply rule to just the host and not its subdomains

### ISSUE THREAD

**Issue by migueldemoura** [gorhill/uMatrix#695]
I can't figure out a way of applying a rule to just the host and not its subdomains. Wiki didn't help either.

E.g. with cookies:
I allow cookies from [example.com](example.com) with `example.com first-party cookie` or `example.com example.com cookie`. This allows the website to read said cookies.
However, this also allows, as expected, any subdomain of [example.com](example.com) to also read cookies. I know I can manually block subdomains, but not only is that a PITA, but it also pollutes the rule list and opens the door to unsolicited cookies in case a new subdomain is used.

**Comment by gorhill** [comment]
> I can't figure out a way of applying a rule to just the host and not its subdomains. 

Not possible, by design -- it's the core principle of how uMatrix works.
