### ISSUE TITLE
Will updating hosts files affect previously set rule?

### ISSUE THREAD

**Issue by rekixex** [gorhill/uMatrix#696]
With default _block-all / allow exceptionally_ approach: for example, you 'allow' (globally or on specific website) some hostname which is not part of hosts files (let's say www.example.com). When this hostname later becomes part of hosts files after updating (for example, it starts serving adware / malware), will that affect previously set 'allow' rule? Will that override rule for hostname?

In this scenario, _allow-all / block exceptionally_ approach would 'block' hostname www.example.com after hosts files update, since this approach doesn't rely on 'allowing' specific hostname.

**Comment by migueldemoura** [comment]
Assuming that example.com is blocked through a host rule:

`example.com example.com * allow` -> overrides host rule;
`example.com * * allow` -> host rule prevails.

**Comment by rekixex** [comment]
@migueldemoura 

> `example.com example.com * allow` -> overrides host rule

Right, it overrides host rule despite later hosts files update which brings `example.com` to block list? Assuming that `example.com example.com * allow` overrides host rule, would it be better if uMatrix didn't honor this overriding ONLY in case where hosts files update added `example.com` to block list?

As an analogy, anti-malware software allows you to run specific file ONLY until that file becomes malicious. In other words, it doesn't allow you to run that file ONLY in case where update brings the file to block list (this is very simplistic view, excluding heuristics, etc. but that is not relevant in this example).

@gorhill Can you comment on this? I think this is important because legitimate 3rd party domain which we allow (`example.com example.com * allow`) may become malicious and subsequently part of hosts files at some point of time.

**Comment by gorhill** [comment]
> Can you comment on this?

The same precedence logic applies after an update.

**Comment by rekixex** [comment]
@gorhill From my experience, rules from hosts files rarely need to be overridden for sites to function properly (and I even use some more hosts files than default in uMatrix). As legitimate 3rd party domain which we allow (`example.com example.com * allow`) may become malicious, I think it would be more rational if precedence logic did not apply after an update, because user could still override the rule if needed.

Therefore, I suggest you to change this behavior if that is possible. It would improve security and privacy without the loss of functionality.

This is the only behavior I do not like in this excellent extension.

**Comment by gorhill** [comment]
> Therefore, I suggest you to change this behavior if that is possible

Declined.

It just does not make sense in the first place to create a rule such as `example.com example.com * allow`, so I am not going to spend precious time addressing a such non-issue. Whoever creates such a rule will have to bear the responsibility of whatever negative side-effect such rule can have -- just as is the case for _any other rules_.

**Comment by rekixex** [comment]
@gorhill 

`example.com example.com * allow` is not a good example of what I tried to explain. My mistake.

I will explain this issue on a real website.

Website: https://www.wunderground.com/

`wxug.com` tries to load 2 scripts when you load https://www.wunderground.com/ (you can test it for yourself). You need `wxug.com` for `wunderground.com` to function properly so you allow it (according to documentation: https://github.com/gorhill/uMatrix/wiki/Rules-syntax):

`wunderground.com wxug.com * allow`

Now `wxug.com` loads 11 plugins and 2 scripts.

Let's assume `wxug.com` becomes **malicious** and subsequently part of hosts files at some point of time. And let's assume you update hosts files regularly.

Expected behavior: uMatrix should block `wxug.com` despite user previously allowed it, because it is now part of hosts files because it is malicious. User can still override it if needed.

Current behavior: uMatrix honors previously set allow rule for `wxug.com`, despite `wxug.com` is now part of hosts files because it is malicious.

This is a legitimate issue.

**Comment by gorhill** [comment]
If you fear that anything you allow may become part of a hosts file (which content are not necessarily literally malicious), then don't create permanent rules.

**Comment by migueldemoura** [comment]
I understand both view-points and my opinion is that such feature would have to be optional and possibly even opt-in.

@rekixex, that use case is valid but not common because hosts that you manually whitelist are **unlikely** to become malicious - they could become sources of tracking scripts, but not malware - sysadmins are likely to find that out before list maintainers do (and the update cron is triggered). And if you whitelisted such host for that service before, you did so because it was probably needed for the page to display properly and you checked what it was for (uMatrix is for advanced users).

Finally, you can do fine-grained control over what loads by coupling uMatrix and uBO simply by denying all scripts from that host and manually allowing the ones you want.

**Comment by gorhill** [comment]
In the big picture, open source software developers should not burn themselves out and/or bloat a code base to address ever smaller and questionable worries by ever smaller number of users (up to a single one).

**Comment by rekixex** [comment]
@migueldemoura 

> my opinion is that such feature would have to be optional and possibly even opt-in.

I agree. I would be satisfied if such feature was available as optional.

> that use case is valid but not common because hosts that you manually whitelist are **unlikely** to become malicious - they could become sources of tracking scripts, but not malware

I used term **malicious** only as example of worst-case scenario.

@gorhill 

> In the big picture, open source software developers should not burn themselves out and/or bloat a code base to address ever smaller and questionable worries by ever smaller number of users (up to a single one).

This extension is truly excellent, it offers great control over network requests. In my opinion, the most important extension for securing Chrome / Firefox. Thanks for your work, I really appreciate it. :)

However, I disagree that this is 'questionable worry'. Yes, it is unlikely, but not impossible.

_Allow-all / block exceptionally_ approach would be effective in this scenario. I think that _block-all / allow exceptionally_ approach deserves the same ability in this specific case.

I understand that it would require much work. This is only a suggestion, not a request.

Cheers. :)

**Comment by rekixex** [comment]
@migueldemoura 

> my opinion is that such feature would have to be optional and possibly even opt-in.

I agree. I would be satisfied if such feature was available as optional.

> that use case is valid but not common because hosts that you manually whitelist are **unlikely** to become malicious - they could become sources of tracking scripts, but not malware

I used term **malicious** only as example of worst-case scenario.

@gorhill 

> In the big picture, open source software developers should not burn themselves out and/or bloat a code base to address ever smaller and questionable worries by ever smaller number of users (up to a single one).

This is more of a suggestion than a request.

However, I disagree that this is 'questionable worry'. Yes, it is unlikely, but not impossible.

_Allow-all / block exceptionally_ approach would be effective in this scenario. I think that _block-all / allow exceptionally_ approach deserves the same ability in this specific case.

**Comment by rekixex** [comment]
@migueldemoura 

> my opinion is that such feature would have to be optional and possibly even opt-in.

I agree. I would be satisfied if such feature was available as optional.

> that use case is valid but not common because hosts that you manually whitelist are **unlikely** to become malicious - they could become sources of tracking scripts, but not malware

I used term **malicious** only as example of worst-case scenario.

@gorhill 

> In the big picture, open source software developers should not burn themselves out and/or bloat a code base to address ever smaller and questionable worries by ever smaller number of users (up to a single one).

This is more of a suggestion than a request.

However, I disagree that this is 'questionable worry'. It is unlikely, but not impossible.

_Allow-all / block exceptionally_ approach would be effective in this scenario. I think that _block-all / allow exceptionally_ approach deserves the same ability in this specific case.
