### ISSUE TITLE
[Chrome] Latest version from github is 0.9.9b0 instead b2?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#699]
If I install the latest beta of uMatrix for Chrome, it displays v0.9.9 which means b0 ... but it should be b2 which means 0.9.9.2 or not? Or is u uMatrix not the same version logic as in uBlock?

**Comment by gorhill** [comment]
> is u uMatrix not the same version logic as in uBlock?

Yes, not the same scripts to generate the version, these were modernized in uBO to account for beta versions, not so in uMatrix.

**Comment by Alpengreis** [comment]
All right, thank you very much ... and closed.
