### ISSUE TITLE
Feature Request: Easily allow adding a set of rules to the active scope

### ISSUE THREAD

**Issue by ibotty** [gorhill/uMatrix#702]
Adding e.g. recaptcha, youtube or vimeo rules to allow a site to load is while easily possible pretty tiring because having to reload the page many times. It would be great if one could either allow adding a set of rules to the active scope (e.g. selecting from a dropdown) or, more complicated but arguably better ui, having set of such hosts appear in the domain list, so that you could allow i.e. all youtube domains with one click.

**Comment by gorhill** [comment]
Duplicate of #30.

**Comment by ibotty** [comment]
Oh. I did not find that issue. Thanks for your work bzw.
