### ISSUE TITLE
Error when dealing with DOMParser.parseFromString()

### ISSUE THREAD

**Issue by laniakea64** [gorhill/uMatrix#706]
**Environment:**
SeaMonkey 2.46
uMatrix 0.9.9b2
new profile

**Steps-to-reproduce:**
1) install uMatrix, restart browser
2) open Web Console and run this code
```
var x = new DOMParser();
x.parseFromString('<img src="http://example.com/" />', 'text/html');
```

**Actual results:**
This error appears in the Browser Console -
```
TypeError: contextWindow is null [Learn More]  frameModule.js:161:14
```

------------
(Might as well respond to the inevitable reply now, to save some time - yes, I do have a real-world example of this which doesn't involve the Web Console, but it requires a login. :) )

**Comment by gorhill** [comment]
SeaMonkey 2.46 is based on which version of Firefox?

**Comment by byte-jra** [comment]
49

**Comment by gorhill** [comment]
Related: https://github.com/gorhill/uBlock/issues/1893

**Comment by laniakea64** [comment]
Fixed, thanks! :smiley:

**Comment by alice-margatroid** [comment]
Your own problem if it goes to your inbox. So it does go to mine, block me if you can't handle a polite question. Stop spamming and harassing me already.
