### ISSUE TITLE
anti fingerprinting request

### ISSUE THREAD

**Issue by TheSkyEye** [gorhill/uMatrix#707]
Can we have anti fingerprinting system in uMatrix like in this extension https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf
This is an open source extension, so maybe you can use the code.
The code is at https://github.com/andryou/scriptsafe

Thanks you for your jobs !

**Comment by gorhill** [comment]
Duplicate of #644.
