### ISSUE TITLE
[feature request] sub-domain independent rules

### ISSUE THREAD

**Issue by EMLVIRUS** [gorhill/uMatrix#708]
Add abilities for independent rules for every sub-domain under a specific domain:
e.g. mail.google.com and drive.google.com provides different contents so that we may hope to add different rules.
but www.google.com and scholar.google.com should be same.
conclusion:
add a button for that.

**Comment by gorhill** [comment]
Just use the scope selector to select the scope in which you want the rule to apply.

**Comment by EMLVIRUS** [comment]
You may misunderstand me so let me put this more precisely:

Step 1:
I visit Google to search something with such a rule:
google.com * cookie block
so Google search doesn't set cookie for me.
Step 2:
I go to drive.google.com but now I have to login

Problem: I have to revert rule in step 1 to login as uMatrix treats google.com and drive.google.com as the same domain and applies with same domain-scope rules.

Expectation: I hope to apply different rules for main domain and every sub-domains for a site.

**Comment by gorhill** [comment]
Just create an allow rule for cookies on `drive.google.com`.
