### ISSUE TITLE
Request: Global-disable button

### ISSUE THREAD

**Issue by Gittyperson** [gorhill/uMatrix#709]
On several websites (including e-payments etc.) it's not enough to "disable matrix filtering for this scope" and completely disabling the extension via the browser's options is required to quickly make them work. The same result can be achieved by selecting 'all' (*) then 'Allow' and then refresh, but ultimately this requires a lot more clicks and time. Also, the refresh operation may cause problems especially during payments, while disabling the extension takes instant effect (although not entirely sure on the necessity of a refresh - a secondary matter, anyway).

For speed and convenience's sake, the request would be an additional UI button which essentially disables the extension with a single click. Could also apply to uBlock, even though less websites require a global disable to work.

Thanks again for your important work.

**Comment by gorhill** [comment]
> a lot more clicks and time

Global disable: 1 click.
Selecting global scope and disabling matrix filtering: 3 clicks.

For such a rarely used feature, I find 3 clicks vs 1 click to be acceptable, considering that the benefit is that I do not have to throw in new code and UI.

Declined.

**Comment by Gittyperson** [comment]
Thanks for answering. Please note that it's not just the clicks that accumulate the time required. Also, the action would need to be reversed every time so it's 6 clicks vs 2.

Of course, if nobody deems this useful there's no point. Thanks again.

**Comment by gorhill** [comment]
To reverse it can be one click on the eraser.

**Comment by uBlock-user** [comment]
Disable uMatrix for that website entirely via `matrix-off: example.com true` or use global-allow/block exceptionally mode. You do have options like these. Both of these options require to be done only once.

**Comment by Gittyperson** [comment]
@gorhill you are right, I forgot about the eraser, but: you'd still have to revert from global scope mode, so it's not really one click.
