### ISSUE TITLE
Only some scripts/frames/whatever shown at once

### ISSUE THREAD

**Issue by samus43** [gorhill/uMatrix#712]
I'm not entirely sure if this is a bug or not, but only some of the scripts and frames and whatever are shown in the matrix at once and you have to enable some to see more. This leads to me having to login to a website multiple times until every required script or whatever is enabled. Why is umatrix not showing all scripts or iframes the first time?

**Comment by byte-jra** [comment]
Because neither the browser nor uMatrix could know what content a certain iframe/script loads until it tries to. So it's inevitable to reload multiple times if content at the lower layers is blocked from executing.

**Comment by samus43** [comment]
What do you mean by lower layers?

**Comment by gorhill** [comment]
There is no issue as per your report. This is not a place for support.
