### ISSUE TITLE
Migrate user backup/restore functionality to 'Settings' tab

### ISSUE THREAD

**Issue by glitsj16** [gorhill/uMatrix#714]
Hi, I wonder if you'd consider putting the user backup/restore functionality under the 'Settings' tab (cfr. uBlock). As it currently resides under the 'About' pane, it feels a bit out of place there. Just a cosmetic suggestion/question, functionality itself works just fine here.

Regards

**Comment by weflower** [comment]
I was just about to open a similar thread. It's not a big deal but it would be nice if uBlock and uMatrix were consistent with backup/restore buttons.

**Comment by gorhill** [comment]
Duplicate of #330.
