### ISSUE TITLE
YouTube ads leaking through

### ISSUE THREAD

**Issue by Geremia** [gorhill/uMatrix#716]
With 0.9.9b4, YouTube video ads are not being blocked. I didn't have this problem before. I'm not sure if YouTube changed how they do ads or if something with µMatrix changed.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by Geremia** [comment]
@gorhill This "issue" couldn't fall under "feature request"?

**Comment by gorhill** [comment]
uMatrix is not an "ad blocker", it's a network request blocker working at hostname- and type-level granularity.

**Comment by Geremia** [comment]
@gorhill  I found this: https://github.com/gorhill/uBlock/wiki/FAQ#can-ublock-origin-filter-youtube-ads
thanks
