### ISSUE TITLE
Cannot Disable 'Use Prediction Service' Chrome Dev

### ISSUE THREAD

**Issue by Gridlocked** [gorhill/uMatrix#722]
This looks like a change to Chrome, its only in Dev which has a new user interface for settings.  Just wondering if you were aware of this coming change or if there is a way of disabling it.

**Comment by gorhill** [comment]
Browser bug: <https://bugs.chromium.org/p/chromium/issues/detail?id=693301>.

Prefetching is disabled, it's just the rendering of the button which is incorrect with the new Material Design page.

**Comment by gorhill** [comment]
See `chrome://predictors/`, select the "Resource Prefetch Predictor" tab, it says "Resource prefetch prediction is disabled".

**Comment by Gridlocked** [comment]
Thanks!

**Comment by uBlock-user** [comment]
You can disable the new material design interface for Settings page via `chrome://flags` if you want and it will be back to old behaviour.

**Comment by runofthemill** [comment]
@gorhill - this may merit a separate issue, but how can I *enable* this feature? 

In Chrome 56.0.2924.87 (64-bit) on macOS:

<img width="423" alt="screen shot 2017-03-04 at 2 48 10 pm" src="https://cloud.githubusercontent.com/assets/8418440/23582884/c549f6b8-00e9-11e7-8889-6bc3e6b7f352.png">

I don't see a flag to enable in `chrome://flags` and `chrome://predictors/` doesn't have an option:

<img width="453" alt="screen shot 2017-03-04 at 2 50 51 pm" src="https://cloud.githubusercontent.com/assets/8418440/23582894/0be2c744-00ea-11e7-8eb5-d350dd249b02.png">

**Comment by gorhill** [comment]
> this may merit a separate issue, but how can I enable this feature?

You can't with uMatrix. There is no point using uMatrix if it can't guarantee that no connection is made to remote servers for blocked network requests.

**Comment by runofthemill** [comment]
That's a very good point! 😹 Nevermind :P

**Comment by uBlock-user** [comment]
> I don't see a flag to enable in chrome://flags

chrome://flags/#enable-md-settings

Set it to **Disabled**
