### ISSUE TITLE
Swap ordering of save changes and revert changes buttons.

### ISSUE THREAD

**Issue by redactedscribe** [gorhill/uMatrix#724]
I use both uBlock and uMatrix. Sometimes it requires me to work with both, back and forth, till a site functions as it should. The ordering of the save changes and revert changes buttons are not unified between the two extensions and this leads me to always checking which button I'm pressing than being able to rely on their ordering. I have mistakenly clicked the wrong button in cases due to the unnecessary inconsistency.

I decided to ask this of uMatrix, as by the number of stars on the uBlock repository, uMatrix is not as popular and swapping the button ordering would be less disruptive done here.

Thanks.

**Comment by uBlock-user** [comment]
No, contrary to what you believe, I would rather have uBlock swap the order, I find uMatrix's order perfect by design.

**Comment by redactedscribe** [comment]
My only wish is consistency between the two, but it seems this is not what the author considers an issue.
