### ISSUE TITLE
Add Support for WebSocket Connections for Chromium

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uMatrix#727]
Currently uMatrix cannot detect WebSocket based connections made via `ws://*/*` and `wss://*/*` So will you be adding support for it in the development build ?

It would be very helpful if uMatrix could detect such connections and users can block at will.

Test-case - http://beta.speedtest.net/ 

Umatrix doesn't detect websocket connections made there in `other` or anywhere else, it's completely bypassed.

**Comment by toshiya44** [comment]
It's working on my end.
![image](https://cloud.githubusercontent.com/assets/20046789/23829461/c5dc462c-06bf-11e7-8cbc-861b405e13e1.png)

**Comment by toshiya44** [comment]
It's working on my end.
![image](https://cloud.githubusercontent.com/assets/20046789/23829467/e5072832-06bf-11e7-824f-3c4037989950.png)

**Comment by uBlock-user** [comment]
> uMatrix 0.9.9b4

I'm on version 0.9.3.6, the latest release on the WebStore.

**Comment by rjkpa** [comment]
> uMatrix 0.9.9b4

I'm on the WebStore release version 0.9.3.6.

**Comment by toshiya44** [comment]
Yeah, it doesn't seem to be working on Chrome (I guess uBO extra helps uBO only).

**Comment by Atavic** [comment]
>Currently uMatrix cannot detect WebSocket based connections made via ws:// and wss://
So will you be adding support for it in the development build ?

WebSocket schemes are handled at system level.
What you can do inside a browser is prevent to load the specific scripts that activate websocket connections.

> The WebSocket Protocol is an independent TCP-based protocol.  

https://tools.ietf.org/html/rfc6455#section-1.7

**Comment by rjkpa** [comment]
> prevent to load the specific scripts that activate websocket connections.

Technical details do not matter. Also that's a preventive measure fyi, and uBlock origin already has the ability, so should uMatrix too. That's the point. On top of this, beginning with Chrome 58 websocket connections are natively detected by Chrome, so it shouldn't be an issue anymore.

**Comment by Atavic** [comment]
You should look at the OSI Layers: you can't manage WebSockets neither in an addon nor in a browser, as WebSockets do not happen at application layer only. They go beyond that.

**Comment by Atavic** [comment]
@rjkpa Are you referring to [uBO-Extra](https://github.com/gorhill/uBO-Extra)?

**Comment by rjkpa** [comment]
@gorhill Alright, 0.9.9.7 does appear to be detecting WebSocket connections on Chrome, but at All level and not on website level. Why ?

Secondly, in All it shows "request not processed" ? Why and what does that mean ? I do have uBO running too. Here's the logger page - https://i.gyazo.com/d0dd59c6b4de27138a0bce074c9dc724.png

**Comment by gorhill** [comment]
> Secondly, in All it shows "request not processed"

I just checked, and it means that uMatrix is hard-coded to deal only with `http[s]:`requests, I need to change this to deal with `ws[s]:` as well.

**Comment by rjkpa** [comment]
| but at All level and not on website level in the logger. Why ?

Would you also answer that please ? Like in uBO we can see it when logging the current website and we don't have to change it to All, so why not the same in uMatrix too ?

**Comment by rjkpa** [comment]
Thanks, it's working now. But why report WebSocket attempts to XHR ? You already said you're going to remove plugins as they're deprecated, so just rename plugins to WS instead. I think that's more sensible than sending WS attempts to as XHRs.
