### ISSUE TITLE
0.9.9b5 version shows up as 0.9.9.4

### ISSUE THREAD

**Issue by spalife** [gorhill/uMatrix#730]
Version shows up as 0.9.9.4 in opera after installation of unpacked uMatrix.chromium.zip today
instead of 0.9.9.5

**Comment by uBlock-user** [comment]
yes because he added the quick fix for UI Glitch issue and changed nothing else.

**Comment by Alpengreis** [comment]
However: it confuses the users ...

**Comment by gorhill** [comment]
Forgot to check in manifest.json, I will regenerate the tag.
