### ISSUE TITLE
Trouble loading website kaspersky

### ISSUE THREAD

**Issue by WagnerGMD** [gorhill/uMatrix#732]
Hello,

I can't access to several kaspersky website like :
- [www.kaspersky.com](https://www.kaspersky.com)
- [www.kaspersky.com.br](https://www.kaspersky.com.br)
- [www.kaspersky.de](https://www.kaspersky.de)
- [www.kaspersky.fr](https://www.kaspersky.fr)
- [www.kaspersky.co.au](https://www.kaspersky.co.au)
- [www.kaspersky.nl](https://www.kaspersky.nl)
- [www.kaspersky.co.ul](https://www.kaspersky.co.uk)
- etc

```
view-source:wyciwyg://2/https://www.kaspersky.co.uk/
view-source:wyciwyg://1/https://www.kaspersky.de/
view-source:wyciwyg://5/https://www.kaspersky.co.au/
etc
```
Each page is white (entirely but not the **view-source**)... At least, it's seem to be fine with another adress (like [usa.kaspersky.com](https://usa.kaspersky.com/)).
I had check with another browser (Vivaldi_v1.7.735.46_x64). So, **apparently** the trouble is present with a Mozilla browser (such as FireFox_v52.0.1 (with **uMatrix_v0.9.3.6**) or CyberFox_v52.0.2 (with **uMatrix_v0.9.9b5**) under Windows 10 x64)

For now, I had found one temporary solution which consist to disable uMatrix but it seem's to only work with FireFox... I had also try to change my DNS or to recreate one profil... It didn't work.

As you can see, uMatrix doesn't recognize the right adress (like in [this picture](http://nsa38.casimages.com/img/2017/03/21/170321111849860084.jpg) or see below). 
```
5.wyciwyg-scheme kaspersky.com xhr allow
5.wyciwyg-scheme kaspersky.com script allow
etc
```

**Comment by xofe** [comment]
Can't seem to reproduce using Firefox 53 beta + uMatrix 0.9.9b7, though the site does take an awful long time to load (but that seems to be a server thing, not an issue with uMatrix).

Possibly related: https://github.com/gorhill/uBlock/issues/936

**Comment by WagnerGMD** [comment]
Indeed, the first one is very very long to load... Apparently, it's require the **HTML5 SessionStorage** (`dom.storage.enabled`) to wok fine.

So after one update (FireFox_v52.0.2 and **uMatrix_v0.9.9b12**), the trouble seem to be gone now (and at the end, I saw the message in the **browser console** (when it was disable)).
