### ISSUE TITLE
[Request] Android version pls :)

### ISSUE THREAD

**Issue by TriMoon** [gorhill/uMatrix#733]
I just love this extension, so i wanted to install it on my Aurora version of firefox on my android tablet.
I was unable because it downloads it, but then nothing....

So can you make a version tobe used on android?

**Comment by uBlock-user** [comment]
> because it downloads it, but then nothing

That's a permissions issue with the Firefox android app, alllow all permissions the app asks in your Android tablet and see if it happens again.

**Comment by gorhill** [comment]
@uBlock-user I did not mark the extension as being compatible with Firefox mobile, making the UI works on mobile does not look like small amount of work, and I have no time for this at this point.

**Comment by uBlock-user** [comment]
@gorhill Shouldn't that be directed at @TriMoon ? I didn't request the android version, he did.

**Comment by TriMoon** [comment]
@gorhill I understand ofcourse, Thanks in case you get time to it in future 😸 

@uBlock-user It wasn't a permission issue as you described 👅 , but thanks for the effort.

**Comment by uBlock-user** [comment]
@TriMoon So what was it ? I faced the same issue with uBO, and it turned out to be a permissions issue.

**Comment by TriMoon** [comment]
@uBlock-user See the answer of @gorhill 😉

**Comment by dragetd** [comment]
FYI: uMatrix is listed for mobile devices (Android 7.1 / FireFox) and can be installed without issues.
It only stays greyed out under the settings.

Not sure if this is a mozilla bug or if the package was labled as android compatible by chance.

**Comment by TriMoon** [comment]
Interesting, can you supply the link under mobile website of the addons?
Because i couldn't find it when i posted this tread and tried by using the desktop site...

**Comment by gorhill** [comment]
@dragetd Something is wrong with the mobile version of AMO then. Firefox for Android is not listed in `install.rdf`, and not a valid target for uMatrix on AMO.

**Comment by dragetd** [comment]
Hmm, you are correct. I googled for 'umatrix firefox' and directly landed on https://addons.mozilla.org/de/firefox/addon/umatrix/ via mobile android. And this site does not tell you anything about incomparability - it shows a button to install and even says it installs successfully when using it. But I guess that is an issue on mozillas side!

**Comment by a90c** [comment]
@gorhill Many thanks for your hard work which changed my whole "browsing" experience.  . 
@TriMoon uMatrix can be installed and its properly working in yandex browser for android(based on chromium), you just have to download the opera extention version for it.(nex format not chrome's crx format in case you want to install it offline in developer mode)
Just a note, you have to be aware that yandex browser has some tracking implimentations(appsflyer, google analytics...) so it is not recommended if your goal is privacy, but you can always make use of a well customized hosts file and some file permissions modifications ;) .

**Comment by TriMoon** [comment]
@a90c , thanks but i'm not touching yandex browser 👅 
(or anyother browser made by any search engine including google, due to the fact that they will ALWAYS do as much as technically possible to gather info THEY want...
So i'll stick with Firefox 😉
