### ISSUE TITLE
[Request] add granularity so controls can be separated by path 

### ISSUE THREAD

**Issue by SuperValue** [gorhill/uMatrix#734]
I'll guess that this has been used before.

My use case is that I want to be able to block cookies in "www.google.com" but I want also to be able to allow cookie access in "https://www.google.com/mapsXXXXXXXXXXX". 

So when searching google.com, google can't see my cookies, but in maps it can so it'll load all my saved places etc. 

This wouldn't be an issue if google had simply built it as a subdomain like "maps.google.com" but it uses a path instead.

**Comment by gorhill** [comment]
This requires to turn uMatrix into a completely different extension.
