### ISSUE TITLE
quickly / globally enabling website elements

### ISSUE THREAD

**Issue by aaronjah** [gorhill/uMatrix#735]
Major props to the developer for making this awesome addon.  It has truly spared me from so many security and privacy issues.  I'm new to GitHub.  Where do I donate to a developer?

I notice that I keep having to allow the same things on every website / scope (youtube / vimeo / captchas / cdns / ajax / etc), which is currently a repetitive and unnecessary agony.  Maybe I'm blind here, but I don't see any option in the settings to allow certain elements "once-and-for-all" on every scope (a global allowance).  Is this feature in development?  If so, I have some suggestions:

It would be nice when one pops open the uMatrix window to also see in highlights a kind of "visual guide" based on either what they have allowed in previous scopes, what is officially recommended for certain pages, what is commonly / currently allowed by uMatrix "QA user base" (I would sign up for that in a heartbeat, if it existed), or even a combination of all three.  But seeing that that might be allot of extra work, a good low-key solution might be where uMatrix dynamically learns to either suggest or automatically allow certain website elements based on a user's previous selections in other scopes, recommending a change whenever something is flagged or blacklisted.  Not sure how this would be done, as I know nothing of programming, but it would be a stellar improvement for this addon nonetheless.  So much time-saving would be happening for all of us.

Color-coding the log entries on the logger for easier navigation would be awesome too, but not near as critical as element-selection assistance.

**Comment by toshiya44** [comment]
See this comment https://github.com/gorhill/uMatrix/issues/685#issuecomment-268620190 , it explains how to set rules for global scope.

**Comment by gorhill** [comment]
Just select the scope you want for your rules using the scope selector. `*` stands for global scope.

**Comment by aaronjah** [comment]
THERE it is!  Marvelous!

@toshiya44 Thank you for the prompt and precise redirect.

@gorhill Thank YOU sir for doing what you do to make this blocking addon not only available and functional, but also a wonderful work of art and a great experience for internet users around the globe!  The internet is a better and safer place on account of your amazing contributions!
