### ISSUE TITLE
[Palemoon] Invisible header on websites with many sources

### ISSUE THREAD

**Issue by Karegohan-And-Kamehameha** [gorhill/uMatrix#737]
As the title says, the header for the uMatrix UI is not displayed correctly on websites with many sources, particularly when the scrollbar appears. The elements of the UI are still clickable and work, but are displayed as a blank bar.
https://i.imgur.com/SlyJqQh.png

Versions:
Palemoon 27.2.0 x64
uMatrix 0.9.3.6

**Comment by gorhill** [comment]
You have user styles interfering?

**Comment by haruismywaifu** [comment]
I just tried turning all userstyles off, it had no effect and the bug still persists.

**Comment by gorhill** [comment]
I can't reproduce, you will have to investigate what causes this on your side.

**Comment by haruismywaifu** [comment]
I think I figured it out. The issue only occurs when APZ is enabled (setting layers.async-pan-zoom.enabled is set to true).

**Comment by gorhill** [comment]
I still can't reproduce with `layers.async-pan-zoom.enabled` set to `true`.

**Comment by Atavic** [comment]
Maybe it's related with `meta name="viewport"` value? Which system is affected?

**Comment by haruismywaifu** [comment]
I'm on Windows 7 64bit. I tried forcing D3D9 and OpenGL rendering, both were affected.
