### ISSUE TITLE
no temporary disable

### ISSUE THREAD

**Issue by TeKett** [gorhill/uMatrix#740]
or just basic enable and disable like script blocker and add blocker has.

umatrix falsely blocks a page i want to access, its a cnet download link, but the only way to access it from what i see is to remove umatrix and then access the link and re install umatrix.

it even blocks the link it give me when it says its blocked, i mean why? if the user opens a page and it gets blocked, and then manually past the page while on the same tab as the blocked one, shouldnt that flag that the user wants to access the page and it should not be blocked?

**Comment by gorhill** [comment]
Just use the matrix to create a rule which removes the block.

Closing as _invalid_, as there is no issue with uMatrix, and anyways you did not provide any steps-to-reproduce to at least be given a hint on how to deal with your issue. Probably this will answer your case: <https://github.com/gorhill/uMatrix/issues/203#issuecomment-190795113>.
