### ISSUE TITLE
Support for container tabs

### ISSUE THREAD

**Issue by allo-** [gorhill/uMatrix#741]
It would be great, if uMatrix would be aware of firefox container (user contexts) tabs and would allow different rules for different containers. For example all of twitter could be whitelisted in the "social media" context, while everything from social networks is blacklisted in the default container, so like and "tweet this" buttons can't track you (even without the login cookies) in the default context.

**Comment by nidico** [comment]
I came here to open the same feature request. I think uMatrix + multi-account containers would be a very useful match.

**Comment by ArchangeGabriel** [comment]
What you want then is more likely some implementation of https://github.com/mozilla/multi-account-containers/issues/309.
