### ISSUE TITLE
"all" tab is very often not clickable

### ISSUE THREAD

**Issue by xuedi** [gorhill/uMatrix#744]
Recently, about 2 or 3 weeks ago, on all my machines (chrome browsers) the "all" tab is not clickable, if i click outside the umatrix (to close it) reopen, the "all" tab is clickable again. It happens only once in a while.

Env: Vanilla chromium 57.0.2987.110 (64-bit) on arch Linux with just uMatrix & uBlock orign plugin installed

**Comment by gorhill** [comment]
What is _"all" tab_?

You did not provide your version of uMatrix.

**Comment by xuedi** [comment]
[http://imgur.com/QX2UWXn](url)

**Comment by stade5000** [comment]
I too have this problem. It happens about 10-20 % of the time.

uMatrix 0.9.3.4 & Opera 44.0.2510.1218 on Linux

**Comment by gorhill** [comment]
@stade5000 There is a known issue with uMatrix 0.9.3.4 and recent versions of Chromium, see #711. This has been fixed in uMatrix 1.0.0. I need to upload this version to Opera store.
