### ISSUE TITLE
Make sure uMatrix localizations are pulled prior to dev releases

### ISSUE THREAD

**Issue by TonnesM** [gorhill/uMatrix#745]
Currently, localizations for uMatrix at Crowdin are not pulled prior to dev releases, unlike uBlock’s. Needless to say, this brings localizers into an uncertain state, and release versions may contain some surprises (although localizers _could_ replace files for themselves.)

Is there any reason not to do so and if not, could this become part of the procedure?

(Side note: please check PMs on Crowdin occasionally, since their notification feature obviously doesn’t work and PMs containing questions like these are to no avail, according to several project owners’ feedback.)

**Comment by gorhill** [comment]
Maybe I should just give up on this project? I had to work more than I could afford for all the changes in that one single release, and apparently it was still not enough.

**Comment by gorhill** [comment]
I will try to do better.
