### ISSUE TITLE
[0.9.9b7 from AMO/github][uMatrix WE is ok] .mp4 videos still reported in the image column

### ISSUE THREAD

**Issue by SXZ1** [gorhill/uMatrix#746]
Hello!
uMatrix 0.9.9b7 from AMO/github: .mp4 videos are still reported in the image column. STR:
Go to https://secure.fanboy.co.nz/test.mp4
Click on uMatrix icon - video is reported in the image column

Bug is not reproduced with uMatrix WebExtension from this post: https://github.com/gorhill/uMatrix/releases/tag/0.9.9b7
uMatrix WE reports this .mp4 video in the media column.

Thank you very much, your addons are a work of art!

**Comment by Havokdan** [comment]
I think it's a good idea to move still on betas versions, the item referred to above for "media".

**Comment by xofe** [comment]
Can confirm. It seems the type for media resources is set to `image` in [line 1719 of /platform/firefox/vapi-background.js](https://github.com/gorhill/uMatrix/blob/master/platform/firefox/vapi-background.js#L1719).

Changing this value to `media` (as it was set before https://github.com/gorhill/uMatrix/commit/83b342d4e4d768d57f1c982d9bf6b673ad35526e) causes the resource to be correctly reported in the "media" column, and listed in the logger as type `media`.
