### ISSUE TITLE
uMatrix.webext.zip 0.9.9b7 does not install with chrome web browser

### ISSUE THREAD

**Issue by kleytr6s** [gorhill/uMatrix#748]
i am using google chrome. this error occurs Manifest file is missing or unreadable.

also, will the webextension.zip become the main/only release?
what is the purpose of the webextension.zip?

**Comment by SXZ1** [comment]
I installed uMatrix.webext.zip 0.9.9b7 without any problems in Nightly 30-03-17: set xpinstall.signatures.required to false, download uMatrix.webext.zip, open about:addons - click on gear icon - Install from file - Select zip file.

**Comment by CrisBRM** [comment]
... maybe it's because web extensions is a firefox API... for firefox?
