### ISSUE TITLE
Cant install 0.9.9b7 since it is unsigned

### ISSUE THREAD

**Issue by aspera7** [gorhill/uMatrix#749]
Is there any way of installing the latest release? Firefox it is unsigned and does not allow me to install it. I managed to bypass that by modifications in about:config but it got disabled. The latest version avaiable in Mozilla repository is from June 24, 2016... Am I missing something?

**Comment by jjohns71** [comment]
@aspera7 scroll down to the bottom of the [uMatrix AMO page](https://addons.mozilla.org/en-us/firefox/addon/umatrix/) and select the down arrows to unhide the 'Development Channel' build. You should be able to add a signed version of the beta via the '+ Add to Firefox' button. Installing via this method will also allow to auto update the extension when new beta builds are released and published to AMO.

![beta](https://cloud.githubusercontent.com/assets/6795795/24559959/a9f63b4e-160e-11e7-8c5f-6a18995ecdb6.PNG)

Please close this Issue now as it is Invalid. Thanks

**Comment by aspera7** [comment]
Thanks a lot, issue resolved. Closing.
