### ISSUE TITLE
nightly has prevented this site from installing an unverified add-on

### ISSUE THREAD

**Issue by grinapo** [gorhill/uMatrix#751]
Pre-rel xpi cannot be installed anymore it seems; unsigned package install is rejected without override options.
I try to avoid using emotionally charged expletives about mozilla nowadays.

**Comment by gorhill** [comment]
If you want to use uMatrix's dev build, install from AMO: <https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/beta>.

**Comment by grinapo** [comment]
1) indeed, selecting specific version in AMO works. Thanks! (This probably should be reflected in your release links here on github, ignorant bastards like me just expect the link to install the xpi.)
2) it was required since bot uMatrix and uBlockO magically stopped working (without any explanation or visible message whatsoever)
3) xpinstall.signatures.required defaults to true, I haven't touched it. If this wasn't the case then the nightly yesterday activated/changed it.
4) it's so nice that mozilla hides this info that words cannot describe it. Along with the happy riddance of NPAPI (so everything java related stopped working, which basically covers 99% of racked server management interfaces) this really provides the silver lining to the Mozilla-2017-feeling™.

**Comment by gorhill** [comment]
> uMatrix and uBlockO magically stopped working (without any explanation or visible message whatsoever)


There was a breaking change in Nightly, see <https://github.com/gorhill/uBlock/issues/2505>. Fixed in dev versions.
