### ISSUE TITLE
Allow shorter intervals for deletion of non-blocked session cookies

### ISSUE THREAD

**Issue by murdarar** [gorhill/uMatrix#754]
Please allow single digit intervals for deletion and add an option to include local storage.

15 minutes are too high for privacy concerned users.

**Comment by murdarar** [comment]
Sure is nice to rule with an iron fist and decline comment-less. Whatever.

**Comment by gorhill** [comment]
Make the case why 15 minutes is an issue -- just saying so does not make the case. The 15 minutes has been picked because internally this is how often uBO polls internally, there would be no point going lower.
