### ISSUE TITLE
Filter window intermittently doesn't expand all the way

### ISSUE THREAD

**Issue by JesseBilsten** [gorhill/uMatrix#755]
When uMatrix is opened on click, the window intermittently doesn't expand entirely. This happens to me frequently, sometimes 10-20 times in a row before it will completely render and allow for interaction. I'm on the latest release of the tool: 0.9.9.12

![umatrix](https://cloud.githubusercontent.com/assets/699874/24680100/730cf27e-1944-11e7-9f9c-719405fac9fc.gif)

**Comment by ddraws** [comment]
Duplicate of https://github.com/gorhill/uMatrix/issues/694

**Comment by gorhill** [comment]
Is that MacOS?

**Comment by JesseBilsten** [comment]
Yes. It's OS X 10.12.4

**Comment by gorhill** [comment]
Duplicate of #694.
