### ISSUE TITLE
Broken in Nightly 55.0a1 (2017-04-05) (64-bit)

### ISSUE THREAD

**Issue by jungletek** [gorhill/uMatrix#756]
As subject says. Was working fine on the build from April 3rd. I didn't update to an intermediate build, so it broke sometime between then and now.

Button went missing from my toolbar, and it's not available in the customize menu. Still there in addons list, but the core functionality clearly isn't working as a certain site that was well-behaved with the plugin working is now suddenly throwing popups, which alerted me to uMatrix's absence.

**Comment by gorhill** [comment]
uMatrix version please.

**Comment by JadeSnail** [comment]
Same here, using uMatrix 0.9.3.6.

**Comment by gorhill** [comment]
Installed the [dev build from AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta), changes in Nightly broke the stable version.

**Comment by jungletek** [comment]
Thanks for the timely response, and sorry I wasn't already on the dev-branch; I wasn't aware of it's existence.
