### ISSUE TITLE
Is it difficult to deploy uMatrix to MS Edge in the same way as uBlock Origin?

### ISSUE THREAD

**Issue by electricessence** [gorhill/uMatrix#757]
https://github.com/gorhill/uMatrix/issues/655

I successfully installed uBlock Origin on edge through the MS Store.
https://www.microsoft.com/en-us/store/p/app/9nblggh444l4

It would be really nice to have uMatrix as an option but I can understand that if it's difficult to do it may not be worth the effort.

**Comment by gorhill** [comment]
Why open a duplicate issue? Someone will have to port to Edge.

**Comment by electricessence** [comment]
Duped because I couldn't comment. :/
