### ISSUE TITLE
Umatrix UI not responding

### ISSUE THREAD

**Issue by WagnerGMD** [gorhill/uMatrix#758]
Hello

as you can see in [this picture](http://nsa37.casimages.com/img/2017/04/07/170407032452507384.jpg), sometimes Umatrix doesn't respond (it's seem empty)...
For me, the easier way to fix this trouble consist to switch to (or open) another program. Then the bug seem's to be gone. Perhaps the browser isn't responding ?

Do you need more information (like antivirus, addons, drivers, etc) ? Since [the last issue](https://github.com/gorhill/uMatrix/issues/732), nothing has changed (still Mozilla browser under W10 (both x64)).

**PS : For the record**, do you believe I can discover the cause via one software like [WhatIsHang](http://www.nirsoft.net/utils/what_is_hang.html), etc ? 
About [AppCrashView](http://www.nirsoft.net/utils/app_crash_view.html), no I can't because I didn't keep the data. In fact, I had meet several crash by the past (like one by month). However, a long time ago I had decide to change my OS (W8.1 ---> W10) and these crashs are gone since.

**Comment by gorhill** [comment]
No browser name/version provided, no uMatrix version provided.

**Comment by WagnerGMD** [comment]
Like I said, it was mentionned [there](https://github.com/gorhill/uMatrix/issues/732#issuecomment-291948259). By the word Mozilla, I refer to Firefox and from my point of view, it's clear (or obvious) but I decide to add the links.

So, to resume yes there are the latest (as today like FireFox_v52.0.2 and uMatrix_v0.9.9b12).

**Comment by gorhill** [comment]
> Like I said, it was mentionned there.

I should not be asked to go hunting for such basic information.

> By the word Mozilla, I refer to Firefox

Nightly is not Firefox. Developers need exact information, not be asked to guess.

So far you are the only one reporting such an issue with uMatrix 0.9.9b12 + Firefox 52. Look in the browser console if there are any error which could be related when the issue occurs. 

> can discover the cause via one software like WhatIsHang, etc ?

uMatrix is not an application, it's an extension written using HTML/CSS/JS, all the diagnosing must be done through the browser dev tools. If the browser crash, it's a browser issue, as HTML/CSS/JS is not supposed to crash the browser.

**Comment by Atavic** [comment]
@WagnerGMD The culprit is the browser, maybe there's an AV or a software Firewall (with HIDS module) causing the hang in your system?

**Comment by WagnerGMD** [comment]
> Nightly is not Firefox.

None sense at all... I won't argue on this matter but in fact, it isn't a specific trouble about the current version (neither FireFox or  uMatrix).

To resume, In the last two weeks, I had met the trouble (a few times by day). And like I was assuming, there's still nothing in the browser console... 
About the AV. by the past it was eset_v9 (under W8.1) and now, it's eset_v10 (under W10).
The firewall is provide by Windows.
