### ISSUE TITLE
media rules are saved as plugin rules

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uMatrix#759]
### Steps to Reproduce

- Go to https://www.youtube.com/watch?v=af0tUR0GZUI

- Open the popup UI and under `media` column white-list connections from `googlevideo.com`  

- Browse to `chrome-extension://ogfcmafjalglgifnmanfmnieipoejdcf/dashboard.html#user-rules` and the rule is saved as `youtube.com googlevideo.com plugin allow`     

- Expected Result - `youtube.com googlevideo.com media allow` Actual Result - `youtube.com googlevideo.com plugin allow`

### Browser/version

- Chromium 59/uMatrix 1.0.0

**Comment by gorhill** [comment]
There is no `media` type in uMatrix, internally the `media` column maps to `plugin`. For backward compatibility sake, I can't just rename `plugin` to `media`.

**Comment by Havokdan** [comment]
Could not make both have the same function, at least temporarily, "media" and "plugin" in the rules, being in the wiki that the ideal would be to use "media" from this version onwards?

**Comment by uBlock-user** [comment]
So it will stay like this ?

**Comment by gorhill** [comment]
I don't like this discrepancy. A solution is to internally to create a new `media` type, and make `plugin` obsolete and map it to `media`.

**Comment by rjkpa** [comment]
Any update on this ?
