### ISSUE TITLE
uMatrix icon gone after last firefox update

### ISSUE THREAD

**Issue by MarcSN311** [gorhill/uMatrix#760]
On Firefox Nightly Build 55.0a1 (2017-04-11) (64-bit) the uMatrix Icon disappeared from the Toolbar. (uMatrix version 1.12.0) it also doesn't appear in the customize screen, so it can't be manually added.

I tried this in a clean profile.

**Comment by gorhill** [comment]
There is no version 1.12.0, that does not exist.

**Comment by MarcSN311** [comment]
sorry i clicked on the wrong button, thats my uBlock Origin Version. uMatrix Version is 0.9.3.6

**Comment by gorhill** [comment]
Duplicate of #756.

Please search existing issues before opening a new one.

**Comment by MarcSN311** [comment]
sorry, only searched for open issues.
