### ISSUE TITLE
Why is release 1.0.0 not available on AMO?

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#761]
Hi Gorhill

I want NOT stress you, it's a question only ...

Is there any reason that RELEASE 1.0.0 is not available on AMO or COULD it be that you forgot that?

Thanks in advance for any info and greetings!

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/25011639/0e5ffb10-203c-11e7-9fb5-4c03096a1311.png)
