### ISSUE TITLE
Problem on login

### ISSUE THREAD

**Issue by c30ra** [gorhill/uMatrix#764]
I've recently experienced a issue where i'm unable to login to bitdefender central. Basically when i subimit the login data a page is loaded, but that page is filtered by uMatrix, suddenly the login form page is reloaded, without performing any login. The only solution i found is to completely disable the add-on and reload the page. The shutdown button actually doesn't stop filtering.

**Comment by gorhill** [comment]
Front page of the project: [Regarding broken sites](https://github.com/gorhill/uMatrix#regarding-broken-sites).

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
