### ISSUE TITLE
Opera crash

### ISSUE THREAD

**Issue by Nostro01** [gorhill/uMatrix#766]
Hi
I found this problem, when I missclicked on my tablet.
Browser: Opera 44.0.2510.1218
uMatrix Version: 1.0.0 from Chrome Webstore (The same Problem exist to with the 0.9.3.4 version of the Opera store)
Step 1: Open private window in Opera
Step 2: Close normal window in Opera
Step 3: Click on uMatrix icon
Step 4: Click on the header which opens the Dashboard
-> Opera crashes
With Chrome and Vivaldi, it opens a new normal window with the Dashboard. When you let a normal window open in Opera, it opens the Dashboard in the normal window.

**Comment by gorhill** [comment]
Browser crashes must be reported to browser devs. uMatrix is just HTML/CSS/JS, this is not supposed to crash a browser.
