### ISSUE TITLE
Sign self-hosted Firefox releases

### ISSUE THREAD

**Issue by polyzen** [gorhill/uMatrix#769]
It's now over 2 weeks since 1.0.0 was released, and it's still [unavailable on AMO](https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/). Evidently it [was submitted](https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/format%3Arss).

Please consider signing your self-hosted releases of uMatrix (and uBlock):
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign

Some extensions that do this:
- https://noscript.net/
- https://github.com/Synzvato/decentraleyes
- https://github.com/willsALMANJ/pentadactyl-signed
- https://github.com/akhodakivskiy/VimFx

**Comment by gorhill** [comment]
Just use the dev build on AMO, it's pretty much always ahead of stable or at least just the same.
