### ISSUE TITLE
Umatrix ignores ruleset 

### ISSUE THREAD

**Issue by iaz3** [gorhill/uMatrix#772]
On a particular website i use, the images appear to be hosted at IP addresses rather than using a domain(I *think* it's has some sort of p2p network going on.). umatrix, despite having both implicit and explicit rules allowing images, images on that domain, images from that ip address, and images from that ip address on that website, continues to log a blocked request to that domain. The issue can ONLY be resolved by disabling the extension VIA chrome, as umatrix will continue to incorrectly block it even when turned off for the website.

I would provide better reproducing steps if i could, but the site is both private login entry with manuel cookie copying from other places, and NSFW, so..

summary: Umatrix is incorrectly blocking images from an IP address, even when disabled for the site, and even with the implicit image allow rule and with explicit rules.

**Comment by gorhill** [comment]
You have to provide evidence to support there is an issue, all details, step-to-reproduce, etc.. With such evidence, no point opening an issue. I will close and re-open if and only if you provide repro steps for anybody to reproduce.

**Comment by iaz3** [comment]
L:ooked at Strict https, and seems to be part of the issue.

The question then becomes does it make sense to apply to an IP address, since an ip address can not be HTTPS, let alone subject to the security issues that require HTTPS for domains

And, why it applies even if you disable umatrix for a site.
