### ISSUE TITLE
[FYI] Spoofing Referrer headers in uMatrix

### ISSUE THREAD

**Issue by Atavic** [gorhill/uMatrix#773]
[referrer-spoofing](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches#referrer-spoofing) is explained in the Wiki. In the last sentence:

[...] _the referrer will be spoofed using the_ `http://www.example.com/` _string_.

The referrer here is also stripped down to the minimum for a correctly working and privacy-aware browsing.

@fmarier's post [Tweaking Referrers For Privacy in Firefox](https://feeding.cloud.geek.nz/posts/tweaking-referrer-for-privacy-in-firefox/) goes indepth about the Referer header.

> A more secure  option is to strip cross-origin referrers and leave same-origin referrers alone.

https://github.com/ghacksuserjs/ghacks-user.js/issues/5#issuecomment-280872100

**Comment by gorhill** [comment]
After reading the blog post, it does seem to me that uMatrix could treat non-`GET` requests differently for referrer-spoofing purpose: remove the `Referer` header instead of spoofing it.

**Comment by Atavic** [comment]
Optimal choice.
