### ISSUE TITLE
Outdated with user URL

### ISSUE THREAD

**Issue by alberizo** [gorhill/uMatrix#774]
Hi guys. I'm was trying move my rules to a file on my hosting, but I´m having problems, it's looks a bug (or maybe I'm doing wrong).

I made this simple hosts file

![umatrix_file](https://cloud.githubusercontent.com/assets/1484680/25557870/233a9b58-2d1b-11e7-9528-cba0412e00f2.jpg)

And I added to umatrix hosts files list (The URL is OK)

![umatrix](https://cloud.githubusercontent.com/assets/1484680/25557885/49abc082-2d1b-11e7-858e-796e21e16490.jpg)

I click in Update button but nothing happend. No update and rules aren't working.
And now if I remove my URL from list and check any default host file always shown like outdated

![umatrix_final](https://cloud.githubusercontent.com/assets/1484680/25557895/87908e96-2d1b-11e7-85bc-a770874358f4.jpg)

I tried add manually to hosts-files.json and I created the folder with my file and path but browsers says the plugin is corrupted.

My enviroment:
Windows 7
Firefox 53.0 64 bits & Opera 44.0 (Same behaviour in two browsers)
uMatrix 0.9.3.0

**Comment by gorhill** [comment]
> I made this simple hosts file

That is not a valid [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)) format, these are uMatrix rules. uMatrix rules are not hosts file entries. You cannot load uMatrix rules from a remote resources, you have to import them in _My rules_.

**Comment by alberizo** [comment]
I get it, I'm stupid!! I thougth is like AdBlock system, because when you have lot of uMatrix rules is very hard the management of new add. It would be a cool feature or at least show an advice when you add it.
Thanks for response.
