### ISSUE TITLE
[Possible bug] Cannot unblock static.payserve.com

### ISSUE THREAD

**Issue by levicki** [gorhill/uMatrix#776]
I am not sure if I am doing something wrong, but I have this in my rules:

    * static.payserve.com image allow

But when I try to open this image:

    http://static.payserve.com/static_01/15000/15181/image_2_90_136.jpg

uMatrix is blocking it.

First time I attempted to open that image it told me that the domain `payserve.com` is blacklisted in Peter Lowe's Ad Server List (I checked and indeed there is `127.0.0.1 payserve.com` in there), and it offered me to whitelist `static.payserve.com` termporarily or permanently. I first tried termporarily, but it again prevented me from loading the image still offering to whitelist the sub-domain. I then whitelisted it permanently and now it is no longer offering whitelisting but it is still blocking it.

What is worse, I cannot find where this non-working exception is stored so I can remove it. In the logger window there is no clue as to why it is still being blocked. Any help is appreciated.

**Comment by gorhill** [comment]
When you enter the URL of an image in the address bar, the browser will load the image as a document first, so uMatrix is being told that a document from `static.payserve.com` is being requested, which means a `image` rule like `* static.payserve.com image allow` won't accomplish nothing. You will need to allow document type specifically if you want the image to load, while not blanket-allowing anything else from `static.payserve.com`:

    * static.payserve.com doc allow

> it offered me to whitelist `static.payserve.com` termporarily or permanently

There is no such thing in uMatrix, you are confusing with uBlock.

**Comment by levicki** [comment]
@gorhill 

My bad, forgot to mention that the images from `static.payserve.com` would not load even from the page they were on (possibly NSFW):

    http://mysexykittens.com/photo.php?slug=c17_freshfaces_696

Shouldn't the rule I had allowed that? I don't understand why it is still being blocked.

Thanks for explanation about doc filter though, wasn't aware of that at all.

**Comment by gorhill** [comment]
> the images from `static.payserve.com` would not load even from the page they were on 

Thumbnails at `http://mysexykittens.com/photo.php?slug=c17_freshfaces_696` load fine with your rule `* static.payserve.com image allow`. Something else was preventing them from loading.

**Comment by levicki** [comment]
Then it must be uBlock Origin, that is the only other thing I have that might be blocking it. But according to you I have added a permanent exception there... now I am confused.

**Comment by gorhill** [comment]
Disabling strict-blocking for `static.payserve.com` in uBO will not cause 3rd-party requests to `static.payserve.com` to be whitelisted.

Strict-blocking is only the blocking of the root document, nothing more. If you want 3rd-party requests to `static.payserve.com` to be allowed when visiting `mysexykittens.com`, you will need an exception filter to counter `payserve.com` in Peter Lowe's (just like you also needed an allow rule for uMatrix):

    @@||static.payserve.com^$image,domain=mysexykittens.com

Or make use of uBO dynamic filtering's `allow` rule:

    mysexykittens.com static.payserve.com * allow

A rare case where `allow` is useful -- the rule can be created by just locally "greening" `static.payserve.com` while on `mysexykittens.com`.

**Comment by levicki** [comment]
@gorhill 

Thanks for the detailed explanation. It would be really helpful if this could be made more clear in a respective uBlock Origin / uMatrix window which shows up when something is blocked.
