### ISSUE TITLE
Moving tab to new window allows everything from that tab

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#777]
After moving a tab to a new window on Firefox 52 uMatrix reports the current location as `blank:about-scheme` with everything set to allow.

After checking the logger I have also confirmed that after that websites are not filtered at all(i.e. requests that were filtered before the move are not filtered after.)

**Comment by gorhill** [comment]
Same for uBO: https://github.com/gorhill/uBlock/issues/1120

**Comment by gorhill** [comment]
Can't reproduce with the webext version of uMatrix.
