### ISSUE TITLE
Conflict with Tempermonkey in modifying "Content-Security-Policy"

### ISSUE THREAD

**Issue by VictorSu000** [gorhill/uMatrix#778]
uMatrix and Tempermonkey seem to work well so far, but an warning message pops up, which says "During network requests Tempermonkey can't modify "Content-Security-Policy" in response headers, because this modification conflicts with another extension uMatrix."

![image](https://cloud.githubusercontent.com/assets/18596923/25622743/080c1720-2f88-11e7-8fdc-e235c758184b.png)

**Comment by gorhill** [comment]
Browser limitation, only one extension can modify a header. You will have to pick which one you want to modify the header. Take note that uMatrix **never** make a CSP header **less** strict, it only makes them same or stricter. I believe Tampermonkey can potentially make the CSP header less strict. You will have to seek information with Tampermonkey authors.

**Comment by uBlock-user** [comment]
@VictorSu000 Open settings and set the settings page to Advanced mode, scroll down to the end and in Security category somewhere, there's a CSP setting, disable it.
