### ISSUE TITLE
Script info

### ISSUE THREAD

**Issue by CrisBRM** [gorhill/uMatrix#78]
Case in point: github's Content Delivery Network runs 2 scripts on a given webpage. Using µMatrix I am given no information regarding said scripts, but if I open [Chameleon](https://github.com/ghostwords/chameleon) I can make use of its [fingerprinting detection features](https://github.com/ghostwords/chameleon#coverage) and easily find out what they're doing or at least I will have more info to work with instead of having to block scripts blindly and see what works, which is exceptionally dangerous (as far as fingerprinting goes) on sites you're not familiar with or just don't trust.

![issue](https://cloud.githubusercontent.com/assets/9098352/5350615/a7a00d88-7f3f-11e4-85fa-686fd3e31697.png)

I would like your input on having each script display a list of things it's doing/accessing on mouse over.

**Comment by gorhill** [comment]
Kitchen sink syndrome.

uMatrix's primary purpose is to block/allow requests. Chameleon's primary purpose is to detect fingerprinting-like activity.

**Comment by CrisBRM** [comment]
What I meant is that uMatrix should present the user with tooltips regarding the location/name of the script, on mouse over, without having to resort to the network logger.

**Comment by gorhill** [comment]
Looks to me the dev console can do that job very well already, it shows the full URL of what is being blocked. What you are asking doesn't fit in the popup UI model, and I don't intend to change it.
