### ISSUE TITLE
uMatrix hang on opening in Chrome 64 bit version

### ISSUE THREAD

**Issue by johnswolter** [gorhill/uMatrix#780]
All pages I've been accessing appear to have the same issue.  uMatrix hangs when opening uMatrix using [Mouse-Left-Click] on the Chrome app icon.   

![image](https://cloud.githubusercontent.com/assets/497452/25715896/1ae5c596-30cb-11e7-89c9-415d6d51bf27.png)

This is new the last few weeks.  

Here's my Chrome & uMatrix information
Chrome Version: 58.0.3029.96 (64-bit)

uMatrix
![image](https://cloud.githubusercontent.com/assets/497452/25716023/9661c242-30cb-11e7-9ec8-1dd1a1823add.png)

Hope that gives you some clues.

Cheers

**Comment by gorhill** [comment]
Can't reproduce. You will have to investigate this on your side.
