### ISSUE TITLE
Youtube/Google one-tap 2FA does not work

### ISSUE THREAD

**Issue by thomasklash** [gorhill/uMatrix#783]
**Summary**
Upon signing in to YouTube, you are greeted with a 2FA prompt. An option for 2FA is the "one-tap" solution, which asks you to press "Yes" on your phone, and you are logged in.

**Expected result**
You are logged in to YouTube

**Actual result**
The prompt instantly times out, over and over"
![firefox_2017-05-12_16-49-54](https://cloud.githubusercontent.com/assets/14216632/25986660/2acd5c34-3734-11e7-975f-f393ec87a559.png)

**Platform details**
_**OS**_: Windows 7 64-bit
**_Browser_**: Fiirefox Nightly 55.0a1 (2017-05-10) (64-bit)
**_uMatrix_**: 1.0.1b0

**Other details**
I am certain this is uMatrix, as I have tried:
Firefox in safe-mode - works
Firefox with all other addons I have - works
Firefox with only uMatrix - does not work
Also, disable uMatrix using the "power" button does not fix it, neither does turning off all other functionality of it without disabling the addon.

**Comment by gorhill** [comment]
uMatrix blocks only what its ruleset tells it to block.

Did you look at the logger?

> neither does turning off all other functionality 

What "other functionality" **exactly**?

Most likely explanation is that your ruleset is causing you trouble, you will have to make more effort to rule out this -- read **carefully** the font page of the project and [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by thomasklash** [comment]
I said I tried disabling it using the power button, wouldn't that disable the ruleset?
By other functionality I meant referrer and user-agent spoofing.

**Comment by gorhill** [comment]
Again:

> Did you look at the logger?

**Comment by thomasklash** [comment]
Oh, I should have let you know that I can't test it anymore because I am locked out from that method of 2FA by Google for "a few hours".

**Comment by thomasklash** [comment]
![image](https://cloud.githubusercontent.com/assets/14216632/26000500/8c743be6-376c-11e7-847f-1bfc52f031d0.png)

**Comment by jjohns71** [comment]
FWIW I have no issue with Firefox 53.0.2 (Not nightly..) and uMatrix 1.0.1b0

@thomasklash I believe if you add the following rules to your 'My Rules' tab and commit them it should resolve your issue:

`google.com accounts.youtube.com frame allow`
`google.com accounts.youtube.com script allow`
`google.com content.googleapis.com script allow`
`google.com content.googleapis.com xhr allow`
`google.com gstatic.com script allow`
`google.com gstatic.com xhr allow`

**Comment by uBlock-user** [comment]
Whitelist all third-party domains on `youtube.com` for the time-being and see if it still happens, that will verify whether it's a ruleset issue or not.

**Comment by gorhill** [comment]
There is no need to try random stuff, it always come down to: Use. The. Logger.

All cases of ruleset getting in the would have been resolved with the logger, and selecting _"All"_ entries to also find out stuff blocked in other contexts. When I say the extension is for "advanced users", there is the implicit assumption that advanced users are those who will investigate using the tools at their disposalm and the logger is at the top of these tools.

I will be closing until there is a case actually made that uMatrix blocks stuff which it should not block, along with the supporting evidence. This is not the case here, since obviously the logger was never used.

**Comment by thomasklash** [comment]
Hi,

I used the logger :)

![image](https://cloud.githubusercontent.com/assets/14216632/26214280/25fdfb72-3c3f-11e7-82cd-2dcab11b4e6b.png)
