### ISSUE TITLE
The matrix scroll position gets reset on hover

### ISSUE THREAD

**Issue by jonnyrobbie** [gorhill/uMatrix#784]
Present in both 1.0.0 and 1.0.1b0 webext version Firefox nightly (several latest releases), Linux.

1. Load any site where there are so many rows in the matrix so umatrix has to show the vertical scrollbar.

2. Scroll down a bit,

3. Hover over the matrix.

The scroll gets reset to the home position. This makes it impossible to use umatrix on any sites where the number of rows is so big they hide under the scrollbar as I'm completely unable to make any changes to the matrix.

**Comment by jonnyrobbie** [comment]
Ok, I've tried to disable Classic Theme restorer. The scroll reset is no longer present, but on the other hand, the whole matrix looks messed up:

http://i.imgur.com/aSo368Z.png

**Comment by dangranos** [comment]
Can confirm this happening on Firefox Nightly 55.0a1 (2017-05-13). I don't have the "Classic Theme Restorer" installed but I'm using the "developer dark" theme, though.

**Comment by gorhill** [comment]
Browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1350077>.
