### ISSUE TITLE
Pale Moon: Umatrix icon in new toolbars make the toolbars a bit larger

### ISSUE THREAD

**Issue by geplus** [gorhill/uMatrix#786]
Hi, 
referring to #785

Browser: pale moon ;  OS: Linux

Steps for reproduce the issue:

1) Create a new toolbar in palemmon (right click near the address bar - customize - add toolbar)
2) Enable the new toolbar (right click near the address bar - flag the new toolbar you've created)
3) Try to put the uMatrix icon in the new toolbar: pay attention and you'll see thath the toolbar changes its dimesions, becoming a little larger than before

**Comment by gorhill** [comment]
> becoming a little larger than before

That's true for other icons too, this is not specific to uMatrix. If I put Pale Moon's own "Downloads" icon in there, the toolbar's height is also increased. If I then put uMatrix's icon, the toolbar height's stays the same -- meaning uMatrix does not behave any differently than other standard icons.

**Comment by geplus** [comment]
mmm... in my case the issue doesn't happens with the downloads icon.

I have the option "use small icons" enabled" , maybe the issue happens with this option enabled

**Comment by Atavic** [comment]
A general issue that was present for years.

**Comment by gorhill** [comment]
> "use small icons" enabled

Where is that option?

**Comment by Atavic** [comment]
By r-clicking on the browser GUI. Then choose customize.
