### ISSUE TITLE
UI glitching and flickering when hovering over items

### ISSUE THREAD

**Issue by bgiesing** [gorhill/uMatrix#788]
Browser: Chrome 60.0.3100.0 dev (64-bit)

Flags enabled:
```
--process-per-site --enable-browser-task-scheduler --bypass-app-banner-engagement-checks --enable-add-to-shelf --enable-appcontainer --enable-canvas-2d-dynamic-rendering-mode-switching --enable-display-list-2d-canvas --enable-experimental-canvas-features --enable-fast-unload --enable-google-branded-context-menu --enable-gpu-rasterization --enable-md-feedback --enable-nacl --enable-push-api-background-mode --enable-settings-window --enable-site-settings --enable-spelling-feedback-field-trial --enable-tab-audio-muting --enable-zero-copy --load-media-router-component-extension=1 --num-raster-threads=3 --secondary-ui-md --enable-smooth-scrolling --top-chrome-md=material --windows10-custom-titlebar --enable-features=BackgroundVideoTrackOptimization,DisplayPersistenceToggleInPermissionPrompts,ExpensiveBackgroundTimerThrottling,FeaturePolicy,FontCacheScaling,GdiTextPrinting,LoadingWithMojo,MaterialDesignBookmarks,MaterialDesignExtensions,MaterialDesignSettings,MediaRemoting,MemoryAblation,MemoryCoordinator,NewAudioRenderingMixingStrategy,NewOmniboxAnswerTypes,NewUsbBackend,NoStatePrefetch,OmniboxEntitySuggestions,OriginTrials,OverlayScrollbar,RunAllFlashInAllowMode,ScrollAnchoring,ServiceWorkerNavigationPreload,SpeculativeResourcePrefetching,TranslateLanguageByULP,TranslateUI2016Q2,WebRTC-H264WithOpenH264FFmpeg,ZeroSuggestRedirectToChrome,affiliation-based-matching,brotli-encoding,password-import-export --disable-features=PreferHtmlOverPlugins
```

OS: Windows 10 Fall Creators Update (Redstone 3) Insider Preview Build 16199.1000

When clicking the extension icon to open the panel, the UI completely glitches out making it really hard to use. When hovering over buttons, the glitch changes cropping off a different portion of the UI.

GIF of the glitch: https://gfycat.com/NegligibleRepulsiveIberianlynx

EDIT: Forgot uMatrix version: uMatrix 1.0.0

**Comment by gorhill** [comment]
Definitely not a uMatrix issue, report to browser devs.

**Comment by bgiesing** [comment]
I just tried with Chrome's hardware acceleration on (I usually have it off cause Intel driver issues) and it works fine so it's either a browser bug like you said or a problem with uMatrix and not having hardware acceleration.

Where do you report bugs to Chrome?

**Comment by uBlock-user** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=724811

It's patched in canary. Wait till the roll-out to other channels.

**Comment by uBlock-user** [comment]
Filed a new bug report which is reproducible - https://bugs.chromium.org/p/chromium/issues/detail?id=726974
