### ISSUE TITLE
Make placeholders in iframes clickable

### ISSUE THREAD

**Issue by emersion** [gorhill/uMatrix#789]
Commit 622d0a7e9dbd44c2d52d054829232fa3da18bf9d adds a placeholder in `<iframe>`.

It would be useful to make the placeholder clickable (`<a href="{{url}}" target="_blank" rel="noreferrer noopener">`) to be able to open pages on a case-by-case basis.

**Comment by gorhill** [comment]
It is, the link is the up arrow.

**Comment by emersion** [comment]
My bad. I didn't realize.

Is there a reason why the URL is not clickable, but only the arrow is?

**Comment by gorhill** [comment]
I can't remember why -- I am guessing I wanted to be sure people wouldn't click reflexively on the link, it had to be a conscious action.

**Comment by emersion** [comment]
Maybe it would make it more explict to replace the arrow by something like this: http://fontawesome.io/icon/external-link/

This is Wikipedia's one:
```
data:image/svg+xml,%3C%3Fxml version%3D"1.0" encoding%3D"UTF-8" standalone%3D"no"%3F%3E%3Csvg xmlns%3D"http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg" width%3D"12" height%3D"12"%3E%3Cpath fill%3D"%23fff" stroke%3D"%2306c" d%3D"M1.5 4.518h5.982V10.5H1.5z"%2F%3E%3Cpath d%3D"M5.765 1H11v5.39L9.427 7.937l-1.31-1.31L5.393 9.35l-2.69-2.688 2.81-2.808L4.2 2.544z" fill%3D"%2306f"%2F%3E%3Cpath d%3D"M9.995 2.004l.022 4.885L8.2 5.07 5.32 7.95 4.09 6.723l2.882-2.88-1.85-1.852z" fill%3D"%23fff"%2F%3E%3C%2Fsvg%3E
```

**Comment by leedoyle** [comment]
@emersion I find the arrow almost perfect, both noticeable when I look for it and not intrusive when I don't. Anyway, you are free to tweak it on your machine.

**Comment by gorhill** [comment]
> I can't remember why

Now I do, I will write it down before I forget again.

You might not necessarily want to navigate to the URL as is, sometimes you may want to use the URL but without the added cruft at the end. Not making the whole URL a link makes easy to copy only a specific part of the URL -- something annoying/difficult to do when the whole text is a link.
