### ISSUE TITLE
Excessive memory usage in Chrome x64 after adjusting rules on various sites

### ISSUE THREAD

**Issue by Nocturnalizer** [gorhill/uMatrix#79]
Hi,

I recently installed uMatrix and have been going to my most used sites to apply the right rules to them. After doing this for an hour or so I looked at Chrome's task manager and noticed that uMatrix is now using over 200MB of memory. I'm using the very latest version of Chrome 64-bit (39.0.2171.95) on Windows 8.1 x64. Is this sort of figure correct? I've done quite a few reloads of sites while adjusting the rules and domains so I was wondering if this would be why, but that seems like a lot of memory usage.

![capture](https://cloud.githubusercontent.com/assets/8000507/5372325/d70932a2-803e-11e4-93e0-2497475b2685.JPG)

**Comment by muse03** [comment]
This bug is non-existent on alt Chromium browsers Slimjet [Chromium version 40] and Opera 28 [Chromium version 41].

**Comment by gorhill** [comment]
> This bug is non-existent on alt Chromium browsers Slimjet [Chromium version 40] and Opera 28 

The bug is present in Opera 28. It's a blink engine bug.

Why the easy-to-verify false statement?

**Comment by muse03** [comment]
My mistake, Slimjet has an memory optimization setting which perhaps caused the low memory usage:

[url=http://imgur.com/pwcwg32][img]http://i.imgur.com/pwcwg32.png[/img][/url]
