### ISSUE TITLE
media vs plugin

### ISSUE THREAD

**Issue by gcb** [gorhill/uMatrix#791]
I just noticed that chrome version calls plugins 'Media' on the UI. Which sounds wrong. People are enabling flash and java thinking they are enabling html5 media elements. Or did i get this wrong?

I am assuming this behaviour from the only issue with those keywords: https://github.com/gorhill/uMatrix/issues/759

**Comment by gorhill** [comment]
It's explained in the [Release notes](https://github.com/gorhill/uMatrix/releases/tag/1.0.0).
