### ISSUE TITLE
video from Time.com is neither listed under MEDIA nor OTHER

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uMatrix#794]
is this expected behavior that the video at the top of this page is not listed in uMatrix's media and other column?

http://time.com/4793832/the-weight-loss-trap/

**Comment by gorhill** [comment]
It's not listed because there is no media served by the page.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Please use the logger before opening invalid issue -- that simple step would have saved time to you and me.
