### ISSUE TITLE
This add-on uses legacy technology

### ISSUE THREAD

**Issue by LIyoai** [gorhill/uMatrix#797]
On the Firefox website https://addons.mozilla.org/en-US/firefox/addon/umatrix/?src=ss there is a message "Please note this add-on uses legacy technology, which gives it access to all browser functions and data without requesting your permission."

Is it possible to update to "new" technology?

**Comment by byte-jra** [comment]
1) https://www.ghacks.net/2017/03/09/firefox-legacy-add-on-or-webextension-how-to-find-out/
2) https://github.com/gorhill/uMatrix/releases
3) all clear?


(webext.xpi isn't default in AMO)

**Comment by LIyoai** [comment]
Ok, thanks :-)
