### ISSUE TITLE
umatrix still interferes, albeit being turned off

### ISSUE THREAD

**Issue by lovetheguitar** [gorhill/uMatrix#806]
I don't know where I can check what umatrix is doing, but fact is, it breaks my ebanking website, even if I allow everything or turn it off completely.

Only thing to fix the websites functionality was to deactivate it in the extensions menu completely.

Using 62.0.3202.89 (Official Build) (64-bit) on Mac High Sierra
uMatrix 1.1.2

Will be happy to provide logs etc., just let me know.

**Comment by uBlock-user** [comment]
Disable referrer/useragent spoofing along with strict HTTPS and check if it still happens.

**Comment by leedoyle** [comment]
@lovetheguitar please check the logger (the black box button in the top right corner of the popup)

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
