### ISSUE TITLE
Cloud storage merge button broken

### ISSUE THREAD

**Issue by warnellw** [gorhill/uMatrix#807]
Hi there,

It appears one of the recent updates has broken the button used for pulling and merging rules from cloud storage (Chrome on Windows 10). Please see the screenshot below of uMatrix v1.1.2:

![button](https://user-images.githubusercontent.com/3211186/32702465-b5d92a3a-c7b5-11e7-8d71-056ce8d15267.JPG)

Thank you for creating and maintaining this excellent extension.

**Comment by gorhill** [comment]
I imported the code from uBO and forgot to remove the merge button, it's not supported in uMatrix.

**Comment by gorhill** [comment]
I was wrong, merging from cloud was supported, I just needed to import the modified CSS from uBO.
