### ISSUE TITLE
Popup UI displays network requests from previous loads even after subsequent refresh events

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uMatrix#809]
### Describe the issue

Popup UI displays network requests from previous loads even after subsequent refresh events.

### One or more specific URLs where the issue occurs

https://en.wikipedia.org/wiki/The_Good_Doctor_(TV_series)

### Screenshot in which the issue can be seen

Popup UI after a refresh - https://i.imgur.com/AFMI3hk.png

Logger UI after a refresh - https://i.imgur.com/MwsjV2X.png

### Steps for anyone to reproduce the issue

1) Keeping the uMatrix logger open, browse to https://en.wikipedia.org/wiki/The_Good_Doctor_(TV_series) and make sure all other tabs to this specific page are not open.

2) As this is the first load, all network requests fired for this event will be shown in the logger and in the Popup UI which are from domains `wikimedia.org` and `wikipedia.org` respectively. 

3) Now hit refresh and keep an eye on the logger and as you can see only network requests from `wikipedia.org` will appear as all resources from `wikimedia.org` were already loaded and cached so the network request was never fired this time, hence it will not appear in the logger either.

4) Now open the Popup UI and you will still see `*.wikimedia.org`  entry even though no network request was fired for this URL during the refresh event. 

### Expected result

Popup UI should only show a single entry from `wikipedia.org` on subsquent refresh events as resources from `wikimedia.org` are already loaded and cached, hence no network request was sent via Chrome.

### Actual result

Popup UI still shows `wikimedia.org`  entry even though no network requests was fired for this URL during the refresh event.

### Your settings

- OS/version: Win 10 Pro x64
- Browser/version: Chromium 64
- uMatrix version: 1.1.2

**Comment by gorhill** [comment]
By design.

**Comment by rjkpa** [comment]
but the same behavior is not present in uBO's popup UI, why ?

**Comment by gorhill** [comment]
I have created documentation for this: <https://github.com/gorhill/uMatrix/wiki/Lingering-domain-entries-in-the-matrix>.

**Comment by rjkpa** [comment]
Thank you, that does make sense for uMatrix's behavior.
