### ISSUE TITLE
incorrect behaviour on twitter affecting browser-wide shortcuts

### ISSUE THREAD

**Issue by leedoyle** [gorhill/uMatrix#810]
When visiting twitter.com with default uMatrix settings (with twimg.com blocked, it being a third party domain), browser hotkeys, e.g. Ctrl+F and Ctrl+D don't work. Allowing  scripts from **abs.twimg.com** (or twimg.com in general) solves the issue. I reproduced the bug on Firefox 55-56 on Linux (uMatrix 1.0.0 legacy), 
Chromium 61 on Linux w/ uMatrix Version 1.0.0 (the latest in Chrome Store) and Chromium 62.0.3202.89 (Official Build) Ubuntu build, uMatrix 1.1.2.
Steps to reproduce: 
- visit twitter.com with default settings (twimg.com should be blocked), e.g. this page https://twitter.com/AP
- try to make use of Chromium or Firefos browser shortcuts like ctrl+l, ctrl+d, ctrl+s and try page down/up button as well, on Firefox also try ctrl+shift+A and ctrl+R, on Chromium try ctrl+shift+o and ctrl+h.
Curiously enough, ctrl+t and ctrl+w will still work, and so would alt+f4 (at least in Firefox 56 and Chromium 62). Google cached twitter pages behave the same. 
Personally I wouldn't consider it a major issue, but who knows, maybe some bug that stands behind it could affect other websites as well. The reason I've reported it is that it's not the website that breaks, but browser behaviour.

P.S. RequestPolicyContinued and NoScript show the same behaviour with twimg.com blocked, where NoScript normally(that is by default) tackes the issue (when scripts from both twitter.com and twimg.com are blocked by default) by redirecting to the mobile version of the site.

**Comment by ArchangeGabriel** [comment]
As well as ytimg.com is third party on youtube, but AFAIR this one doesn’t work properly without this.

AFAIK that’s expected behaviour, you’re the one in charge of white-listing appropriate 3rd-party (in the sense of originating from another domain).

**Comment by ArchangeGabriel** [comment]
Though I’ve just seen your edit, and I’m more perplex now…

**Comment by leedoyle** [comment]
@ArchangeGabriel please pay attention to the description of the issue, not just the title. Supposing you were on youtube and blocked some domain, like ytimg, and this would cause your browser shortkeys (I'm not saying it will, let's just suppose) like ctrl+k, ctrl+s, ctrl+l, ctrl+d not to work - would you agree that'd be a bug?

**Comment by ArchangeGabriel** [comment]
I’ve read it (else I wouldn’t have noticed twimg.com for instance) but it’s only when you edited your title that I’ve realized you were talking of browser shortcut, not eventual twitter shortcuts.

**Comment by gorhill** [comment]
This is not a uMatrix issue, this is a site issue as a result of blocking stuff on it.

**Comment by leedoyle** [comment]
Right. Sorry for the inconvenience, it didn't seem obvious to me.

**Comment by ArchangeGabriel** [comment]
If you block scripts for the main domain, it works again too. I suspect they try to override Ctrl+F in some way.

**Comment by leedoyle** [comment]
@ArchangeGabriel and not just ctrl+f, but almost all browser shortcuts there is.
