### ISSUE TITLE
Scroll bar covers last menu section

### ISSUE THREAD

**Issue by spodermenpls** [gorhill/uMatrix#811]
Using uMatrix 1.1.0 on Firefox 57 64-bit, the scroll bar is still partially covering the last menu section ("Others"/"Andere" in German):

![umatrix](https://user-images.githubusercontent.com/23747593/32772255-99894380-c925-11e7-8055-b097c668bfa8.JPG)

**Comment by gorhill** [comment]
Browser bug, report to bugzillaplease. uBO-Scope is also afflicted by this. Chromium's versions are fine.

**Comment by gorhill** [comment]
I consider the isse related to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1309143

**Comment by ArchangeGabriel** [comment]
Now that I think about it, the real issue is more likely this: https://bugzilla.mozilla.org/show_bug.cgi?id=1147847
