### ISSUE TITLE
[Feature Request] Auto-Reload

### ISSUE THREAD

**Issue by DabeDotCom** [gorhill/uMatrix#813]
[BTW — I'm splitting this off of #691 because that conflated two unrelated issues...]

Anyway, I agree with @Goldich that, if the user made any changes, clicking off the settings dialog and back into the browser tab should automatically initiate a page refresh.

As a recent switcher from NoScript [Thanks, Firefox Quantum!] I keep stubbing my toe on the fact that uMatrix doesn't automatically reload the page when I click away from the popup menu.  (I can't tell you how many times today I've ended up sitting there looking like an idiot for ~3–4 seconds before I realized that it was waiting on **ME** to do something...)

Honestly, though, I can't really imagine a scenario where I'd want to enable scripts for a site but then *NOT* reload the page immediately afterwards...  (And, conversely, if I **DISABLE** a site, I _absolutely_ don't want the current, insecure instance to remain open anymore!)

At any rate, I haven't really dug into the source very deeply, but I see `dropDownMenuHide()` is already being called when `.dropdown-menu-capture` is clicked; and I'm guessing the logic to track changes would be similar to [`Matrix.prototype.diff`](https://github.com/gorhill/uMatrix/blob/ef09f42af8a44651044da91a51a20c1d0098ba58/src/js/matrix.js#L853) (only with an even *more* temporary list of changes...)

Worst case, this auto-reload behavior *could* be made configurable with a Feature Flag / User Preference...

Thanks!!  :-D

**Comment by DabeDotCom** [comment]
I see you already **had** all this, but removed it in be3e86e055f05e80bdc7c98804e9c2cb1a616872.

Sorry to salt an old wound...  :-}

**Comment by ruv** [comment]
What was the reason to remove auto-reload option?
