### ISSUE TITLE
Certain Sites Won't Load Completely

### ISSUE THREAD

**Issue by Pulusha** [gorhill/uMatrix#816]
Since updating to version 1.1.0 (and above), I’ve noticed certain sites won’t load completely (examples: www.origin.com | www.virustotal.com) even after allowing the necessary domains and reloading the page.

The workaround that I’ve found is to clear all of Firefox’s history/data, after allowing the required domains in uMatrix, and then reload the page for it to display.

I have all domains blocked by default, by the way.

uMatrix 1.1.4
Firefox 57 (x64)
Windows 10 (x64)

**Comment by gorhill** [comment]
> The workaround that I’ve found is to clear all of Firefox’s history/data

You did not provide **exact** repro steps.

Shift-click the browser reload button when you have such issues, the browser is probably using its in-memory cache and bypassing uMatrix's handlers.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
