### ISSUE TITLE
Firefox quantum - frames still blocked after pressing umatrix reload button

### ISSUE THREAD

**Issue by Anden** [gorhill/uMatrix#819]
Hi,

With the new Firefox Quantum (57.0) it looks like the behaviour for the uMatrix reload button has changed. Before it would bypass the cache, which is needed to display any previously blocked iframes. With Firefox Quantum it does not bypass the cache.
This actually works on chromium, so it looks like there are some differences in how Firefox and Chromium caches iframes.

Example reproducer:
1. Go to http://jsfiddle.net/e4pf3ghu/
2. Allow everything for first party, and frames from everywhere
3. Press the uMatrix reload button

Expected result:
The iframes are shown

Actual result:
The iframes are still blocked

Workaround:
Force a full reload with ctrl-f5, or shift clicking the Firefox reload button.

I suspect changing [platform/chromium/vapi-background.js:349](https://github.com/gorhill/uMatrix/blob/master/platform/chromium/vapi-background.js#L349) to ``chrome.tabs.reload(tabId, true);`` would fix it (where true is bypass cache).

**Comment by gorhill** [comment]
There is a cost to bypass the cache, I want this to be an explicit choice by the user.

**Comment by gorhill** [comment]
Ok, the reload button in the popup will take into account the shift key to bypass the cache, just like the browser's own reload button.

**Comment by Anden** [comment]
You mentioned in your commit that it is _sometimes_ necessary to do a full reload, do you know more exactly when it is necessary? I know how you feel about wasting your time, so if you don't know I'll run some tests myself.

In any case, thanks for the quick response and for your great add-ons!

**Comment by gorhill** [comment]
It depends of the browser cache -- that's something which can't be predicted. For example, you may decide to block images after loading a page, and a reload may cause the image to still display, because sometimes they are still in the short-term memory cache. Another time you may go back in history and the page barely report any network traffic because it's all served from browser cache, bypassing the webRequest API.

**Comment by Anden** [comment]
Ok, thanks a lot!
