### ISSUE TITLE
Heads up, having issues with uMatrix ignoring some rules, and blocking things, even if filtering is disabled, in latest FF beta build.

### ISSUE THREAD

**Issue by BradensPCs** [gorhill/uMatrix#820]
In Fifrefox 58.0b4, a video via embedy.me was not loading. Allowing embedy.me in uMatrix did not work, disabling filtering for the scope did not work, only disabling uMatrix entirely worked, but even then it was acting goofy, possibly partly an issue in FF. I installed FF 57 over the beta installation and then everything was fine. Just a heads up in case this info helps head off a future issue.

**Comment by anewuser** [comment]
https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
