### ISSUE TITLE
I can't make rules with *.githubusercontent.com

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uMatrix#831]
uMatrix 1.1.10
Firefox 57.0

I can't make rules with `*.githubusercontent.com` through the umatrix interface.
And with the some other domains too. But I don't remember which ones.

![umatrix_report](https://user-images.githubusercontent.com/15322618/33164681-1b91604e-d05e-11e7-83f6-3c6aaf468298.png)

I have this rule `github.com githubusercontent.com image allow` but I made it manually.

Also when I am pressing `the PrintScreen key` on my keyboard, the umatrix panel is quickly disappearing.

**Comment by benoit-pierre** [comment]
Dupplicate of #155: `avatars0.githubusercontent.com` is a root domain.

**Comment by jhsagl4a** [comment]
ok
