### ISSUE TITLE
What is "other"?

### ISSUE THREAD

**Issue by T-vK** [gorhill/uMatrix#832]
I couldn't find any mention of it in the Readme or in the Wiki.  
The `httpswitchboard` Readme only says `<video>, <audio>, etc.`.   

But isn't that what `media` already does?  What is `etc.` supposed to mean?  
Is it simply every content-type not covered by image, css, media and script? Would that mean that an XHR request for json or xml would be blocked by the setting? And what about websocket and web-rtc? 

I also don't quite understand when the decision on what kind of data it is is made and what is actually being blocked. E.g. does it just look for the file extension and request headers and the block the request or does it scan the response headers and then block the response?

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

> 
For **support/discussions**, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-umatrix/5131).

**Comment by elypter** [comment]
to be fair it is a bug because the wiki is missing this info

**Comment by gorhill** [comment]
I am still working on that wiki page, but the part which answers the question here is in there now: <https://github.com/gorhill/uMatrix/wiki/The-popup-panel#the-type-cells>.

Sorry for having been dismissive.
