### ISSUE TITLE
gray uMatrix dashboard

### ISSUE THREAD

**Issue by waterwood2017** [gorhill/uMatrix#835]
why is my uMatrix dashboard gray after 10 minutes and the pages are not working anymore. even if I reload it without closing the browser. When I close the browser and open it all goes for 10 minutes.

windows 10
firefox 57

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Could be your anti-virus interfering? In any case, something on your side is interfering with your Firefox. You are best placed to investigate this on your side.
