### ISSUE TITLE
Icon missing from the toolbar

### ISSUE THREAD

**Issue by RobertVisser** [gorhill/uMatrix#836]
Raymond, Hi. Happy Thanksgiving. On Firefox Developer Edition v58.0b1 with the update to uMatrix 1.1.11b0 I've lost the uMatrix icon in the toolbar. In addition since I'm now seeing ads which I hadn't before, I suspect uMatrix isn't active. I did check my prefs. It says it's active. Any thoughts? Thanks. Rob

**Comment by gorhill** [comment]
The browser is responsible for the icon in the toolbar, and to enable/disable extension. Please bring this issue to Firefox support.
