### ISSUE TITLE
unable to select/list scope in uMatrix drop-down in Chromium Version 62.0.3202.94 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (32-bit)

### ISSUE THREAD

**Issue by foo4thought** [gorhill/uMatrix#842]
unable to view/navigate/select different scopes in uMatrix 1.1.10 in Chromium Version 62.0.3202.94 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (32-bit) 

instead of normal/expected behavior to show global, top-level and/or sub-domains, no list is generated and instead, horizontal sub-sections of the now-displayed domain appear to be selected.

this also happens with uMatrix 1.1.10 on Firefox 57 on the same system, so may be specific to this Ubuntu build.

**Comment by foo4thought** [comment]
![screenshot from 2017-11-24 19-38-46](https://user-images.githubusercontent.com/516505/33226001-8a22b312-d150-11e7-9d58-ee70679dd49b.png)
was supposed to be part of the original submission

**Comment by gorhill** [comment]
I just tried and it works fine.

Not sure what you are reporting: when you click on `github.`, the scope does not become `github.com`?

**Comment by ravenise** [comment]
I am having the exact same problem in windows 7 in firefox 57!

![umatrix](https://user-images.githubusercontent.com/7063611/33228869-ffab07ec-d178-11e7-8630-2d8c98f07c6b.png)

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/33230289-6d441da4-d1ae-11e7-8094-f64130da4e4f.png)<br><sup>Just click the proper hostname label to select various scopes.</sup>

**Comment by ArchangeGabriel** [comment]
@foo4thought @ravenise That’s the new UI for the scope selector. ;)
