### ISSUE TITLE
unable to select list scope / global in uMatrix drop-down in FireFox 57 64bit (windows 7)

### ISSUE THREAD

**Issue by ravenise** [gorhill/uMatrix#844]
instead of normal/expected behavior to show global, top-level and/or sub-domains, no list is generated and instead, horizontal sub-sections of the now-displayed domain appear to be selected.

This has also been reported in Ubuntu in both Firefox and Chromium browsers.

![umatrix](https://user-images.githubusercontent.com/7063611/33228895-55ce8aea-d179-11e7-83ee-407bf02ba4d6.png)

**Comment by ravenise** [comment]
Note the new asterix beside the dropdown in the latest version of uMatrix; perhaps I am missing something; perhaps one must hit the new asterix and click "all." Not sure; they have not updated the global section of the user guide however; they still show the old drop down menu there.

**Comment by Havokdan** [comment]
Maybe: https://github.com/gorhill/uMatrix/wiki/Scope-selector
?

**Comment by theDuckIsAlive** [comment]
The scope selector is now clickable.

you can click on it to select the sub-domain, domain or the tld. 
or you can set the `global scope` by clicking the [ * ] icon on a Menu-Bar.

```
addons.mozilla.org
       mozilla.org
              .org
                 *
```


sub-domain  `addons.mozilla.org`
![um1](https://user-images.githubusercontent.com/19785040/33229401-ee38fad0-d1c5-11e7-9599-3fa4af9295ff.png)


domain             ` mozilla.org`
![um2](https://user-images.githubusercontent.com/19785040/33229388-9c7e27d8-d1c5-11e7-9865-ac07c8385424.png)


tld                       ` .org`
![um3](https://user-images.githubusercontent.com/19785040/33229406-0874ea30-d1c6-11e7-9b1d-bebc38314ad4.png)



global-scope `*`
![um4](https://user-images.githubusercontent.com/19785040/33229409-138c5afc-d1c6-11e7-9bc5-ec162b991cd2.png)


 



for futher information please reffer to:
https://github.com/gorhill/uMatrix/wiki/The-popup-panel

**Comment by Thorin-Oakenpants** [comment]
... just wiped all my typing ... theDuckIsAlive **just** beat me to it

**Comment by gorhill** [comment]
Read the release notes please.

**Comment by gorhill** [comment]
Also @ravenise, there was no reason for you to open the issue here, you were aware of the [exact duplicate to this one](https://github.com/gorhill/uMatrix/issues/842) since [you commented in it](https://github.com/gorhill/uMatrix/issues/842#issuecomment-346927080) a few minutes prior to opening this one.
