### ISSUE TITLE
Selected tab not highlighted in logger as per uBlock

### ISSUE THREAD

**Issue by pwd-github** [gorhill/uMatrix#845]
When you select the logger in uMatrix, it doesn't highlight the current (or last tab) like uBlock does.

1: Open a tab
2: Click the uMatrix icon
3: Click the logger icon
4: See that the last tab wasn't selected in the tab drop down as per is the default (and superior) behaviour in uBlock

**Comment by gorhill** [comment]
I will add the ability to choose to open the logger as a popup window at the same time.

**Comment by gorhill** [comment]
Duplicate of #539.
