### ISSUE TITLE
Minor UI Issues (Low Priority)

### ISSUE THREAD

**Issue by ShaunLeeClarke** [gorhill/uMatrix#847]
First of all, LOVE the extension. Switched from NoScript after upgrading to Firefox 57.0 and haven't wanted to switch back!

Just some small, minor and probably easy to fix UI issues.

First of all if you have a long list of items and a scrollbar appears, the width doesn't increase to accommodate this so part of the "others" section is mostly obscured by the scrollbar.

I also found if I have a website with content from a really long domain name, the domain name text will appear beyond it's cell and behind and in between the red/green cells.

Screenshot attached showing both.

Lastly, not sure if it's intentional, but I find it odd that text is selectable within the window - but that could be by design.

Hope this helps :).

![reallytemp](https://user-images.githubusercontent.com/33991768/33235880-58384478-d297-11e7-8f93-6a33d119e5e8.png)

**Comment by ArchangeGabriel** [comment]
See https://github.com/gorhill/uMatrix/issues/182 for the second issue. I can confirm the scroll-bar issue, one website that exhibits this is http://www.frandroid.com.

**Comment by gorhill** [comment]
The scrollbar issue is a browser bug, it does not occur with chromium, and it also occurs with other extensions in instances for which no scrollbats should be shown at all and yet they are.

See #811.

@ShaunLeeClarke, just to be sure... I usually advise to not go full granular like I see in your screenshot, but rather keep that level of granularity for only when it's necessary.

See <https://github.com/gorhill/uMatrix/wiki/The-popup-panel#the-destination--type-cells>.

In the end it's up to you, I just want to be sure it's a deliberate choice, not that you thought you _had_ to set your rules this way.

**Comment by gorhill** [comment]
> I find it odd that text is selectable within the window

What text specifically? There is an issue opened in here somewhere which asks to be able to select the hostnames in the matrix, it's currently not possible.

**Comment by ShaunLeeClarke** [comment]
If you click and drag in the uMatrix window, it is possible to select text just as if it was a standard HTML page, which seems undesirable in what I feel should act more like an application than a webpage. Can attach a screenshot if you can't reproduce.

**Comment by gorhill** [comment]
Well, extensions are now HTML documents. If I click in the background of the popup panel and press click and move the mouse, yes, I can select text in there.

**Comment by gorhill** [comment]
If I add `user-select: none;` to the `body` element, it's not possible to select anymore.

**Comment by ShaunLeeClarke** [comment]
:)

**Comment by ShaunLeeClarke** [comment]
> @ShaunLeeClarke, just to be sure... I usually advise to not go full granular like I see in your screenshot, but rather keep that level of granularity for only when it's necessary.

I'm with you. I think I just started out this way, I don't mind. Interesting to see all the parts that make up a page :).

**Comment by h1z1** [comment]
Been going NUTS over this.  The only time I've run into this is in Chromium! (despite @gorhill above).  Interestingly enough if I do an inspection, I can restore temporarily by disabling justify-content in #toolbarContainer.   It moves the revert icon over

**Comment by popveneer** [comment]
I can confirm the same issue in Firefox 57.0.3 (64-bit), UMatrix1.2.0:
![image](https://user-images.githubusercontent.com/35353069/34854025-bd9e801e-f6fc-11e7-9e78-aeedc6cdb57e.png)

Interestingly the scroll bars appear for both horz and vert and are usable but disappear immediately when  the uMatrix hovered over.  The issue has affected me for at least the last year though and is intermittent.

Hope that's helpful or at least cathartic.  It sounds like it's all in the browser unfortunately.

**Comment by Cerberus-tm** [comment]
As to text being selectable, I hope that doesn't change! As mentioned, being able to select hosts can be highly useful in certain scenarios.

**Comment by h1z1** [comment]
Played with this again, won't claim to know the backends of uM nor that what I'm seeing is related to this.    It appears though that changing the minimum displayTextSize in dashboard.html from 12 to 10, allows one to drop the font sufficiently enough that no clipping occurs.   Whether that is the best way I don't know.

@gorhill was the intent of that feature meant to adjust scroll bars on the dashboard as well?  They don't appear for me unless I make other changes to the css in popup.

**Comment by kavenstein** [comment]
Firefox 58.0.2 (64-bit) on xubuntu linux 16.04:
Two behaviors:
1. When the UMatrix icon appears on the toolbar to the right of the address bar, clicking on it results in expected behavior with all UMatrix elements visible and selectable. All good!

2. When the firefox window is resized horizontally (to make it narrower) until the UMatrix icon is no longer visible and replaced by a >> button, then clicking the >> button to expose the UMatrix icon and clicking the UMatrix icon causes Umatrix to display its window with controls showing on the left 2/3 and masked out on the right 1/3 of the window.



![exposed](https://user-images.githubusercontent.com/36827355/36647642-ae060a96-1a3d-11e8-8a64-81e178b76e2e.jpg)
![cropped](https://user-images.githubusercontent.com/36827355/36647644-bd226718-1a3d-11e8-9f01-81a5eaf88208.jpg)

**Comment by Alpengreis** [comment]
@gorhill 
> The scrollbar issue is a browser bug, it does not occur with chromium, and it also occurs with other extensions in instances for which no scrollbars should be shown at all and yet they are.

Okay, it's a browser bug, but how awesome would it be if you could support us Firefox users nevertheless with a workaround till the browser bug is away at some day hopefully? It's really annoying ...
