### ISSUE TITLE
hosts subdomain whitelisting

### ISSUE THREAD

**Issue by tyngdekraften** [gorhill/uMatrix#848]
hphosts flags proxad.net as ad tracking server
the ftp.proxad.net subdomain is not an ad tracking server
hphosts do not whitelist this subdomain
umatrix allows me to whitelist this subdomain
umatrix do not come with a whitelist like ublock filters do
is this considered an hphosts issue for not whitelisting the subdomain?
is this considered an umatrix issue for not whitelisting at all?
is this considered wontfix as the hosts file is not supposed to consider subdomains?

**Comment by ArchangeGabriel** [comment]
uMatrix is not responsible for error in the shared rules files AFAIK. You should report to hphosts instead I think.

**Comment by gorhill** [comment]
By design, a block rule for a domain propagates to subdomains -- as opposed to when the hosts file is used in a OS. Hosts files do not support whitelisting.

I don't plan to support pre-whitelisted hostnames in uBO, this is for users to decide.

**Comment by gorhill** [comment]
> umatrix allows me to whitelist this subdomain

You do not need to whitelist, just remove the block rules from the matrix UI. Internally, that would be `* ftp.proxad.net * inherit`.
