### ISSUE TITLE
[offtopic] contact info

### ISSUE THREAD

**Issue by vrobolab** [gorhill/uMatrix#850]
@gorhill  please provide your contact information, preferrably jabber or email, IRC will suffice too. 
I want you to develop a plugin (extension) for Firefox, but do not want to disclose all the information publicly yet. Of cource, the plugin will be free and open source.
My budget is big, as well as your future impact on everyone's security.

**Comment by gorhill** [comment]
Sorry, I don't want to be contacted for such demands, that's why I don't provide contact info. These are hobbies, I don't intend for these projects to be more than this.

**Comment by vrobolab** [comment]
Let it be one more hobby, I do not force you to sign any contracts and work full-time. However you could make Firefox users more secure and will earn some good cash. For my plugin a deep understanding of how Firefox works is needed, because plugin must intercept and block network requests on the low-level, and I believe you are the optimal candidate for such task as your plugins work in similar way.
Let me show you the concept and you will decide if you are interested or not.
You could give me some temporary email, e.g. from 10minutemail.com

**Comment by gorhill** [comment]
Why does it have to be discussed out of public eye? I prefer these things are talked about openly. If in the end it's to serve users' interests, it's only natural to talk about this publicly.

**Comment by vrobolab** [comment]
Because I am paranoid and I do not want big brothers such as Mozilla Corporation know about my involvement in this extension :) 
I still do not believe in their good intentions of creating the thing I want to fight with this extension.
