### ISSUE TITLE
Domain grouping inconsistent

### ISSUE THREAD

**Issue by Certary** [gorhill/uMatrix#851]
Sometimes domains and their subdomains are grouped together like in this example with gstatic.com:
![grouping](https://user-images.githubusercontent.com/8588987/33283193-59dffa7c-d3ab-11e7-92a8-3434ffacdd4c.png)

But other times they aren't grouped like in this example with githubusercontent.com:
![no grouping](https://user-images.githubusercontent.com/8588987/33283597-9b732b98-d3ac-11e7-8597-5f36faf34d46.png)

Making them group consistently would not only help save clicks when blocking/allowing a whole domain but would also enable you to block/allow a domains with load balancer as can be seen in the example with githubusercontent.com.

**Comment by gorhill** [comment]
By design. The matrix is made of 4 distinct sections, in order from top to bottom:

- First party
- Whitelisted
- Domains with no rules
- Blacklisted

**Comment by ArchangeGabriel** [comment]
@gorhill That’s not the correct answer. ;)
@Certary The correct answer is duplicate of #831 (and in turn of #155 and #54).

**Comment by gorhill** [comment]
Oh that's right, I went strictly by the title, and read diagonally for the rest. Sorry.

@ArchangeGabriel is right, duplicate.

**Comment by Certary** [comment]
Thanks for the quick responses! And sorry for not finding the existing issues ;)
@gorhill The link you're providing in your response to #54 is broken.
