### ISSUE TITLE
pronunciation clarification

### ISSUE THREAD

**Issue by micah** [gorhill/uMatrix#854]
Hi,

A simple 'issue' - I'm just wondering how you pronounce uMatrix. Some people call it 'you matrix', but the small 'u' makes me wonder if its supposed to be 'micro matrix'.

Since you are the author, you should be able to decide! I could not find the information anywhere 😺

**Comment by gorhill** [comment]
Please let's stick to actual issue as requested in CONTRIBUTING.

People can pronounce it as they wish.

**Comment by anarcat** [comment]
FWIW, i wish to pronounce it "you-matrix". :p "micro-matrix" is just silly, especially on large sites where the matrix becomes too big... ;)

(sorry for the noise, i couldn't resist)

**Comment by micah** [comment]
Alright, but I was wondering how **you** pronounce it.  After all, I don't want to have a 'GIF' situation on our hands.

**Comment by micah** [comment]
i stick with 'um, a tricks' thank you very much.
