### ISSUE TITLE
Minor UI issue (Chrome)

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uMatrix#856]
I use Chrome Beta 63.0.3239.59 on Win 10 1709, both 64-bit with uMatrix 1.1.12.

Today I saw this minor UI problem:
![truncated-umatrix](https://user-images.githubusercontent.com/11355601/33347554-89680df0-d493-11e7-91a7-42e364989bf4.png)
As you can see is the last "cell line" a bit truncated.
It's REALLY a minor issue, nevertheless it's not really right ...

**Comment by gorhill** [comment]
Unable to reproduce.

**Comment by gorhill** [comment]
Really, I think you are not just scrolling completely to the bottom.

**Comment by Alpengreis** [comment]
URL is: https://www.conrad.ch/de/ekastu-sekur-atemschutzmaske-mandil-412-183-filterklasseschutzstufe-ffp3v-5-st-831756.html

Here a better screenshot, I am definitely at bottom ...
![truncated_umatrix](https://user-images.githubusercontent.com/11355601/33348730-c2989cf8-d497-11e7-8d1a-00031feae703.JPG)
Filterlists: ALL default filter lists.

**Comment by gorhill** [comment]
Sorry, can't reproduce. You will have to investigate yourself about why you suffer the issue since I can't reproduce:

![a](https://user-images.githubusercontent.com/585534/33350105-1d96e60a-d46b-11e7-80cd-61f87141e3f9.png)

**Comment by Alpengreis** [comment]
Thank you. I have even a wider scrollbar too ... I know such things are difficult to handle (each system is a bit different, etc). I'll try to find out why I have this here ... could be a dpi setting, graphic card driver thing, font thing, or or ...
Just one question: you have tried with actual chrome BETA too I assume?!

**Comment by Alpengreis** [comment]
JFI: it SEEMS, here is only the expanded part of matrix "affected".

If I change this ...

<div class="matSection" data-expandos="233">

... into this ...

<div class="matSection" data-expandos="233" style="
    height: 56px;
">

all is good HERE.

If no explicite value of height is set there it takes the value 52px.

**Comment by Alpengreis** [comment]
JFI: it SEEMS, here is only the expanded part of matrix "affected".

If I change this ...

`<div class="matSection" data-expandos="233">`

... into this ...

`<div class="matSection" data-expandos="233" style="
    height: 56px;
">`

all is good HERE.

If no explicite value of height is set there it takes the value 52px.

**Comment by gorhill** [comment]
Your browser is supposed to properly compute the height which is needed, there is no need to resort to hardcoded values.

**Comment by uBlock-user** [comment]
I'm on Chromium 64, can't reproduce.
