### ISSUE TITLE
uMatrix not blocking everything (including doc requests) when it should?

### ISSUE THREAD

**Issue by stolenbowtie** [gorhill/uMatrix#858]
When I visit any website and turn the 1st party domain cell to light red it will not block text from the site. However, when I click again to make it dark red, uMatrix does block the root doc request and a message is displayed that loading of the site was prevented.
This means that there is a difference in blocking policy between light red and dark red cells (at least for 1-st party site requests, where I could verify this behaviour).
Does the difference between dark red / light red also hold for 3rd party requests? And does this mean I have to dark-red-click a lot of cells when I want to make sure that a 3rd party site never receives any requests at all (be it script, image, etc., or even simple text / root document requests) because light red is not sufficient to block, e.g., doc requests?
As a workaround I had the idea to add the following two rules to my permanent rules set
"* * doc block"
"* 1st-party doc allow"
Will this work? How do I controll the doc requests in the matrix?
(B.t.w.: After adding these two rules I realized that even dark red clicking the 1-st party cell in the innermost scope of any website does no longer block the doc request, so "* 1st-party doc allow" seems to dominate the stricter "[specialURL] 1st-party doc block" rule. Assuming that dark-red clicking a left-most cell toggles the doc request policy, doesn't this conflict with the rules propagation principles?)

**Comment by gorhill** [comment]
This is not an issue, this is a question. I do ask to not burden the issue tracker with support issue.

I have close the issue tracker in the past because of this burden.

Remove `* * doc allow` if you want root document to be blocked like other resources.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/wiki/How-to-have-root-documents-blocked-by-default-everywhere
