### ISSUE TITLE
firefox-esr - only old umatrix 1.0.0 - do not delete cookies

### ISSUE THREAD

**Issue by frank-github** [gorhill/uMatrix#859]
no other, never version available for firefox-esr? Do I have to use 1.0.0 until firefox-esr will switch to new API-version firefox?

I want to delete session cookies after 30min not used anymore, but seems umatrix do not delete cookies anytime. Only restart of firefox will delete them :-(
Known bug of old version? Something wrong with firefox-esr and umatrix?

Frank

**Comment by gorhill** [comment]
I don't maintain legacy version anymore.

Someone will have to step up to maintain the legacy version.
