### ISSUE TITLE
MVPS Hosts file wont update to latest version

### ISSUE THREAD

**Issue by JimDop** [gorhill/uMatrix#860]
All the Host file lists are showing as **outdated**, even when a forced reload is done.

 Example:
 http://winhelp2002.mvps.org/hosts.htm

  Umatrix only loads an old version dated Sep 15,2017 when the actual latest is Today 11/30 !!

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by JimDop** [comment]
I tested Umatrix on a clean profile, and it seems to load the latest  MVPS file.

So what is blocking the loads on my normal profile, which was only recently created in honor of the FF 57 release?

**Comment by gorhill** [comment]
1. MVPS was updated by the maintainer(s) on Nov. 30 -- the last update had been on Sep 15. There was no issue at all.

2. Now you report an issue with your own ruleset blocking behind-the-scene network requests. It's your own doing, there is a `matrix-off: behind-the-scene true` in out of the box ruleset. You removed it. There are consequences doing so.
