### ISSUE TITLE
"Delete non-blocked session cookies" deletes them for disabled scope

### ISSUE THREAD

**Issue by t33rex** [gorhill/uMatrix#867]
From user viewpoint it makes more sense the site cookies not to be affected by uMatrix if it is set to off for the site scope.

Example where this may be useful: I have some locally installed web applications (on a local web server). I need to re-login to them although uMatrix is turned off for them. This causes inconvenience.

**Comment by gorhill** [comment]
This is already the case.

You will need to provide repro steps as asked from you in CONTRIBUTING.

I will reopen if you make the case as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Actually, trying to understand your issue, I realize you are asking me to make the feature do make the opposite of what it says it does.

**Comment by t33rex** [comment]
The STR is:

1. Install http://www.kimai.org/ on a local web server
2. Set uMatrix to Delete non-blocked session cookies after N minutes.
3. Log-in to kimai and disable uMatrix for its scope and refresh the page
4. Wait N minutes
5. Refresh kimai

Expected: user should stay logged in
Actual: user is logged out (cookies auto deleted)
