### ISSUE TITLE
Page about:addons isn't block as expected

### ISSUE THREAD

**Issue by WagnerGMD** [gorhill/uMatrix#868]
```
* * * block
* 1st-party css allow
* 1st-party image allow
```
Hello,

at first you should remove the page **about:addons** from the whitelist.  As reminder, once it's done uMatrix is supposed to block everything.
Then just reload it.
What do you see ? The addon catalogue is still there, right ?
This trouble seem to exist only with the uMatrix WebExtension.  Because it's contrary with the uMatrix Legacy (also known as uMatrix.firefox.xpi)

Kind regards.

**Comment by gorhill** [comment]
`about:addons` is a priviledged page, webext extensions do not work on these.

**Comment by theWalkingDuck** [comment]
That priviledged page uses Google-Analytics and the best thing you can do is to remove the link to AMO site or to remove the whole "Get Add-ons" panel.

Steps to remove the Get Add-ons panel:

- open `about:config`
- search for  `extensions.webservice.discoverURL`
- remove the URL (set the value to empty string)

or you can go a step forward and remove the whole panel

- create a new boolean preference `extensions.getAddons.showPane`
- and set it to `false`

more info at:
	https://github.com/ghacksuserjs
```
ghacks-user.js
	user_pref("extensions.getAddons.showPane", false); // hidden pref
	user_pref("extensions.webservice.discoverURL", "");
```

**Comment by WagnerGMD** [comment]
Thank you for the explanation @gorhill and for the solution @theWalkingDuck which seeem's to work fine and no I wasn't aware.
