### ISSUE TITLE
uMatrix 1.1.13rc0 Referrer Spoofing enable/disable option still appearing on uMatrix Popup panel

### ISSUE THREAD

**Issue by jjohns71** [gorhill/uMatrix#869]
Using latest uMatrix 1.1.13rc0 the Referrer agent spoofing setting for on/off is still visible on the popup panel even though the functionality has been removed elsewhere in uMatrix.

"Disabled":
![frame01](https://user-images.githubusercontent.com/6795795/33559447-cd59704e-d8da-11e7-9254-1cbf328dbac8.png)

"Enabled":
![frame02](https://user-images.githubusercontent.com/6795795/33559448-cd664274-d8da-11e7-8733-37c85a6b7f9d.png)

The option seems to now be a dead button and changes no actual settings but visually should probably be removed to avoid user confusion.

**Comment by gorhill** [comment]
Referrer spoofing has not been removed, user agent spoofing has been removed.
