### ISSUE TITLE
Blacklist/Whitelist missing

### ISSUE THREAD

**Issue by jankkm** [gorhill/uMatrix#87]
I just switched from HTTPSB to uMatrix and it feels really good so far. I'm only missing the option to blacklist (and also to whitelist) hostnames.
There are several hosts that I really don't want to connect to. ever. and in HTTPSB I put them on the blacklist. Now I had to create a hosts file that I put on a private server and added it to the hosts files in uMatrix. This is kind of a work around and not very convenient.
I don't really get why those lists got ditched in uMatrix. Maybe I just don't get it so I would be very thankful for an explanation.

**Comment by m-j-r** [comment]
I kind of agree with this request - what I would like is to be able to right-click on a item in the matrix and select 'block globally' or 'allow globally', not affecting the 2 options currently available to modify the the current scope.

A particular example would be to allow script requests from jquery.com

**Comment by sogen** [comment]
+1, how do I whitelist jquery.com??

**Comment by gorhill** [comment]
`* jquery.com * allow`

From the UI, you have to select global scope `*`, then allow `jquery.com` domain, then persist rule by clicking on padlock.

**Comment by sogen** [comment]
Thanks!
