### ISSUE TITLE
NOT A BUG: I just wanted to say thank you Raymond Hill

### ISSUE THREAD

**Issue by fredddii** [gorhill/uMatrix#871]
You must get bombarded with gratitude for your software. I originally started with uBlock which I thought was amazing as it is, and now recently I have switched over to uMatrix because of the mining scripts that are becoming rampant.

It was a bit confusing at first (coming from the legacy NoScript where I could just blacklist or whitelist per domain), but now that I have gotten the hang of it I prefer it more.

Thank you for making your beautiful software available freely.

**Comment by gorhill** [comment]
Thanks. I've gotten back to use uMatrix as well lately (without uBO enabled), and I am back to appreciate the unique advantages of uMatrix over uBO, and also by using it I am better placed to keep improving it -- it had been a bit neglected since a while now.
