### ISSUE TITLE
[Request] noTabFound appearance

### ISSUE THREAD

**Issue by Remu-rin** [gorhill/uMatrix#872]
"No web page found" message is good, but that version of popup lacks ability to go to dashboard via usual black titlebar. Ideally, it could also have the logger button (like uBO) and the black "Revert all temp changes" button (though they weren't reachable in previous popup without content). All other elements are related to content of the tab and don't have to be there, indeed.

**Comment by theWalkingDuck** [comment]
btw, this is easily reproducable just by setting the option to "Show a blank page" when Firefox starts.
The URL in this case is `about:blank` but it seems uMatrix can't see/find the scope.

On the other hand if I open `about:blank` manually, uMatrix sets the right scope (`blank.about-scheme`).

**Comment by theWalkingDuck** [comment]
I have no issue when I click "new tab", uMatrix sets the scope `newtab.about-scheme`.

I see "No web page found" only with the setting `Show a blank page` when Firefox starts.

**Comment by uBlock-user** [comment]
Before the commit, in Chromium, opening newtab, the scope was set to `google.com`, if you had Google as the default search engine, now it correctly sets to `newtab.chrome-scheme`, so thanks for the quick fix.

**Comment by theWalkingDuck** [comment]
With the new release uM 1.1.20, the issue with firefox seems to be resolved now.
Tested on FF57, 58 + 59.
Thank you !
