### ISSUE TITLE
uMatrix network connections

### ISSUE THREAD

**Issue by Eriton33** [gorhill/uMatrix#875]
Hi,

when firefox is started with uMatrix enabled, there are several network connections initiated by uMatrix.
While firefox itself can be cofigured not to connect to any server on startup, I did not find any option in uMatrix that seems to enable/disable any feature that seems to be responsible for the initiated network connection. The connections arre kept established the hole time the firefox process is active.

1. What are these connections for? Is uMatrix phoning home?

2. Can I disable this behavior?

**Comment by gorhill** [comment]
> when firefox is started with uMatrix enabled, there are several network connections initiated by uMatrix [...] The connections arre kept established the hole time the firefox process is active

uMatrix does not initiate connection on start up (unless one of the filter lists enabled is not present locally -- this happens at 1st launch only), and does not keep "connections [...] established the hole time the firefox process is active".

Your issue is missing all the details to make the case you are trying to make, you provide absolutely no technical details supporting your assertions.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by ArchangeGabriel** [comment]
As @gorhill pointed, this is filter lists retrieving & updating. So disabling lists should remove connections.

**Comment by gorhill** [comment]
As said, this occurs only the first time uMatrix is launched for hosts files which are not part of the package, this does not happens ever again afterward, unless one wipe uBO's indexedDB somehow.

And the claim "keep "connections [...] established" is nonsense.

**Comment by ArchangeGabriel** [comment]
OK, I agree. But aren’t filter lists updated? At least there is a checkbox to “Auto-update“ them.

**Comment by gorhill** [comment]
> But aren’t filter lists updated?

Sure, but some minutes _after_ start up, and only when needed -- just like with uBO. The update period in uMatrix is longer than with uBO: 11-13 days (uBO is ~4-5 days unless explicitly set by a filter list directive).

**Comment by Eriton33** [comment]
I tried to replicate the problem and found out that it does indeed have to do with the filters being updated.

On my (arch) linux system the problem seems to be that the filters are reset after firefox is restarted. On windows the filter update seems to work just fine.

When disabling all filters, I noticed that the "Apply changes" button steys grey/inactive and the changes to the filter list cannot be applied. This might also explain why the updated files are not saved when firefox is restarted. This leads to the described behavior, where uMatrix reconnects to the update servers at every start of firefox. However when I tried to replicate it on Ubuntu 17.10 this issue did not exist and uMatrix works as expected. Therefore I suspect this has to do with some distribution dependend feature like apparmor which might prevent uMatrix to save the changes after updating the filter lists.

I will try to figure out what feature causes this behaviour and what linux distributions are affected. To better understand what is happening, could somebody please tell me where on a linux system uMatrix tries to save those files?

Thanks
