### ISSUE TITLE
[feature suggestion] allow the use of .tld

### ISSUE THREAD

**Issue by elypter** [gorhill/uMatrix#876]
in userscripts you can use mydomain.tld to match all top level domains of mydomain so instead of repeating rules for mydomain.org, mydomain.com, mydomain.net, ... you only need a single line. since you seem to like making umatrix rules more concise (https://github.com/gorhill/uMatrix/issues/825) i thought this would be a nice addition.

**Comment by gorhill** [comment]
#825 does not requires a rewrite of the core filtering code.

Your suggestion would require a serious rewrite of the core filtering, and would cause quite an additional overhead to what is there now.

Declined.
