### ISSUE TITLE
uMatrix My rules reset randomly

### ISSUE THREAD

**Issue by Addicted5** [gorhill/uMatrix#877]
Hi, it seems uMatrix settings resetting randomly.
May be after firefox crash or firefox update.
But i already seen 5-6 time losing uMatrix settings already. It seems those issue started after firefox 57 version(or whatever that version that brought new webextension thing)

**Comment by uBlock-user** [comment]
Probably a bug with FF 57, hasn't happened to me on FF 59 yet.

**Comment by gorhill** [comment]
Your issue is un-actionnable. Investigate on your site to find the root cause of your issue. Browser crash can lead to strorage corruption, it's out of uMatrix's scope.
