### ISSUE TITLE
[Request] Serious browsing privacy concerns + suggestions

### ISSUE THREAD

**Issue by t33rex** [gorhill/uMatrix#881]
I have found (by watching the Logger and tcpdump) that both Firefox and Chromium browsers communicate with Google, Mozilla, Amazon and other hosts upon browser startup (no tabs open) and even after shutdown, although data reporting is completely disabled. See [more details](https://forums.opensuse.org/showthread.php/528559-Paranoid-browser-test-is-there-privacy-in-FOSS).

Considering the privacy implications of this (organization knowing each time you start the browser, periodic pings etc) it seems no browser is completely safe. I think it may be a good idea to have rules which block all these `behind-the-scenes` spying requests but without affecting the work of extensions. Some ideas how I see this can be accomplished:

- Time based: `behind-the-scenes` blocked completely with an option to open only for a short time (each hour, or at a fixed time)

- Rules which allow only extensions to be updated through a particular `behind-the-scenes` request (if that is possible?). Can also be time based (if previous suggestion is possible)

- Rules which allow only uMatrix and uBO rules to update 3rd party lists but block all other `behind-the-scenes` requests. I think that should make more sense than adding all these manually as rules as the extensions already knows these urls.

- Button to manually open the needed `behind-the-scenes` requests in order to update extensions and filter lists which automatically closes after that.

- Perhaps also worth considering (yes, I know it is not that simple): @gorhill's fork of Chromium or Firefox - with privacy enhanced, in which all that spying stuff is removed. I read that some browser called Waterfox claims it is FF with all telemetry removed but haven't tested it yet (just info).

I think these may increase the unsolicited telemetry which seems impossible to block through browser settings.

Is any of that possible and worth considering?

**Comment by uBlock-user** [comment]
> @gorhill's fork of Chromium or Firefox - with privacy enhanced, in which all that spying stuff is removed. 

Use Chromium custom buit from https://chromium.woolyss.com/

**Comment by t33rex** [comment]
> Use Chromium custom buit from https://chromium.woolyss.com/

I believe that's what I am using:
https://en.opensuse.org/Chromium

**Comment by uBlock-user** [comment]
> I believe that's what I am using:
https://en.opensuse.org/Chromium

You didn't mention this anywhere, otherwise I wouldn't have suggested.
