### ISSUE TITLE
[question] Which blocks the request first: uBo or uMatrix?

### ISSUE THREAD

**Issue by t33rex** [gorhill/uMatrix#882]
I am willing to block certain `behind-the-scene` requests. Tested scenario:

1. Set rule to block youtube.com in `behind-the-scene` (read cases below)
2. Open youtube.com
3. Watch loggers of uBO and uMatrix

Cases:
a. If in 1. uBO blocks but uM allows - loggers show the request is blocked in uBO, but not in uMatrix
b. If in 1. uMatrix blocks but uBO allows - loggers shows that uMatrix blocks but uBO allows
c. If both uBO and uMatrix are set to block - both loggers show that the request is blocked, i.e. the request still reaches the other extension

So what is the proper (earliest) way to block a request? And what is the priority? I.e. if a request is blocked by one extension - is it allowed after that by the other one (i.e. does it still "pass")?

**Comment by gorhill** [comment]
> For question/support/discussions, there is Mozilla Discourse:
https://www.reddit.com/r/uMatrix/

(I corrected the "Mozilla Discourse" to "Reddit's /r/uMatrix")
