### ISSUE TITLE
[Request] Choosing script (or other file) to block or allow.

### ISSUE THREAD

**Issue by Krantek** [gorhill/uMatrix#884]
It would be very (very!) useful making it possible of choosing script (or other file) to block or allow.

![1](https://user-images.githubusercontent.com/34579455/34052141-d3a14f6a-e1c9-11e7-94d0-8a121bc5479b.png)

It can be done from uMatrix logger page by adding few buttons there: "ALLOW and BLOCK".

![2](https://user-images.githubusercontent.com/34579455/34052150-d95084d0-e1c9-11e7-9a4d-bce9ca08d13e.png)

**Comment by gorhill** [comment]
Use uBlock Origin if you want higher granularity.
