### ISSUE TITLE
Some features from uBo to Umatrix

### ISSUE THREAD

**Issue by sebast889** [gorhill/uMatrix#885]
I noticed some things added in uBo that is very nice features but not added in uMatrix.

- Date and time added to end of backup name.
- Logger button when clicked in popup should go to the tab it was opened from right now it just opens logger with All tabs.
- Settings export option. Only rules can be exported right now

Maybe you can think of some more useful features in uBo missing from uMatrix as you know better than me what was added

Thanks

**Comment by gorhill** [comment]
Please search opened issues before opening new ones, all these points are already opened.
