### ISSUE TITLE
uMatrix: One Step from Ideal

### ISSUE THREAD

**Issue by Krantek** [gorhill/uMatrix#886]
uBlock Origin (like AdblockPlus) is for those who doesnt want to worry about Ads and dont want to know how it works.
But uMatrix is for those who want to have control of situation (and see all the map). 
And I think uMatrix is in one step from ideal extension. 
This step is: "My filters" option (window), like in uBlock Origin, where you can write your own filters (full site or some element) + with support Adblock Plus filter syntax.
I use uMatrix + uBlock (uBlock with unpluged all filters except "My filters") but I (and people like me) want to use only one, ideal extension.
I don`t think its to hard to add this option to uMAtrix. Am I wrong?

**Comment by ArchangeGabriel** [comment]
Hard is likely not the question. Yet the answer will be “use uBlock Origin”, because they have different purpose.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
HTTPSwitchBoard was that extension, then it was split into uBO + uMX.
