### ISSUE TITLE
Noscript and Umatrix differences

### ISSUE THREAD

**Issue by 3k2** [gorhill/uMatrix#887]
I've been trying to read the differences between noscript (latest) and umatrix (latest) versions but I can't really understand what they are exactly because it would appear that noscript can do somethings that umatrix isn't able to but still some users do claim it can do them or even more in certain cases. 

Some users recommend using ublock + noscript + umatrix but I feel like you should rather use just umatrix or noscript for better usage?

Tho it would seem that the latest noscript is really suffering atm now from this new extension thing going on in firefox?

https://hackademix.net/2017/12/11/noscript-and-the-downloads-permission/
https://hackademix.net/2017/12/04/noscript-quantum-vs-legacy-in-a-nutshell-2/

overall I just can't seem to decide should I stay with ublock + umatrix or switch over? I have been using both more or less with ublock.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
