### ISSUE TITLE
URL doesn't load properly even when filtering is disabled for this scope

### ISSUE THREAD

**Issue by fimmwolf** [gorhill/uMatrix#888]
The site is  https://www.fanatical.com/en/search?types=game&types=dlc 
(sells games online)

I dont get images loading so I disable for this scope. No change. 

I go to Tools > Addons > Extensions and disable uMatrix site loads properly.

I hold shift when launching firefox (safemode)  site loads properly

images:
site not loading:   https://imgur.com/a/cvJvY
site loading with uMatrix disabled:  https://imgur.com/a/Z0qCR

My settings in uMatrix:
https://imgur.com/a/Qblqn

-->

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
https://github.com/gorhill/uMatrix/wiki/Per-scope-switches

**Comment by fimmwolf** [comment]
ah thank you. 

Have since turned off referrer spoofing.

**Comment by gorhill** [comment]
I thought "Strict HTTPS" (to forbid mixed content) would have been the issue.
