### ISSUE TITLE
Not all elements show up

### ISSUE THREAD

**Issue by Darkcast** [gorhill/uMatrix#889]
I noticed that when I enter a new website and start white listing stuff some of the stuff will not show up in the list, for example if I go to a website that has en embedded iframe like youtube if I refresh or turn off the plugin in the whole page I still wont be able to see the block content. the only way I am able to see the iframe so I can enabling it is by disabling the app in firefox refresh FF and then re-enable then I see the missing IF or cdn etc.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
