### ISSUE TITLE
UI broken for Firefox ESR in uMatrix >1.1.18

### ISSUE THREAD

**Issue by jaatroko** [gorhill/uMatrix#890]
In uMatrix git master starting with commit fa2658c, the UI (popup,dashboard,logger) is completely unfunctional (only initial/"background" elements drawn, clicking things has no effect) in the legacy version for Firefox ESR (52.5.2) created by tools/build-firefox.sh. When opening the popup, the browser console says: `TypeError: vAPI.messaging.send is not a function`.

**Comment by ArchangeGabriel** [comment]
Legacy version is not supported anymore. You will have to wait for next ESR (59, in about 3 months I think) to get updated uMatrix.

**Comment by gorhill** [comment]
uMatrix is marked as being compatible with Firefox 56+, you had to bypass the warning of incompatibility to install it.
