### ISSUE TITLE
Maybe a minor UI issues

### ISSUE THREAD

**Issue by brucehuanglove** [gorhill/uMatrix#894]
Hi, 
    Thanks for your great web-ext!
    I have encountered a UI issue with the toolbar.

Suppose I had the following rules:

` user.qzone.qq.com qzonestyle.gtimg.cn script allow `

Then, I navigated my firefox to user.qzone.qq.com, in the toolbar, I saw the following: 
![4pc jbrla6k3dmzdc3 l yc](https://user-images.githubusercontent.com/34432985/34318364-c72f3840-e800-11e7-87b1-1e69f3cf6fb2.png)
The "script square" was red.
In my opinion, I think the square should be green.
If I am wrong, please close it and tell me the reason.
Thanks for your reading.

**Comment by gorhill** [comment]
Can you explained why you closed the issue?

**Comment by brucehuanglove** [comment]
I am sorry to open this issue.
when I wrote down all process, I found that the "scope level" was under "domain", so the square should be red but not green.
sorry to disturb you.
