### ISSUE TITLE
Whitelist wikimedia.org domain by default

### ISSUE THREAD

**Issue by nemobis** [gorhill/uMatrix#895]
With uMatrix 1.1.20 in Firefox 57.0.1 and default rulesets, if I open a page in the la.wikipedia.org domain, or even commons.wikimedia.org, cookies are blocked from the wikimedia.org domain, including e.g. meta.wikimedia.org.

Cookies and resources from the central domain wikimedia.org are essential for the correct functioning of all ~800 wikis. and they should be whitelisted by default, if the wikis depending on them are supposed to be whitelisted. For instance, banners (including fundraising banners by CentralNotice) may place some central cookie on meta.wikimedia.org to avoid being displayed again.

**Comment by gorhill** [comment]
There is no built-in specific whitelist rules, by design.
