### ISSUE TITLE
www.smashcast.tv not loading live streams

### ISSUE THREAD

**Issue by SuperSandro2000** [gorhill/uMatrix#896]
Live streams are not loading with uMatrix enabled but all filtering turned off. (Smashcast is a merge of hitbox.tc and azubu.tv)
To reproduce that issue:
1. load smashhit.tv
2. allow everything on that side
3. Shift + F5 
4. ads load but the live stream does buffer forever
After disabling uMatrix in Chromes extension everything works just fine.

[www.smashcast.tv-1514297670567.log](https://github.com/gorhill/uMatrix/files/1587440/www.smashcast.tv-1514297670567.log)
Chrome 63.0.3239.84
Windows 8.1

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by SuperSandro2000** [comment]
You're right. Disabling referrer spoofer fixed the issue... sorry about that
