### ISSUE TITLE
UI scaling issue on Win10 desktop

### ISSUE THREAD

**Issue by rkost** [gorhill/uMatrix#898]
Maybe a duplicate of #694 - sorry if so.

So this appears only to be a problem on windows 10 devices with more than one screen connected (no scroll bars whatsoever - By the way: this also happens to uBlock origin):

![image](https://user-images.githubusercontent.com/11631510/34422310-fb4dd326-ec14-11e7-86a6-d495a1f4a8e1.png)

As one can see the plugin content is shown to big. Scrollbars are there for a fragment of a second and then disappear forever.

## Setup: 

  - Windows 10 Pro 64bit (1709 currently but also earlier versions). 
  - Two monitors connected:
    1. 4k screen (scaling is set to 150%)
    1. 1080P screen (scaling is set to 100%)
  - Firefox 57.0.2

Problem **only occurs** iff firefox is displayed on the **second screen** (the 1080p one). Everything works fine on the other one.

This issue **does not exist** when installing uMatrix in **chrome** so either firefox does a poor job rescaling plugins or there is something wrong with uMatrix.

**Comment by gorhill** [comment]
> with more than one screen connected

Browser issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1387340>.

**Comment by Cerberus-tm** [comment]
Update (from the Mozilla bug above): this issue has been fixed, and the fix will be implemented in FF 58 (or 59).
