### ISSUE TITLE
tutoriel FR 

### ISSUE THREAD

**Issue by Floruit** [gorhill/uMatrix#90]
Bonjour, serait-il possible d'avoir un tutoriel entier en FR svp ?

**Comment by Snapy** [comment]
Peux-tu préciser le contenu attendu : explication des différentes fonctionnalités, les différentes approches possibles (i.e NoScript, bloqueur de pubs), traduction des pages du wiki ?

**Comment by Floruit** [comment]
Bonjour et merci de ta réponse , 

Pour un utilisateur lambda , je suit vite déboussolé par ce qu'il faut activer ou non ! le principe en lui même est clair ( autorisation ou non avec vert et rouge et sauvegarde  ) mais dans les " règles"  par exemple , j'ai suivi le tuto anglais pour auoriser youtube partout , mais a chaque site nouveau il faut que je l'active ainsi que  ymtg ou un truc du genre , donc cela je n'ai pas compris par exemple , aussi je voit a peu près ce qu'est les CSS , script et frame , mais je pense que d'autre n'ont pas du tout ses notions .... donc expliquer ce qui est utile de débloquer des fois , par exemple sur CCM , le CSS est desctivé par default il faut donc activer le CSS , sur d'autre site , j'y vais parfois au petit bonheur la chance , j'active / desactive les ligne une par une pour trouver ce qui est bloqué :D

**Comment by Snapy** [comment]
J'ai fait un [Google Doc] (https://docs.google.com/document/d/1g514TRu4ZpEb60PlXjgrMRz9HRHfifdnVX1LEwgQPPc/) pour t'aider/répondre à tes questions.

Pour faire court :
- µMatrix est pour des utilisateurs plutôt avancés
- Pour YouTube 
  - Tes règles ont juste besoin d'être un peu modifiées
  - Certains changements de YouTube peuvent rendre des règles non fonctionnelles. 
- Regarde sur Wikipédia (ou d'autres sites) pour les types de requêtes (CSS, script, frames...).
- Renseigne-toi sur les sites que tu débloques "au petit bonheur la chance" à moins d'être sûr.

Si tu as d'autres questions ou besoin de plus de précisions n'hésite pas à me demander.

**P.S** : Lis bien les quelques infos utiles de la fin.

**Comment by Floruit** [comment]
merci je savait pas pour le premier asterisque . 

avec le temps je commence a connaitre certains truc , et maintenant je regarde , ce que les ligne vont me " débloquer " ( par exemple si y'a un 1 dans script je sait que cela va activer un script ) . 

je vais me pencher sur la syntaxe aussi :) 

j'avoue ne pas etre un utilisateur confirmer, mais comme " noscript " n'existe plus sur opéra , c'est la seule alterantve que j'ai trouvé :D

**Comment by Snapy** [comment]
Il n'y a pas de grandes difficultés à apprendre à utiliser µMatrix (documentation + syntaxe + bidouille).
En effet, pas beaucoup d'extensions sur Opera mais si tu installes [cette extension] (https://addons.opera.com/fr/extensions/details/download-chrome-extension-9) tu auras accès au catalogue Chrome et donc à un plus grand choix (comme ScriptSafe).
Concernant µBlock (même si ce n'est pas l'endroit approprié), ce qui est bloqué vient soit des listes, soit des filtres créés, soit par le [filtrage dynamique] (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide). Dans la popup (quand tu cliques sur l’icône) tu devrais voir un œil : clique et tu pourras voir les éléments bloqués/bloquables de la page et en bidouillant tu devrais pouvoir t'en sortir.
Sinon je ne vois de quoi tu parles quand tu dis "activer une IP"

**Comment by Floruit** [comment]
"Sinon je ne vois de quoi tu parles quand tu dis "activer une IP"

en faite , les video du site sont bloqué par défault , pour les lire , faut activer en vert par exemple 100.01.02.03 sur une autre video se sera 101.01..02.03 , etc..... j'apparente cela a une adresse IP , mais je me trompe peut-etre !
