### ISSUE TITLE
Storage used not determined

### ISSUE THREAD

**Issue by steffanson** [gorhill/uMatrix#906]
On the "about page" there's a line which reads: `Used storage: ? bytes`

I tested with a new created profile, where I only installed uMatrix 1.2.0.
The debugger reports no error.  Please let me how I can help you at debugging this issue.

### Version
Kubuntu 17.10
Firefox 57.0.4
uMatrix 1.2.0

**Comment by gorhill** [comment]
Browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1385832
