### ISSUE TITLE
Flickering and CPU usage caused by blocked images

### ISSUE THREAD

**Issue by Hyundy** [gorhill/uMatrix#909]
Example URL: https://www.reddit.com/r/firefox/

1.2.0 Firefox 58 (behaviour seen on Linux and Android)

The text displayed in the placeholder of a blocked image will sometimes move up and down slightly. On some pages like the above, this causes the rest of the page to move up and down slightly.

**Comment by gorhill** [comment]
When you block stuff, expect pages to not render perfectly pixel-wise.

**Comment by Hyundy** [comment]
I think this is actually a change in Firefox that causes this, not uMatrix, as I first thought.

Although, I can only reproduce it with uMatrix and not uBlock Origin, in clean and old profiles ("Hide placeholders of blocked elements" in uB was turned off).

https://imgur.com/a/3kjyo

Two examples.
