### ISSUE TITLE
Uncaught DOMExceptions with uMatrix installed

### ISSUE THREAD

**Issue by DigiAngel** [gorhill/uMatrix#910]
Topic...here's the line that I get.  Even with uMatrix disabled for the site I see these..I have to completely remove uMatrix in order for a couple sites to work.

Uncaught DOMException: Blocked a frame with origin "https://site" from accessing a cross-origin frame.

What other information can I provide?  Thank you.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22

**Comment by DigiAngel** [comment]
Thanks @uBlock-user.
