### ISSUE TITLE
[Feature Request] Storage Viewer

### ISSUE THREAD

**Issue by zero77** [gorhill/uMatrix#911]
Can you please implement a storage viewer, like the storage tab in Firefox developer menu.
Because, once you have left a web page in Firefox, to my knowledge you can’t see what still being stored by that domain.
Thanks

**Comment by gorhill** [comment]
Go to `about:debugging`, "uBlock Origin", click "Debug", select "Storage".

Reminder: please respect [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
