### ISSUE TITLE
Add menu option to turn "Forbid web workers" on/off globally

### ISSUE THREAD

**Issue by breznak** [gorhill/uMatrix#913]
In the latest uMatrix (1.2.0) on FF (57) on Linux, 
I'm able to toggle the use of WebWorkers on per-site basis. It would be nice to be able to **turn the workers off as default** (usefulness of this is mentioned in the changelog/wiki) and only allow them where needed.

**Comment by ArchangeGabriel** [comment]
You already have two equivalent ways of doing this:
1. Select the global scope “*”, and turn of workers.
2. Go to the settings page of uMatrix, then to your rules and add `no-workers: * true`.

**Comment by breznak** [comment]
Awesome! Thank you @ArchangeGabriel  
Closing as solved.

**Comment by Comandante1983** [comment]
Space prog.... Stuff(+_+)O:-):-$
