### ISSUE TITLE
Evernote Web Clipper is not working cause uMatrix blocks requests by default

### ISSUE THREAD

**Issue by qwertier** [gorhill/uMatrix#914]
Evernote Web Clipper is a very common addon, which allows user to make a copy of a web page directly into Evernote.
But uMatrix blocks requests to www.evernote.com from any site. That makes Web Clipper to run into failed state.

I propose to add these rules by default:

* www.evernote.com * allow
* evernote.com cookie allow

Adding them allows Evernote Web Clipper to work properly!
Thank you!

**Comment by gorhill** [comment]
By design there isn't and won't be any specific whitelist rules in uMatrix. Each users can add them as needed.

**Comment by uBlock-user** [comment]
Why default ? Just because you use that extension, doesn't mean everybody else does. Whoever uses it is expected to add that by themselves.
