### ISSUE TITLE
[Pull Request] Option For Wider Cookie And Cash Clearing Time

### ISSUE THREAD

**Issue by zero77** [gorhill/uMatrix#917]
A lot of web pages can be viewed within 15 minutes thus, allowing a lot of viewed pages to be logged by trackers.

I propose allowing users to be allowed to set the time but from a wider time span starting from 1 minute and letting them make up their minds on the matter.

Thanks
	
See: 
https://github.com/gorhill/uMatrix/pull/916
https://github.com/gorhill/uMatrix/pull/915

**Comment by Thorin-Oakenpants** [comment]
The `15` is a placeholder, you can enter a lower value AFAIK. I assume the same for the cookies.
![15-is-a-placeholder](https://user-images.githubusercontent.com/16656956/34918712-eca40048-f9bb-11e7-95be-319583a8491b.png)

**Comment by uBlock-user** [comment]
> allowing a lot of viewed pages to be logged by trackers.

Not possible if trackers are blocked.
