### ISSUE TITLE
Webpage tracking using only CSS

### ISSUE THREAD

**Issue by sebast889** [gorhill/uMatrix#918]
I came across this https://github.com/jbtronics/CrookedStyleSheets

It can track some things like fonts installed on user OS, browser resolution and if the user hovers over a link. I'm wondering if there is something uMatrix can do to protect against this without fully disallowing CSS requests.

**Comment by gorhill** [comment]
Block CSS.

**Comment by sebast889** [comment]
Yes I know blocking CSS can stop this but is there no other way to protect against this type of tracking without blocking CSS totally?

**Comment by gorhill** [comment]
Use the Tor browser.

**Comment by gorhill** [comment]
If you think something can be done which is well within the scope of uMatrix's purpose, please share. Closing for now.

**Comment by uBlock-user** [comment]
> track some things like fonts installed on user OS, browser resolution 

It's already being done by various fingerprinting methods, so this is not news anymore.
