### ISSUE TITLE
Scrollbar covers the matrix

### ISSUE THREAD

**Issue by BadAssTux** [gorhill/uMatrix#919]
Hello
I am using uMatrix 1.2.0 on Firefox 57.0.4 on KDE Ubuntu - German language.
When I visit a website which has many scripts etc. which are blockable there is a scrollbar on the right side of the matrixside which covers a little bit of the matrix.

![umatrix_bug](https://user-images.githubusercontent.com/35473202/34966741-3a6801d8-fa5e-11e7-8d4b-02b7345aac14.jpg)

**Comment by gorhill** [comment]
Duplicate of #811.
