### ISSUE TITLE
option missing to preload all CSS on pageload to prevent CSS tracking

### ISSUE THREAD

**Issue by rubo77** [gorhill/uMatrix#920]
There should be an option for sites to preload all needed images for the stylesheets, so CSS-only-tracking will be undermined. 

See https://github.com/jbtronics/CrookedStyleSheets#what-can-you-do-to-prevent-tracking-via-this-method

**Comment by tauxeta** [comment]
Discussion on the issue https://news.ycombinator.com/item?id=16157773

**Comment by gorhill** [comment]
Please file an issue with browser devs, this is best handled in there.

**Comment by rubo77** [comment]
What are browser devs?
