### ISSUE TITLE
AMO Beta Version?

### ISSUE THREAD

**Issue by puff-m-d** [gorhill/uMatrix#921]
Hello,

I am a bit confused by the beta versions on AMO...
I see that you released 1.2.1rc2 today on the GitHub page but...
The version showing released today on AMO is version 1.2.1rc0...
Is this some bug on the AMO beta page (or possibly a typo) as since this version number is lower than 1.2.1rc1, uMatrix is not updating? Should the version on AMO be 1.2.1rc2 so it would update?
I hope this makes some sense as this is confusing to me, as it is strange that AMO went from 1.2.1rc1 to 1.2.1rc0...

**Comment by gorhill** [comment]
My bad, I ended up uploading the wrong version. Fixed by uploading 1.2.1rc2.
