### ISSUE TITLE
uMatrix breaks voting on StackOverflow in Firefox 57.0.1

### ISSUE THREAD

**Issue by ThePowerOfDreams** [gorhill/uMatrix#923]
On Firefox 57.0.1 on Ubuntu 18.04 nightly, with the out-of-the-box uMatrix configuration (hadn't yet configured it, was just evaluating its functionality), StackOverflow voting buttons are broken; clicks don't trigger a vote. Disabling uMatrix and reloading the SO page restores the functionality.

**Comment by gorhill** [comment]
[Front page of the project](https://github.com/gorhill/uMatrix#warnings):

> uMatrix does not guarantee that sites will work fine: it is for advanced users who can figure how to un-break sites, because essentially uMatrix is a firewall which works in relaxed block-all/allow-exceptionally mode out of the box: it is not unexpected that sites will break.
> 
> So this means do not file issues to report broken sites when the sites are broken because uMatrix does its job as expected. I will close any such issue without further comment.
