### ISSUE TITLE
Disabling filtering still applies CSP policy

### ISSUE THREAD

**Issue by nmschulte** [gorhill/uMatrix#926]
Visiting a locally hosted document which makes use of web workers (served by the same host).  `http://localhost:3000/`.

Disabling uMatrix (via the power button, disabling the two "forbid ..." and the two "spoof ..." options, and reloading w/out browser cache) still leaves behind a Content-Security-Policy that interferes with my application.

In Chrome (Chromium `Version 61.0.3163.100 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`), I receive a `worker-src 'none'` violation:
```
[Report Only] Refused to create a worker from 'http://localhost:3000/worker.js' because it violates the following Content Security Policy directive: "worker-src 'none'".
```

In Firefox (`57.0.4 (64-bit)`), I receive a `child-src 'none'` violation:
```
Content Security Policy: The page’s settings observed the loading of a resource at http://localhost:3000/worker.js (“child-src 'none'”). A CSP report is being sent.
```

Additionally, Firefox complains about these aspects of CSP when viewing the document:
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
```
```
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.
```

---

The only way I can get around this is to disable uMatrix at the extension/add-on level.  No matter of twiddling with the rules or adding my own CSP HTTP headers or HTML meta tags to allow the workers/etc. suffices.

**Comment by gorhill** [comment]
It's not a `Content-Security-Policy`, it's a `Content-Security-Policy-Report-Only`, it has not effect except for allowing uMatrix to know when a web page tries to use a web worker.

**Comment by nmschulte** [comment]
To clarify, you're stating that I'm simply mis-interpreting these "[Report Only]" error messages as errors, when really they're just notices (of would-be errors), and the browser actually _does_ allow and create the workers?

**Comment by gorhill** [comment]
> you're stating that I'm simply mis-interpreting these "[Report Only]" error messages as errors

Yes, because you said:

> leaves behind a Content-Security-Policy that interferes with my application.

They are report-only CSP directives, they can't interfere with your application. If you do not want the csp-report, see <https://github.com/gorhill/uMatrix/wiki/Raw-settings#disablecspreportinjection>.

**Comment by nmschulte** [comment]
@gorhill Thank you.

**Comment by nmschulte** [comment]
Is it conceivable, sensible, to disable the CSP Report injection if there's an enabled `matrix-off` rule for a domain/host?

**Comment by gorhill** [comment]
The purpose is for uMatrix to be able to _report_ that web workers are used on a site. Without this CSP reports, it's not possible to inform about this. Such information is key in deciding what rules should apply to a site.

**Comment by nmschulte** [comment]
Understood.  Given that this is only here to workaround a bug, it's low priority anyway.

My rationale is this: `matrix-off` is like a "disable this extension for this domain/host," so there's no need to check for web workers, let alone enforce any uMatrix rules.

**Comment by gorhill** [comment]
> `matrix-off` is like a "disable uMatrix extension for this domain/host

It's [not](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches):

> The per-scope switches are independent from the matrix filtering switch, meaning that if you toggle off matrix filtering, the per-scope switches which are toggled on will still apply. For example, one could turn off matrix filtering while keeping the ability to forbid mixed content.

If a site is mining coins, you want to know about this, regardless of the state of uMatrix, and arguably even more so if one disabled all parts of uMatrix.

**Comment by u17194907425** [comment]
> for allowing uMatrix to know when a web page tries to use a web worker

@gorhill, does it mean that there is no way to avoid seeing this `[Report Only]` message?

**Comment by gorhill** [comment]
As said above, see <https://github.com/gorhill/uMatrix/wiki/Raw-settings#disablecspreportinjection>.

**Comment by u17194907425** [comment]
@gorhill, oh crap, my bad. I didn't word my question correctly.

I mean if I go through `disableCSPReportInjection` I'll disable a part of functionality of uMatrix. Is there any other way to keep the plugin monitoring workers but avoid this warning? I'm talking about my web server where I can control Headers.

E.g. any chance that setting `Content-Security-Policy-Report-Only` headers form the server will suppress the `[Report Only]` warning? Or it is an inevitable consequence of uMatrix working as designed?

**Comment by gorhill** [comment]
It does not matter who set the content security policy, the browser will always output violations at the console.

**Comment by gorhill** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1376953>

**Comment by nmschulte** [comment]
Ah, I see that the CSP spec has no support for blacklisting, hence the need for a global/always-on `worker-src: none` report-only CSP.

Would it be possible to maintain the whitelist in real-time / per-request/domain, and refuse to add domains with `no-worker: true` rules?

@gorhill, could uMatrix use a more selective value for `worker-src` than `none`?  This would help out in the cases where uMatrix's global "forbid web workers" is not enabled.  If a domain has `no-workers`, couldn't we specify `worker-src:

**Comment by gorhill** [comment]
> This would prevent CSP reports for whitelisted domains

As already pointed out, the report is needed to inform about use of workers. Not blocking workers on a domain is not equivalent to "don't tell me if workers are being used" on this domain.

**Comment by nmschulte** [comment]
> As already pointed out, the report is needed to inform about use of workers.

chicken / egg.  got it.  thanks for sticking with me.
