### ISSUE TITLE
When first installing uMatrix, the setting "Auto-update hosts files" is disabled by default

### ISSUE THREAD

**Issue by darkred** [gorhill/uMatrix#928]
_Using uMatrix 1.3.2 in Firefox 58 and Chrome 63 (win10x64)._

When first installing uMatrix (I use it in Firefox and Firefox)
the setting in uMatrix's dashboad: "Host Files | Auto-update hosts files" is disabled by default.

In contrast, when first installing uBlock Origin, the relevant setting in uBO's dashboard: "3rd-party filters | "Auto-update filter lists" is enabled by default.

**My suggestion is the "Auto-update hosts files" setting to be enabled by default in uMatrix as well, 
in order to make sure that the hosts files will be kept up-to-date by default.**

Also, in the [Privacy policy](https://github.com/gorhill/uMatrix/wiki/Privacy-policy) wiki page it says that:

> uMatrix does not collect any data of any kind.
> 
>   - uMatrix has no home server.
>   - uMatrix doesn't embed any kind of analytic hooks in its code.
> 
> The only time uMatrix connects to a remote server is to update the hosts files and other related assets. **If you disable auto-update in the "Hosts files" pane in the dashboard, uMatrix will not connect to any remote server, unless you click "Update now" and only if there are assets deemed "out of date".**

The last sentence IMHO suggests that disabling the autoupdate of hosts files (for privacy concerns)
should be a user opt-out action, not the default behavior of the extension.

Thank you

**Comment by h1z1** [comment]
Read that as the opposite - It doesn't call home by default, that is a good thing.  Drove me nuts that uBO does this and without asking.   Default third party rules are dangerous.

**Comment by gorhill** [comment]
> It doesn't call home by default

It never calls "home", I don't own GitHub servers.

>  Default third party rules are dangerous.

They are all block rules.

**Comment by h1z1** [comment]
>> It doesn't call home by default

> It never calls "home", I don't own GitHub servers.

Extended home? :)   Never said your home though.  Will uM not download them on first run?

>> Default third party rules are dangerous.

> They are all block rules

Indeed, they are  run by third parties though.

**Comment by gorhill** [comment]
> Indeed, they are run by third parties though.

The point is, how are 3rd-party blocking rules "dangerous"? I can't make sense of this. By that logic, default-deny is dangerous since all 3rd-party requests are blocked by default.

**Comment by h1z1** [comment]
Same could be said the other way - If the default is deny then why are these needed?  Blocking 3rd party anything is the point of umatrix.  There's nothing to stop them from including rules I'd rather not waste even memory on or risk typos breaking (easylist for example).  Considering 99% of them are never hit..

Unlike running a dns server, hosts files are not databases.  There is an overhead in reading pointless, large files over and over.

I don't personally need nor care for yet another server somewhere on the Internet keeping a record of me.  I much rather software _ASK_ on install whether users want to download external lists first.

**Comment by Remu-rin** [comment]
> Same could be said the other way - If the default is deny then why are these needed?

1. To block css and images from those known bad domains, even when they are allowed globally. And in some cases content from those domains is 1st-party scripts /XHR/etc (subdomain). Privacy.
2. To clean up matrix via moving them to the end of popup, plus making it possible to hide all of them to one string. Usability.

**Comment by Remu-rin** [comment]
> Don't think you understand what default deny means as it includes 1st and 3rd party requests.

Defaults of uM is not clean default deny. It allows everything from 1st-party, plus css and images from 3rd-party. And hosts-filters are useful there. Most users don't go full default deny, even me (in 1st-party I block only scripts)

> I don't understand that.

Compare this. Which variant is more clean and easy to use?
![image](https://user-images.githubusercontent.com/28995228/35478294-f1578224-03fa-11e8-8c56-7961e3800a9f.png)
![image](https://user-images.githubusercontent.com/28995228/35478299-fbd816d2-03fa-11e8-90f3-e86b9347652a.png)
Or imagine a case, when instead of beemray there would be something starting from W letter. It will be at the end of matrix (because it's sorted alphabetically), after all of those bad domains. Hosts-filters will put up neutral/unknown domains and put down bad domains.

**Comment by gorhill** [comment]
It's ok if people do not want hosts files, it's there choice, uMatrix does not force anybody to keep the checkboxes checked. The dubious claim here is _"third party rules are dangerous"_. **None** of these imported rules will relax uMatrix's current ruleset -- it's the opposite they contribute to make the current ruleset stricter, so "dangerous" here amount to nothing more than FUD.

**Comment by h1z1** [comment]
FUD?  My point was the lists are now going to be enabled by default.  Whether users choose to use them or not is entirely their own.  Regarding the interface itself, I prefer the second image. 

Don't know where you guys get this but I expect you'll restrict and lock this thread like you usually do.  Screenshots taken.

**Comment by gorhill** [comment]
> FUD? My point was the lists are now going to be enabled by default.

I responded to your:

>  Default third party rules are dangerous.

Just make a convincing argument as to why adding more block rules on top of whatever ruleset is in effect is "dangerous".

**Comment by uBlock-user** [comment]
> but I expect you'll restrict and lock this thread like you usually do. 

Because of you going offtopic with the whole "Default third party rules are dangerous." thing which is the not issue created by the OP and I think you rather have incorrect or misguided understanding when it comes to 3rd party rules.

**Comment by h1z1** [comment]
> Just make a convincing argument as to why adding more block rules on top of whatever ruleset is in effect is "dangerous".

Why on earth would I do that?  It wan't my argument at all.

Keep making threads like [this](https://github.com/gorhill/uMatrix/issues/860) though and you answer your own question.

**Comment by temporaryaccount** [comment]
I agree with @h1z1 here. Any automatic connection made by a privacy-related extension without the user explicitly allowing it is... bad manners, at least. I don't want those lists downloaded to my computer when I'm installing uMatrix. I don't want it to periodically contact Github (or any other) servers to check for updates. Besides, even when unchecking the checkboxes those files remain in the profile.

Would it be too hard to implement a simple yes/no dialog box after installation with something like this:

> Would you like to subscribe to a blocklist xxx maintained by zzz? It will help you block unwanted hosts in case you don't intend to use the whitelist model.
