### ISSUE TITLE
Race Condition?

### ISSUE THREAD

**Issue by Penguin-Guru** [gorhill/uMatrix#930]
I have been having a lot of issues with a certain Windows P.C. so please know that this could be system specific. That said, I just restarted my computer, opened Chrome, and noticed that the pre-existing tabs loaded some content that Umatrix should be blocking. Some of the tabs loaded unusually slowly, and I was not able to open the Umatrix drop-down menu for a couple seconds after each page loaded. I assume this is related, but I'm not sure what could be causing it. It's not a significant problem for me, I just wanted to mention it here in case this is not previously known.

**Comment by gorhill** [comment]
Neither Chromium and Firefox guarantee that content is loaded _after_ extensions are _ready_.

**Comment by Penguin-Guru** [comment]
Ah, I suppose this behaviour makes sense most of the time. I will go ahead and close this ticket unless you want to leave it open. Thanks for the quick reply and great extension. :)

**Comment by gorhill** [comment]
Surprisingly I could not find any duplicate about this. I want to keep it open for now to find out whether I can bring here uBO's `suspendTabUntilReady` approach, except that it would be the default behavior here. If after this you still have the issue, then it will become a browser one.

**Comment by uBlock-user** [comment]
> except that it would be the default behavior here

but will it be still added as a switch ?
