### ISSUE TITLE
'Delete non-blocked session cookies' deletes them on every browser restart (Chromium 64)

### ISSUE THREAD

**Issue by t33rex** [gorhill/uMatrix#932]
I have just upgraded to chromium-64.0.3282.119-135.1.x86_64 (Linux). This is the first 64.* version I use. In 63.* everything was fine but now I notice that with 'Delete non-blocked session cookies' (60 minutes) I have to re-login to all sites if I restart the browser. Even if I restart it in 30 seconds - I still have to relogin.

No settings were touched whatsoever. If I disable this setting, cookies survive restarts.

**Comment by gorhill** [comment]
I don't have Chromium 64 yet, so I can't test for now.

I looked at the code, and uMatrix properly initialize the last-used time to the current time (`Date.now()`), so this is an odd issue.

**Comment by t33rex** [comment]
Could be a browser bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=795827

**Comment by gorhill** [comment]
But you said:

> If I disable this setting, cookies survive restarts

People in the bug report do not mention uMatrix.

**Comment by t33rex** [comment]
Here is my a report (for something else about cookies) in which I mentioned uMatrix:

https://bugs.chromium.org/p/chromium/issues/detail?id=775080

However I am still unable to pin for sure if it has anything to do with uMatrix because it seems difficult to find a patter. At first I thought it is the browser (because with v.63 everything worked fine). Then I thought uM may not be working correctly with v.64 so I disabled cookie clearing. But after a few restarts the issue with logins not surviving appeared again (and it seems - not for every site). Then I got a reply in the bug report linking to the other bug.

So considering that it is difficult to detect a pattern uM may or it may not have any relation to all that. In any case perhaps it is wiser to wait for the browser bug to be fixed and then test again.

What do you say?

**Comment by gorhill** [comment]
> However I am still unable to pin for sure if it has anything to do with uMatrix

This is not in your originally comment -- you unequivocally said there was an issue with uMatrix. Now you say that you are not sure it's uMatrix, while I do ask repeatedly in here that the case must be made that there is an issue with uMatrix, otherwise I end up _wasting_ a whole lot of time on issues which have nothing to do with uMatrix.
