### ISSUE TITLE
uMatrix blocks service worker even if it's disabled

### ISSUE THREAD

**Issue by AFE-GmdG** [gorhill/uMatrix#933]
# uMatrix blocks service worker even if uMatrix is disabled
## Intro
Hello, I'm one of the developers of [just-run.it](https://just-run.it) and we're using service workers for some caching and offline features. Since, I'm the only one in our team which is using uMatrix.
I found some weird behavior of uMatrix in conjunction with service worker:

## Environment
Windows 10 Pro
Google Chrome, Version 64.0.3282.119 (Offizieller Build) (64-Bit)
uMatrix 1.3.2

## relevant uMatrix Settings
```
https-strict: * true
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: opera-scheme true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow

matrix-off: just-run.it true
```

## Steps to reproduce
- Open the editor in the website [just-run.it/editor](https://just-run.it/editor)
  - maybe you're blocking some scripts, so the site may not work correct.
- Disable uMatrix (or use the configuration from above)
- Open the developer tools, and clean the network tab
- reload the page

## expected behavior
Just run it work correctly

## actual behavior
Just run it failed to load the service worker with a error in the console
```Failed to load resource: net::ERR_BLOCKED_BY_CLIENT```

## additional tests
If you deactivate the uMatrix addon at all in the chrome addon settings page the website is running correctly.

## additional screenshots
![image](https://user-images.githubusercontent.com/14022522/35564977-20644814-05bc-11e8-8965-853718962379.png)
![image](https://user-images.githubusercontent.com/14022522/35564801-b9ef94b2-05bb-11e8-8df5-e7a98f50d25f.png)
![image](https://user-images.githubusercontent.com/14022522/35564824-cfa32580-05bb-11e8-9f69-1a605d92c1b6.png)

**Comment by gorhill** [comment]
You removed built-in rule `matrix-off: behind-the-scene true`. Did you look at the behind-the-scene requests in the logger?

**Comment by uBlock-user** [comment]
Won't happen unless you add a rule like `no-workers: * true` or `no-workers: just-run.it true`
