### ISSUE TITLE
Two simple question about "hyperlink auditing"

### ISSUE THREAD

**Issue by Decopi** [gorhill/uMatrix#941]
Hi! Please, two simple question:

UMatrix has an option called "Block all hyperlink auditing attempts".
My first simple question is if this UMatrix option has similar function as dedicated "URLs cleaner add-ons" have? (NeatUrl, SkipRedirect etc).
I am not looking for perfection. But if the UMatrix option "Block all hyperlink auditing attempts" solves privacy issues, then for me is enough. I don't care about fancy add-ons functions. Privacy and performance is my interest in this question.
I look forward to avoid overlapping of add-ons (overlapping of functions, system performance, RAM, CPU etc). So, I would like to keep UMatrix alone (as much as possible), uninstalling unnecessary add-ons.
Should I uninstall all these add-on that claim to clean URLs, guard privacy etc etc etc?

My second simple question is about the ScripSafe add-on, it has an option called "Remove Possible Hash Tracking" (remove possible tracking tokens passed using hash, where there is an attribute and value). Is it option the analog  "Block all hyperlink auditing attempts" in UMatrix?

Thank you in advance!

**Comment by migueldemoura** [comment]
When navigating the settings page of uMatrix, you can click the link to get more information regarding the "block all [hyperlink auditing](https://html.spec.whatwg.org/multipage/semantics.html#hyperlink-auditing) attempts".

That link seems outdated though, but such info can be found here: https://html.spec.whatwg.org/multipage/links.html#hyperlink-auditing

uMatrix doesn't "clean" urls, it simply allows you filter requests. You may to keep those extensions if you find they add some value and are appropriate for your threat model.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).
