### ISSUE TITLE
Scope selector no longer remembers my preferred granularity

### ISSUE THREAD

**Issue by ssokolow** [gorhill/uMatrix#944]
Ever since I've upgraded uMatrix from 1.0, I've found myself having to double-check that I'm not setting the wrong rules because my muscle memory expects the scope selector to remember that I prefer to set rules with subdomain granularity, but every time I close the uMatrix 1.3.2 popup, it resets to domain-level granularity.

(ie. "No, I don't *want** to set this rule for all `google.com` subdomains! Stop trying to trick me into over-granting!")

**Comment by gorhill** [comment]
Dashboard => _Settings_ => _"Default scope level"_ => set it to "Site".

**Comment by ssokolow** [comment]
Ahh. Not sure how I missed that.

That said, the meaning of "Site" isn't exactly clear, since it's an abstract concept that only sometimes correlates to a specific subdomain and it's also not the same form used in the browser action popup.

It might be be a good idea to do one of the following:

1. Add a &nbsp;  ?⃝   &nbsp; button which clarifies each scope name with an example
2. Use "subdomain" instead of "site" in the "Default scope level" dropdown so it's unambiguous.
2. Use "www.site.com", "site.com", and "*" as the options in the "Default scope level" dropdown so they visibly match the browser action.
