### ISSUE TITLE
Behind-the-scene requests & SPDY

### ISSUE THREAD

**Issue by gavin20** [gorhill/uMatrix#95]
Hello,

Not sure if this is an issue or more of a question - is it possible to monitor spdy connections? I do have an option to review [chrome-scheme](https://i.imgur.com/ZMmWObo.jpg), but I do not see the below connections in uMatrix. I was hoping more control over these connections - if possible, maybe force thru http?

Via chrome://net-internals/#spdy

Host	Alternate Protocol
www.gstatic.com
www.google.com
ssl.gstatic.com
mail.google.com
lh3.googleusercontent.com
encrypted.google.com
clients6.google.com
clients5.google.com
clients2.google.com
apis.google.com
ajax.googleapis.com
accounts.google.com

**Comment by gorhill** [comment]
`chrome-scheme` is not what you are looking for, as it is for pages which URL starts with `chrome://` -- `chrome://extensions/` for example.

`chromium-behind-the-scene` is where you will find network requests which are made outside any tab. To access the `chromium-behind-the-scene` matrix, just go to uMatrix's dashboard, and bring up uMatrix pop-up while on any page in the dashboard:

![c](https://cloud.githubusercontent.com/assets/585534/5597268/3bb59a16-926d-11e4-82fa-3cff66a5922c.png)

**Comment by gavin20** [comment]
Gotcha - here's what I see though. Looks like it's missing mail.google.com & googleusercontent.com. These connections are accessed via homepage extension(ANTP widgets - rss feed/meta tiles/gmail).

![](https://i.imgur.com/e5UVkkn.png)

![](https://i.imgur.com/YTBjxJp.png)

**Comment by gorhill** [comment]
> Looks like it's missing mail.google.com & googleusercontent.com. These connections are accessed via homepage extension(ANTP widgets - rss feed/meta tiles/gmail).

You will probably find them on the tab where they occurred: if a network request can be traced back to a specific tab, it will appear in the matrix for that tab. The `chromium-behind-the-scene` matrix is for those network which can't be tracked to a specific tab.

**Comment by gavin20** [comment]
I do see some behind-the-scene requests, but not all of them. Example - I show the following url_requests occur in 'chrome://net-internals/#events' when I first launch Chrome. My expectation would be to see the following entries in uMatrix's Statistic page -

https://mail.google.com/mail/u/0/feed/atom?nocache
http://127.0.0.1/?osname=win
https://clients2.google.com/service/update2

I do recall these entries being visible in earlier uMatrix builds in the statistics page, including HTTP Switchboard. I also redirect Chrome variations server url to 127.0.0.1, which I used to see in the statistics page, enabled via flag "--variations-server-url=http://127.0.0.1".

**Comment by gorhill** [comment]
Ok look... Your first message there was no context whatsoever in how you got the requests in your lists. It is difficult to answer properly and in a time-saving manner.

Here it is: **all** net requests are recorded in one matrix or another, **except** for those documented as not going through the webRequest API (webSockets, update-related, web store-related).

_Now_ you are disclosing a bit more information which should have been disclosed in the first report to save time: **"when I first launch Chrome"**. That is issue #93, and even if I come around as improving this, it is really un-fixable as per browser design.

Bottom-line, I can't investigate for you remotely if you don't look first at every details before reporting to confirm there is really an issue. In your first report you did not look at the behind-the-scene matrix. In your second report, there is no `mail.google.com`.

So this: except for the known shortcomings of the webRequest API, please give me **exact repro steps** for whatever issue you have carefully confirmed on your side. So far I did see anything unexpected. I need repro steps, and before posting them, ensure it has nothing to do with the known shortcoming.

**Comment by gorhill** [comment]
With the unified logger, users will no longer miss network requests, so long as they go through the web request API.
