### ISSUE TITLE
Some entries are only briefly shown in uMatrix

### ISSUE THREAD

**Issue by stonie08** [gorhill/uMatrix#951]
On some websites, hosts for scripts and also the number indicators are only shown briefly in the uMatrix window (due to redirects or similar), making it very hard to allow them. At the moment it's required to either add the entries manually or allow all of the website, specifically allow the problematic entries and revoking the overall clearance.

One example (the most recent I encountered) is https://aar.ark-group.org/ . Iirc I had the same problem with amazon support chat windows.
Steps to reproduce:
* Start by disallowing everything except overall image and css, and 1st party frames.
* go to https://aar.ark-group.org/
* allow aar.ark-group.org scripts
* refresh
* click on any item in the list
* You'll get the message: `The xxxx terrain is missing! Why don't you add it?`
* check umatrix for available hosts to figure out "what's missing"

When clicking on any of the entries in the list uMatrix will very briefly show  a 1 at the XHR field for aar.ark-group.org and a titanmods.xyz host indicating there are scripts from that site as well. Because they are only listed for such a short time, and only after one clicked on any of the entries on the list on the website, one has a very hard time to actually check what's missing on the site and allow it, without granting permissions for everything. The log gives an indicator on it, but doesn't allow for selectively allowing hosts like the normal uMatrix view does.

**Comment by gorhill** [comment]
Use the logger in such case, you can bring the popup panel from the logger: <https://github.com/gorhill/uMatrix/wiki/How-to-access-the-popup-panel-when-there-is-no-toolbar>.

**Comment by gorhill** [comment]
Never mind, the logger does not help in the current case.

**Comment by gorhill** [comment]
I am going to add a dropdown list for the 3rd-cell, from which one can click a rule to add to the temporary ruleset:

| Source            | Destination             | Type
| -----------------:| -----------------------:| ----:
| aar.ark-group.org | r3tiles-a.titanmods.xyz | xhr
| aar.ark-group.org | r3tiles-a.titanmods.xyz |   *
| aar.ark-group.org |           titanmods.xyz | xhr
| aar.ark-group.org |           titanmods.xyz |   *
|     ark-group.org | r3tiles-a.titanmods.xyz | xhr
|     ark-group.org | r3tiles-a.titanmods.xyz |   *
|     ark-group.org |           titanmods.xyz | xhr
|     ark-group.org |           titanmods.xyz |   *
|                 * |           titanmods.xyz | xhr
|                 * |           titanmods.xyz |   *

**Comment by stonie08** [comment]
Thanks for the fast response. 
Clicking on the second cell opens the pop-up panel for that specific request (kind of). I think it'd look cleaner to have these entries in the popup-panel in the logger as well, as the rest of the design is indicating this behavior: All affected entries in the logger remain black, while unrelated entries turn grey.

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/46244753-9159a880-c3b1-11e8-8fd1-1090c6183ed5.png)
