### ISSUE TITLE
Keep uMatrix dialog open

### ISSUE THREAD

**Issue by madduck** [gorhill/uMatrix#955]
It's awesome that I can keep the uMatrix dialog open while a page loads and watch in real-time what happens. But when I interact with a website by mouse or keyboard, it closes. Unfortunately, often things happen so quickly between redirects that I can't get it to open fast enough to see e.g. why a payment would have failed.

Would it be possible to add an option to keep the dialog open, or maybe detach it into its own window somehow?

**Comment by Atavic** [comment]
That's a difficult one, extensions run inside the browser and the drop-dwon window is affected by the focus (that's why your interactions cause it to close).

**Comment by Atavic** [comment]
That's a difficult one, extensions run inside the browser and the drop-down window is affected 
by the focus (that's why your interactions cause it to close).

**Comment by gorhill** [comment]
It's not possible, the browser controls the popup panel, uMatrix just renders in it using HTML/CSS/JS.

Just bring the popup panel from with the logger, this one is fully controlled by uMatrix: <https://github.com/gorhill/uMatrix/wiki/How-to-access-the-popup-panel-when-there-is-no-toolbar>.

**Comment by madduck** [comment]
Thank you @gorhill, this is precisely what I was looking for. I am
sorry I didn't know about the wiki beforehand…

-- 
The sender e-mail address used (github.com@pobox.madduck.net)
is valid and specific to our correspondence. It should not indicate any
affiliation with your organisation.
 
Die verwendete E-mail-Adresse (github.com@pobox.madduck.net)
ist gültig und spezifisch für unsere Korrespondenz. Sie soll in keiner Weise
auf eine Verbindung mit Ihrer Organisation hindeuten.
 
Spamtrap: github.com.bogus@pobox.madduck.net
