### ISSUE TITLE
uMatrix not propely handling embedded videos at NameThatPorn.com?

### ISSUE THREAD

**Issue by boxfreind** [gorhill/uMatrix#958]
Warning: links may contain adult content.
To replicate issue:
I have installed a portable version of FF 58.0.2 with no other extensions besides uMatrix to rule out other extensions disrupting it. I go to https://namethatporn.com/post/87462-whats-the-name-of-this-porn-actor.html. The embedded video is blocked. I go to the uMatrix dashboard and allow 9content.com, embeddy.me, and xhmaster.com, including the frames. I click the lock icon to save my changes, and then the reload button. It is still blocked and no new entries are in the dashboard. I believe this is where the issue lies, elements from the video at xhamster (among others) are not being properly handed through to the site. In the top left hand corner of the space where the video would be there is a link: https://embedy.me/?u=http%3A%2F%2Fxhamster.com%2Fmovies%2F3200462%2Fhorny_lesbian_glamour_milf_eats_babes_pussy.html&eapi=37e838885e9fd07692e5da83e515878e. I follow the link. On that page I allow xhamster. com and I lock in the changes and reload. This embed is blocked as well. I follow the link https://xhamster.com/xembed.php?video=3200462 and I allow xhcdn.com and static-ec-2.xhcdn.com. I reaload and the video plays. I go back to the embedy.me page and reload the page. No changes have been registered. The video will not load, and the xhcdn elements have not loaded in the dashboard. Same goes for the video at NameThatPorn. 
This happens here as well, but with a video hosted by Xvideos. https://namethatporn.com/post/742133-whats-the-name-of-this-porn-star.html
Now, I will detail how I can get the video to play. If I click on the "disable matrix filtering for this scope" button, uMatrix should stop blocking anything on the page. I do so, I lock it in, and I reload. The video is STILL being blocked!
I go to about:addons and I disable uMatrix in the extensions tab. I go back to the NTP page and reload the page. It's STILL being blocked!!! What???
I hit shift+f2 to open the FF console and I type restart and hit enter. FF restarts. I go to the page at NTP. STILL BLOCKED!!!
I go back to about:addons and this time I REMOVE uMatrix. I also clear the cookies and the cache. Once again, I restart through the console. Now all the videos are playing fine.
I reinstall uMatrix. I restart FF. Now the videos are being blocked again. 
Could this be some sort of anti-adblocker tech being employed at NameThatPorn? Is there something in the uMatrix settings I could tweak to work around this?

**Comment by boxfreind** [comment]
What the heck? I just reinstalled uMatrix to continue troubleshooting and now the icon for the extension is missing. I can find where the extension is on the toolbar, but it is blank. If I click it, a tiny white dropdown appears but it is very small and completely devoid of anything to click on. What on earth is going on???

**Comment by boxfreind** [comment]
Additional: is it a good or bad idea to use both uMatrix and uBlock Origin?

**Comment by user234683** [comment]
> I go back to about:addons and this time I REMOVE uMatrix. **I also clear the cookies and the cache.** 
try doing that after disabling matrix filtering for the scope.

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by Raavizz** [comment]
>  @boxfreind : What the heck? What on earth is going on??? fucked

Stop your drama / agression / toxicity / negativity / vulgar words.

**Comment by hukkay** [comment]
@boxfreind Stop your drama / vulgarity / spamming of porn links
