### ISSUE TITLE
Safari version

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#96]
To track progress of a possible version for Safari

**Comment by filipecatraia** [comment]
I'd love to have it, is there a way to help?

**Comment by kilsey** [comment]
Also dying to have this - uBlock isn't quite enough on its own for Safari

**Comment by underscorephil** [comment]
+1

**Comment by caobo** [comment]
+1

**Comment by AndreasBackx** [comment]
Any reason why this is declined?

**Comment by gorhill** [comment]
@AndreasBackx Can you port it?

**Comment by AndreasBackx** [comment]
I can port it, I was just wondering about the reasoning behind the declined request.

**Comment by gorhill** [comment]
Because I can't, no OSX, no Safari, but more importantly, no time.
