### ISSUE TITLE
Documentation of "Cloud Storage Support"

### ISSUE THREAD

**Issue by 1stone** [gorhill/uMatrix#962]
I wonder what kind of service the "cloud storage support" is providing.
After enabling it on the setting tab, I see buttons to push/pull rules, but where is it stored? 
Where is that "cloud"?
Will it allow me to sync it with other browsers?

Unfortunately, I can't find any description or documentation for this in the wiki.
Is it really missing, or did I oversee it?

**Comment by overdodactyl** [comment]
Unless I'm mistaken, the documentation for uBO's cloud storage applies to uMatrix as well:

https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by 1stone** [comment]
Hmm... ok. Thanks for the information.
I'm new to uMatrix and didn't notice the relationship to uBO.
