### ISSUE TITLE
First-party JS interaction with extensions such as Violentmonkey

### ISSUE THREAD

**Issue by wavexx** [gorhill/uMatrix#966]
I'd like to disable JS by default, including first-party JS. However this has the side-effect that any script injected via Violentmonkey obviously cannot run. Behavior as intended, I know. But since uMatrix is for advanced users, this is what I do:

I often inject little scripts to restore simple functionality on some websites. My main example here would be reddit: I intentionally avoid running all their JS, and simply use my own one-liner to collapse/expand subthreads.

The "spoof noscript" option added recently gave me this idea: can be spoof <script> tags to disable JS instead of setting a content policy, so that I can still inject my own later on?

**Comment by gorhill** [comment]
What you ask is out of scope of uMatrix. If you are using Firefox, try a filter such as `reddit.com##^script`.

**Comment by wavexx** [comment]
On Thu, Mar 08 2018, Raymond Hill wrote:
> What you ask is out of scope of uMatrix. If you are using Firefox, try a filter such as
> reddit.com##^script.

I guess using uBlock?

**Comment by gorhill** [comment]
Yes, I corrected my comment afterward.
