### ISSUE TITLE
Unresponsive switchboard in Nightly

### ISSUE THREAD

**Issue by korpjack** [gorhill/uMatrix#968]
The popup menu appears and responds to hovering but not clicking. The cells are not responding. None of the clickable buttons in that popup is working. uMatrix is doing its job - blocking things and everything - it's just the interface that is broken. As a result, I am unable to make any further changes to the rules from this popup. Issue started around two days ago and very likely to do with Nightly's v.61 update.

Nightly 61.0a1 (64-bit)
Windows 7

**Comment by kasiub** [comment]
I also have the same issue (only difference is Windows 10 not 7).

**Comment by Porkepix** [comment]
Reproduced on Archlinux too, latest Nightly. Can check on a mac this evening.
Question is, did it broke on the addon update or Nightly's update.

**Comment by JW-IT** [comment]
same problem win10-64bit, nightly 61.0a1-64bit
and i am pretty sure, that there was no addon update, but the nightly's update is the culprit

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1445537

**Comment by Hoerli1337** [comment]
Same here with Win10 64bit and Nightly 64bit 61.0a1 (2018-03-14).
Tested with 2 systems.

**Comment by 0re5ama** [comment]
same here with arch linux and Nightly.

**Comment by davidjb** [comment]
The issue has just been fixed according to the Bugzilla link; guess we'll see when the next Nightly comes out.

**Comment by davidjb** [comment]
FF Nightly update just installed has fixed the issue on uMatrix/uBlock Origin for me; 61.0a1 (2018-03-15) (64-bit) on Mac 10.13.3. 🎉

**Comment by korpjack** [comment]
Issue has been resolved by the latest update in Nightly.
https://hg.mozilla.org/mozilla-central/rev/6ed4300a066b

**Comment by JW-IT** [comment]
can confirm, latest nightly update fixed this
win10 (64bit), Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by nailyk-fr** [comment]
Wanna say the same. 
Fixed here on 61.0a1 (2018-03-18) on devuan ascii.

**Comment by Porkepix** [comment]
@korpjack or @gorhill This issue should probably be closed then?

**Comment by gorhill** [comment]
OP should close it, I no longer care to close issues, too much of a time sink.
