### ISSUE TITLE
Revert/Commit button hangup

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uMatrix#971]
### Steps to Reproduce

1) Browse to `https://www2.fmovies.se/`

2) Open the popup UI and block `script` from domain `cdnjs.cloudflare.com`, should look like this - https://i.gyazo.com/e15c7dcf4273984e507157d0a8c80f6e.png

3) Do a cache free reload of the page by pressing Ctrl + R or Ctrl + Refresh button near the address bar.

4) Now open Dashboard and browse to `My rules`, click on the `Revert` button, observe that it won't grey out and nothing happens, button appears stuck, now click on the `Commit` button, observe the same behavior there as well.

### Browser Info

Chromium 67/ uMatrix 1.3.3.9
Win 10 x64

**Comment by uBlock-user** [comment]
@gorhill made a video to show it looks like 

![](https://i.gyazo.com/481af3f199ee9e42f9ad0975f80b3cd9.mp4)

**Comment by korpjack** [comment]
I could be wrong, but it looks like both sides of the rules (perma and temp) are the same. Are they? If they are nothing would change.

**Comment by uBlock-user** [comment]
Not completely same, when I click the revert button the new rules in temp get deleted, but the button remains active, and so does the commit button. The buttons are getting stuck, that's the issue.

**Comment by gorhill** [comment]
Not found in issue report:

- Whether this occurs in stable release of the browser
- Whether errors are reported in page and extension console

**Comment by uBlock-user** [comment]
Were you able to reproduce ?

**Comment by talklittle** [comment]
I had this problem when Firefox (59.0.1) auto-updated from uMatrix 1.3.2 to 1.3.4.

Solved by exporting rules to a file, editing and deleting all rules, then re-importing the rules from the file.

Maybe some rule formatting difference going from 1.3.2 to 1.3.4, e.g. trailing whitespace?

**Comment by uBlock-user** [comment]
> Solved by exporting rules to a file, editing and deleting all rules, then re-importing the rules from the file.

That's a workround, not a solution when the bug exists in the extension itself. I could fix it too by rrebooting the chrome that way.

**Comment by korpjack** [comment]
I am using Firefox (no issues), but I took a look at the source and the mechanism that toggles those buttons' visibility is done this way:  `uDom('#diff').toggleClass('dirty', response.temporaryRules !== response.permanentRules);`   
The `toggleClass` adds or removes the `dirty` class from the container div. To debug this in chrome, one could check if this class name gets added/removed with each click by using inspect-element, and proceed from there.

**Comment by uBlock-user** [comment]
Well, I guess you were unable to reproduce ultimately, so I will close it.
