### ISSUE TITLE
Umatrix Filtering Disabled by Default on many pages!

### ISSUE THREAD

**Issue by ravenise** [gorhill/uMatrix#977]
Umatrix was working fine for months, suddenly I must click "enable/disble matrix filtering for this scope" on nearly every page I visit to enable umatrix filtering. Why is that, and how do I enable matrix filtering globally?  Using google chrome on windows, sandboxed in sandboxie.  Using the latest Umatrix with my personally imported definitions.

**Comment by ravenise** [comment]
Found the solution, simply remove the following from Umatrix rules:

matrix-off: * true

**Comment by gorhill** [comment]
Which is a rule you added yourself.

**Comment by Atavic** [comment]
@ravenise Great! Now you can close this.

**Comment by ravenise** [comment]
Quite possibly, though could be due to malware or hackers
