### ISSUE TITLE
Meaning of entries in Dashboard Statistics

### ISSUE THREAD

**Issue by hrj** [gorhill/uMatrix#98]
I happened to see my Dashboard Statistics for the first time today, and was alarmed to see dozens of these in green:
```
12:43:36 AM	other	<a>	https://www.google-analytics.com/collect
```

I am 99.99% sure I have not enabled this (did a quick grep in the rules as well), so I am quite confused.

* What kind of request is this? Why is it tagged with `other`?
* Is it possible to know which tab it came from?
* If it appears in the log, does it imply that uMatrix can block it, but I have set some rule unknowingly to allow it?

**Comment by gorhill** [comment]
1. Probably hyperlink auditing
1. No
1. Behind-the-scene matrix

**Comment by hrj** [comment]
Thanks. I do see some related entries in behind-the-scene matrix (which I just discovered).

On that matrix, filtering was disabled and all entries were faded green. Is this the default, or did I disable it (but have forgotten)?

**Comment by gorhill** [comment]
Default, or else it would break too many important things. The users must set it to block themselves.

**Comment by hrj** [comment]
Can you please list the important things? I am now blocking everything in the behind-the-scene-matrix and would like to know what I am breaking.

**Comment by gorhill** [comment]
https://github.com/gorhill/httpswitchboard/wiki/Behind-the-scene-requests

**Comment by hrj** [comment]
Thanks. So the list of important functionality affected by blocking B-T-S requests seems to be:

* Requests made by extensions
* Requests made by browser to install or update extensions

Can that be called a complete list of *known* important uses?

**Comment by my-password-is-password** [comment]
Another thing to remember is that just because requests shows up green in uMatrix it doesn't exactly mean the requests are being made. uBlock may be blocking it so you have to check in uBlock's log.

**Comment by hrj** [comment]
Ah ok, thanks. I am not using uBlock; only uMatrix.
