### ISSUE TITLE
Yandex search blocked completely

### ISSUE THREAD

**Issue by EC-O-DE** [gorhill/uMatrix#985]
Just recently uMatrix has started to block yandex/ru/ua/com search completely...

**Comment by uBlock-user** [comment]
It's blocked by Dan Pollock's HOSTS File, and uMatrix merely enforces full blockage because the domain is listed there. So contact them.

**Comment by EC-O-DE** [comment]
But still... ;)

**Comment by Atavic** [comment]
>unblock it yourself

https://github.com/gorhill/uMatrix/issues/341

**Comment by uBlock-user** [comment]
> #341 

?

**Comment by Atavic** [comment]
>?

Gorhill instructions to override Pollock's blacklist.
https://github.com/gorhill/uMatrix/issues/341#issuecomment-137846859

**Comment by uBlock-user** [comment]
Oh yeah that, you quote specific part of my reply, so I thought you were linking me to something else.

This is how I did it..

`name.domain name.domain * inherit`

**Comment by gorhill** [comment]
Best is to link to the wiki: <https://github.com/gorhill/uMatrix/wiki/How-to-get-past-%22uMatrix-has-prevented-the-following-page-from-loading%22>.
