### ISSUE TITLE
Site can read cookies even though they are blocked

### ISSUE THREAD

**Issue by chang301** [gorhill/uMatrix#987]
**Site**: duckduckgo.com
**Browser**: latest FF + Chrome

### Steps to reproduce:

- block all cookies
- open duckduckgo.com
- set a language
- search something in another tab

**expected behavior**: no language set
**actual behavior**: language is read from cookie

**further proof**: edit the cookie language string manually. it does read directly from the cookie.

How can this happen?

**Comment by guakamole** [comment]
+1

I'll add that, even worse, sites can **write** cookies even though they are blocked in the matrix.

Note that it seems to be related to first party cookies only (third party are blocked by firefox anyway so I can't tell).

Firefox 61.0a1 and uMatrix 1.3.4.

**Comment by ArchangeGabriel** [comment]
@guakamole Writing cookies is allowed by uMatrix. [Read the doc](https://github.com/gorhill/uMatrix/wiki/Cookies).

**Comment by theWalkingDuck** [comment]
uMatrix is working properly.
That cookie is not leaving your browser at all.
The  `Drop Down menu` is not set by the DDG server, it's set by a local script 
that reads the cookie and changes the `value` of the `Drop Down menu` after a page load.

**Comment by ArchangeGabriel** [comment]
They are currently issues with cookie deletion in some cases, see #878. The minimum interval is set by the browser AFAIK.

**Comment by Atavic** [comment]
That requirement is most of the times a workaround to bypass adblockers or grab as much data as possible from the visitor's browsers. That's why we should block scripts when not needed.

**Comment by gorhill** [comment]
The idea is if someone is unhappy with the 0-120 seconds gap before cookies are deleted by uMatrix, whitelist cookies in uMatrix and use a specialized extension which does what you want if you can find one.

**Comment by chang301** [comment]
I've tried finding more ways to block cookies (although personally the uMatrix approach is fine for me, I just wish you couldn't circumvent it so easily) but nothing beats the uMatrix interface in terms of usability. Feels very natural.

**Comment by GeographicCone** [comment]
> I've tried finding more ways to block cookies

Cookie-AutoDelete works great for me with uMatrix and uBlock Origin:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete
