### ISSUE TITLE
Firefox version conflict before installing uMatrix

### ISSUE THREAD

**Issue by GITMichaelK** [gorhill/uMatrix#988]
I'm running Firefox 59.0.2 as well on a WINDOWS as on a kUBUNTU-PC. On both machines, tried to add uMatrix using the Firefox-search for Add-Ons but it's claiming a "newer" version at least Firefox 56.0a1. and that I would use Firefox 52.0, which definitely is not right. Having this issue, the download-button is not accessible.
Attached screenshot (German language) showing as well the error message (red line) ans the version window
![umatrix](https://user-images.githubusercontent.com/34304987/38319224-d3c1ba5e-3820-11e8-9541-e4070044dda5.png)
How can I solve this? Thank you!

**Comment by zippy5** [comment]
You likely set `privacy.resistFingerprinting` to `true`.

You can still download it from AMO, manually install it, or temporarily turn off the setting.

Regardless, you should look into what settings do before you change them.

**Comment by GITMichaelK** [comment]
Thank you, perfect solution.
