### ISSUE TITLE
Feature request: Ability to view the behind-the-scenes matrix and request count from the per-tab matrix

### ISSUE THREAD

**Issue by hrj** [gorhill/uMatrix#99]
* Currently, the presence and location of the behind-the-scenes matrix is not easily discoverable. I just discovered it (after using HTTPSB/uMatrix for several months).
* Even if the location is known, it is inconvenient to go to the settings, then check the BTS matrix for any BTS entries.
* Since some important functionality of the browser depends on BTS requests, they are not filtered by default. Hence, it is doubly important to make the BTS matrix and the request counts discoverable.

**Comment by CrisBRM** [comment]
Gorhil will probably not do this (rightly so in my opinion) because it would make everything unintuitive and more confusing, and there would need to be a separation to know which is which, which would also make things rather cluttered.
Furthermore, the behind-the-scenes matrix is pretty much "use and forget" after a full day of use, since they don't really disappear until after you relaunch chrom*.

**Comment by hrj** [comment]
I can see how it would be confusing and an overload of information. But IMO not making it discoverable defeats the purpose of the extension; it leads the user to believe that requests are being blocked when they are not.

Could an intermediate solution be possible: a count of behind the scene requests is shown on the per-tab matrix. Clicking this brings up the behind-the-scenes matrix, or a message that explains B-T-S and then allows the user to proceed to the B-T-S matrix.

PS: I fixed a typo in my first comment, I had meant to write: "*not* easily discoverable" but had omitted the *not*

**Comment by gorhill** [comment]
> not easily discoverable

Let's not exaggerate:

![c](https://cloud.githubusercontent.com/assets/585534/5613160/d700a3fc-94ad-11e4-9739-5dac98743160.png)

**Comment by hrj** [comment]
That screenshot talks about b-t-s requests, not the b-t-s matrix AFAICT.

I am a fan of uMatrix. I have helped install this extension on many of my friends' computers. As a long time user, I am just expressing my opinion. Am not trying to exaggerate.
