### ISSUE TITLE
Ruleset pane size miscalculated

### ISSUE THREAD

**Issue by warnellw** [gorhill/uMatrix#990]
Hi there,

In uMatrix v1.3.6 on Chrome on Windows, the size of the ruleset panes are not calculated correctly when cloud storage is being used. It prevents being able to see some of the rules at the end of the list (both windowed and full screen):

![rules](https://user-images.githubusercontent.com/3211186/38460064-969af3a4-3a80-11e8-8047-a31358a5d0a3.PNG)

After hiding the cloud storage widget with dev tools:

![rulesnocloud](https://user-images.githubusercontent.com/3211186/38460074-c12fb352-3a80-11e8-8e0f-84da2e8b31d1.PNG)

It appears that the size of the ruleset panes are being calculated before the cloud storage widget is displayed/inserted.

**Comment by uBlock-user** [comment]
I can reproduce. Activate `Enable cloud storage support ` and click on `My Rules`, try to scroll to the end and will cut before the end. Deactivate it to go back to normal scrollable end.

**Comment by uBlock-user** [comment]
I can reproduce. Activate **Enable cloud storage support**  and click on **My Rules**, try to scroll to the end and will cut before the end. Deactivate it to go back to normal scrollable end.

@gorhill Changing height of the div `codeMirror Container code MirrorMergeContainer vfill-available` after the cloud widget is added from 512 to **440px** seems to fix the issue. 

![](https://i.gyazo.com/91f26223cbeeb26dedba1db614899f2c.png)

**Comment by gorhill** [comment]
Fix will be in dev build 1.7.3b1. Until next stable release is published, workaround is to slightly resize the browser window.
