### ISSUE TITLE
GUI: Long host names going under matrix make it impossible to read the domain

### ISSUE THREAD

**Issue by levicki** [gorhill/uMatrix#991]
Host names like this:

```bw-1651cf0d2f737d7adeab84d339dbabd3-bcs.s3.amazonaws.com```

Result in matrix which looks like this:

![image](https://user-images.githubusercontent.com/16415478/38568737-b1372f96-3ce9-11e8-95db-3693c9e9c155.png)

In my opinion,, either those names should be shortened to something like:

```bw-1...3-bcs.s3.amazonaws.com```

And the mouseover should show the full name in tooltip, or the matrix column with host name should expand itself to fit.

Browser is Chrome, but I observed this with Firefox too. If you need more information, please let me know.

**Comment by ArchangeGabriel** [comment]
Duplicate: https://github.com/gorhill/uMatrix/issues/182

**Comment by levicki** [comment]
Which is a duplicate of #46, an almost four year old issue. Is it impossible to fix?

I see Raymond's comment about browser rendering the text and uMatrix not knowing it will be cut, but it seems to be possible to check the text width in pixels by using invisible DIV:

https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript

I am not sure how much that would slow the rendering though?

**Comment by theWalkingDuck** [comment]
A clean solution would be adding a `title` attribute whenever the host name exceeds a certain length.

`<b title="longHostNameXxxxxxx.com">longHostNameXxxxxxx.com </b>`

**Comment by uBlock-user** [comment]
https://github.com/gorhill/httpswitchboard/issues/133#issuecomment-42762309
