### ISSUE TITLE
Umatrix Broken, Had to remove / reinstall; Thankfully I had backed up my rules a few days before

### ISSUE THREAD

**Issue by ravenise** [gorhill/uMatrix#994]
This is what umatrix looked like; accessing options by right clicking the icon lead to mostly blank pages; just a umatrix symbol, and 4-5 little file icons in the top left denoting each profile window for umatrix. did a system restore recently; wondering if that had anything to do with it; zema showing nothing; previously, enabling and disabling umatrix fixed this issue which popped up once before; this time, no luck had to remove it & reinstall. Other extensions appeared to be broken as well, like user agent switcher https://add0n.com/useragent-switcher.html which could not access the list of agents; i blv from url.

Here is a picture of what umatrix looked like: using the latest srware iron.
https://postimg.cc/image/xidjp6ovr/

**Comment by uBlock-user** [comment]
probably a broken build of SRWare Iron.

**Comment by gorhill** [comment]
I don't even understand why someone would use SR Iron over [Chromium itself](https://chromium.woolyss.com/#chromium-forks).
