### ISSUE TITLE
Youtube trouble when watching videos...

### ISSUE THREAD

**Issue by EC-O-DE** [gorhill/uMatrix#996]
[Imgur](https://i.imgur.com/9OTxtDh.png)

Edit: addition: Dear @gwarser - I have no clue why YouTube has started to behave like that. I'm at odds. I went through my perm and temp ruleset tables and I just don't see anything that could explain. I'm sorry. I hope I haven't wasted your time. uMatrix is one of the best extensions ever. Please bear with me.

**Comment by gwarser** [comment]
https://github.com/gorhill/uMatrix/wiki/How-to-get-past-%22uMatrix-has-prevented-the-following-page-from-loading%22
